# Generated by Django 6.0.8 on 2026-08-28 11:42

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models

import waldur_core.core.fields
import waldur_core.core.validators


class Migration(migrations.Migration):
    replaces = [
        ("waldur_autoprovisioning", "0001_initial"),
        ("waldur_autoprovisioning", "0002_rule_project_role"),
        (
            "waldur_autoprovisioning",
            "0003_rule_created_rule_modified_rule_uuid_and_more",
        ),
        ("waldur_autoprovisioning", "0004_rule_name"),
        (
            "waldur_autoprovisioning",
            "0005_remove_rule_plans_rule_plan_rule_plan_attributes_and_more",
        ),
        ("waldur_autoprovisioning", "0006_rule_project_name_template"),
        ("waldur_autoprovisioning", "0007_alter_rule_customer"),
        ("waldur_autoprovisioning", "0008_add_user_identity_sources"),
        (
            "waldur_autoprovisioning",
            "0009_rule_user_assurance_levels_rule_user_nationalities_and_more",
        ),
    ]

    dependencies = [
        ("marketplace", "0148_offering_access_url"),
        ("marketplace", "0169_maintenanceannouncement_and_more"),
        ("permissions", "0016_userrole_modified_alter_userrole_created"),
        ("structure", "0049_migrate_organization_groups"),
        ("structure", "0066_alter_accesssubnet_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="Rule",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=150,
                        validators=[waldur_core.core.validators.validate_name],
                        verbose_name="name",
                    ),
                ),
                ("uuid", waldur_core.core.fields.UUIDField()),
                ("user_affiliations", models.JSONField(blank=True, default=list)),
                ("user_email_patterns", models.JSONField(blank=True, default=list)),
                (
                    "user_identity_sources",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of allowed identity sources (identity providers).",
                    ),
                ),
                (
                    "user_nationalities",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of allowed nationality codes (ISO 3166-1 alpha-2). User must have one of these.",
                    ),
                ),
                (
                    "user_organization_types",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of allowed organization type URNs (SCHAC). User must match one.",
                    ),
                ),
                (
                    "user_assurance_levels",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of required assurance URIs. User must have ALL of these.",
                    ),
                ),
                (
                    "project_name_template",
                    models.CharField(
                        blank=True,
                        help_text="Template for project name. Supports {username}, {email}, {full_name} variables",
                        max_length=255,
                        null=True,
                    ),
                ),
                ("plan_attributes", models.JSONField(blank=True, default=dict)),
                ("plan_limits", models.JSONField(blank=True, default=dict)),
                (
                    "use_user_organization_as_customer_name",
                    models.BooleanField(default=False),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="structure.customer",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="marketplace.plan",
                    ),
                ),
                (
                    "project_role",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="permissions.role",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
