# Generated by Django 4.2.20 on 2025-06-26 12:24

import uuid

import django.utils.timezone
import model_utils.fields
from django.db import migrations

import waldur_core.core.fields


def gen_uuids(apps, schema_editor):
    Rule = apps.get_model("waldur_autoprovisioning", "Rule")
    RulePlans = apps.get_model("waldur_autoprovisioning", "RulePlans")

    for rule in Rule.objects.all():
        rule.uuid = uuid.uuid4()
        rule.save(update_fields=["uuid"])

    for rule in RulePlans.objects.all():
        rule.uuid = uuid.uuid4()
        rule.save(update_fields=["uuid"])


class Migration(migrations.Migration):
    dependencies = [
        ("waldur_autoprovisioning", "0002_rule_project_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="rule",
            name="created",
            field=model_utils.fields.AutoCreatedField(
                default=django.utils.timezone.now,
                editable=False,
                verbose_name="created",
            ),
        ),
        migrations.AddField(
            model_name="rule",
            name="modified",
            field=model_utils.fields.AutoLastModifiedField(
                default=django.utils.timezone.now,
                editable=False,
                verbose_name="modified",
            ),
        ),
        migrations.AddField(
            model_name="rule",
            name="uuid",
            field=waldur_core.core.fields.UUIDField(),
        ),
        migrations.AddField(
            model_name="ruleplans",
            name="created",
            field=model_utils.fields.AutoCreatedField(
                default=django.utils.timezone.now,
                editable=False,
                verbose_name="created",
            ),
        ),
        migrations.AddField(
            model_name="ruleplans",
            name="modified",
            field=model_utils.fields.AutoLastModifiedField(
                default=django.utils.timezone.now,
                editable=False,
                verbose_name="modified",
            ),
        ),
        migrations.AddField(
            model_name="ruleplans",
            name="uuid",
            field=waldur_core.core.fields.UUIDField(),
        ),
        migrations.RunPython(gen_uuids, reverse_code=migrations.RunPython.noop),
    ]
