# Generated by Django 4.2.20 on 2025-07-13 21:53

from django.db import migrations, models

import waldur_core.core.validators


class Migration(migrations.Migration):
    dependencies = [
        (
            "waldur_autoprovisioning",
            "0003_rule_created_rule_modified_rule_uuid_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="rule",
            name="name",
            field=models.CharField(
                default="Rule",
                max_length=150,
                validators=[waldur_core.core.validators.validate_name],
                verbose_name="name",
            ),
            preserve_default=False,
        ),
    ]
