# Generated by Django 4.2.23 on 2025-07-15 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("marketplace", "0169_maintenanceannouncement_and_more"),
        ("waldur_autoprovisioning", "0004_rule_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="rule",
            name="plans",
        ),
        migrations.AddField(
            model_name="rule",
            name="plan",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="marketplace.plan",
            ),
        ),
        migrations.AddField(
            model_name="rule",
            name="plan_attributes",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="rule",
            name="plan_limits",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.DeleteModel(
            name="RulePlans",
        ),
    ]
