# Generated by Django 4.2.23 on 2025-10-30 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("structure", "0066_alter_accesssubnet_options"),
        ("waldur_autoprovisioning", "0006_rule_project_name_template"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rule",
            name="customer",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="structure.customer",
            ),
        ),
        migrations.AddField(
            model_name="rule",
            name="use_user_organization_as_customer_name",
            field=models.BooleanField(default=False),
        ),
    ]
