# Generated by Django 4.2.18 on 2025-02-11 15:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    replaces = [
        ("waldur_auth_social", "0001_initial"),
        ("waldur_auth_social", "0002_remoteeduteamsuser"),
        ("waldur_auth_social", "0003_delete_remoteeduteamsuser"),
        ("waldur_auth_social", "0004_identityprovider"),
        ("waldur_auth_social", "0005_identityprovider_logout_url"),
        ("waldur_auth_social", "0006_identityprovider_enable_post_logout_redirect"),
        ("waldur_auth_social", "0007_identityprovider_enable_pkce"),
    ]

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OAuthToken",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("provider", models.CharField(max_length=32)),
                ("access_token", models.TextField()),
                ("refresh_token", models.TextField()),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="auth_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "provider")},
            },
        ),
        migrations.CreateModel(
            name="IdentityProvider",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("provider", models.CharField(max_length=32, unique=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "client_id",
                    models.CharField(
                        help_text="ID of application used for OAuth authentication.",
                        max_length=200,
                    ),
                ),
                (
                    "client_secret",
                    models.CharField(
                        help_text="Application secret key.", max_length=200
                    ),
                ),
                ("verify_ssl", models.BooleanField(default=True)),
                (
                    "discovery_url",
                    models.CharField(
                        help_text="The endpoint for endpoint discovery.", max_length=200
                    ),
                ),
                (
                    "userinfo_url",
                    models.CharField(
                        help_text="The endpoint for fetching user info.", max_length=200
                    ),
                ),
                (
                    "token_url",
                    models.CharField(
                        help_text="The endpoint for obtaining auth token.",
                        max_length=200,
                    ),
                ),
                (
                    "auth_url",
                    models.CharField(
                        help_text="The endpoint for authorization request flow.",
                        max_length=200,
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        help_text="Human-readable identity provider is label.",
                        max_length=200,
                    ),
                ),
                (
                    "management_url",
                    models.CharField(
                        blank=True,
                        help_text="The endpoint for user details management.",
                        max_length=200,
                    ),
                ),
                ("protected_fields", models.JSONField(default=list)),
                (
                    "logout_url",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="The endpoint used to redirect after sign-out.",
                        max_length=200,
                    ),
                ),
                ("enable_post_logout_redirect", models.BooleanField(default=True)),
                ("enable_pkce", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["label"],
            },
        ),
    ]
