# Generated by Django 6.0.8 on 2026-09-03 15:37

from importlib import import_module

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import waldur_core.core.migration_operations


def _original(name):
    """A replaced migration's module: its data code runs from there, unchanged."""
    return import_module(__name__.rpartition(".")[0] + "." + name)


class Migration(migrations.Migration):
    replaces = [
        ("waldur_auth_social", "0001_initial"),
        ("waldur_auth_social", "0002_remoteeduteamsuser"),
        ("waldur_auth_social", "0003_delete_remoteeduteamsuser"),
        ("waldur_auth_social", "0004_identityprovider"),
        ("waldur_auth_social", "0005_identityprovider_logout_url"),
        ("waldur_auth_social", "0006_identityprovider_enable_post_logout_redirect"),
        ("waldur_auth_social", "0007_identityprovider_enable_pkce"),
        ("waldur_auth_social", "0008_identityprovider_scope"),
        ("waldur_auth_social", "0009_identityprovider_attribute_mapping"),
        ("waldur_auth_social", "0010_apply_provider_defaults"),
        ("waldur_auth_social", "0011_fill_extra_scope"),
        ("waldur_auth_social", "0012_update_eduteams_user_claim_and_email"),
        ("waldur_auth_social", "0013_enable_notifications_for_eduteams_users"),
        ("waldur_auth_social", "0014_identityprovider_allowed_redirects"),
        ("waldur_auth_social", "0015_alter_identityprovider_options"),
    ]

    dependencies = [
        ("core", "0050_notificationtemplate_path_unique"),
        ("core", "__first__"),
    ]

    operations = [
        migrations.CreateModel(
            name="IdentityProvider",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("provider", models.CharField(max_length=32, unique=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "client_id",
                    models.CharField(
                        help_text="ID of application used for OAuth authentication.",
                        max_length=200,
                    ),
                ),
                (
                    "client_secret",
                    models.CharField(
                        help_text="Application secret key.", max_length=200
                    ),
                ),
                ("verify_ssl", models.BooleanField(default=True)),
                (
                    "discovery_url",
                    models.CharField(
                        help_text="The endpoint for endpoint discovery.", max_length=200
                    ),
                ),
                (
                    "userinfo_url",
                    models.CharField(
                        help_text="The endpoint for fetching user info.", max_length=200
                    ),
                ),
                (
                    "token_url",
                    models.CharField(
                        help_text="The endpoint for obtaining auth token.",
                        max_length=200,
                    ),
                ),
                (
                    "auth_url",
                    models.CharField(
                        help_text="The endpoint for authorization request flow.",
                        max_length=200,
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        help_text="Human-readable identity provider is label.",
                        max_length=200,
                    ),
                ),
                (
                    "management_url",
                    models.CharField(
                        blank=True,
                        help_text="The endpoint for user details management.",
                        max_length=200,
                    ),
                ),
                ("protected_fields", models.JSONField(default=list)),
                (
                    "logout_url",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="The endpoint used to redirect after sign-out.",
                        max_length=200,
                    ),
                ),
                ("enable_post_logout_redirect", models.BooleanField(default=True)),
                ("enable_pkce", models.BooleanField(default=False)),
                (
                    "scope",
                    models.CharField(
                        blank=True,
                        help_text="Space-separated list of scopes to request during authentication.",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "attribute_mapping",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='A JSON object mapping Waldur User model fields to OIDC claims. Example: {"first_name": "given_name", "last_name": "family_name", "email": "email"}',
                    ),
                ),
                (
                    "user_claim",
                    models.CharField(
                        default="sub",
                        help_text="The OIDC claim from the userinfo endpoint to be used as the value for the lookup field.",
                        max_length=100,
                    ),
                ),
                (
                    "user_field",
                    models.CharField(
                        default="username",
                        help_text="The field in Waldur User model to be used for looking up the user",
                        max_length=100,
                    ),
                ),
                (
                    "extra_fields",
                    models.CharField(
                        blank=True,
                        help_text="Space-separated list of extra fields to persist.",
                        max_length=200,
                        null=True,
                    ),
                ),
            ],
            options={
                "ordering": ["label"],
            },
        ),
        migrations.CreateModel(
            name="OAuthToken",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("provider", models.CharField(max_length=32)),
                ("access_token", models.TextField()),
                ("refresh_token", models.TextField()),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="auth_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "provider")},
            },
        ),
        waldur_core.core.migration_operations.FlushDeferredSql(),
        migrations.RunPython(
            code=_original("0010_apply_provider_defaults").apply_provider_defaults,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.RenameField(
            model_name="identityprovider",
            old_name="scope",
            new_name="extra_scope",
        ),
        waldur_core.core.migration_operations.FlushDeferredSql(),
        migrations.RunPython(
            code=_original("0011_fill_extra_scope").fill_eduteams_extra_scope,
        ),
        waldur_core.core.migration_operations.FlushDeferredSql(),
        migrations.RunPython(
            code=_original(
                "0012_update_eduteams_user_claim_and_email"
            ).update_eduteams_user_claim_and_email,
        ),
        waldur_core.core.migration_operations.FlushDeferredSql(),
        migrations.RunPython(
            code=_original(
                "0013_enable_notifications_for_eduteams_users"
            ).enable_notifications_for_eduteams_users,
        ),
        migrations.AlterModelOptions(
            name="identityprovider",
            options={"ordering": ["label", "id"]},
        ),
        migrations.AddField(
            model_name="identityprovider",
            name="allowed_redirects",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text='List of allowed redirect URLs for OAuth authentication. URLs must be exact matches (origin only: scheme + domain + port). HTTPS required except for localhost. No wildcards, paths, query params, or fragments. Example: ["https://portal1.example.com", "https://portal2.example.com:8443"]. If empty, falls back to HOMEPORT_URL setting.',
            ),
        ),
    ]
