# Generated by Django 2.2.24 on 2021-10-06 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('waldur_auth_social', '0002_remoteeduteamsuser'),
    ]

    operations = [
        migrations.DeleteModel(name='RemoteEduteamsUser',),
    ]
