# Generated by Django 6.0.8 on 2026-08-19 21:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("waldur_vmware", "0028_virtualmachine_is_available"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="disk",
            options={"ordering": ["-created", "id"]},
        ),
        migrations.AlterModelOptions(
            name="port",
            options={"ordering": ["-created", "id"]},
        ),
        migrations.AlterModelOptions(
            name="virtualmachine",
            options={"ordering": ["-created", "id"]},
        ),
    ]
