# Generated by Django 6.0.8 on 2026-09-16 14:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("waldur_vmware", "0001_squashed_0029"),
    ]

    operations = [
        migrations.AlterField(
            model_name="datastore",
            name="capacity",
            field=models.PositiveBigIntegerField(
                blank=True, help_text="Capacity, in MB.", null=True
            ),
        ),
        migrations.AlterField(
            model_name="datastore",
            name="free_space",
            field=models.PositiveBigIntegerField(
                blank=True, help_text="Available space, in MB.", null=True
            ),
        ),
    ]
