# Generated by Django 4.2.14 on 2024-09-07 18:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("structure", "0046_project_start_date"),
        ("openstack", "0034_image_tenant"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="flavor",
            unique_together={("settings", "backend_id")},
        ),
        migrations.RemoveField(
            model_name="flavor",
            name="error_message",
        ),
        migrations.RemoveField(
            model_name="flavor",
            name="error_traceback",
        ),
        migrations.RemoveField(
            model_name="flavor",
            name="state",
        ),
    ]
