# Generated by Django 6.0.2 on 2026-03-06 15:08

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import django_fsm
import model_utils.fields
from django.db import migrations, models

import waldur_core.core.fields
import waldur_core.core.models
import waldur_core.core.validators
import waldur_core.structure.models

# Functions from the following migrations need manual copying.
# Move them and any dependencies into this file, then update the
# RunPython operations to refer to the local versions:
# waldur_openstack.migrations.0044_floatingip_external_address
# waldur_openstack.migrations.0045_floatingip_external_address
# waldur_openstack.migrations.0051_alter_port_admin_state_up
# waldur_openstack.migrations.0053_remove_duplicates
# waldur_openstack.migrations.0065_populate_external_network_refs


class Migration(migrations.Migration):
    replaces = [
        ("openstack", "0040_volume_type_disabled"),
        ("openstack", "0041_fix_primary_key_sequences"),
        ("openstack", "0042_instance_task_id_snapshot_task_id_tenant_action_and_more"),
        ("openstack", "0043_alter_backup_options_alter_port_options_and_more"),
        ("openstack", "0044_floatingip_external_address"),
        ("openstack", "0045_floatingip_external_address"),
        ("openstack", "0046_remove_snapshot_schedule"),
        ("openstack", "0047_alter_backup_state_alter_floatingip_state_and_more"),
        ("openstack", "0048_networkrbacpolicy"),
        ("openstack", "0049_port_runtime_state"),
        ("openstack", "0050_port_status"),
        ("openstack", "0051_alter_port_admin_state_up"),
        ("openstack", "0052_router_ports"),
        ("openstack", "0053_remove_duplicates"),
        ("openstack", "0054_add_constraint"),
        ("openstack", "0055_nullable_backend_id"),
        ("openstack", "0056_alter_router_backend_id"),
        ("openstack", "0057_tenant_update_triggered"),
        ("openstack", "0058_alter_backup_instance_alter_backup_snapshots_and_more"),
        ("openstack", "0059_alter_instanceavailabilityzone_tenant"),
        ("openstack", "0060_alter_backup_description_and_more"),
        ("openstack", "0061_instance_is_available_tenant_is_available_and_more"),
        ("openstack", "0062_tenant_skip_router"),
        ("openstack", "0063_image_backend_created_at"),
        ("openstack", "0064_external_network_models"),
        ("openstack", "0065_populate_external_network_refs"),
        ("openstack", "0066_server_group_policies"),
        ("openstack", "0067_loadbalancer"),
    ]

    dependencies = [
        ("marketplace", "0145_clean_price_logs"),
        ("openstack", "0039_remove_old_instance"),
        ("structure", "0056_customer_project_metadata_checklist"),
        ("structure", "0073_alter_projectdigestconfiguration_uuid"),
    ]

    operations = [
        migrations.AddField(
            model_name="volumetype",
            name="disabled",
            field=models.BooleanField(default=False),
        ),
        migrations.RunSQL(
            sql=[
                "SELECT setval(pg_get_serial_sequence('openstack_backup', 'id'), (SELECT MAX(id) FROM openstack_backup) + 1);",
                "SELECT setval(pg_get_serial_sequence('openstack_backuprestoration', 'id'), (SELECT MAX(id) FROM openstack_backuprestoration) + 1);",
                "SELECT setval(pg_get_serial_sequence('openstack_flavor', 'id'), (SELECT MAX(id) FROM openstack_flavor) + 1);",
                "SELECT setval(pg_get_serial_sequence('openstack_image', 'id'), (SELECT MAX(id) FROM openstack_image) + 1);",
                "SELECT setval(pg_get_serial_sequence('openstack_instance', 'id'), (SELECT MAX(id) FROM openstack_instance) + 1);",
                "SELECT setval(pg_get_serial_sequence('openstack_instanceavailabilityzone', 'id'), (SELECT MAX(id) FROM openstack_instanceavailabilityzone) + 1);",
                "SELECT setval(pg_get_serial_sequence('openstack_securitygroup', 'id'), (SELECT MAX(id) FROM openstack_securitygroup) + 1);",
                "SELECT setval(pg_get_serial_sequence('openstack_servergroup', 'id'), (SELECT MAX(id) FROM openstack_servergroup) + 1);",
                "SELECT setval(pg_get_serial_sequence('openstack_snapshot', 'id'), (SELECT MAX(id) FROM openstack_snapshot) + 1);",
                "SELECT setval(pg_get_serial_sequence('openstack_snapshotrestoration', 'id'), (SELECT MAX(id) FROM openstack_snapshotrestoration) + 1);",
                "SELECT setval(pg_get_serial_sequence('openstack_volume', 'id'), (SELECT MAX(id) FROM openstack_volume) + 1);",
                "SELECT setval(pg_get_serial_sequence('openstack_volumeavailabilityzone', 'id'), (SELECT MAX(id) FROM openstack_volumeavailabilityzone) + 1);",
                "SELECT setval(pg_get_serial_sequence('openstack_volumetype', 'id'), (SELECT MAX(id) FROM openstack_volumetype) + 1);",
            ],
        ),
        migrations.AddField(
            model_name="instance",
            name="task_id",
            field=models.CharField(blank=True, max_length=155, null=True),
        ),
        migrations.AddField(
            model_name="snapshot",
            name="task_id",
            field=models.CharField(blank=True, max_length=155, null=True),
        ),
        migrations.AddField(
            model_name="tenant",
            name="action",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="tenant",
            name="action_details",
            field=waldur_core.core.fields.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="tenant",
            name="task_id",
            field=models.CharField(blank=True, max_length=155, null=True),
        ),
        migrations.AddField(
            model_name="volume",
            name="task_id",
            field=models.CharField(blank=True, max_length=155, null=True),
        ),
        migrations.AlterModelOptions(
            name="backup",
            options={"ordering": ["-created"]},
        ),
        migrations.AlterModelOptions(
            name="port",
            options={"ordering": ["-created"]},
        ),
        migrations.AlterModelOptions(
            name="router",
            options={"ordering": ["-created"]},
        ),
        migrations.AlterModelOptions(
            name="securitygroup",
            options={"ordering": ["-created"]},
        ),
        migrations.AlterModelOptions(
            name="servergroup",
            options={"ordering": ["-created"]},
        ),
        migrations.AddField(
            model_name="floatingip",
            name="external_address",
            field=models.JSONField(
                default=list,
                editable=False,
                help_text="An optional address that maps to floating IP's address",
            ),
        ),
        migrations.RunPython(migrations.RunPython.noop, migrations.RunPython.noop),
        migrations.RenameField(
            model_name="floatingip",
            old_name="external_address",
            new_name="external_address_old",
        ),
        migrations.AddField(
            model_name="floatingip",
            name="external_address",
            field=models.GenericIPAddressField(
                editable=False,
                help_text="An optional address that maps to floating IP's address",
                null=True,
            ),
        ),
        migrations.RunPython(migrations.RunPython.noop, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="floatingip",
            name="external_address_old",
        ),
        migrations.RemoveField(
            model_name="snapshot",
            name="snapshot_schedule",
        ),
        migrations.RemoveField(
            model_name="backup",
            name="backup_schedule",
        ),
        migrations.DeleteModel(
            name="SnapshotSchedule",
        ),
        migrations.DeleteModel(
            name="BackupSchedule",
        ),
        migrations.AlterField(
            model_name="backup",
            name="state",
            field=django_fsm.FSMIntegerField(
                choices=[
                    (5, "CREATION_SCHEDULED"),
                    (6, "CREATING"),
                    (1, "UPDATE_SCHEDULED"),
                    (2, "UPDATING"),
                    (7, "DELETION_SCHEDULED"),
                    (8, "DELETING"),
                    (3, "OK"),
                    (4, "ERRED"),
                ],
                default=5,
            ),
        ),
        migrations.AlterField(
            model_name="floatingip",
            name="state",
            field=django_fsm.FSMIntegerField(
                choices=[
                    (5, "CREATION_SCHEDULED"),
                    (6, "CREATING"),
                    (1, "UPDATE_SCHEDULED"),
                    (2, "UPDATING"),
                    (7, "DELETION_SCHEDULED"),
                    (8, "DELETING"),
                    (3, "OK"),
                    (4, "ERRED"),
                ],
                default=5,
            ),
        ),
        migrations.AlterField(
            model_name="instance",
            name="state",
            field=django_fsm.FSMIntegerField(
                choices=[
                    (5, "CREATION_SCHEDULED"),
                    (6, "CREATING"),
                    (1, "UPDATE_SCHEDULED"),
                    (2, "UPDATING"),
                    (7, "DELETION_SCHEDULED"),
                    (8, "DELETING"),
                    (3, "OK"),
                    (4, "ERRED"),
                ],
                default=5,
            ),
        ),
        migrations.AlterField(
            model_name="network",
            name="state",
            field=django_fsm.FSMIntegerField(
                choices=[
                    (5, "CREATION_SCHEDULED"),
                    (6, "CREATING"),
                    (1, "UPDATE_SCHEDULED"),
                    (2, "UPDATING"),
                    (7, "DELETION_SCHEDULED"),
                    (8, "DELETING"),
                    (3, "OK"),
                    (4, "ERRED"),
                ],
                default=5,
            ),
        ),
        migrations.AlterField(
            model_name="port",
            name="state",
            field=django_fsm.FSMIntegerField(
                choices=[
                    (5, "CREATION_SCHEDULED"),
                    (6, "CREATING"),
                    (1, "UPDATE_SCHEDULED"),
                    (2, "UPDATING"),
                    (7, "DELETION_SCHEDULED"),
                    (8, "DELETING"),
                    (3, "OK"),
                    (4, "ERRED"),
                ],
                default=5,
            ),
        ),
        migrations.AlterField(
            model_name="router",
            name="state",
            field=django_fsm.FSMIntegerField(
                choices=[
                    (5, "CREATION_SCHEDULED"),
                    (6, "CREATING"),
                    (1, "UPDATE_SCHEDULED"),
                    (2, "UPDATING"),
                    (7, "DELETION_SCHEDULED"),
                    (8, "DELETING"),
                    (3, "OK"),
                    (4, "ERRED"),
                ],
                default=5,
            ),
        ),
        migrations.AlterField(
            model_name="securitygroup",
            name="state",
            field=django_fsm.FSMIntegerField(
                choices=[
                    (5, "CREATION_SCHEDULED"),
                    (6, "CREATING"),
                    (1, "UPDATE_SCHEDULED"),
                    (2, "UPDATING"),
                    (7, "DELETION_SCHEDULED"),
                    (8, "DELETING"),
                    (3, "OK"),
                    (4, "ERRED"),
                ],
                default=5,
            ),
        ),
        migrations.AlterField(
            model_name="servergroup",
            name="state",
            field=django_fsm.FSMIntegerField(
                choices=[
                    (5, "CREATION_SCHEDULED"),
                    (6, "CREATING"),
                    (1, "UPDATE_SCHEDULED"),
                    (2, "UPDATING"),
                    (7, "DELETION_SCHEDULED"),
                    (8, "DELETING"),
                    (3, "OK"),
                    (4, "ERRED"),
                ],
                default=5,
            ),
        ),
        migrations.AlterField(
            model_name="snapshot",
            name="state",
            field=django_fsm.FSMIntegerField(
                choices=[
                    (5, "CREATION_SCHEDULED"),
                    (6, "CREATING"),
                    (1, "UPDATE_SCHEDULED"),
                    (2, "UPDATING"),
                    (7, "DELETION_SCHEDULED"),
                    (8, "DELETING"),
                    (3, "OK"),
                    (4, "ERRED"),
                ],
                default=5,
            ),
        ),
        migrations.AlterField(
            model_name="subnet",
            name="state",
            field=django_fsm.FSMIntegerField(
                choices=[
                    (5, "CREATION_SCHEDULED"),
                    (6, "CREATING"),
                    (1, "UPDATE_SCHEDULED"),
                    (2, "UPDATING"),
                    (7, "DELETION_SCHEDULED"),
                    (8, "DELETING"),
                    (3, "OK"),
                    (4, "ERRED"),
                ],
                default=5,
            ),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="state",
            field=django_fsm.FSMIntegerField(
                choices=[
                    (5, "CREATION_SCHEDULED"),
                    (6, "CREATING"),
                    (1, "UPDATE_SCHEDULED"),
                    (2, "UPDATING"),
                    (7, "DELETION_SCHEDULED"),
                    (8, "DELETING"),
                    (3, "OK"),
                    (4, "ERRED"),
                ],
                default=5,
            ),
        ),
        migrations.AlterField(
            model_name="volume",
            name="state",
            field=django_fsm.FSMIntegerField(
                choices=[
                    (5, "CREATION_SCHEDULED"),
                    (6, "CREATING"),
                    (1, "UPDATE_SCHEDULED"),
                    (2, "UPDATING"),
                    (7, "DELETION_SCHEDULED"),
                    (8, "DELETING"),
                    (3, "OK"),
                    (4, "ERRED"),
                ],
                default=5,
            ),
        ),
        migrations.CreateModel(
            name="NetworkRBACPolicy",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("uuid", waldur_core.core.fields.UUIDField()),
                ("backend_id", models.CharField(blank=True, max_length=255)),
                (
                    "policy_type",
                    models.CharField(
                        choices=[
                            ("access_as_shared", "Shared"),
                            ("access_as_external", "External"),
                        ],
                        default="access_as_shared",
                        max_length=255,
                    ),
                ),
                (
                    "network",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rbac_policies",
                        to="openstack.network",
                    ),
                ),
                (
                    "target_tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="network_rbac_policies",
                        to="openstack.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Network RBAC Policy",
                "verbose_name_plural": "Network RBAC Policies",
                "ordering": ["-created"],
                "unique_together": {("network", "target_tenant", "policy_type")},
            },
        ),
        migrations.AddField(
            model_name="port",
            name="admin_state_up",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="port",
            name="status",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.RunPython(migrations.RunPython.noop, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="port",
            name="admin_state_up",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.RunPython(migrations.RunPython.noop, migrations.RunPython.noop),
        migrations.AddField(
            model_name="router",
            name="ports",
            field=models.ManyToManyField(
                blank=True, related_name="routers", to="openstack.port"
            ),
        ),
        migrations.RunPython(migrations.RunPython.noop, migrations.RunPython.noop),
        migrations.RunPython(migrations.RunPython.noop, migrations.RunPython.noop),
        migrations.AlterUniqueTogether(
            name="port",
            unique_together={("tenant", "backend_id")},
        ),
        migrations.AlterUniqueTogether(
            name="router",
            unique_together={("tenant", "backend_id")},
        ),
        migrations.AlterField(
            model_name="port",
            name="backend_id",
            field=models.CharField(
                blank=True, help_text="Port ID in OpenStack", max_length=255, null=True
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="update_triggered",
            field=models.DateTimeField(
                blank=True,
                help_text="Timestamp of when tenant update was last triggered",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="backup",
            name="instance",
            field=models.ForeignKey(
                help_text="Instance that this backup is created from",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="backups",
                to="openstack.instance",
            ),
        ),
        migrations.AlterField(
            model_name="backup",
            name="snapshots",
            field=models.ManyToManyField(
                help_text="Snapshots that comprise this backup",
                related_name="backups",
                to="openstack.snapshot",
            ),
        ),
        migrations.AlterField(
            model_name="backup",
            name="tenant",
            field=models.ForeignKey(
                help_text="OpenStack tenant this backup belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="backups",
                to="openstack.tenant",
            ),
        ),
        migrations.AlterField(
            model_name="backuprestoration",
            name="backup",
            field=models.ForeignKey(
                help_text="Backup from which the instance is being restored",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="restorations",
                to="openstack.backup",
            ),
        ),
        migrations.AlterField(
            model_name="backuprestoration",
            name="flavor",
            field=models.ForeignKey(
                blank=True,
                help_text="Flavor to be used for the restored instance. If not specified, original instance flavor will be used",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="openstack.flavor",
            ),
        ),
        migrations.AlterField(
            model_name="backuprestoration",
            name="instance",
            field=models.OneToOneField(
                help_text="Instance that is being restored from the backup",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="openstack.instance",
            ),
        ),
        migrations.AlterField(
            model_name="floatingip",
            name="address",
            field=models.GenericIPAddressField(
                blank=True,
                default=None,
                help_text="The public IPv4 address of the floating IP",
                null=True,
                protocol="IPv4",
            ),
        ),
        migrations.AlterField(
            model_name="floatingip",
            name="backend_network_id",
            field=models.CharField(
                editable=False,
                help_text="ID of network in OpenStack where this floating IP is allocated",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="floatingip",
            name="external_address",
            field=models.GenericIPAddressField(
                editable=False,
                help_text="Optional address that maps to floating IP's address in external networks",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="floatingip",
            name="port",
            field=models.ForeignKey(
                blank=True,
                help_text="OpenStack port this floating IP is associated with",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="floating_ips",
                to="openstack.port",
            ),
        ),
        migrations.AlterField(
            model_name="floatingip",
            name="tenant",
            field=models.ForeignKey(
                help_text="OpenStack tenant this floating IP belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="floating_ips",
                to="openstack.tenant",
            ),
        ),
        migrations.AlterField(
            model_name="instance",
            name="availability_zone",
            field=models.ForeignKey(
                blank=True,
                help_text="Availability zone where this instance is located",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="openstack.instanceavailabilityzone",
            ),
        ),
        migrations.AlterField(
            model_name="instance",
            name="backend_id",
            field=models.CharField(
                blank=True,
                help_text="Instance ID in the OpenStack backend",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="instance",
            name="connect_directly_to_external_network",
            field=models.BooleanField(
                default=False,
                help_text="If True, instance will be connected directly to external network",
            ),
        ),
        migrations.AlterField(
            model_name="instance",
            name="directly_connected_ips",
            field=models.CharField(
                blank=True,
                help_text="Comma-separated list of directly connected IP addresses",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="instance",
            name="flavor_name",
            field=models.CharField(
                blank=True,
                help_text="Name of the flavor used by this instance",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="instance",
            name="hypervisor_hostname",
            field=models.CharField(
                blank=True,
                help_text="Name of the hypervisor hosting this instance",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="instance",
            name="security_groups",
            field=models.ManyToManyField(
                blank=True,
                help_text="Security groups attached to this instance",
                related_name="instances",
                to="openstack.securitygroup",
            ),
        ),
        migrations.AlterField(
            model_name="instance",
            name="server_group",
            field=models.ForeignKey(
                blank=True,
                help_text="Server group this instance belongs to",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="openstack.servergroup",
            ),
        ),
        migrations.AlterField(
            model_name="instance",
            name="subnets",
            field=models.ManyToManyField(
                help_text="Subnets connected to this instance through ports",
                through="openstack.Port",
                to="openstack.subnet",
            ),
        ),
        migrations.AlterField(
            model_name="instance",
            name="tenant",
            field=models.ForeignKey(
                help_text="OpenStack tenant this instance belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="instances",
                to="openstack.tenant",
            ),
        ),
        migrations.AlterField(
            model_name="instanceavailabilityzone",
            name="available",
            field=models.BooleanField(
                default=True,
                help_text="Indicates whether this availability zone is available for instance provisioning",
            ),
        ),
        migrations.AlterField(
            model_name="instanceavailabilityzone",
            name="settings",
            field=models.ForeignKey(
                help_text="Service settings for this availability zone",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="structure.servicesettings",
            ),
        ),
        migrations.AlterField(
            model_name="network",
            name="is_external",
            field=models.BooleanField(
                default=False,
                help_text="Defines whether this network is external (public) or internal (private)",
            ),
        ),
        migrations.AlterField(
            model_name="network",
            name="segmentation_id",
            field=models.IntegerField(
                help_text="VLAN ID for VLAN networks or tunnel ID for VXLAN/GRE networks",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="network",
            name="tenant",
            field=models.ForeignKey(
                help_text="OpenStack tenant this network belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="networks",
                to="openstack.tenant",
            ),
        ),
        migrations.AlterField(
            model_name="network",
            name="type",
            field=models.CharField(
                blank=True,
                help_text="Network type, such as local, flat, vlan, vxlan, or gre",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="networkrbacpolicy",
            name="network",
            field=models.ForeignKey(
                help_text="Network that this RBAC policy applies to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rbac_policies",
                to="openstack.network",
            ),
        ),
        migrations.AlterField(
            model_name="networkrbacpolicy",
            name="policy_type",
            field=models.CharField(
                choices=[
                    ("access_as_shared", "Shared"),
                    ("access_as_external", "External"),
                ],
                default="access_as_shared",
                help_text="Type of access granted - either shared access or external network access",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="networkrbacpolicy",
            name="target_tenant",
            field=models.ForeignKey(
                help_text="Tenant that is granted access to the network through this policy",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="network_rbac_policies",
                to="openstack.tenant",
            ),
        ),
        migrations.AlterField(
            model_name="port",
            name="admin_state_up",
            field=models.BooleanField(
                blank=True,
                help_text="Administrative state of the port. If down, port does not forward packets",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="port",
            name="device_id",
            field=models.CharField(
                blank=True,
                help_text="ID of device (instance, router etc) to which this port is connected",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="port",
            name="device_owner",
            field=models.CharField(
                blank=True,
                help_text="Entity that uses this port (e.g. network:router_interface)",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="port",
            name="instance",
            field=models.ForeignKey(
                blank=True,
                help_text="Instance to which this port is attached",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ports",
                to="openstack.instance",
            ),
        ),
        migrations.AlterField(
            model_name="port",
            name="mac_address",
            field=models.CharField(
                blank=True, help_text="MAC address of the port", max_length=32
            ),
        ),
        migrations.AlterField(
            model_name="port",
            name="network",
            field=models.ForeignKey(
                blank=True,
                help_text="Network to which this port belongs",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ports",
                to="openstack.network",
            ),
        ),
        migrations.AlterField(
            model_name="port",
            name="port_security_enabled",
            field=models.BooleanField(
                default=True,
                help_text="If True, security groups and rules will be applied to this port",
            ),
        ),
        migrations.AlterField(
            model_name="port",
            name="security_groups",
            field=models.ManyToManyField(
                help_text="Security groups associated with this port",
                related_name="ports",
                to="openstack.securitygroup",
            ),
        ),
        migrations.AlterField(
            model_name="port",
            name="status",
            field=models.CharField(
                blank=True,
                help_text="Port status in OpenStack (e.g. ACTIVE, DOWN)",
                max_length=30,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="port",
            name="subnet",
            field=models.ForeignKey(
                blank=True,
                help_text="Subnet to which this port belongs",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ports",
                to="openstack.subnet",
            ),
        ),
        migrations.AlterField(
            model_name="port",
            name="tenant",
            field=models.ForeignKey(
                help_text="OpenStack tenant this port belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ports",
                to="openstack.tenant",
            ),
        ),
        migrations.AlterField(
            model_name="router",
            name="backend_id",
            field=models.CharField(
                blank=True,
                help_text="Router ID in OpenStack",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="router",
            name="fixed_ips",
            field=waldur_core.core.fields.JSONField(
                default=list,
                help_text="List of fixed IP addresses assigned to the router interfaces",
            ),
        ),
        migrations.AlterField(
            model_name="router",
            name="ports",
            field=models.ManyToManyField(
                blank=True,
                help_text="Network ports attached to this router",
                related_name="routers",
                to="openstack.port",
            ),
        ),
        migrations.AlterField(
            model_name="router",
            name="routes",
            field=waldur_core.core.fields.JSONField(
                default=list, help_text="List of routes configured on the router"
            ),
        ),
        migrations.AlterField(
            model_name="router",
            name="tenant",
            field=models.ForeignKey(
                help_text="OpenStack tenant this router belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="routers",
                to="openstack.tenant",
            ),
        ),
        migrations.AlterField(
            model_name="securitygrouprule",
            name="backend_id",
            field=models.CharField(
                blank=True,
                help_text="ID of the security group rule in the OpenStack backend",
                max_length=36,
            ),
        ),
        migrations.AlterField(
            model_name="securitygrouprule",
            name="cidr",
            field=models.CharField(
                blank=True,
                help_text="CIDR notation for the source/destination network address range",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="securitygrouprule",
            name="direction",
            field=models.CharField(
                choices=[("ingress", "ingress"), ("egress", "egress")],
                default="ingress",
                help_text="Traffic direction - either 'ingress' (incoming) or 'egress' (outgoing)",
                max_length=8,
            ),
        ),
        migrations.AlterField(
            model_name="securitygrouprule",
            name="ethertype",
            field=models.CharField(
                choices=[("IPv4", "IPv4"), ("IPv6", "IPv6")],
                default="IPv4",
                help_text="IP protocol version - either 'IPv4' or 'IPv6'",
                max_length=40,
            ),
        ),
        migrations.AlterField(
            model_name="securitygrouprule",
            name="from_port",
            field=models.IntegerField(
                help_text="Starting port number in the range (1-65535)",
                null=True,
                validators=[django.core.validators.MaxValueValidator(65535)],
            ),
        ),
        migrations.AlterField(
            model_name="securitygrouprule",
            name="protocol",
            field=models.CharField(
                blank=True,
                choices=[("tcp", "tcp"), ("udp", "udp"), ("icmp", "icmp")],
                help_text="The network protocol (TCP, UDP, ICMP, or empty for any protocol)",
                max_length=40,
            ),
        ),
        migrations.AlterField(
            model_name="securitygrouprule",
            name="remote_group",
            field=models.ForeignKey(
                blank=True,
                help_text="Remote security group that this rule references, if any",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="openstack.securitygroup",
            ),
        ),
        migrations.AlterField(
            model_name="securitygrouprule",
            name="security_group",
            field=models.ForeignKey(
                help_text="Security group this rule belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rules",
                to="openstack.securitygroup",
            ),
        ),
        migrations.AlterField(
            model_name="securitygrouprule",
            name="to_port",
            field=models.IntegerField(
                help_text="Ending port number in the range (1-65535)",
                null=True,
                validators=[django.core.validators.MaxValueValidator(65535)],
            ),
        ),
        migrations.AlterField(
            model_name="servergroup",
            name="policy",
            field=models.CharField(
                blank=True,
                choices=[("affinity", "Affinity")],
                help_text="Server group policy determining the rules for scheduling servers in this group",
                max_length=40,
            ),
        ),
        migrations.AlterField(
            model_name="snapshot",
            name="backend_id",
            field=models.CharField(
                blank=True,
                help_text="Snapshot ID in the OpenStack backend",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="snapshot",
            name="metadata",
            field=waldur_core.core.fields.JSONField(
                blank=True,
                help_text="Additional information about the snapshot stored as key-value pairs",
            ),
        ),
        migrations.AlterField(
            model_name="snapshot",
            name="source_volume",
            field=models.ForeignKey(
                help_text="Volume from which this snapshot was created",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="snapshots",
                to="openstack.volume",
            ),
        ),
        migrations.AlterField(
            model_name="snapshot",
            name="tenant",
            field=models.ForeignKey(
                help_text="OpenStack tenant this snapshot belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="snapshots",
                to="openstack.tenant",
            ),
        ),
        migrations.AlterField(
            model_name="snapshotrestoration",
            name="snapshot",
            field=models.ForeignKey(
                help_text="Snapshot from which the volume is being restored",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="restorations",
                to="openstack.snapshot",
            ),
        ),
        migrations.AlterField(
            model_name="snapshotrestoration",
            name="volume",
            field=models.OneToOneField(
                help_text="Volume that is being restored from the snapshot",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="restoration",
                to="openstack.volume",
            ),
        ),
        migrations.AlterField(
            model_name="subnet",
            name="allocation_pools",
            field=waldur_core.core.fields.JSONField(
                default=dict,
                help_text="List of IP ranges available for allocation in this subnet",
            ),
        ),
        migrations.AlterField(
            model_name="subnet",
            name="cidr",
            field=models.CharField(
                blank=True,
                help_text="IPv4 network address in CIDR format (e.g. 192.168.0.0/24)",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="subnet",
            name="disable_gateway",
            field=models.BooleanField(
                default=False,
                help_text="If True, no gateway IP address will be allocated",
            ),
        ),
        migrations.AlterField(
            model_name="subnet",
            name="enable_dhcp",
            field=models.BooleanField(
                default=True,
                help_text="If True, DHCP service will be enabled on this subnet",
            ),
        ),
        migrations.AlterField(
            model_name="subnet",
            name="gateway_ip",
            field=models.GenericIPAddressField(
                help_text="IP address of the gateway for this subnet",
                null=True,
                protocol="IPv4",
            ),
        ),
        migrations.AlterField(
            model_name="subnet",
            name="ip_version",
            field=models.SmallIntegerField(
                default=4, help_text="IP protocol version (4 or 6)"
            ),
        ),
        migrations.AlterField(
            model_name="subnet",
            name="network",
            field=models.ForeignKey(
                help_text="Network to which this subnet belongs",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subnets",
                to="openstack.network",
            ),
        ),
        migrations.AlterField(
            model_name="subnet",
            name="tenant",
            field=models.ForeignKey(
                help_text="OpenStack tenant this subnet belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="openstack.tenant",
            ),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="backend_id",
            field=models.CharField(
                blank=True,
                help_text="ID of tenant in the OpenStack backend",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="external_network_id",
            field=models.CharField(
                blank=True,
                help_text="ID of external network connected to OpenStack tenant",
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="internal_network_id",
            field=models.CharField(
                blank=True,
                help_text="ID of internal network in OpenStack tenant",
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="user_password",
            field=models.CharField(
                blank=True, help_text="Password of the tenant user", max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="user_username",
            field=models.CharField(
                blank=True, help_text="Username of the tenant user", max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="volume",
            name="availability_zone",
            field=models.ForeignKey(
                blank=True,
                help_text="Availability zone where this volume is located",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="openstack.volumeavailabilityzone",
            ),
        ),
        migrations.AlterField(
            model_name="volume",
            name="backend_id",
            field=models.CharField(
                blank=True,
                help_text="Volume ID in the OpenStack backend",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="volume",
            name="bootable",
            field=models.BooleanField(
                default=False,
                help_text="Indicates if this volume can be used to boot an instance",
            ),
        ),
        migrations.AlterField(
            model_name="volume",
            name="image",
            field=models.ForeignKey(
                blank=True,
                help_text="Image that this volume was created from, if any",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="openstack.image",
            ),
        ),
        migrations.AlterField(
            model_name="volume",
            name="image_metadata",
            field=waldur_core.core.fields.JSONField(
                blank=True,
                help_text="Metadata of the image this volume was created from",
            ),
        ),
        migrations.AlterField(
            model_name="volume",
            name="image_name",
            field=models.CharField(
                blank=True,
                help_text="Name of the image this volume was created from",
                max_length=150,
            ),
        ),
        migrations.AlterField(
            model_name="volume",
            name="instance",
            field=models.ForeignKey(
                blank=True,
                help_text="Instance that this volume is attached to, if any",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="volumes",
                to="openstack.instance",
            ),
        ),
        migrations.AlterField(
            model_name="volume",
            name="metadata",
            field=waldur_core.core.fields.JSONField(
                blank=True,
                help_text="Arbitrary key-value pairs associated with the volume",
            ),
        ),
        migrations.AlterField(
            model_name="volume",
            name="source_snapshot",
            field=models.ForeignKey(
                blank=True,
                help_text="Snapshot that this volume was created from, if any",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="volumes",
                to="openstack.snapshot",
            ),
        ),
        migrations.AlterField(
            model_name="volume",
            name="tenant",
            field=models.ForeignKey(
                help_text="OpenStack tenant this volume belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="volumes",
                to="openstack.tenant",
            ),
        ),
        migrations.AlterField(
            model_name="volume",
            name="type",
            field=models.ForeignKey(
                blank=True,
                help_text="Type of the volume (e.g. SSD, HDD)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="openstack.volumetype",
            ),
        ),
        migrations.AlterField(
            model_name="instanceavailabilityzone",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                help_text="OpenStack tenant this availability zone belongs to",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="instance_availability_zones",
                to="openstack.tenant",
            ),
        ),
        migrations.AlterField(
            model_name="volumeavailabilityzone",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="volume_availability_zones",
                to="openstack.tenant",
            ),
        ),
        migrations.AlterField(
            model_name="backup",
            name="description",
            field=models.CharField(
                blank=True, max_length=4096, verbose_name="description"
            ),
        ),
        migrations.AlterField(
            model_name="floatingip",
            name="description",
            field=models.CharField(
                blank=True, max_length=4096, verbose_name="description"
            ),
        ),
        migrations.AlterField(
            model_name="instance",
            name="description",
            field=models.CharField(
                blank=True, max_length=4096, verbose_name="description"
            ),
        ),
        migrations.AlterField(
            model_name="network",
            name="description",
            field=models.CharField(
                blank=True, max_length=4096, verbose_name="description"
            ),
        ),
        migrations.AlterField(
            model_name="port",
            name="description",
            field=models.CharField(
                blank=True, max_length=4096, verbose_name="description"
            ),
        ),
        migrations.AlterField(
            model_name="router",
            name="description",
            field=models.CharField(
                blank=True, max_length=4096, verbose_name="description"
            ),
        ),
        migrations.AlterField(
            model_name="securitygroup",
            name="description",
            field=models.CharField(
                blank=True, max_length=4096, verbose_name="description"
            ),
        ),
        migrations.AlterField(
            model_name="securitygrouprule",
            name="description",
            field=models.CharField(
                blank=True, max_length=4096, verbose_name="description"
            ),
        ),
        migrations.AlterField(
            model_name="servergroup",
            name="description",
            field=models.CharField(
                blank=True, max_length=4096, verbose_name="description"
            ),
        ),
        migrations.AlterField(
            model_name="snapshot",
            name="description",
            field=models.CharField(
                blank=True, max_length=4096, verbose_name="description"
            ),
        ),
        migrations.AlterField(
            model_name="subnet",
            name="description",
            field=models.CharField(
                blank=True, max_length=4096, verbose_name="description"
            ),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="description",
            field=models.CharField(
                blank=True, max_length=4096, verbose_name="description"
            ),
        ),
        migrations.AlterField(
            model_name="volume",
            name="description",
            field=models.CharField(
                blank=True, max_length=4096, verbose_name="description"
            ),
        ),
        migrations.AlterField(
            model_name="volumetype",
            name="description",
            field=models.CharField(
                blank=True, max_length=4096, verbose_name="description"
            ),
        ),
        migrations.AddField(
            model_name="instance",
            name="can_be_managed",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="tenant",
            name="can_be_managed",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="volume",
            name="can_be_managed",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="tenant",
            name="skip_creation_of_default_router",
            field=models.BooleanField(
                default=False,
                help_text="If True, default router will not be created for this tenant",
            ),
        ),
        migrations.AddField(
            model_name="image",
            name="backend_created_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="ExternalNetwork",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=4096, verbose_name="description"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=150,
                        validators=[waldur_core.core.validators.validate_name],
                        verbose_name="name",
                    ),
                ),
                ("uuid", waldur_core.core.fields.UUIDField()),
                ("backend_id", models.CharField(db_index=True, max_length=255)),
                ("is_shared", models.BooleanField(default=False)),
                ("is_default", models.BooleanField(default=False)),
                ("status", models.CharField(blank=True, max_length=30)),
                (
                    "settings",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="structure.servicesettings",
                    ),
                ),
            ],
            options={
                "unique_together": {("settings", "backend_id")},
            },
            bases=(waldur_core.core.models.BackendModelMixin, models.Model),
        ),
        migrations.AddField(
            model_name="customeropenstack",
            name="external_network_ref",
            field=models.ForeignKey(
                blank=True,
                help_text="External network for this customer",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="customer_openstack_settings",
                to="openstack.externalnetwork",
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="external_network_ref",
            field=models.ForeignKey(
                blank=True,
                help_text="External network connected to OpenStack tenant",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tenants",
                to="openstack.externalnetwork",
            ),
        ),
        migrations.CreateModel(
            name="ExternalSubnet",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=4096, verbose_name="description"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=150,
                        validators=[waldur_core.core.validators.validate_name],
                        verbose_name="name",
                    ),
                ),
                ("uuid", waldur_core.core.fields.UUIDField()),
                ("backend_id", models.CharField(db_index=True, max_length=255)),
                ("cidr", models.CharField(blank=True, max_length=32)),
                ("gateway_ip", models.GenericIPAddressField(blank=True, null=True)),
                ("ip_version", models.SmallIntegerField(default=4)),
                ("enable_dhcp", models.BooleanField(default=True)),
                ("allocation_pools", models.JSONField(blank=True, default=list)),
                ("dns_nameservers", models.JSONField(blank=True, default=list)),
                (
                    "public_ip_range",
                    models.CharField(
                        blank=True,
                        help_text="Public CIDR mapped to this subnet (for carrier-grade NAT overlay)",
                        max_length=32,
                    ),
                ),
                (
                    "network",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subnets",
                        to="openstack.externalnetwork",
                    ),
                ),
            ],
            options={
                "unique_together": {("network", "backend_id")},
            },
            bases=(waldur_core.core.models.BackendModelMixin, models.Model),
        ),
        migrations.RunPython(migrations.RunPython.noop, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="servergroup",
            name="policy",
            field=models.CharField(
                blank=True,
                choices=[
                    ("affinity", "Affinity"),
                    ("anti-affinity", "Anti-affinity"),
                    ("soft-affinity", "Soft affinity"),
                    ("soft-anti-affinity", "Soft anti-affinity"),
                ],
                help_text="Server group policy determining the rules for scheduling servers in this group",
                max_length=40,
            ),
        ),
        migrations.CreateModel(
            name="LoadBalancer",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=4096, verbose_name="description"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=150,
                        validators=[waldur_core.core.validators.validate_name],
                        verbose_name="name",
                    ),
                ),
                ("uuid", waldur_core.core.fields.UUIDField()),
                (
                    "backend_id",
                    models.CharField(
                        blank=True,
                        help_text="Load balancer ID in Octavia",
                        max_length=255,
                        null=True,
                    ),
                ),
                ("error_message", models.TextField(blank=True)),
                ("error_traceback", models.TextField(blank=True)),
                (
                    "state",
                    django_fsm.FSMIntegerField(
                        choices=[
                            (5, "CREATION_SCHEDULED"),
                            (6, "CREATING"),
                            (1, "UPDATE_SCHEDULED"),
                            (2, "UPDATING"),
                            (7, "DELETION_SCHEDULED"),
                            (8, "DELETING"),
                            (3, "OK"),
                            (4, "ERRED"),
                        ],
                        default=5,
                    ),
                ),
                (
                    "vip_address",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="Virtual IP address of the load balancer",
                        null=True,
                        protocol="IPv4",
                    ),
                ),
                (
                    "vip_subnet_id",
                    models.CharField(
                        blank=True,
                        help_text="Subnet ID for the VIP (required for creation)",
                        max_length=64,
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        default="ovn",
                        help_text="Octavia provider (e.g. ovn for OVN LBaaS)",
                        max_length=64,
                    ),
                ),
                (
                    "provisioning_status",
                    models.CharField(
                        blank=True,
                        editable=False,
                        help_text="Octavia provisioning status: ACTIVE, PENDING_CREATE, etc.",
                        max_length=32,
                    ),
                ),
                (
                    "operating_status",
                    models.CharField(
                        blank=True,
                        editable=False,
                        help_text="Octavia operating status: ONLINE, OFFLINE, etc.",
                        max_length=32,
                    ),
                ),
                (
                    "attached_floating_ip",
                    models.ForeignKey(
                        blank=True,
                        help_text="Floating IP attached to the VIP port",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="load_balancers",
                        to="openstack.floatingip",
                    ),
                ),
                (
                    "vip_port_id",
                    models.CharField(
                        blank=True,
                        help_text="Neutron port ID for the VIP (for Floating IP and security groups)",
                        max_length=36,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="structure.project",
                    ),
                ),
                (
                    "service_settings",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="structure.servicesettings",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        help_text="OpenStack tenant this load balancer belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="load_balancers",
                        to="openstack.tenant",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "ordering": ["-created"],
                "unique_together": {("tenant", "backend_id")},
            },
            bases=(
                waldur_core.core.models.DescendantMixin,
                waldur_core.core.models.BackendModelMixin,
                waldur_core.structure.models.StructureLoggableMixin,
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="Pool",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=4096, verbose_name="description"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=150,
                        validators=[waldur_core.core.validators.validate_name],
                        verbose_name="name",
                    ),
                ),
                ("uuid", waldur_core.core.fields.UUIDField()),
                ("error_message", models.TextField(blank=True)),
                ("error_traceback", models.TextField(blank=True)),
                (
                    "state",
                    django_fsm.FSMIntegerField(
                        choices=[
                            (5, "CREATION_SCHEDULED"),
                            (6, "CREATING"),
                            (1, "UPDATE_SCHEDULED"),
                            (2, "UPDATING"),
                            (7, "DELETION_SCHEDULED"),
                            (8, "DELETING"),
                            (3, "OK"),
                            (4, "ERRED"),
                        ],
                        default=5,
                    ),
                ),
                (
                    "backend_id",
                    models.CharField(
                        blank=True,
                        help_text="Pool ID in Octavia",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "protocol",
                    models.CharField(
                        choices=[("TCP", "TCP"), ("UDP", "UDP")],
                        help_text="Protocol for the pool: TCP, UDP (OVN supports TCP and UDP)",
                        max_length=16,
                    ),
                ),
                (
                    "lb_algorithm",
                    models.CharField(
                        choices=[
                            ("ROUND_ROBIN", "Round Robin"),
                            ("LEAST_CONNECTIONS", "Least Connections"),
                            ("SOURCE_IP", "Source IP"),
                            ("SOURCE_IP_PORT", "Source IP Port"),
                        ],
                        default="SOURCE_IP_PORT",
                        help_text="Load balancing algorithm. OVN requires SOURCE_IP_PORT.",
                        max_length=32,
                    ),
                ),
                (
                    "provisioning_status",
                    models.CharField(
                        blank=True,
                        editable=False,
                        help_text="Octavia provisioning status: ACTIVE, PENDING_CREATE, etc.",
                        max_length=32,
                    ),
                ),
                (
                    "operating_status",
                    models.CharField(
                        blank=True,
                        editable=False,
                        help_text="Octavia operating status: ONLINE, OFFLINE, etc.",
                        max_length=32,
                    ),
                ),
                (
                    "load_balancer",
                    models.ForeignKey(
                        help_text="Load balancer this pool belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pools",
                        to="openstack.loadbalancer",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="structure.project",
                    ),
                ),
                (
                    "service_settings",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="structure.servicesettings",
                    ),
                ),
            ],
            options={
                "ordering": ["-created"],
                "abstract": False,
                "unique_together": {("load_balancer", "backend_id")},
            },
            bases=(
                waldur_core.core.models.DescendantMixin,
                waldur_core.core.models.BackendModelMixin,
                waldur_core.structure.models.StructureLoggableMixin,
                models.Model,
                django_fsm.ConcurrentTransitionMixin,
            ),
        ),
        migrations.CreateModel(
            name="Listener",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=4096, verbose_name="description"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=150,
                        validators=[waldur_core.core.validators.validate_name],
                        verbose_name="name",
                    ),
                ),
                ("uuid", waldur_core.core.fields.UUIDField()),
                ("error_message", models.TextField(blank=True)),
                ("error_traceback", models.TextField(blank=True)),
                (
                    "state",
                    django_fsm.FSMIntegerField(
                        choices=[
                            (5, "CREATION_SCHEDULED"),
                            (6, "CREATING"),
                            (1, "UPDATE_SCHEDULED"),
                            (2, "UPDATING"),
                            (7, "DELETION_SCHEDULED"),
                            (8, "DELETING"),
                            (3, "OK"),
                            (4, "ERRED"),
                        ],
                        default=5,
                    ),
                ),
                (
                    "backend_id",
                    models.CharField(
                        blank=True,
                        help_text="Listener ID in Octavia",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "protocol",
                    models.CharField(
                        choices=[("TCP", "TCP"), ("UDP", "UDP")],
                        help_text="Protocol for the listener: TCP, UDP (OVN supports TCP and UDP)",
                        max_length=16,
                    ),
                ),
                (
                    "protocol_port",
                    models.IntegerField(
                        help_text="Port on which the listener listens",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(65535),
                        ],
                    ),
                ),
                (
                    "provisioning_status",
                    models.CharField(
                        blank=True,
                        editable=False,
                        help_text="Octavia provisioning status: ACTIVE, PENDING_CREATE, etc.",
                        max_length=32,
                    ),
                ),
                (
                    "operating_status",
                    models.CharField(
                        blank=True,
                        editable=False,
                        help_text="Octavia operating status: ONLINE, OFFLINE, etc.",
                        max_length=32,
                    ),
                ),
                (
                    "load_balancer",
                    models.ForeignKey(
                        help_text="Load balancer this listener belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="listeners",
                        to="openstack.loadbalancer",
                    ),
                ),
                (
                    "default_pool",
                    models.ForeignKey(
                        blank=True,
                        help_text="Default pool for this listener",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="listeners",
                        to="openstack.pool",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="structure.project",
                    ),
                ),
                (
                    "service_settings",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="structure.servicesettings",
                    ),
                ),
            ],
            options={
                "ordering": ["-created"],
                "abstract": False,
                "unique_together": {("load_balancer", "backend_id")},
            },
            bases=(
                waldur_core.core.models.DescendantMixin,
                waldur_core.core.models.BackendModelMixin,
                waldur_core.structure.models.StructureLoggableMixin,
                models.Model,
                django_fsm.ConcurrentTransitionMixin,
            ),
        ),
        migrations.CreateModel(
            name="PoolMember",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=4096, verbose_name="description"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=150,
                        validators=[waldur_core.core.validators.validate_name],
                        verbose_name="name",
                    ),
                ),
                ("uuid", waldur_core.core.fields.UUIDField()),
                ("error_message", models.TextField(blank=True)),
                ("error_traceback", models.TextField(blank=True)),
                (
                    "state",
                    django_fsm.FSMIntegerField(
                        choices=[
                            (5, "CREATION_SCHEDULED"),
                            (6, "CREATING"),
                            (1, "UPDATE_SCHEDULED"),
                            (2, "UPDATING"),
                            (7, "DELETION_SCHEDULED"),
                            (8, "DELETING"),
                            (3, "OK"),
                            (4, "ERRED"),
                        ],
                        default=5,
                    ),
                ),
                (
                    "backend_id",
                    models.CharField(
                        blank=True,
                        help_text="Member ID in Octavia",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "address",
                    models.GenericIPAddressField(
                        help_text="IP address of the backend server"
                    ),
                ),
                (
                    "protocol_port",
                    models.PositiveIntegerField(
                        help_text="Port on the backend server",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(65535),
                        ],
                    ),
                ),
                (
                    "subnet_id",
                    models.CharField(
                        blank=True,
                        help_text="Subnet ID for the member (required for creation)",
                        max_length=36,
                    ),
                ),
                (
                    "weight",
                    models.PositiveSmallIntegerField(
                        default=1, help_text="Weight for load balancing (1-256)"
                    ),
                ),
                (
                    "provisioning_status",
                    models.CharField(
                        blank=True,
                        editable=False,
                        help_text="Octavia provisioning status: ACTIVE, PENDING_CREATE, etc.",
                        max_length=32,
                    ),
                ),
                (
                    "operating_status",
                    models.CharField(
                        blank=True,
                        editable=False,
                        help_text="Octavia operating status: ONLINE, OFFLINE, etc.",
                        max_length=32,
                    ),
                ),
                (
                    "pool",
                    models.ForeignKey(
                        help_text="Pool this member belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="openstack.pool",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="structure.project",
                    ),
                ),
                (
                    "service_settings",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="structure.servicesettings",
                    ),
                ),
            ],
            options={
                "ordering": ["-created"],
                "abstract": False,
                "unique_together": {("pool", "backend_id")},
            },
            bases=(
                waldur_core.core.models.DescendantMixin,
                waldur_core.core.models.BackendModelMixin,
                waldur_core.structure.models.StructureLoggableMixin,
                models.Model,
                django_fsm.ConcurrentTransitionMixin,
            ),
        ),
        migrations.CreateModel(
            name="HealthMonitor",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=4096, verbose_name="description"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=150,
                        validators=[waldur_core.core.validators.validate_name],
                        verbose_name="name",
                    ),
                ),
                ("uuid", waldur_core.core.fields.UUIDField()),
                ("error_message", models.TextField(blank=True)),
                ("error_traceback", models.TextField(blank=True)),
                (
                    "state",
                    django_fsm.FSMIntegerField(
                        choices=[
                            (5, "CREATION_SCHEDULED"),
                            (6, "CREATING"),
                            (1, "UPDATE_SCHEDULED"),
                            (2, "UPDATING"),
                            (7, "DELETION_SCHEDULED"),
                            (8, "DELETING"),
                            (3, "OK"),
                            (4, "ERRED"),
                        ],
                        default=5,
                    ),
                ),
                (
                    "backend_id",
                    models.CharField(
                        blank=True,
                        help_text="Health monitor ID in Octavia",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "monitor_type",
                    models.CharField(
                        choices=[("TCP", "TCP"), ("UDP", "UDP")],
                        db_column="type",
                        help_text="Health check type: TCP, UDP (OVN supports TCP and UDP only)",
                        max_length=16,
                    ),
                ),
                (
                    "delay",
                    models.PositiveIntegerField(
                        help_text="Interval between health checks in seconds"
                    ),
                ),
                (
                    "timeout",
                    models.PositiveIntegerField(
                        help_text="Time in seconds to timeout a health check"
                    ),
                ),
                (
                    "max_retries",
                    models.PositiveIntegerField(
                        help_text="Number of retries before marking member as down"
                    ),
                ),
                (
                    "provisioning_status",
                    models.CharField(
                        blank=True,
                        editable=False,
                        help_text="Octavia provisioning status: ACTIVE, PENDING_CREATE, etc.",
                        max_length=32,
                    ),
                ),
                (
                    "operating_status",
                    models.CharField(
                        blank=True,
                        editable=False,
                        help_text="Octavia operating status: ONLINE, OFFLINE, etc.",
                        max_length=32,
                    ),
                ),
                (
                    "pool",
                    models.OneToOneField(
                        help_text="Pool this health monitor belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="health_monitor",
                        to="openstack.pool",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="structure.project",
                    ),
                ),
                (
                    "service_settings",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="structure.servicesettings",
                    ),
                ),
            ],
            options={
                "ordering": ["-created"],
                "abstract": False,
            },
            bases=(
                waldur_core.core.models.DescendantMixin,
                waldur_core.core.models.BackendModelMixin,
                waldur_core.structure.models.StructureLoggableMixin,
                models.Model,
                django_fsm.ConcurrentTransitionMixin,
            ),
        ),
    ]
