# Generated by Django 4.2.14 on 2024-09-30 17:50

from django.db import migrations, models

import waldur_core.core.fields


class Migration(migrations.Migration):
    dependencies = [
        ("openstack", "0041_fix_primary_key_sequences"),
    ]

    operations = [
        migrations.AddField(
            model_name="instance",
            name="task_id",
            field=models.CharField(blank=True, max_length=155, null=True),
        ),
        migrations.AddField(
            model_name="snapshot",
            name="task_id",
            field=models.CharField(blank=True, max_length=155, null=True),
        ),
        migrations.AddField(
            model_name="tenant",
            name="action",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="tenant",
            name="action_details",
            field=waldur_core.core.fields.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="tenant",
            name="task_id",
            field=models.CharField(blank=True, max_length=155, null=True),
        ),
        migrations.AddField(
            model_name="volume",
            name="task_id",
            field=models.CharField(blank=True, max_length=155, null=True),
        ),
    ]
