# Generated by Django 4.2.16 on 2024-11-05 14:46
import ipaddress

from django.db import migrations, models


def fill_external_address(apps, schema_editor):
    TENANT_TYPE = "OpenStack.Tenant"
    INSTANCE_TYPE = "OpenStack.Instance"

    Offering = apps.get_model("marketplace", "Offering")
    Resource = apps.get_model("marketplace", "Resource")
    Instance = apps.get_model("openstack", "Instance")
    FloatingIP = apps.get_model("openstack", "FloatingIP")
    ContentType = apps.get_model("contenttypes", "ContentType")

    def get_external_ips(offering, ips):
        external_ips = []
        ipv4_external_ip_mapping = offering.secret_options.get(
            "ipv4_external_ip_mapping", []
        )
        if not (ipv4_external_ip_mapping or ips or offering):
            return external_ips

        for ip in ips:
            ip_address = ipaddress.ip_address(ip)

            for offering_external_ip in ipv4_external_ip_mapping:
                ip_network = ipaddress.ip_network(offering_external_ip["floating_ip"])

                if ip_address in ip_network:
                    external_ips.append(
                        ".".join(offering_external_ip["external_ip"].split(".")[:-1])
                        + "."
                        + ip.split(".")[-1]
                    )

        return external_ips

    def update_external_addresses_of_resource(resource, apps):
        if resource.content_type and resource.object_id:
            instance = (
                apps.get_model(
                    resource.content_type.app_label, resource.content_type.model
                )
                .objects.filter(id=resource.object_id)
                .first()
            )

            if not instance:
                return
        else:
            return

        floating_ips = FloatingIP.objects.filter(port__instance=instance).exclude(
            address__isnull=True
        )
        resource.backend_metadata["external_address"] = []

        for floating_ip in floating_ips:
            external_ips = get_external_ips(
                resource.offering.parent,
                [floating_ip.address],
            )

            floating_ip.external_address = external_ips
            resource.backend_metadata["external_address"].extend(external_ips)

            floating_ip.save()
            resource.save()

    def update_external_addresses_of_offering_floating_ips(parent_offering, apps):
        offerings = Offering.objects.filter(parent=parent_offering, type=INSTANCE_TYPE)

        if not offerings:
            return

        resources = Resource.objects.filter(
            offering__in=offerings,
            content_type=ContentType.objects.get_for_model(Instance),
        ).exclude(object_id__isnull=True)

        for resource in resources:
            update_external_addresses_of_resource(resource, apps)

    for offering in Offering.objects.all():
        if offering.type != TENANT_TYPE:
            continue

        update_external_addresses_of_offering_floating_ips(offering, apps)


class Migration(migrations.Migration):
    dependencies = [
        ("openstack", "0043_alter_backup_options_alter_port_options_and_more"),
        ("marketplace", "0145_clean_price_logs"),
    ]

    operations = [
        migrations.AddField(
            model_name="floatingip",
            name="external_address",
            field=models.JSONField(
                default=list,
                editable=False,
                help_text="An optional address that maps to floating IP's address",
            ),
        ),
        migrations.RunPython(fill_external_address),
    ]
