# Generated by Django 4.2.16 on 2024-11-05 14:46

from django.db import migrations, models

from waldur_mastermind.marketplace_openstack import TENANT_TYPE
from waldur_mastermind.marketplace_openstack.utils import (
    update_external_addresses_of_offering_floating_ips,
)


def fill_external_address(apps, schema_editor):
    Offering = apps.get_model("marketplace", "Offering")

    for offering in Offering.objects.all():
        if offering.type != TENANT_TYPE:
            continue

        update_external_addresses_of_offering_floating_ips(offering)


class Migration(migrations.Migration):
    dependencies = [
        ("openstack", "0043_alter_backup_options_alter_port_options_and_more"),
        ("marketplace", "0145_clean_price_logs"),
    ]

    operations = [
        migrations.AddField(
            model_name="floatingip",
            name="external_address",
            field=models.JSONField(
                default=list,
                editable=False,
                help_text="An optional address that maps to floating IP's address",
            ),
        ),
        migrations.RunPython(fill_external_address),
    ]
