# Generated by Django 4.2.20 on 2025-05-07 13:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("openstack", "0049_port_runtime_state"),
    ]

    operations = [
        migrations.AddField(
            model_name="port",
            name="status",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
