# Generated by Django 4.2.20 on 2025-05-13 07:35

from django.db import migrations, models

port_values = {}


def convert_admin_state_up_to_boolean(apps, schema_editor):
    Port = apps.get_model("openstack", "Port")
    for port in Port.objects.all():
        if port.admin_state_up == "True":
            port_values[port.id] = True
        elif port.admin_state_up == "False":
            port_values[port.id] = False
        else:
            port_values[port.id] = None
        port.save()


def copy_temp_to_admin_state_up(apps, schema_editor):
    Port = apps.get_model("openstack", "Port")
    for port in Port.objects.all():
        port.admin_state_up = port_values.get(port.id, None)
        port.save()


class Migration(migrations.Migration):
    dependencies = [
        ("openstack", "0050_port_status"),
    ]

    operations = [
        migrations.RunPython(convert_admin_state_up_to_boolean),
        migrations.AlterField(
            model_name="port",
            name="admin_state_up",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.RunPython(copy_temp_to_admin_state_up),
    ]
