# Generated by Django 4.2.20 on 2025-05-13 07:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("openstack", "0054_add_constraint"),
    ]

    operations = [
        migrations.AlterField(
            model_name="port",
            name="backend_id",
            field=models.CharField(max_length=255, blank=True, null=True),
        ),
    ]
