# Generated by Django 4.2.20 on 2025-07-21 17:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("openstack", "0055_nullable_backend_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="router",
            name="backend_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
