# Generated by Django on 2026-01-06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("openstack", "0061_instance_is_available_tenant_is_available_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="skip_creation_of_default_router",
            field=models.BooleanField(
                default=False,
                help_text="If True, default router will not be created for this tenant",
            ),
        ),
    ]
