# Generated by Django 4.2.27 on 2026-01-22 15:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("openstack", "0062_tenant_skip_router"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="backend_created_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
