# Generated by Django 5.2.11

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import django_fsm
import model_utils.fields
from django.db import migrations, models

import waldur_core.core.fields
import waldur_core.core.models
import waldur_core.core.validators
import waldur_core.structure.models


class Migration(migrations.Migration):
    dependencies = [
        ("openstack", "0066_server_group_policies"),
        ("structure", "0073_alter_projectdigestconfiguration_uuid"),
    ]

    operations = [
        migrations.CreateModel(
            name="LoadBalancer",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=4096, verbose_name="description"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=150,
                        validators=[waldur_core.core.validators.validate_name],
                        verbose_name="name",
                    ),
                ),
                ("uuid", waldur_core.core.fields.UUIDField()),
                (
                    "backend_id",
                    models.CharField(
                        blank=True,
                        help_text="Load balancer ID in Octavia",
                        max_length=255,
                        null=True,
                    ),
                ),
                ("error_message", models.TextField(blank=True)),
                ("error_traceback", models.TextField(blank=True)),
                (
                    "state",
                    django_fsm.FSMIntegerField(
                        choices=[
                            (5, "CREATION_SCHEDULED"),
                            (6, "CREATING"),
                            (1, "UPDATE_SCHEDULED"),
                            (2, "UPDATING"),
                            (7, "DELETION_SCHEDULED"),
                            (8, "DELETING"),
                            (3, "OK"),
                            (4, "ERRED"),
                        ],
                        default=5,
                    ),
                ),
                (
                    "vip_address",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="Virtual IP address of the load balancer",
                        null=True,
                        protocol="IPv4",
                    ),
                ),
                (
                    "vip_subnet_id",
                    models.CharField(
                        blank=True,
                        help_text="Subnet ID for the VIP (required for creation)",
                        max_length=64,
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        default="ovn",
                        help_text="Octavia provider (e.g. ovn for OVN LBaaS)",
                        max_length=64,
                    ),
                ),
                (
                    "provisioning_status",
                    models.CharField(
                        blank=True,
                        help_text="Octavia provisioning status: ACTIVE, PENDING_CREATE, etc.",
                        max_length=32,
                        editable=False,
                    ),
                ),
                (
                    "operating_status",
                    models.CharField(
                        blank=True,
                        help_text="Octavia operating status: ONLINE, OFFLINE, etc.",
                        max_length=32,
                        editable=False,
                    ),
                ),
                (
                    "attached_floating_ip",
                    models.ForeignKey(
                        blank=True,
                        help_text="Floating IP attached to the VIP port",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="load_balancers",
                        to="openstack.floatingip",
                    ),
                ),
                (
                    "vip_port_id",
                    models.CharField(
                        blank=True,
                        help_text="Neutron port ID for the VIP (for Floating IP and security groups)",
                        max_length=36,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="structure.project",
                    ),
                ),
                (
                    "service_settings",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="structure.servicesettings",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        help_text="OpenStack tenant this load balancer belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="load_balancers",
                        to="openstack.tenant",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "ordering": ["-created"],
                "unique_together": {("tenant", "backend_id")},
            },
            bases=(
                waldur_core.core.models.DescendantMixin,
                waldur_core.core.models.BackendModelMixin,
                waldur_core.structure.models.StructureLoggableMixin,
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="Pool",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=4096, verbose_name="description"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=150,
                        validators=[waldur_core.core.validators.validate_name],
                        verbose_name="name",
                    ),
                ),
                ("uuid", waldur_core.core.fields.UUIDField()),
                ("error_message", models.TextField(blank=True)),
                ("error_traceback", models.TextField(blank=True)),
                (
                    "state",
                    django_fsm.FSMIntegerField(
                        choices=[
                            (5, "CREATION_SCHEDULED"),
                            (6, "CREATING"),
                            (1, "UPDATE_SCHEDULED"),
                            (2, "UPDATING"),
                            (7, "DELETION_SCHEDULED"),
                            (8, "DELETING"),
                            (3, "OK"),
                            (4, "ERRED"),
                        ],
                        default=5,
                    ),
                ),
                (
                    "backend_id",
                    models.CharField(
                        blank=True,
                        help_text="Pool ID in Octavia",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "protocol",
                    models.CharField(
                        choices=[("TCP", "TCP"), ("UDP", "UDP")],
                        help_text="Protocol for the pool: TCP, UDP (OVN supports TCP and UDP)",
                        max_length=16,
                    ),
                ),
                (
                    "lb_algorithm",
                    models.CharField(
                        choices=[
                            ("ROUND_ROBIN", "Round Robin"),
                            ("LEAST_CONNECTIONS", "Least Connections"),
                            ("SOURCE_IP", "Source IP"),
                            ("SOURCE_IP_PORT", "Source IP Port"),
                        ],
                        default="SOURCE_IP_PORT",
                        help_text="Load balancing algorithm. OVN requires SOURCE_IP_PORT.",
                        max_length=32,
                    ),
                ),
                (
                    "provisioning_status",
                    models.CharField(
                        blank=True,
                        help_text="Octavia provisioning status: ACTIVE, PENDING_CREATE, etc.",
                        max_length=32,
                        editable=False,
                    ),
                ),
                (
                    "operating_status",
                    models.CharField(
                        blank=True,
                        help_text="Octavia operating status: ONLINE, OFFLINE, etc.",
                        max_length=32,
                        editable=False,
                    ),
                ),
                (
                    "load_balancer",
                    models.ForeignKey(
                        help_text="Load balancer this pool belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pools",
                        to="openstack.loadbalancer",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="structure.project",
                    ),
                ),
                (
                    "service_settings",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="structure.servicesettings",
                    ),
                ),
            ],
            options={
                "ordering": ["-created"],
                "abstract": False,
                "unique_together": {("load_balancer", "backend_id")},
            },
            bases=(
                waldur_core.core.models.DescendantMixin,
                waldur_core.core.models.BackendModelMixin,
                waldur_core.structure.models.StructureLoggableMixin,
                models.Model,
                django_fsm.ConcurrentTransitionMixin,
            ),
        ),
        migrations.CreateModel(
            name="Listener",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=4096, verbose_name="description"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=150,
                        validators=[waldur_core.core.validators.validate_name],
                        verbose_name="name",
                    ),
                ),
                ("uuid", waldur_core.core.fields.UUIDField()),
                ("error_message", models.TextField(blank=True)),
                ("error_traceback", models.TextField(blank=True)),
                (
                    "state",
                    django_fsm.FSMIntegerField(
                        choices=[
                            (5, "CREATION_SCHEDULED"),
                            (6, "CREATING"),
                            (1, "UPDATE_SCHEDULED"),
                            (2, "UPDATING"),
                            (7, "DELETION_SCHEDULED"),
                            (8, "DELETING"),
                            (3, "OK"),
                            (4, "ERRED"),
                        ],
                        default=5,
                    ),
                ),
                (
                    "backend_id",
                    models.CharField(
                        blank=True,
                        help_text="Listener ID in Octavia",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "protocol",
                    models.CharField(
                        choices=[("TCP", "TCP"), ("UDP", "UDP")],
                        help_text="Protocol for the listener: TCP, UDP (OVN supports TCP and UDP)",
                        max_length=16,
                    ),
                ),
                (
                    "protocol_port",
                    models.IntegerField(
                        help_text="Port on which the listener listens",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(65535),
                        ],
                    ),
                ),
                (
                    "provisioning_status",
                    models.CharField(
                        blank=True,
                        help_text="Octavia provisioning status: ACTIVE, PENDING_CREATE, etc.",
                        max_length=32,
                        editable=False,
                    ),
                ),
                (
                    "operating_status",
                    models.CharField(
                        blank=True,
                        help_text="Octavia operating status: ONLINE, OFFLINE, etc.",
                        max_length=32,
                        editable=False,
                    ),
                ),
                (
                    "load_balancer",
                    models.ForeignKey(
                        help_text="Load balancer this listener belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="listeners",
                        to="openstack.loadbalancer",
                    ),
                ),
                (
                    "default_pool",
                    models.ForeignKey(
                        blank=True,
                        help_text="Default pool for this listener",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="listeners",
                        to="openstack.pool",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="structure.project",
                    ),
                ),
                (
                    "service_settings",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="structure.servicesettings",
                    ),
                ),
            ],
            options={
                "ordering": ["-created"],
                "abstract": False,
                "unique_together": {("load_balancer", "backend_id")},
            },
            bases=(
                waldur_core.core.models.DescendantMixin,
                waldur_core.core.models.BackendModelMixin,
                waldur_core.structure.models.StructureLoggableMixin,
                models.Model,
                django_fsm.ConcurrentTransitionMixin,
            ),
        ),
        migrations.CreateModel(
            name="PoolMember",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=4096, verbose_name="description"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=150,
                        validators=[waldur_core.core.validators.validate_name],
                        verbose_name="name",
                    ),
                ),
                ("uuid", waldur_core.core.fields.UUIDField()),
                ("error_message", models.TextField(blank=True)),
                ("error_traceback", models.TextField(blank=True)),
                (
                    "state",
                    django_fsm.FSMIntegerField(
                        choices=[
                            (5, "CREATION_SCHEDULED"),
                            (6, "CREATING"),
                            (1, "UPDATE_SCHEDULED"),
                            (2, "UPDATING"),
                            (7, "DELETION_SCHEDULED"),
                            (8, "DELETING"),
                            (3, "OK"),
                            (4, "ERRED"),
                        ],
                        default=5,
                    ),
                ),
                (
                    "backend_id",
                    models.CharField(
                        blank=True,
                        help_text="Member ID in Octavia",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "address",
                    models.GenericIPAddressField(
                        help_text="IP address of the backend server"
                    ),
                ),
                (
                    "protocol_port",
                    models.PositiveIntegerField(
                        help_text="Port on the backend server",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(65535),
                        ],
                    ),
                ),
                (
                    "subnet_id",
                    models.CharField(
                        blank=True,
                        help_text="Subnet ID for the member (required for creation)",
                        max_length=36,
                    ),
                ),
                (
                    "weight",
                    models.PositiveSmallIntegerField(
                        default=1, help_text="Weight for load balancing (1-256)"
                    ),
                ),
                (
                    "provisioning_status",
                    models.CharField(
                        blank=True,
                        help_text="Octavia provisioning status: ACTIVE, PENDING_CREATE, etc.",
                        max_length=32,
                        editable=False,
                    ),
                ),
                (
                    "operating_status",
                    models.CharField(
                        blank=True,
                        help_text="Octavia operating status: ONLINE, OFFLINE, etc.",
                        max_length=32,
                        editable=False,
                    ),
                ),
                (
                    "pool",
                    models.ForeignKey(
                        help_text="Pool this member belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="openstack.pool",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="structure.project",
                    ),
                ),
                (
                    "service_settings",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="structure.servicesettings",
                    ),
                ),
            ],
            options={
                "ordering": ["-created"],
                "abstract": False,
                "unique_together": {("pool", "backend_id")},
            },
            bases=(
                waldur_core.core.models.DescendantMixin,
                waldur_core.core.models.BackendModelMixin,
                waldur_core.structure.models.StructureLoggableMixin,
                models.Model,
                django_fsm.ConcurrentTransitionMixin,
            ),
        ),
        migrations.CreateModel(
            name="HealthMonitor",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=4096, verbose_name="description"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=150,
                        validators=[waldur_core.core.validators.validate_name],
                        verbose_name="name",
                    ),
                ),
                ("uuid", waldur_core.core.fields.UUIDField()),
                ("error_message", models.TextField(blank=True)),
                ("error_traceback", models.TextField(blank=True)),
                (
                    "state",
                    django_fsm.FSMIntegerField(
                        choices=[
                            (5, "CREATION_SCHEDULED"),
                            (6, "CREATING"),
                            (1, "UPDATE_SCHEDULED"),
                            (2, "UPDATING"),
                            (7, "DELETION_SCHEDULED"),
                            (8, "DELETING"),
                            (3, "OK"),
                            (4, "ERRED"),
                        ],
                        default=5,
                    ),
                ),
                (
                    "backend_id",
                    models.CharField(
                        blank=True,
                        help_text="Health monitor ID in Octavia",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "monitor_type",
                    models.CharField(
                        choices=[("TCP", "TCP"), ("UDP", "UDP")],
                        db_column="type",
                        help_text="Health check type: TCP, UDP (OVN supports TCP and UDP only)",
                        max_length=16,
                    ),
                ),
                (
                    "delay",
                    models.PositiveIntegerField(
                        help_text="Interval between health checks in seconds"
                    ),
                ),
                (
                    "timeout",
                    models.PositiveIntegerField(
                        help_text="Time in seconds to timeout a health check"
                    ),
                ),
                (
                    "max_retries",
                    models.PositiveIntegerField(
                        help_text="Number of retries before marking member as down"
                    ),
                ),
                (
                    "provisioning_status",
                    models.CharField(
                        blank=True,
                        help_text="Octavia provisioning status: ACTIVE, PENDING_CREATE, etc.",
                        max_length=32,
                        editable=False,
                    ),
                ),
                (
                    "operating_status",
                    models.CharField(
                        blank=True,
                        help_text="Octavia operating status: ONLINE, OFFLINE, etc.",
                        max_length=32,
                        editable=False,
                    ),
                ),
                (
                    "pool",
                    models.OneToOneField(
                        help_text="Pool this health monitor belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="health_monitor",
                        to="openstack.pool",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="structure.project",
                    ),
                ),
                (
                    "service_settings",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="structure.servicesettings",
                    ),
                ),
            ],
            options={
                "ordering": ["-created"],
                "abstract": False,
            },
            bases=(
                waldur_core.core.models.DescendantMixin,
                waldur_core.core.models.BackendModelMixin,
                waldur_core.structure.models.StructureLoggableMixin,
                models.Model,
                django_fsm.ConcurrentTransitionMixin,
            ),
        ),
    ]
