# Generated by Django 6.0.2 on 2026-03-27 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("openstack", "0067_loadbalancer"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="loadbalancer",
            name="vip_subnet_id",
        ),
        migrations.AddField(
            model_name="loadbalancer",
            name="vip_subnet",
            field=models.ForeignKey(
                default=None,
                help_text="Subnet for the load balancer VIP",
                on_delete=django.db.models.deletion.SET_NULL,
                to="openstack.subnet",
                null=True,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="loadbalancer",
            name="provider",
            field=models.CharField(
                default="ovn",
                editable=False,
                help_text="Octavia provider (e.g. ovn for OVN LBaaS)",
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="loadbalancer",
            name="vip_port_id",
            field=models.CharField(
                blank=True,
                editable=False,
                help_text="Neutron port ID for the VIP (for Floating IP and security groups)",
                max_length=36,
            ),
        ),
        migrations.AlterField(
            model_name="pool",
            name="lb_algorithm",
            field=models.CharField(
                choices=[
                    ("ROUND_ROBIN", "Round Robin"),
                    ("LEAST_CONNECTIONS", "Least Connections"),
                    ("SOURCE_IP", "Source IP"),
                    ("SOURCE_IP_PORT", "Source IP port"),
                ],
                default="SOURCE_IP_PORT",
                help_text="Load balancing algorithm.",
                max_length=32,
            ),
        ),
        migrations.RemoveField(
            model_name="loadbalancer",
            name="vip_port_id",
        ),
        migrations.AddField(
            model_name="loadbalancer",
            name="vip_port",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                help_text=(
                    "Neutron VIP port in Waldur (for floating IP and security groups)"
                ),
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="openstack.port",
            ),
        ),
        migrations.AddField(
            model_name="healthmonitor",
            name="max_retries_down",
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AlterField(
            model_name="healthmonitor",
            name="delay",
            field=models.PositiveIntegerField(
                default=5, help_text="Interval between health checks in seconds"
            ),
        ),
        migrations.AlterField(
            model_name="healthmonitor",
            name="max_retries",
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AlterField(
            model_name="healthmonitor",
            name="timeout",
            field=models.PositiveIntegerField(
                default=5, help_text="Time in seconds to timeout a health check"
            ),
        ),
        migrations.RemoveField(
            model_name="poolmember",
            name="subnet_id",
        ),
        migrations.AddField(
            model_name="poolmember",
            name="subnet",
            field=models.ForeignKey(
                blank=True,
                help_text="Neutron subnet for the member (same tenant as the load balancer)",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="openstack.subnet",
            ),
        ),
    ]
