# Generated by Django 6.0.5 on 2026-05-28 21:59

import waldur_openstack.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("openstack", "0073_instance_config_drive"),
    ]

    operations = [
        migrations.AlterField(
            model_name="securitygrouprule",
            name="protocol",
            field=models.CharField(
                blank=True,
                help_text="Network protocol: 'tcp', 'udp', 'icmp', empty (any) or an IANA protocol number 0-255 (e.g. '112' for VRRP).",
                max_length=40,
                validators=[
                    waldur_openstack.models.validate_security_group_rule_protocol
                ],
            ),
        ),
    ]
