# Generated by Django 6.0.5 on 2026-06-02 13:24

import waldur_core.core.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("openstack", "0074_alter_securitygrouprule_protocol"),
    ]

    operations = [
        migrations.CreateModel(
            name="Trait",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uuid", waldur_core.core.fields.UUIDField()),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
            options={
                "ordering": ("name",),
            },
        ),
        migrations.AddField(
            model_name="hypervisor",
            name="traits",
            field=models.ManyToManyField(
                blank=True,
                help_text="Placement traits (capability flags) reported for this host.",
                related_name="hypervisors",
                to="openstack.trait",
            ),
        ),
    ]
