# Generated by Django 6.0.7 on 2026-07-14 11:16

from django.db import migrations, models

import waldur_core.core.validators


class Migration(migrations.Migration):
    dependencies = [
        ("openstack", "0077_alter_instance_directly_connected_ips"),
    ]

    operations = [
        migrations.AlterField(
            model_name="instance",
            name="image_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="instance",
            name="name",
            field=models.CharField(
                max_length=255,
                validators=[waldur_core.core.validators.validate_name],
                verbose_name="name",
            ),
        ),
        migrations.AlterField(
            model_name="volume",
            name="image_name",
            field=models.CharField(
                blank=True,
                help_text="Name of the image this volume was created from",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="volume",
            name="name",
            field=models.CharField(
                max_length=255,
                validators=[waldur_core.core.validators.validate_name],
                verbose_name="name",
            ),
        ),
    ]
