# Generated by Django 6.0.8 on 2026-08-19 21:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("openstack", "0078_alter_instance_image_name_alter_instance_name_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="backup",
            options={"ordering": ["-created", "id"]},
        ),
        migrations.AlterModelOptions(
            name="floatingip",
            options={
                "ordering": ["-created", "id"],
                "verbose_name": "Floating IP",
                "verbose_name_plural": "Floating IPs",
            },
        ),
        migrations.AlterModelOptions(
            name="healthmonitor",
            options={"ordering": ["-created", "id"]},
        ),
        migrations.AlterModelOptions(
            name="instance",
            options={"ordering": ["name", "created", "id"]},
        ),
        migrations.AlterModelOptions(
            name="listener",
            options={"ordering": ["-created", "id"]},
        ),
        migrations.AlterModelOptions(
            name="loadbalancer",
            options={"ordering": ["-created", "id"]},
        ),
        migrations.AlterModelOptions(
            name="network",
            options={"ordering": ["-created", "id"]},
        ),
        migrations.AlterModelOptions(
            name="pool",
            options={"ordering": ["-created", "id"]},
        ),
        migrations.AlterModelOptions(
            name="poolmember",
            options={"ordering": ["-created", "id"]},
        ),
        migrations.AlterModelOptions(
            name="port",
            options={"ordering": ["-created", "id"]},
        ),
        migrations.AlterModelOptions(
            name="router",
            options={"ordering": ["-created", "id"]},
        ),
        migrations.AlterModelOptions(
            name="securitygroup",
            options={"ordering": ["-created", "id"]},
        ),
        migrations.AlterModelOptions(
            name="servergroup",
            options={"ordering": ["-created", "id"]},
        ),
        migrations.AlterModelOptions(
            name="snapshot",
            options={"ordering": ["-created", "id"]},
        ),
        migrations.AlterModelOptions(
            name="subnet",
            options={
                "ordering": ["-created", "id"],
                "verbose_name": "Subnet",
                "verbose_name_plural": "Subnets",
            },
        ),
        migrations.AlterModelOptions(
            name="tenant",
            options={"ordering": ["-created", "id"]},
        ),
        migrations.AlterModelOptions(
            name="volume",
            options={"ordering": ["-created", "id"]},
        ),
    ]
