# Generated by Django 6.0.8 on 2026-08-24 09:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("openstack", "0080_alter_hypervisorinventory_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="instance",
            name="backend_missing_since",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="snapshot",
            name="backend_missing_since",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tenant",
            name="backend_missing_since",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="volume",
            name="backend_missing_since",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
