# Generated by Django 6.0.8 on 2026-09-08 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("openstack", "0082_instance_metadata"),
    ]

    operations = [
        migrations.AddField(
            model_name="subnet",
            name="router",
            field=models.ForeignKey(
                blank=True,
                help_text="Router this subnet is attached to. Set explicitly at creation time, otherwise recorded from the backend once the attachment is made. While the subnet is disconnected it keeps the router it was last attached to, which is the one a reconnect returns it to.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="subnets",
                to="openstack.router",
            ),
        ),
    ]
