# Generated by Django 6.0.8 on 2026-09-15 18:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("openstack", "0085_subnet_ipv6_modes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="externalsubnet",
            name="cidr",
            field=models.CharField(blank=True, max_length=43),
        ),
    ]
