# Generated by Django 6.0.8 on 2026-09-03 15:38

import django.db.models.deletion
import django.utils.timezone
import django_fsm
import model_utils.fields
from django.conf import settings
from django.db import migrations, models

import waldur_core.core.fields
import waldur_core.core.models
import waldur_core.core.validators
import waldur_core.structure.models


class Migration(migrations.Migration):
    replaces = [
        ("waldur_firecrest", "0001_initial"),
        ("waldur_firecrest", "0002_extend_job_model"),
        ("waldur_firecrest", "0003_alter_job_report"),
        ("waldur_firecrest", "0004_alter_job_state"),
        ("waldur_firecrest", "0005_alter_job_description"),
        ("waldur_firecrest", "0006_alter_job_options"),
    ]

    dependencies = [
        ("core", "__first__"),
        ("structure", "0001_squashed_0036"),
    ]

    operations = [
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=4096, verbose_name="description"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=150,
                        validators=[waldur_core.core.validators.validate_name],
                        verbose_name="name",
                    ),
                ),
                ("uuid", waldur_core.core.fields.UUIDField()),
                ("error_message", models.TextField(blank=True)),
                ("error_traceback", models.TextField(blank=True)),
                (
                    "state",
                    django_fsm.FSMIntegerField(
                        choices=[
                            (5, "CREATION_SCHEDULED"),
                            (6, "CREATING"),
                            (1, "UPDATE_SCHEDULED"),
                            (2, "UPDATING"),
                            (7, "DELETION_SCHEDULED"),
                            (8, "DELETING"),
                            (3, "OK"),
                            (4, "ERRED"),
                        ],
                        default=5,
                    ),
                ),
                ("backend_id", models.CharField(blank=True, max_length=255)),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="slurm_jobs",
                        verbose_name="Batch script file",
                    ),
                ),
                (
                    "report",
                    models.JSONField(blank=True, null=True, verbose_name="Job output"),
                ),
                ("runtime_state", models.CharField(blank=True, max_length=100)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="structure.project",
                    ),
                ),
                (
                    "service_settings",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="structure.servicesettings",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="Reference to user which submitted job",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created", "id"],
                "abstract": False,
            },
            bases=(
                waldur_core.core.models.DescendantMixin,
                waldur_core.core.models.BackendModelMixin,
                waldur_core.structure.models.StructureLoggableMixin,
                models.Model,
                django_fsm.ConcurrentTransitionMixin,
            ),
        ),
    ]
