# Generated by Django 4.2.24 on 2025-10-20 10:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("waldur_firecrest", "0004_alter_job_state"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="description",
            field=models.CharField(
                blank=True, max_length=4096, verbose_name="description"
            ),
        ),
    ]
