# Generated by Django 4.2.24 on 2026-01-21 20:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("structure_tests", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="testnewinstance",
            name="can_be_managed",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="testnewinstance",
            name="description",
            field=models.CharField(
                blank=True, max_length=4096, verbose_name="description"
            ),
        ),
        migrations.AlterField(
            model_name="testsnapshot",
            name="description",
            field=models.CharField(
                blank=True, max_length=4096, verbose_name="description"
            ),
        ),
        migrations.AlterField(
            model_name="testsubresource",
            name="description",
            field=models.CharField(
                blank=True, max_length=4096, verbose_name="description"
            ),
        ),
        migrations.AlterField(
            model_name="testvolume",
            name="description",
            field=models.CharField(
                blank=True, max_length=4096, verbose_name="description"
            ),
        ),
    ]
