# -*- coding: utf-8; indent-tabs-mode: nil; tab-width: 2; -*-

---
- name: Start VM instances
  connection: local
  hosts: localhost
  tasks:
    - name: Start VM instances
      waldur_os_add_instance:
        access_token: "{{ access_token }}"
        api_url: "{{ api_url }}"
        data_volume_size: 1
        flavor: m1.little
        floating_ip: auto
        image: CentOS
        name: Waldur
        project: "{{ project_uuid }}"
        provider: "{{ provider_uuid }}"
        security_groups:
          - default
          - ping
          - ssh
        ssh_key: "{{ public_key_uuid }}"
        subnet: "{{ subnet_uuid }}"
        system_volume_size: 30
        wait: true
      register: vm_instance

    - name: Set instance facts
      set_fact:
        public_ip: "{{ vm_instance.instance.external_ips.0 }}"

    - name: Add instance to dynamic inventory
      add_host:
        ansible_ssh_private_key_file: "{{ private_key_path }}"
        ansible_ssh_user: centos
        groups: created_vm_instances
        hostname: "{{ public_ip }}"

    - name: Get SSH public key data
      uri:
        headers:
          Authorization: "Token {{ access_token }}"
        url: "{{ api_url }}keys/{{ user_key_uuid }}/"
      register: key_data

    - name: Set SSH public key fact
      set_fact:
        public_key: "{{ key_data.json.public_key }}"

    - name: Wait for instance to respond to SSH
      wait_for:
        delay: 10
        host: "{{ public_ip }}"
        port: 22


- name: Add SSH public key to instance authorized keys
  become: yes
  hosts: created_vm_instances
  tasks:
    - name: Add SSH public key to instance authorized keys
      authorized_key:
        key: "{{ hostvars.localhost.public_key }}"
        state: present
        user: centos


- name: Install and configure PostgreSQL 9.6 server
  hosts: created_vm_instances
  tasks:
    - name: Enable package repositories
      package:
        name: https://download.postgresql.org/pub/repos/yum/9.6/redhat/rhel-7-x86_64/pgdg-centos96-9.6-3.noarch.rpm

    - name: Install packages
      package:
        name: postgresql96-server

    - name: Set up PostgreSQL server
      command: /usr/pgsql-9.6/bin/postgresql96-setup initdb
        creates=/var/lib/pgsql/9.6/data/pg_hba.conf

    - name: Enable and start services
      service:
        enabled: yes
        name: postgresql-9.6
        state: started
