# Generated by Django 4.2.8 on 2024-01-31 20:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("support", "0006_requesttype_backend_name"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="supportuser",
            unique_together={("backend_name", "backend_id", "is_active")},
        ),
    ]
