# Generated by Django 6.0.2 on 2026-03-06 15:12

import django.core.validators
import django_fsm
from django.db import migrations, models

import waldur_core.core.fields

# Functions from the following migrations need manual copying.
# Move them and any dependencies into this file, then update the
# RunPython operations to refer to the local versions:
# waldur_mastermind.support.migrations.0013_add_uuid_to_issue_status
# waldur_mastermind.support.migrations.0015_rename_templates


class Migration(migrations.Migration):
    replaces = [
        ("support", "0011_alter_feedback_evaluation"),
        ("support", "0012_alter_attachment_state_alter_comment_state_and_more"),
        ("support", "0013_add_uuid_to_issue_status"),
        ("support", "0014_alter_issuestatus_uuid"),
        ("support", "0015_rename_templates"),
        ("support", "0016_remove_first_response_sla"),
        ("support", "0017_alter_priority_description"),
        ("support", "0018_issue_is_available"),
        ("support", "0019_add_processing_log_to_issue"),
        ("support", "0020_add_request_type_is_active_order"),
        ("support", "0021_allow_nullable_request_type_backend_id"),
    ]

    dependencies = [
        (
            "support",
            "0002_add_backend_name_field_squashed_0010_remove_template_native_description_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="feedback",
            name="evaluation",
            field=models.SmallIntegerField(
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(10),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="attachment",
            name="state",
            field=django_fsm.FSMIntegerField(
                choices=[
                    (5, "CREATION_SCHEDULED"),
                    (6, "CREATING"),
                    (1, "UPDATE_SCHEDULED"),
                    (2, "UPDATING"),
                    (7, "DELETION_SCHEDULED"),
                    (8, "DELETING"),
                    (3, "OK"),
                    (4, "ERRED"),
                ],
                default=5,
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="state",
            field=django_fsm.FSMIntegerField(
                choices=[
                    (5, "CREATION_SCHEDULED"),
                    (6, "CREATING"),
                    (1, "UPDATE_SCHEDULED"),
                    (2, "UPDATING"),
                    (7, "DELETION_SCHEDULED"),
                    (8, "DELETING"),
                    (3, "OK"),
                    (4, "ERRED"),
                ],
                default=5,
            ),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="state",
            field=django_fsm.FSMIntegerField(
                choices=[
                    (5, "CREATION_SCHEDULED"),
                    (6, "CREATING"),
                    (1, "UPDATE_SCHEDULED"),
                    (2, "UPDATING"),
                    (7, "DELETION_SCHEDULED"),
                    (8, "DELETING"),
                    (3, "OK"),
                    (4, "ERRED"),
                ],
                default=5,
            ),
        ),
        migrations.AlterField(
            model_name="issue",
            name="state",
            field=django_fsm.FSMIntegerField(
                choices=[
                    (5, "CREATION_SCHEDULED"),
                    (6, "CREATING"),
                    (1, "UPDATE_SCHEDULED"),
                    (2, "UPDATING"),
                    (7, "DELETION_SCHEDULED"),
                    (8, "DELETING"),
                    (3, "OK"),
                    (4, "ERRED"),
                ],
                default=5,
            ),
        ),
        migrations.AddField(
            model_name="issuestatus",
            name="uuid",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.RunPython(migrations.RunPython.noop, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="issuestatus",
            name="uuid",
            field=waldur_core.core.fields.UUIDField(),
        ),
        migrations.RunPython(migrations.RunPython.noop, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="issue",
            name="first_response_sla",
        ),
        migrations.AlterField(
            model_name="priority",
            name="description",
            field=models.CharField(
                blank=True, max_length=4096, verbose_name="description"
            ),
        ),
        migrations.AddField(
            model_name="issue",
            name="can_be_managed",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="issue",
            name="processing_log",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Internal processing log for debugging order lifecycle events. Visible only to staff.",
            ),
        ),
        migrations.AlterModelOptions(
            name="requesttype",
            options={"ordering": ["order", "name"]},
        ),
        migrations.AddField(
            model_name="requesttype",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Whether this request type is available for issue creation.",
            ),
        ),
        migrations.AddField(
            model_name="requesttype",
            name="order",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Display order. First type (lowest order) is the default.",
            ),
        ),
        migrations.AlterField(
            model_name="requesttype",
            name="backend_id",
            field=models.IntegerField(
                blank=True,
                help_text="Backend ID for synced types. Null for manually created types.",
                null=True,
                unique=True,
            ),
        ),
    ]
