# Generated by Django 2.2.19 on 2021-04-23 09:48

from django.db import migrations, models


def switch_to_ten_point_system(apps, schema_editor):
    Feedback = apps.get_model('support', 'Feedback')

    for feedback in Feedback.objects.all():
        feedback.evaluation *= 2
        feedback.save()


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0012_issue_feedback_request'),
    ]

    operations = [
        migrations.RunPython(switch_to_ten_point_system),
        migrations.AlterField(
            model_name='feedback',
            name='evaluation',
            field=models.SmallIntegerField(
                choices=[
                    (1, '1'),
                    (2, '2'),
                    (3, '3'),
                    (4, '4'),
                    (5, '5'),
                    (6, '6'),
                    (7, '7'),
                    (8, '8'),
                    (9, '9'),
                    (10, '10'),
                ]
            ),
        ),
    ]
