# Generated by Django 4.2.23 on 2025-09-05 17:28

from django.db import migrations

import waldur_core.core.fields


class Migration(migrations.Migration):
    dependencies = [
        ("support", "0013_add_uuid_to_issue_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="issuestatus",
            name="uuid",
            field=waldur_core.core.fields.UUIDField(),
        ),
    ]
