# Generated by Django 4.2.24 on 2025-10-03 12:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("support", "0015_rename_templates"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="issue",
            name="first_response_sla",
        ),
    ]
