# Generated by Django 3.2.14 on 2022-08-16 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0017_alter_requesttype_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='remote_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
