# Generated by Django 4.2.23 on 2025-11-26 15:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("support", "0017_alter_priority_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="issue",
            name="can_be_managed",
            field=models.BooleanField(default=True),
        ),
    ]
