# Generated by Django 3.2.14 on 2022-09-12 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0018_issue_remote_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='remote_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
