# Generated by Django 4.2.24 on 2026-01-06 12:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("support", "0019_add_processing_log_to_issue"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="requesttype",
            options={"ordering": ["order", "name"]},
        ),
        migrations.AddField(
            model_name="requesttype",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Whether this request type is available for issue creation.",
            ),
        ),
        migrations.AddField(
            model_name="requesttype",
            name="order",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Display order. First type (lowest order) is the default.",
            ),
        ),
    ]
