# Generated by Django 4.2.27 on 2026-02-07

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.conf import settings
from django.db import migrations, models

import waldur_core.core.fields
import waldur_core.core.validators


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("marketplace", "0205_backfill_initial_revisions"),
        ("support", "0021_allow_nullable_request_type_backend_id"),
    ]

    operations = [
        # --- SLA fields on Issue ---
        migrations.AddField(
            model_name="issue",
            name="first_response_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Timestamp of first response from support staff.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="issue",
            name="first_response_deadline",
            field=models.DateTimeField(
                blank=True,
                help_text="Deadline for first response from support staff.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="issue",
            name="resolution_deadline",
            field=models.DateTimeField(
                blank=True, help_text="Deadline for issue resolution.", null=True
            ),
        ),
        migrations.AddField(
            model_name="issue",
            name="sla_breached",
            field=models.BooleanField(
                default=False, help_text="Whether SLA has been breached for this issue."
            ),
        ),
        # --- IssueStatusTransition ---
        migrations.CreateModel(
            name="IssueStatusTransition",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uuid", waldur_core.core.fields.UUIDField()),
                ("from_status", models.CharField(max_length=255)),
                ("to_status", models.CharField(max_length=255)),
            ],
            options={
                "ordering": ["from_status", "to_status"],
                "unique_together": {("from_status", "to_status")},
            },
        ),
        # --- ProviderHelpdesk (with final backend_type choices) ---
        migrations.CreateModel(
            name="ProviderHelpdesk",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("uuid", waldur_core.core.fields.UUIDField()),
                (
                    "backend_type",
                    models.CharField(
                        choices=[
                            ("basic", "Basic (built-in)"),
                            ("email", "Email"),
                            ("atlassian", "Atlassian JIRA"),
                            ("zammad", "Zammad"),
                            ("smax", "SMAX"),
                        ],
                        default="basic",
                        max_length=50,
                    ),
                ),
                (
                    "settings",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Backend-specific configuration.",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("webhook_secret", models.CharField(blank=True, max_length=255)),
                (
                    "notification_email",
                    models.EmailField(
                        blank=True,
                        help_text="Primary email for notifications.",
                        max_length=254,
                    ),
                ),
                ("notify_on_new_ticket", models.BooleanField(default=True)),
                ("notify_on_comment", models.BooleanField(default=True)),
                ("notify_on_escalation", models.BooleanField(default=True)),
                ("notify_on_sla_warning", models.BooleanField(default=True)),
                ("last_health_check", models.DateTimeField(blank=True, null=True)),
                ("last_health_status", models.CharField(blank=True, max_length=50)),
                ("failed_routing_count", models.PositiveIntegerField(default=0)),
                (
                    "service_provider",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="provider_helpdesk",
                        to="marketplace.serviceprovider",
                    ),
                ),
            ],
            options={
                "verbose_name": "Provider helpdesk",
                "verbose_name_plural": "Provider helpdesks",
            },
        ),
        # --- Routing fields on Issue ---
        migrations.AddField(
            model_name="issue",
            name="parent_issue",
            field=models.ForeignKey(
                blank=True,
                help_text="Parent issue if this is a provider-routed child issue.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="child_issues",
                to="support.issue",
            ),
        ),
        migrations.AddField(
            model_name="issue",
            name="provider_helpdesk",
            field=models.ForeignKey(
                blank=True,
                help_text="Provider helpdesk this issue was routed to.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="issues",
                to="support.providerhelpdesk",
            ),
        ),
        migrations.AddField(
            model_name="issue",
            name="escalated_at",
            field=models.DateTimeField(
                blank=True, help_text="When the issue was escalated.", null=True
            ),
        ),
        migrations.AddField(
            model_name="issue",
            name="escalation_reason",
            field=models.TextField(blank=True, help_text="Reason for escalation."),
        ),
        migrations.AddField(
            model_name="issue",
            name="is_escalated",
            field=models.BooleanField(
                default=False, help_text="Whether this issue has been escalated."
            ),
        ),
        # --- Comment forwarding ---
        migrations.AddField(
            model_name="comment",
            name="is_forwarded",
            field=models.BooleanField(
                default=False,
                help_text="Whether this comment was forwarded from a parent/child issue.",
            ),
        ),
        # --- ProviderSupportUser ---
        migrations.CreateModel(
            name="ProviderSupportUser",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("uuid", waldur_core.core.fields.UUIDField()),
                (
                    "role",
                    models.CharField(
                        choices=[("agent", "Agent"), ("manager", "Manager")],
                        default="agent",
                        max_length=50,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "skills",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of skill tags for routing.",
                    ),
                ),
                (
                    "max_open_tickets",
                    models.PositiveIntegerField(
                        default=20,
                        help_text="Maximum number of open tickets this user can handle.",
                    ),
                ),
                (
                    "provider_helpdesk",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="support_users",
                        to="support.providerhelpdesk",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="provider_support_roles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["user__first_name", "user__last_name"],
                "unique_together": {("provider_helpdesk", "user")},
            },
        ),
        # --- ProviderCannedResponse ---
        migrations.CreateModel(
            name="ProviderCannedResponse",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=150,
                        validators=[waldur_core.core.validators.validate_name],
                        verbose_name="name",
                    ),
                ),
                ("uuid", waldur_core.core.fields.UUIDField()),
                (
                    "text",
                    models.TextField(
                        help_text="Template text. Supports Django template syntax."
                    ),
                ),
                ("category", models.CharField(blank=True, max_length=255)),
                ("usage_count", models.PositiveIntegerField(default=0)),
                (
                    "provider_helpdesk",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="canned_responses",
                        to="support.providerhelpdesk",
                    ),
                ),
            ],
            options={
                "ordering": ["-usage_count", "name"],
            },
        ),
        # --- Issue provider_assignee ---
        migrations.AddField(
            model_name="issue",
            name="provider_assignee",
            field=models.ForeignKey(
                blank=True,
                help_text="Provider support user assigned to this issue.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_issues",
                to="support.providersupportuser",
            ),
        ),
        # --- IssueTag ---
        migrations.CreateModel(
            name="IssueTag",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=150,
                        validators=[waldur_core.core.validators.validate_name],
                        verbose_name="name",
                    ),
                ),
                ("uuid", waldur_core.core.fields.UUIDField()),
                (
                    "color",
                    models.CharField(
                        blank=True,
                        help_text="Hex color code, e.g. #FF0000.",
                        max_length=7,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="issue",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="issues", to="support.issuetag"
            ),
        ),
        # --- IssueLink ---
        migrations.CreateModel(
            name="IssueLink",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uuid", waldur_core.core.fields.UUIDField()),
                (
                    "link_type",
                    models.CharField(
                        choices=[
                            ("related", "Related"),
                            ("blocked_by", "Blocked by"),
                            ("duplicates", "Duplicates"),
                        ],
                        default="related",
                        max_length=50,
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outgoing_links",
                        to="support.issue",
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incoming_links",
                        to="support.issue",
                    ),
                ),
            ],
            options={
                "ordering": ["source", "target"],
                "unique_together": {("source", "target")},
            },
        ),
        # --- SavedFilter ---
        migrations.CreateModel(
            name="SavedFilter",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=150,
                        validators=[waldur_core.core.validators.validate_name],
                        verbose_name="name",
                    ),
                ),
                ("uuid", waldur_core.core.fields.UUIDField()),
                (
                    "filter_params",
                    models.JSONField(
                        default=dict, help_text="Saved filter parameters as JSON."
                    ),
                ),
                (
                    "is_shared",
                    models.BooleanField(
                        default=False,
                        help_text="If True, visible to all staff/support users.",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_filters",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-modified"],
            },
        ),
        # --- CannedResponse (operator-level) ---
        migrations.CreateModel(
            name="CannedResponse",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=150,
                        validators=[waldur_core.core.validators.validate_name],
                        verbose_name="name",
                    ),
                ),
                ("uuid", waldur_core.core.fields.UUIDField()),
                (
                    "text",
                    models.TextField(
                        help_text="Template text. Supports Django template syntax."
                    ),
                ),
                ("category", models.CharField(blank=True, max_length=255)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["category", "name"],
            },
        ),
    ]
