# Generated by Django 6.0.8 on 2026-08-20 13:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("support", "0025_alter_attachment_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cannedresponse",
            options={"ordering": ["category", "name", "id"]},
        ),
        migrations.AlterModelOptions(
            name="comment",
            options={"ordering": ["-created", "id"]},
        ),
        migrations.AlterModelOptions(
            name="issue",
            options={"ordering": ["-created", "id"]},
        ),
        migrations.AlterModelOptions(
            name="issuelink",
            options={"ordering": ["source", "target", "id"]},
        ),
        migrations.AlterModelOptions(
            name="issuetag",
            options={"ordering": ["name", "id"]},
        ),
        migrations.AlterModelOptions(
            name="providercannedresponse",
            options={"ordering": ["-usage_count", "name", "id"]},
        ),
        migrations.AlterModelOptions(
            name="providerhelpdesk",
            options={
                "ordering": ["-created", "id"],
                "verbose_name": "Provider helpdesk",
                "verbose_name_plural": "Provider helpdesks",
            },
        ),
        migrations.AlterModelOptions(
            name="providersupportuser",
            options={"ordering": ["user__first_name", "user__last_name", "id"]},
        ),
        migrations.AlterModelOptions(
            name="requesttype",
            options={"ordering": ["order", "name", "id"]},
        ),
        migrations.AlterModelOptions(
            name="savedfilter",
            options={"ordering": ["-modified", "id"]},
        ),
        migrations.AlterModelOptions(
            name="supportuser",
            options={"ordering": ["name", "id"]},
        ),
    ]
