#!/usr/bin/env bash
set -e

echo '[+] Copying source code'
cp -r /mnt /tmp

echo '[+] Cleaning up jUnit test report directory'
rm -rf /mnt/test_reports
mkdir /mnt/test_reports

echo '[+] Copying pip cache from host to guest'
rsync \
    --archive \
    --recursive \
    --ignore-existing \
    --chown root:root \
    /tmp/pip-cache/ \
    /root/.cache/pip/

echo '[+] Installing Python package under test'
cd /tmp/mnt
pip install --editable .

echo '[+] Copying pip cache from guest to host'
rsync \
    --archive \
    --recursive \
    --ignore-existing \
    --chown user:user \
    /root/.cache/pip/ \
    /tmp/pip-cache/

chown -R user:user /tmp/pip-cache

echo '[+] Running Python linter'
flake8 --ignore E501 --exclude=*migrations* src/

echo '[+] Running security tests'
bandit --ini .bandit -x waldur-core,tests -r src/

echo '[+] Generating Django configuration for application'
cat > /tmp/mnt/src/waldur_mastermind/test_settings.py << EOF
from waldur_core.server.test_settings import *

DATABASES = { 
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'waldur',
        'USER': 'root',
        'HOST': 'db',
        'PORT': 5432,
        'PASSWORD': 'secret',
    }
}
EOF

echo '[+] Running unit tests'
pytest \
    --numprocesses=${NUM_PROCESSES} \
    --nomigrations \
    --reuse-db \
    --ds=waldur_mastermind.test_settings \
    --pyargs waldur_mastermind waldur_core.core \
    --junitxml=/mnt/test_reports/junit.xml

chown -R user:user /mnt/test_reports/
