#!/usr/bin/env bash
set -e

echo '[+] Copying source code'
cp -r /mnt /tmp

echo '[+] Cleaning up jUnit test report directory'
rm -rf /mnt/test_reports
mkdir /mnt/test_reports

echo '[+] Installing Python package under test'
cd /tmp/mnt
python setup.py develop

echo '[+] Running Python linter'
flake8 --ignore E501 --exclude=*migrations* src/

echo '[+] Running security tests'
bandit --ini .bandit -x waldur-core,tests -r src/

echo '[+] Generating Django configuration for application'
cat > /tmp/mnt/src/waldur_mastermind/test_settings.py << EOF
from waldur_core.server.test_settings import *

DATABASES = { 
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'waldur',
        'USER': 'root',
        'HOST': 'db',
        'PORT': 5432,
        'PASSWORD': 'secret',
    }
}
EOF

echo '[+] Running unit tests'
pytest \
    --numprocesses=5 \
    --nomigrations \
    --ds=waldur_mastermind.test_settings \
    --pyargs waldur_mastermind waldur_core.core \
    --junitxml=/mnt/test_reports/junit.xml

chown -R user:user /mnt/test_reports/
