collections:
  - namespace: waldur
    name: structure
    version: 1.0.0
    modules:
      project:
        type: crud
        resource_type: project
        operations:
          list: projects_list
          create: projects_create
          destroy: projects_destroy
        resolvers:
          customer:
            list: customers_list
            retrieve: customers_retrieve
          type:
            list: project_types_list
            retrieve: project_types_retrieve
      customer:
        type: crud
        resource_type: customer
        operations:
          list: customers_list
          create: customers_create
          destroy: customers_destroy
        skip_resolver_check:
          - homepage
  - namespace: waldur
    name: openstack
    version: 1.0.0
    modules:
      instance_facts:
        type: facts
        resource_type: openstack_instance
        list_operation: openstack_instances_list
        retrieve_operation: openstack_instances_retrieve
      security_group_facts:
        type: facts
        resource_type: security_group
        list_operation: openstack_security_groups_list
        retrieve_operation: openstack_security_groups_retrieve
        many: true
        context_params:
          - name: tenant
            resolver:
              list: openstack_tenants_list
              retrieve: openstack_tenants_retrieve
              filter_key: tenant_uuid
      subnet_facts:
        type: facts
        resource_type: subnet
        list_operation: openstack_subnets_list
        retrieve_operation: openstack_subnets_retrieve
        many: true
        context_params:
          - name: tenant
            resolver:
              list: openstack_tenants_list
              retrieve: openstack_tenants_retrieve
              filter_key: tenant_uuid
      vpc:
        type: order
        offering_type: OpenStack.Tenant
        description: Create, update, or delete an OpenStack Tenant via the marketplace.
        resource_type: OpenStack tenant
        has_limits: true
        existence_check_op: openstack_tenants_list
      volume:
        type: order
        offering_type: OpenStack.Volume
        description: Create, update, or delete an OpenStack Volume via the marketplace.
        resource_type: OpenStack volume

        existence_check_op: openstack_volumes_list
        update_op: openstack_volumes_update
        update_check_fields:
          - description

        resolvers:
          type:
            list: openstack_volume_types_list
            retrieve: openstack_volume_types_retrieve
          image:
            list: openstack_images_list
            retrieve: openstack_images_retrieve
          availability_zone:
            list: openstack_volume_availability_zones_list
            retrieve: openstack_volume_availability_zones_retrieve
      instance:
        type: order
        offering_type: OpenStack.Instance

        description: "Create or delete an OpenStack Instance."
        resource_type: "OpenStack instance"

        existence_check_op: "openstack_instances_list"

        resolvers:
          flavor:
            list: "openstack_flavors_list"
            retrieve: "openstack_flavors_retrieve"
          image:
            list: "openstack_images_list"
            retrieve: "openstack_images_retrieve"
          system_volume_type:
            list: "openstack_volume_types_list"
            retrieve: "openstack_volume_types_retrieve"
          data_volume_type:
            list: "openstack_volume_types_list"
            retrieve: "openstack_volume_types_retrieve"
          ssh_key:
            list: "keys_list"
            retrieve: "keys_retrieve"
