# Generated by Django 4.2.18 on 2025-02-12 11:40

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.conf import settings
from django.db import migrations, models

import waldur_core.core.fields
import waldur_core.core.validators

# Functions from the following migrations need manual copying.
# Move them and any dependencies into this file, then update the
# RunPython operations to refer to the local versions:
# waldur_core.permissions.migrations.0002_
# waldur_core.permissions.migrations.0003_role_is_system_role
from waldur_core.permissions.enums import RoleEnum


def fill_system_roles_1(apps, schema_editor):
    ContentType = apps.get_model("contenttypes", "ContentType")

    Role = apps.get_model("permissions", "Role")
    UserRole = apps.get_model("permissions", "UserRole")

    Customer = apps.get_model("structure", "Customer")
    CustomerPermission = apps.get_model("structure", "CustomerPermission")

    Project = apps.get_model("structure", "Project")
    ProjectPermission = apps.get_model("structure", "ProjectPermission")

    Offering = apps.get_model("marketplace", "Offering")
    OfferingPermission = apps.get_model("marketplace", "OfferingPermission")

    customer_ct = ContentType.objects.get_for_model(Customer)
    project_ct = ContentType.objects.get_for_model(Project)
    offering_ct = ContentType.objects.get_for_model(Offering)

    customer_owner = Role.objects.create(
        name=RoleEnum.CUSTOMER_OWNER,
        description="Organization owner",
    )
    customer_support = Role.objects.create(
        name=RoleEnum.CUSTOMER_SUPPORT,
        description="Organization support",
    )
    customer_manager = Role.objects.create(
        name=RoleEnum.CUSTOMER_MANAGER,
        description="Organization service manager",
    )
    project_admin = Role.objects.create(
        name=RoleEnum.PROJECT_ADMIN,
        description="Project administator",
    )
    project_manager = Role.objects.create(
        name=RoleEnum.PROJECT_MANAGER,
        description="Project manager",
    )
    project_member = Role.objects.create(
        name=RoleEnum.PROJECT_MEMBER,
        description="Project member",
    )
    offering_manager = Role.objects.create(
        name=RoleEnum.OFFERING_MANAGER,
        description="Offering manager",
    )

    def create_user_role(permission, **kwargs):
        UserRole.objects.create(
            user=permission.user,
            created_by=permission.created_by,
            created=permission.created,
            expiration_time=permission.expiration_time,
            is_active=permission.is_active,
            **kwargs,
        )

    for permission in CustomerPermission.objects.all():
        role = None
        if permission.role == "owner":
            role = customer_owner
        elif permission.role == "support":
            role = customer_support
        elif permission.role == "service_manager":
            role = customer_manager
        create_user_role(
            permission,
            content_type=customer_ct,
            object_id=permission.customer_id,
            role=role,
        )

    for permission in ProjectPermission.objects.all():
        role = None
        if permission.role == "admin":
            role = project_admin
        elif permission.role == "manager":
            role = project_manager
        elif permission.role == "member":
            role = project_member
        create_user_role(
            permission,
            content_type=project_ct,
            object_id=permission.project_id,
            role=role,
        )

    for permission in OfferingPermission.objects.all():
        create_user_role(
            permission,
            content_type=offering_ct,
            object_id=permission.offering_id,
            role=offering_manager,
        )


def fill_system_roles_2(apps, schema_editor):
    Role = apps.get_model("permissions", "Role")
    Role.objects.all().update(is_system_role=True)


def fill_system_roles_3(apps, schema_editor):
    ContentType = apps.get_model("contenttypes", "ContentType")
    Role = apps.get_model("permissions", "Role")
    Customer = apps.get_model("structure", "Customer")
    Project = apps.get_model("structure", "Project")
    Offering = apps.get_model("marketplace", "Offering")

    customer_ct = ContentType.objects.get_for_model(Customer)
    project_ct = ContentType.objects.get_for_model(Project)
    offering_ct = ContentType.objects.get_for_model(Offering)

    Role.objects.filter(name=RoleEnum.CUSTOMER_OWNER).update(content_type=customer_ct)
    Role.objects.filter(name=RoleEnum.CUSTOMER_SUPPORT).update(content_type=customer_ct)
    Role.objects.filter(name=RoleEnum.CUSTOMER_MANAGER).update(content_type=customer_ct)
    Role.objects.filter(name=RoleEnum.PROJECT_ADMIN).update(content_type=project_ct)
    Role.objects.filter(name=RoleEnum.PROJECT_MANAGER).update(content_type=project_ct)
    Role.objects.filter(name=RoleEnum.PROJECT_MEMBER).update(content_type=project_ct)
    Role.objects.filter(name=RoleEnum.OFFERING_MANAGER).update(content_type=offering_ct)
    Role.objects.filter(content_type=None).update(content_type=customer_ct)


class Migration(migrations.Migration):
    replaces = [
        ("permissions", "0001_initial"),
        ("permissions", "0002_import_data"),
        ("permissions", "0003_role_is_system_role"),
        ("permissions", "0004_translation"),
        ("permissions", "0005_alter_role_name"),
        ("permissions", "0006_role_content_type"),
        ("permissions", "0007_role_is_active"),
    ]

    dependencies = [
        ("marketplace", "0001_squashed_0076"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("contenttypes", "0002_remove_content_type_name"),
        ("structure", "0001_squashed_0036"),
    ]

    operations = [
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=2000, verbose_name="description"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=150,
                        validators=[waldur_core.core.validators.validate_name],
                        verbose_name="name",
                    ),
                ),
                ("uuid", waldur_core.core.fields.UUIDField()),
            ],
            options={
                "abstract": False,
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="UserRole",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uuid", waldur_core.core.fields.UUIDField()),
                ("object_id", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("expiration_time", models.DateTimeField(blank=True, null=True)),
                (
                    "is_active",
                    models.BooleanField(db_index=True, default=True, null=True),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="permissions.role",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
                "ordering": ["created"],
            },
        ),
        migrations.CreateModel(
            name="RolePermission",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("permission", models.CharField(db_index=True, max_length=100)),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="permissions",
                        to="permissions.role",
                    ),
                ),
            ],
        ),
        migrations.RunPython(
            code=fill_system_roles_1,
        ),
        migrations.AddField(
            model_name="role",
            name="is_system_role",
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(
            code=fill_system_roles_2,
        ),
        migrations.AddField(
            model_name="role",
            name="description_da",
            field=models.CharField(
                blank=True, max_length=2000, null=True, verbose_name="description"
            ),
        ),
        migrations.AddField(
            model_name="role",
            name="description_de",
            field=models.CharField(
                blank=True, max_length=2000, null=True, verbose_name="description"
            ),
        ),
        migrations.AddField(
            model_name="role",
            name="description_en",
            field=models.CharField(
                blank=True, max_length=2000, null=True, verbose_name="description"
            ),
        ),
        migrations.AddField(
            model_name="role",
            name="description_es",
            field=models.CharField(
                blank=True, max_length=2000, null=True, verbose_name="description"
            ),
        ),
        migrations.AddField(
            model_name="role",
            name="description_et",
            field=models.CharField(
                blank=True, max_length=2000, null=True, verbose_name="description"
            ),
        ),
        migrations.AddField(
            model_name="role",
            name="description_fr",
            field=models.CharField(
                blank=True, max_length=2000, null=True, verbose_name="description"
            ),
        ),
        migrations.AddField(
            model_name="role",
            name="description_it",
            field=models.CharField(
                blank=True, max_length=2000, null=True, verbose_name="description"
            ),
        ),
        migrations.AddField(
            model_name="role",
            name="description_lt",
            field=models.CharField(
                blank=True, max_length=2000, null=True, verbose_name="description"
            ),
        ),
        migrations.AddField(
            model_name="role",
            name="description_lv",
            field=models.CharField(
                blank=True, max_length=2000, null=True, verbose_name="description"
            ),
        ),
        migrations.AddField(
            model_name="role",
            name="description_nb",
            field=models.CharField(
                blank=True, max_length=2000, null=True, verbose_name="description"
            ),
        ),
        migrations.AddField(
            model_name="role",
            name="description_ru",
            field=models.CharField(
                blank=True, max_length=2000, null=True, verbose_name="description"
            ),
        ),
        migrations.AddField(
            model_name="role",
            name="description_sv",
            field=models.CharField(
                blank=True, max_length=2000, null=True, verbose_name="description"
            ),
        ),
        migrations.AlterField(
            model_name="role",
            name="name",
            field=models.CharField(db_index=True, max_length=150, unique=True),
        ),
        migrations.AddField(
            model_name="role",
            name="content_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="contenttypes.contenttype",
            ),
        ),
        migrations.RunPython(fill_system_roles_3),
        migrations.AlterField(
            model_name="role",
            name="content_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddField(
            model_name="role",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
