# Generated by Django 6.0.8 on 2026-08-28 11:46

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.conf import settings
from django.db import migrations, models

import waldur_core.core.fields


class Migration(migrations.Migration):
    replaces = [
        ("permissions", "0001_initial"),
        ("permissions", "0002_import_data"),
        ("permissions", "0003_role_is_system_role"),
        ("permissions", "0004_translation"),
        ("permissions", "0005_alter_role_name"),
        ("permissions", "0006_role_content_type"),
        ("permissions", "0007_role_is_active"),
        ("permissions", "0008_customer_role"),
        ("permissions", "0009_drop_duplicates"),
        ("permissions", "0010_role_description_ar"),
        ("permissions", "0011_role_description_cs"),
        ("permissions", "00012_rename_order_item_permissions"),
        ("permissions", "0013_alter_rolepermission_unique_together"),
        ("permissions", "0014_unify_log"),
        ("permissions", "0015_customer_manager"),
        ("permissions", "0016_userrole_modified_alter_userrole_created"),
        ("permissions", "0017_role_description_bg_role_description_el_and_more"),
        (
            "permissions",
            "0018_alter_role_description_alter_role_description_ar_and_more",
        ),
        ("permissions", "0019_order_create_permission"),
        ("permissions", "0020_set_consumer_info_permission"),
        ("permissions", "0021_alter_role_name_roleavailability"),
        ("permissions", "0022_userrole_revoke_reason_userrole_revoked_by"),
        ("permissions", "0023_customerroleconcealment"),
        ("permissions", "0024_role_description_km"),
        ("permissions", "0025_alter_role_options_alter_userrole_options"),
        ("permissions", "0026_role_description_hr"),
    ]

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("core", "__first__"),
        ("marketplace", "0001_squashed_0076"),
        ("structure", "0001_squashed_0036"),
    ]

    operations = [
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=4096, verbose_name="description"
                    ),
                ),
                (
                    "description_en",
                    models.CharField(
                        blank=True,
                        max_length=4096,
                        null=True,
                        verbose_name="description",
                    ),
                ),
                (
                    "description_et",
                    models.CharField(
                        blank=True,
                        max_length=4096,
                        null=True,
                        verbose_name="description",
                    ),
                ),
                (
                    "description_lt",
                    models.CharField(
                        blank=True,
                        max_length=4096,
                        null=True,
                        verbose_name="description",
                    ),
                ),
                (
                    "description_lv",
                    models.CharField(
                        blank=True,
                        max_length=4096,
                        null=True,
                        verbose_name="description",
                    ),
                ),
                (
                    "description_ru",
                    models.CharField(
                        blank=True,
                        max_length=4096,
                        null=True,
                        verbose_name="description",
                    ),
                ),
                (
                    "description_it",
                    models.CharField(
                        blank=True,
                        max_length=4096,
                        null=True,
                        verbose_name="description",
                    ),
                ),
                (
                    "description_de",
                    models.CharField(
                        blank=True,
                        max_length=4096,
                        null=True,
                        verbose_name="description",
                    ),
                ),
                (
                    "description_da",
                    models.CharField(
                        blank=True,
                        max_length=4096,
                        null=True,
                        verbose_name="description",
                    ),
                ),
                (
                    "description_sv",
                    models.CharField(
                        blank=True,
                        max_length=4096,
                        null=True,
                        verbose_name="description",
                    ),
                ),
                (
                    "description_es",
                    models.CharField(
                        blank=True,
                        max_length=4096,
                        null=True,
                        verbose_name="description",
                    ),
                ),
                (
                    "description_fr",
                    models.CharField(
                        blank=True,
                        max_length=4096,
                        null=True,
                        verbose_name="description",
                    ),
                ),
                (
                    "description_nb",
                    models.CharField(
                        blank=True,
                        max_length=4096,
                        null=True,
                        verbose_name="description",
                    ),
                ),
                (
                    "description_ar",
                    models.CharField(
                        blank=True,
                        max_length=4096,
                        null=True,
                        verbose_name="description",
                    ),
                ),
                (
                    "description_cs",
                    models.CharField(
                        blank=True,
                        max_length=4096,
                        null=True,
                        verbose_name="description",
                    ),
                ),
                (
                    "description_hr",
                    models.CharField(
                        blank=True,
                        max_length=4096,
                        null=True,
                        verbose_name="description",
                    ),
                ),
                (
                    "description_sl",
                    models.CharField(
                        blank=True,
                        max_length=4096,
                        null=True,
                        verbose_name="description",
                    ),
                ),
                (
                    "description_el",
                    models.CharField(
                        blank=True,
                        max_length=4096,
                        null=True,
                        verbose_name="description",
                    ),
                ),
                (
                    "description_bg",
                    models.CharField(
                        blank=True,
                        max_length=4096,
                        null=True,
                        verbose_name="description",
                    ),
                ),
                (
                    "description_km",
                    models.CharField(
                        blank=True,
                        max_length=4096,
                        null=True,
                        verbose_name="description",
                    ),
                ),
                ("uuid", waldur_core.core.fields.UUIDField()),
                ("name", models.CharField(db_index=True, max_length=150)),
                ("is_system_role", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="clones",
                        to="permissions.role",
                    ),
                ),
            ],
            options={
                "ordering": ["name", "id"],
            },
        ),
        migrations.CreateModel(
            name="UserRole",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("uuid", waldur_core.core.fields.UUIDField()),
                ("object_id", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "revoke_reason",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("expiration_time", models.DateTimeField(blank=True, null=True)),
                (
                    "is_active",
                    models.BooleanField(db_index=True, default=True, null=True),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "revoked_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="permissions.role",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["created", "id"],
            },
        ),
        migrations.CreateModel(
            name="CustomerRoleConcealment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uuid", waldur_core.core.fields.UUIDField()),
                ("object_id", models.PositiveIntegerField()),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="concealments",
                        to="permissions.role",
                    ),
                ),
            ],
            options={
                "unique_together": {("role", "content_type", "object_id")},
            },
        ),
        migrations.CreateModel(
            name="RoleAvailability",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uuid", waldur_core.core.fields.UUIDField()),
                ("object_id", models.PositiveIntegerField()),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="availability",
                        to="permissions.role",
                    ),
                ),
            ],
            options={
                "unique_together": {("role", "content_type", "object_id")},
            },
        ),
        migrations.CreateModel(
            name="RolePermission",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("permission", models.CharField(db_index=True, max_length=100)),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="permissions",
                        to="permissions.role",
                    ),
                ),
            ],
            options={
                "unique_together": {("role", "permission")},
            },
        ),
    ]
