# Generated by Django 6.0.8 on 2026-09-03 15:36

from importlib import import_module

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.conf import settings
from django.db import migrations, models

import waldur_core.core.fields
import waldur_core.core.migration_operations
import waldur_core.core.validators


def _original(name):
    """A replaced migration's module: its data code runs from there, unchanged."""
    return import_module(__name__.rpartition(".")[0] + "." + name)


class Migration(migrations.Migration):
    replaces = [
        ("permissions", "0001_initial"),
        ("permissions", "0002_import_data"),
        ("permissions", "0003_role_is_system_role"),
        ("permissions", "0004_translation"),
        ("permissions", "0005_alter_role_name"),
        ("permissions", "0006_role_content_type"),
        ("permissions", "0007_role_is_active"),
        ("permissions", "0008_customer_role"),
        ("permissions", "0009_drop_duplicates"),
        ("permissions", "0010_role_description_ar"),
        ("permissions", "0011_role_description_cs"),
        ("permissions", "00012_rename_order_item_permissions"),
        ("permissions", "0013_alter_rolepermission_unique_together"),
        ("permissions", "0014_unify_log"),
        ("permissions", "0015_customer_manager"),
        ("permissions", "0016_userrole_modified_alter_userrole_created"),
        ("permissions", "0017_role_description_bg_role_description_el_and_more"),
        (
            "permissions",
            "0018_alter_role_description_alter_role_description_ar_and_more",
        ),
        ("permissions", "0019_order_create_permission"),
        ("permissions", "0020_set_consumer_info_permission"),
        ("permissions", "0021_alter_role_name_roleavailability"),
        ("permissions", "0022_userrole_revoke_reason_userrole_revoked_by"),
        ("permissions", "0023_customerroleconcealment"),
        ("permissions", "0024_role_description_km"),
        ("permissions", "0025_alter_role_options_alter_userrole_options"),
        ("permissions", "0026_role_description_hr"),
    ]

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("core", "__first__"),
        ("logging", "0028_split_openstack_resource_event_groups"),
        ("marketplace", "0001_squashed_0076"),
        ("marketplace", "0107_merge_order_item_with_order_step3"),
        ("structure", "0001_squashed_0036"),
        ("structure", "0040_useragreement_uuid"),
    ]

    operations = [
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=2000, verbose_name="description"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=150,
                        validators=[waldur_core.core.validators.validate_name],
                        verbose_name="name",
                    ),
                ),
                ("uuid", waldur_core.core.fields.UUIDField()),
            ],
            options={
                "abstract": False,
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="RolePermission",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("permission", models.CharField(db_index=True, max_length=100)),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="permissions",
                        to="permissions.role",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserRole",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uuid", waldur_core.core.fields.UUIDField()),
                ("object_id", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("expiration_time", models.DateTimeField(blank=True, null=True)),
                (
                    "is_active",
                    models.BooleanField(db_index=True, default=True, null=True),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="permissions.role",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
                "ordering": ["created"],
            },
        ),
        waldur_core.core.migration_operations.FlushDeferredSql(),
        migrations.RunPython(
            code=_original("0002_import_data").fill_system_roles,
        ),
        migrations.AddField(
            model_name="role",
            name="is_system_role",
            field=models.BooleanField(default=False),
        ),
        waldur_core.core.migration_operations.FlushDeferredSql(),
        migrations.RunPython(
            code=_original("0003_role_is_system_role").fill_system_roles,
        ),
        migrations.AddField(
            model_name="role",
            name="content_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddField(
            model_name="role",
            name="description_da",
            field=models.CharField(
                blank=True, max_length=2000, null=True, verbose_name="description"
            ),
        ),
        migrations.AddField(
            model_name="role",
            name="description_de",
            field=models.CharField(
                blank=True, max_length=2000, null=True, verbose_name="description"
            ),
        ),
        migrations.AddField(
            model_name="role",
            name="description_en",
            field=models.CharField(
                blank=True, max_length=2000, null=True, verbose_name="description"
            ),
        ),
        migrations.AddField(
            model_name="role",
            name="description_es",
            field=models.CharField(
                blank=True, max_length=2000, null=True, verbose_name="description"
            ),
        ),
        migrations.AddField(
            model_name="role",
            name="description_et",
            field=models.CharField(
                blank=True, max_length=2000, null=True, verbose_name="description"
            ),
        ),
        migrations.AddField(
            model_name="role",
            name="description_fr",
            field=models.CharField(
                blank=True, max_length=2000, null=True, verbose_name="description"
            ),
        ),
        migrations.AddField(
            model_name="role",
            name="description_it",
            field=models.CharField(
                blank=True, max_length=2000, null=True, verbose_name="description"
            ),
        ),
        migrations.AddField(
            model_name="role",
            name="description_lt",
            field=models.CharField(
                blank=True, max_length=2000, null=True, verbose_name="description"
            ),
        ),
        migrations.AddField(
            model_name="role",
            name="description_lv",
            field=models.CharField(
                blank=True, max_length=2000, null=True, verbose_name="description"
            ),
        ),
        migrations.AddField(
            model_name="role",
            name="description_nb",
            field=models.CharField(
                blank=True, max_length=2000, null=True, verbose_name="description"
            ),
        ),
        migrations.AddField(
            model_name="role",
            name="description_ru",
            field=models.CharField(
                blank=True, max_length=2000, null=True, verbose_name="description"
            ),
        ),
        migrations.AddField(
            model_name="role",
            name="description_sv",
            field=models.CharField(
                blank=True, max_length=2000, null=True, verbose_name="description"
            ),
        ),
        migrations.AlterField(
            model_name="role",
            name="name",
            field=models.CharField(db_index=True, max_length=150, unique=True),
        ),
        waldur_core.core.migration_operations.FlushDeferredSql(),
        migrations.RunPython(
            code=_original("0006_role_content_type").fill_system_roles,
        ),
        migrations.AddField(
            model_name="role",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="role",
            name="content_type",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="contenttypes.contenttype",
            ),
            preserve_default=False,
        ),
        waldur_core.core.migration_operations.FlushDeferredSql(),
        migrations.RunPython(
            code=_original("0008_customer_role").create_customer_role,
        ),
        waldur_core.core.migration_operations.FlushDeferredSql(),
        migrations.RunPython(
            code=_original("0009_drop_duplicates").drop_duplicates,
        ),
        migrations.AddField(
            model_name="role",
            name="description_ar",
            field=models.CharField(
                blank=True, max_length=2000, null=True, verbose_name="description"
            ),
        ),
        migrations.AddField(
            model_name="role",
            name="description_cs",
            field=models.CharField(
                blank=True, max_length=2000, null=True, verbose_name="description"
            ),
        ),
        waldur_core.core.migration_operations.FlushDeferredSql(),
        migrations.RunPython(
            code=_original(
                "00012_rename_order_item_permissions"
            ).rename_order_item_permissions,
        ),
        waldur_core.core.migration_operations.FlushDeferredSql(),
        migrations.RunPython(
            code=_original(
                "0013_alter_rolepermission_unique_together"
            ).drop_role_permission_duplicates,
        ),
        migrations.AlterUniqueTogether(
            name="rolepermission",
            unique_together={("role", "permission")},
        ),
        waldur_core.core.migration_operations.FlushDeferredSql(),
        migrations.RunPython(
            code=_original("0014_unify_log").unify_log,
        ),
        waldur_core.core.migration_operations.FlushDeferredSql(),
        migrations.RunPython(
            code=_original("0015_customer_manager").upgrade_role,
        ),
        migrations.AddField(
            model_name="role",
            name="description_bg",
            field=models.CharField(
                blank=True, max_length=4096, null=True, verbose_name="description"
            ),
        ),
        migrations.AddField(
            model_name="role",
            name="description_el",
            field=models.CharField(
                blank=True, max_length=4096, null=True, verbose_name="description"
            ),
        ),
        migrations.AddField(
            model_name="role",
            name="description_sl",
            field=models.CharField(
                blank=True, max_length=4096, null=True, verbose_name="description"
            ),
        ),
        migrations.AddField(
            model_name="userrole",
            name="modified",
            field=model_utils.fields.AutoLastModifiedField(
                default=django.utils.timezone.now,
                editable=False,
                verbose_name="modified",
            ),
        ),
        migrations.AlterField(
            model_name="role",
            name="description",
            field=models.CharField(
                blank=True, max_length=4096, verbose_name="description"
            ),
        ),
        migrations.AlterField(
            model_name="role",
            name="description_ar",
            field=models.CharField(
                blank=True, max_length=4096, null=True, verbose_name="description"
            ),
        ),
        migrations.AlterField(
            model_name="role",
            name="description_cs",
            field=models.CharField(
                blank=True, max_length=4096, null=True, verbose_name="description"
            ),
        ),
        migrations.AlterField(
            model_name="role",
            name="description_da",
            field=models.CharField(
                blank=True, max_length=4096, null=True, verbose_name="description"
            ),
        ),
        migrations.AlterField(
            model_name="role",
            name="description_de",
            field=models.CharField(
                blank=True, max_length=4096, null=True, verbose_name="description"
            ),
        ),
        migrations.AlterField(
            model_name="role",
            name="description_en",
            field=models.CharField(
                blank=True, max_length=4096, null=True, verbose_name="description"
            ),
        ),
        migrations.AlterField(
            model_name="role",
            name="description_es",
            field=models.CharField(
                blank=True, max_length=4096, null=True, verbose_name="description"
            ),
        ),
        migrations.AlterField(
            model_name="role",
            name="description_et",
            field=models.CharField(
                blank=True, max_length=4096, null=True, verbose_name="description"
            ),
        ),
        migrations.AlterField(
            model_name="role",
            name="description_fr",
            field=models.CharField(
                blank=True, max_length=4096, null=True, verbose_name="description"
            ),
        ),
        migrations.AlterField(
            model_name="role",
            name="description_it",
            field=models.CharField(
                blank=True, max_length=4096, null=True, verbose_name="description"
            ),
        ),
        migrations.AlterField(
            model_name="role",
            name="description_lt",
            field=models.CharField(
                blank=True, max_length=4096, null=True, verbose_name="description"
            ),
        ),
        migrations.AlterField(
            model_name="role",
            name="description_lv",
            field=models.CharField(
                blank=True, max_length=4096, null=True, verbose_name="description"
            ),
        ),
        migrations.AlterField(
            model_name="role",
            name="description_nb",
            field=models.CharField(
                blank=True, max_length=4096, null=True, verbose_name="description"
            ),
        ),
        migrations.AlterField(
            model_name="role",
            name="description_ru",
            field=models.CharField(
                blank=True, max_length=4096, null=True, verbose_name="description"
            ),
        ),
        migrations.AlterField(
            model_name="role",
            name="description_sv",
            field=models.CharField(
                blank=True, max_length=4096, null=True, verbose_name="description"
            ),
        ),
        migrations.AlterField(
            model_name="userrole",
            name="created",
            field=model_utils.fields.AutoCreatedField(
                default=django.utils.timezone.now,
                editable=False,
                verbose_name="created",
            ),
        ),
        waldur_core.core.migration_operations.FlushDeferredSql(),
        migrations.RunPython(
            code=_original("0019_order_create_permission").add_order_create_permission,
            reverse_code=migrations.RunPython.noop,
        ),
        waldur_core.core.migration_operations.FlushDeferredSql(),
        migrations.RunPython(
            code=_original(
                "0020_set_consumer_info_permission"
            ).add_set_consumer_info_permission,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterModelOptions(
            name="role",
            options={"ordering": ["name", "id"]},
        ),
        migrations.AlterModelOptions(
            name="userrole",
            options={"ordering": ["created", "id"]},
        ),
        migrations.AddField(
            model_name="role",
            name="description_hr",
            field=models.CharField(
                blank=True, max_length=4096, null=True, verbose_name="description"
            ),
        ),
        migrations.AddField(
            model_name="role",
            name="description_km",
            field=models.CharField(
                blank=True, max_length=4096, null=True, verbose_name="description"
            ),
        ),
        migrations.AddField(
            model_name="role",
            name="template",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="clones",
                to="permissions.role",
            ),
        ),
        migrations.AddField(
            model_name="userrole",
            name="revoke_reason",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="userrole",
            name="revoked_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="role",
            name="name",
            field=models.CharField(db_index=True, max_length=150),
        ),
        migrations.CreateModel(
            name="CustomerRoleConcealment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uuid", waldur_core.core.fields.UUIDField()),
                ("object_id", models.PositiveIntegerField()),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="concealments",
                        to="permissions.role",
                    ),
                ),
            ],
            options={
                "unique_together": {("role", "content_type", "object_id")},
            },
        ),
        migrations.CreateModel(
            name="RoleAvailability",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uuid", waldur_core.core.fields.UUIDField()),
                ("object_id", models.PositiveIntegerField()),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="availability",
                        to="permissions.role",
                    ),
                ),
            ],
            options={
                "unique_together": {("role", "content_type", "object_id")},
            },
        ),
    ]
