# Generated by Django 3.2.20 on 2023-09-25 10:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("permissions", "0006_role_content_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="role",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
