# Generated by Django 4.2.18 on 2025-02-12 12:46

from django.core.exceptions import ObjectDoesNotExist
from django.db import migrations, models


def drop_duplicates(apps, schema_editor):
    Role = apps.get_model("permissions", "Role")
    RolePermission = apps.get_model("permissions", "RolePermission")

    for role in Role.objects.all():
        permissions = set(
            RolePermission.objects.filter(role=role).values_list(
                "permission", flat=True
            )
        )
        role.permissions.all().delete()
        RolePermission.objects.bulk_create(
            [
                RolePermission(role=role, permission=permission)
                for permission in permissions
            ]
        )


def rename_order_item_permissions(apps, schema_editor):
    RolePermission = apps.get_model("permissions", "RolePermission")

    for role in RolePermission.objects.filter(permission__contains="ORDER_ITEM"):
        role.permission = role.permission.replace("ORDER_ITEM", "ORDER").replace(
            "ORDER.TERMINATE", "ORDER.CANCEL"
        )
        role.save()


def drop_role_permission_duplicates(apps, schema_editor):
    RolePermission = apps.get_model("permissions", "RolePermission")
    role_permissions = RolePermission.objects.values_list("id", "role", "permission")
    distinct_role_permissions = set()
    for role_permission in role_permissions:
        mapping = role_permission[1:]
        if mapping in distinct_role_permissions:
            id_ = role_permission[0]
            RolePermission.objects.get(id=id_).delete()
        else:
            distinct_role_permissions.add(mapping)


ROLE_MAP = {
    ("customer", "owner"): "CUSTOMER.OWNER",
    ("customer", "service_manager"): "CUSTOMER.MANAGER",
    ("customer", "support"): "CUSTOMER.SUPPORT",
    ("project", "admin"): "PROJECT.ADMIN",
    ("project", "manager"): "PROJECT.MANAGER",
    ("project", "member"): "PROJECT.MEMBER",
    ("offering", None): "OFFERING.MANAGER",
}


def unify_log(apps, schema_editor):
    Event = apps.get_model("logging", "Event")
    for event in Event.objects.filter(
        event_type__in=["role_granted", "role_revoked", "role_updated"]
    ):
        scope_type = event.context.get("structure_type")
        if not scope_type:
            continue
        event.context["scope_type"] = scope_type
        event.context["scope_uuid"] = event.context[f"{scope_type}_uuid"]
        event.context["scope_name"] = event.context[f"{scope_type}_name"]
        old_role_name = event.context.get("role_name")
        if old_role_name:
            event.context["role_name"] = ROLE_MAP.get(
                (event.context["scope_type"], old_role_name.lower())
            )
        else:
            event.context["role_name"] = "OFFERING.MANAGER"
        del event.context["structure_type"]
        event.save()


def upgrade_role(apps, schema_editor):
    Role = apps.get_model("permissions", "Role")
    UserRole = apps.get_model("permissions", "UserRole")
    ContentType = apps.get_model("contenttypes", "ContentType")
    Customer = apps.get_model("structure", "Customer")
    ServiceProvider = apps.get_model("marketplace", "ServiceProvider")

    CustomerContentType = ContentType.objects.get_for_model(Customer)
    ServiceProviderContentType = ContentType.objects.get_for_model(ServiceProvider)

    Role.objects.filter(name="CUSTOMER.MANAGER").update(
        content_type=ServiceProviderContentType
    )

    for user_role in UserRole.objects.filter(
        role__name="CUSTOMER.MANAGER", content_type=CustomerContentType
    ):
        try:
            service_provider = ServiceProvider.objects.get(
                customer_id=user_role.object_id
            )
        except ObjectDoesNotExist:
            print(f"Service provider for customer {user_role.object_id} not found")
            continue
        user_role.content_type = ServiceProviderContentType
        user_role.object_id = service_provider.id
        user_role.save(update_fields=["content_type", "object_id"])


class Migration(migrations.Migration):
    replaces = [
        ("permissions", "0009_drop_duplicates"),
        ("permissions", "0010_role_description_ar"),
        ("permissions", "0011_role_description_cs"),
        ("permissions", "00012_rename_order_item_permissions"),
        ("permissions", "0013_alter_rolepermission_unique_together"),
        ("permissions", "0014_unify_log"),
        ("permissions", "0015_customer_manager"),
    ]

    dependencies = [
        ("permissions", "0008_customer_role"),
    ]

    operations = [
        migrations.RunPython(
            code=drop_duplicates,
        ),
        migrations.AddField(
            model_name="role",
            name="description_ar",
            field=models.CharField(
                blank=True, max_length=2000, null=True, verbose_name="description"
            ),
        ),
        migrations.AddField(
            model_name="role",
            name="description_cs",
            field=models.CharField(
                blank=True, max_length=2000, null=True, verbose_name="description"
            ),
        ),
        migrations.RunPython(
            code=rename_order_item_permissions,
        ),
        migrations.RunPython(
            code=drop_role_permission_duplicates,
        ),
        migrations.AlterUniqueTogether(
            name="rolepermission",
            unique_together={("role", "permission")},
        ),
        migrations.RunPython(
            code=unify_log,
        ),
        migrations.RunPython(
            code=upgrade_role,
        ),
    ]
