# Generated by Django 4.2.24 on 2025-10-20 10:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("permissions", "0017_role_description_bg_role_description_el_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="role",
            name="description",
            field=models.CharField(
                blank=True, max_length=4096, verbose_name="description"
            ),
        ),
        migrations.AlterField(
            model_name="role",
            name="description_ar",
            field=models.CharField(
                blank=True, max_length=4096, null=True, verbose_name="description"
            ),
        ),
        migrations.AlterField(
            model_name="role",
            name="description_bg",
            field=models.CharField(
                blank=True, max_length=4096, null=True, verbose_name="description"
            ),
        ),
        migrations.AlterField(
            model_name="role",
            name="description_cs",
            field=models.CharField(
                blank=True, max_length=4096, null=True, verbose_name="description"
            ),
        ),
        migrations.AlterField(
            model_name="role",
            name="description_da",
            field=models.CharField(
                blank=True, max_length=4096, null=True, verbose_name="description"
            ),
        ),
        migrations.AlterField(
            model_name="role",
            name="description_de",
            field=models.CharField(
                blank=True, max_length=4096, null=True, verbose_name="description"
            ),
        ),
        migrations.AlterField(
            model_name="role",
            name="description_el",
            field=models.CharField(
                blank=True, max_length=4096, null=True, verbose_name="description"
            ),
        ),
        migrations.AlterField(
            model_name="role",
            name="description_en",
            field=models.CharField(
                blank=True, max_length=4096, null=True, verbose_name="description"
            ),
        ),
        migrations.AlterField(
            model_name="role",
            name="description_es",
            field=models.CharField(
                blank=True, max_length=4096, null=True, verbose_name="description"
            ),
        ),
        migrations.AlterField(
            model_name="role",
            name="description_et",
            field=models.CharField(
                blank=True, max_length=4096, null=True, verbose_name="description"
            ),
        ),
        migrations.AlterField(
            model_name="role",
            name="description_fr",
            field=models.CharField(
                blank=True, max_length=4096, null=True, verbose_name="description"
            ),
        ),
        migrations.AlterField(
            model_name="role",
            name="description_it",
            field=models.CharField(
                blank=True, max_length=4096, null=True, verbose_name="description"
            ),
        ),
        migrations.AlterField(
            model_name="role",
            name="description_lt",
            field=models.CharField(
                blank=True, max_length=4096, null=True, verbose_name="description"
            ),
        ),
        migrations.AlterField(
            model_name="role",
            name="description_lv",
            field=models.CharField(
                blank=True, max_length=4096, null=True, verbose_name="description"
            ),
        ),
        migrations.AlterField(
            model_name="role",
            name="description_nb",
            field=models.CharField(
                blank=True, max_length=4096, null=True, verbose_name="description"
            ),
        ),
        migrations.AlterField(
            model_name="role",
            name="description_ru",
            field=models.CharField(
                blank=True, max_length=4096, null=True, verbose_name="description"
            ),
        ),
        migrations.AlterField(
            model_name="role",
            name="description_sl",
            field=models.CharField(
                blank=True, max_length=4096, null=True, verbose_name="description"
            ),
        ),
        migrations.AlterField(
            model_name="role",
            name="description_sv",
            field=models.CharField(
                blank=True, max_length=4096, null=True, verbose_name="description"
            ),
        ),
    ]
