# Generated by Django 6.0.7 on 2026-07-12 06:46

import django.db.models.deletion
from django.db import migrations, models

import waldur_core.core.fields


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("permissions", "0022_userrole_revoke_reason_userrole_revoked_by"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomerRoleConcealment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uuid", waldur_core.core.fields.UUIDField()),
                ("object_id", models.PositiveIntegerField()),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="concealments",
                        to="permissions.role",
                    ),
                ),
            ],
            options={
                "unique_together": {("role", "content_type", "object_id")},
            },
        ),
        migrations.AddField(
            model_name="role",
            name="template",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="clones",
                to="permissions.role",
            ),
        ),
    ]
