# Generated by Django 6.0.8 on 2026-08-27 11:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("permissions", "0025_alter_role_options_alter_userrole_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="role",
            name="description_hr",
            field=models.CharField(
                blank=True, max_length=4096, null=True, verbose_name="description"
            ),
        ),
    ]
