# Generated by Django 6.0.8 on 2026-09-08 21:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("permissions", "0027_role_description_mk_role_description_sq"),
    ]

    operations = [
        migrations.AddField(
            model_name="userrole",
            name="source",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="Provenance of a machine-issued grant, e.g. 'rule:<uuid>'. Empty for grants made by a person. Only rows carrying a source are eligible for automatic reconciliation.",
                max_length=150,
            ),
        ),
    ]
