# Generated by Django 4.2.19 on 2025-03-11 16:35

import django_fsm
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("waldur_azure", "0021_image_locations"),
    ]

    operations = [
        migrations.AlterField(
            model_name="network",
            name="state",
            field=django_fsm.FSMIntegerField(
                choices=[
                    (5, "CREATION_SCHEDULED"),
                    (6, "CREATING"),
                    (1, "UPDATE_SCHEDULED"),
                    (2, "UPDATING"),
                    (7, "DELETION_SCHEDULED"),
                    (8, "DELETING"),
                    (3, "OK"),
                    (4, "ERRED"),
                ],
                default=5,
            ),
        ),
        migrations.AlterField(
            model_name="networkinterface",
            name="state",
            field=django_fsm.FSMIntegerField(
                choices=[
                    (5, "CREATION_SCHEDULED"),
                    (6, "CREATING"),
                    (1, "UPDATE_SCHEDULED"),
                    (2, "UPDATING"),
                    (7, "DELETION_SCHEDULED"),
                    (8, "DELETING"),
                    (3, "OK"),
                    (4, "ERRED"),
                ],
                default=5,
            ),
        ),
        migrations.AlterField(
            model_name="publicip",
            name="state",
            field=django_fsm.FSMIntegerField(
                choices=[
                    (5, "CREATION_SCHEDULED"),
                    (6, "CREATING"),
                    (1, "UPDATE_SCHEDULED"),
                    (2, "UPDATING"),
                    (7, "DELETION_SCHEDULED"),
                    (8, "DELETING"),
                    (3, "OK"),
                    (4, "ERRED"),
                ],
                default=5,
            ),
        ),
        migrations.AlterField(
            model_name="resourcegroup",
            name="state",
            field=django_fsm.FSMIntegerField(
                choices=[
                    (5, "CREATION_SCHEDULED"),
                    (6, "CREATING"),
                    (1, "UPDATE_SCHEDULED"),
                    (2, "UPDATING"),
                    (7, "DELETION_SCHEDULED"),
                    (8, "DELETING"),
                    (3, "OK"),
                    (4, "ERRED"),
                ],
                default=5,
            ),
        ),
        migrations.AlterField(
            model_name="securitygroup",
            name="state",
            field=django_fsm.FSMIntegerField(
                choices=[
                    (5, "CREATION_SCHEDULED"),
                    (6, "CREATING"),
                    (1, "UPDATE_SCHEDULED"),
                    (2, "UPDATING"),
                    (7, "DELETION_SCHEDULED"),
                    (8, "DELETING"),
                    (3, "OK"),
                    (4, "ERRED"),
                ],
                default=5,
            ),
        ),
        migrations.AlterField(
            model_name="sqldatabase",
            name="state",
            field=django_fsm.FSMIntegerField(
                choices=[
                    (5, "CREATION_SCHEDULED"),
                    (6, "CREATING"),
                    (1, "UPDATE_SCHEDULED"),
                    (2, "UPDATING"),
                    (7, "DELETION_SCHEDULED"),
                    (8, "DELETING"),
                    (3, "OK"),
                    (4, "ERRED"),
                ],
                default=5,
            ),
        ),
        migrations.AlterField(
            model_name="sqlserver",
            name="state",
            field=django_fsm.FSMIntegerField(
                choices=[
                    (5, "CREATION_SCHEDULED"),
                    (6, "CREATING"),
                    (1, "UPDATE_SCHEDULED"),
                    (2, "UPDATING"),
                    (7, "DELETION_SCHEDULED"),
                    (8, "DELETING"),
                    (3, "OK"),
                    (4, "ERRED"),
                ],
                default=5,
            ),
        ),
        migrations.AlterField(
            model_name="storageaccount",
            name="state",
            field=django_fsm.FSMIntegerField(
                choices=[
                    (5, "CREATION_SCHEDULED"),
                    (6, "CREATING"),
                    (1, "UPDATE_SCHEDULED"),
                    (2, "UPDATING"),
                    (7, "DELETION_SCHEDULED"),
                    (8, "DELETING"),
                    (3, "OK"),
                    (4, "ERRED"),
                ],
                default=5,
            ),
        ),
        migrations.AlterField(
            model_name="subnet",
            name="state",
            field=django_fsm.FSMIntegerField(
                choices=[
                    (5, "CREATION_SCHEDULED"),
                    (6, "CREATING"),
                    (1, "UPDATE_SCHEDULED"),
                    (2, "UPDATING"),
                    (7, "DELETION_SCHEDULED"),
                    (8, "DELETING"),
                    (3, "OK"),
                    (4, "ERRED"),
                ],
                default=5,
            ),
        ),
        migrations.AlterField(
            model_name="virtualmachine",
            name="state",
            field=django_fsm.FSMIntegerField(
                choices=[
                    (5, "CREATION_SCHEDULED"),
                    (6, "CREATING"),
                    (1, "UPDATE_SCHEDULED"),
                    (2, "UPDATING"),
                    (7, "DELETION_SCHEDULED"),
                    (8, "DELETING"),
                    (3, "OK"),
                    (4, "ERRED"),
                ],
                default=5,
            ),
        ),
    ]
