# Generated by Django 6.0.8 on 2026-08-19 21:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("waldur_azure", "0024_sqlserver_is_available_virtualmachine_is_available"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="network",
            options={"ordering": ["-created", "id"]},
        ),
        migrations.AlterModelOptions(
            name="networkinterface",
            options={"ordering": ["-created", "id"]},
        ),
        migrations.AlterModelOptions(
            name="publicip",
            options={"ordering": ["-created", "id"]},
        ),
        migrations.AlterModelOptions(
            name="resourcegroup",
            options={"ordering": ["-created", "id"]},
        ),
        migrations.AlterModelOptions(
            name="securitygroup",
            options={"ordering": ["-created", "id"]},
        ),
        migrations.AlterModelOptions(
            name="sqldatabase",
            options={"ordering": ["-created", "id"]},
        ),
        migrations.AlterModelOptions(
            name="sqlserver",
            options={"ordering": ["-created", "id"]},
        ),
        migrations.AlterModelOptions(
            name="storageaccount",
            options={"ordering": ["-created", "id"]},
        ),
        migrations.AlterModelOptions(
            name="subnet",
            options={"ordering": ["-created", "id"]},
        ),
        migrations.AlterModelOptions(
            name="virtualmachine",
            options={"ordering": ["-created", "id"]},
        ),
    ]
