# Generated by Django 6.0.8 on 2026-08-28 11:42

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.conf import settings
from django.db import migrations, models

import waldur_core.core.fields
import waldur_core.core.validators


class Migration(migrations.Migration):
    replaces = [
        ("notifications", "0001_initial"),
        ("notifications", "0002_json_field"),
        ("notifications", "0003_rename_notification_broadcastmessage"),
        ("notifications", "0004_messagetemplate"),
        ("notifications", "0005_broadcastmessage_state"),
        ("notifications", "0006_broadcastmessage_fill"),
        ("notifications", "0007_alter_broadcastmessage_send_at"),
        ("notifications", "0008_adminannouncement"),
        ("notifications", "0009_alter_adminannouncement_description"),
    ]

    dependencies = [
        ("core", "__first__"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdminAnnouncement",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=4096, verbose_name="description"
                    ),
                ),
                ("uuid", waldur_core.core.fields.UUIDField()),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("information", "Information"),
                            ("warning", "Warning"),
                            ("danger", "Danger"),
                        ],
                        default="information",
                        max_length=30,
                    ),
                ),
                ("active_from", models.DateTimeField()),
                ("active_to", models.DateTimeField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="MessageTemplate",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=150,
                        validators=[waldur_core.core.validators.validate_name],
                        verbose_name="name",
                    ),
                ),
                ("uuid", waldur_core.core.fields.UUIDField()),
                ("body", models.TextField()),
                ("subject", models.TextField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="BroadcastMessage",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uuid", waldur_core.core.fields.UUIDField()),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("SCHEDULED", "Scheduled"),
                            ("SENT", "Sent"),
                        ],
                        default="DRAFT",
                        max_length=30,
                    ),
                ),
                ("send_at", models.DateField(null=True)),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "subject",
                    models.CharField(
                        max_length=1000,
                        validators=[waldur_core.core.validators.validate_name],
                    ),
                ),
                (
                    "body",
                    models.TextField(
                        validators=[waldur_core.core.validators.validate_name]
                    ),
                ),
                ("query", models.JSONField()),
                ("emails", models.JSONField()),
                (
                    "author",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
