# Generated by Django 3.2 on 2022-01-31 14:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='emails',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='notification',
            name='query',
            field=models.JSONField(),
        ),
    ]
