# Generated by Django 6.0.8 on 2026-10-03 05:18

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.conf import settings
from django.db import migrations, models

import waldur_core.core.fields


class Migration(migrations.Migration):
    dependencies = [
        ("marketplace_metrics", "0001_initial"),
        ("structure", "0041_squashed_0085"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MetricGoal",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("uuid", waldur_core.core.fields.UUIDField()),
                (
                    "comparator",
                    models.CharField(
                        choices=[("ge", "At least"), ("le", "At most")],
                        default="ge",
                        max_length=2,
                    ),
                ),
                ("value", models.DecimalField(decimal_places=6, max_digits=24)),
                (
                    "period",
                    models.CharField(
                        choices=[
                            ("month", "Calendar month"),
                            ("quarter", "Calendar quarter"),
                            ("rolling_30d", "Last 30 days"),
                        ],
                        default="month",
                        max_length=20,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "offering_metric",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="goals",
                        to="marketplace_metrics.offeringmetric",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        help_text="Empty is the offering's default goal.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metric_goals",
                        to="structure.project",
                    ),
                ),
            ],
            options={
                "ordering": ["offering_metric", "project", "id"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("project__isnull", True)),
                        fields=("offering_metric",),
                        name="unique_offering_default_metric_goal",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("project__isnull", False)),
                        fields=("offering_metric", "project"),
                        name="unique_project_metric_goal",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="MetricRollup",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "granularity",
                    models.CharField(
                        choices=[("hour", "Hourly"), ("day", "Daily")], max_length=10
                    ),
                ),
                ("bucket_start", models.DateTimeField()),
                ("count", models.PositiveIntegerField()),
                ("sum", models.DecimalField(decimal_places=6, max_digits=30)),
                ("min", models.DecimalField(decimal_places=6, max_digits=24)),
                ("max", models.DecimalField(decimal_places=6, max_digits=24)),
                ("last", models.DecimalField(decimal_places=6, max_digits=24)),
                ("last_timestamp", models.DateTimeField()),
                (
                    "series",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rollups",
                        to="marketplace_metrics.metricseries",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["granularity", "bucket_start"], name="metric_rollup_age"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("series", "granularity", "bucket_start"),
                        name="unique_metric_rollup",
                    )
                ],
            },
        ),
    ]
