class GlobalRoles:
    admin = 'admin'
    authn_manage = 'authn-manage'
    catalogs_manage = 'catalogs-manage'
    catalogs_use = 'catalogs-use'
    clusters_create = 'clusters-create'
    kontainerdrivers_manage = 'kontainerdrivers-manage'
    nodedrivers_manage = 'nodedrivers-manage'
    podsecuritypolicytemplates_manage = 'podsecuritypolicytemplates-manage'
    roles_manage = 'roles-manage'
    settings_manage = 'settings-manage'
    user = 'user'
    user_base = 'user-base'
    users_manage = 'users-manage'


class ClusterRoles:
    admin = 'admin'
    backups_manage = 'backups-manage'
    cluster_admin = 'cluster-admin'
    cluster_member = 'cluster-member'
    cluster_owner = 'cluster-owner'
    clustercatalogs_manage = 'clustercatalogs-manage'
    clustercatalogs_view = 'clustercatalogs-view'
    clusterroletemplatebindings_manage = 'clusterroletemplatebindings-manage'
    clusterroletemplatebindings_view = 'clusterroletemplatebindings-view'
    configmaps_manage = 'configmaps-manage'
    configmaps_view = 'configmaps-view'
    create_ns = 'create-ns'
    edit = 'edit'
    ingress_manage = 'ingress-manage'
    ingress_view = 'ingress-view'
    nodes_manage = 'nodes-manage'
    nodes_view = 'nodes-view'
    persistentvolumeclaims_manage = 'persistentvolumeclaims-manage'
    persistentvolumeclaims_view = 'persistentvolumeclaims-view'
    project_member = 'project-member'
    project_monitoring_readonly = 'project-monitoring-readonly'
    project_owner = 'project-owner'
    projectcatalogs_manage = 'projectcatalogs-manage'
    projectcatalogs_view = 'projectcatalogs-view'
    projectroletemplatebindings_manage = 'projectroletemplatebindings-manage'
    projectroletemplatebindings_view = 'projectroletemplatebindings-view'
    projects_create = 'projects-create'
    projects_view = 'projects-view'
    read_only = 'read-only'
    secrets_manage = 'secrets-manage'
    secrets_view = 'secrets-view'
    serviceaccounts_manage = 'serviceaccounts-manage'
    serviceaccounts_view = 'serviceaccounts-view'
    services_manage = 'services-manage'
    services_view = 'services-view'
    storage_manage = 'storage-manage'
    view = 'view'
    workloads_manage = 'workloads-manage'
    workloads_view = 'workloads-view'


class ProjectRoleId:
    admin = 'admin'
    backups_manage = 'backups-manage'
    cluster_admin = 'cluster-admin'
    cluster_member = 'cluster-member'
    cluster_owner = 'cluster-owner'
    clustercatalogs_manage = 'clustercatalogs-manage'
    clustercatalogs_view = 'clustercatalogs-view'
    clusterroletemplatebindings_manage = 'clusterroletemplatebindings-manage'
    clusterroletemplatebindings_view = 'clusterroletemplatebindings-view'
    configmaps_manage = 'configmaps-manage'
    configmaps_view = 'configmaps-view'
    create_ns = 'create-ns'
    edit = 'edit'
    ingress_manage = 'ingress-manage'
    ingress_view = 'ingress-view'
    nodes_manage = 'nodes-manage'
    nodes_view = 'nodes-view'
    persistentvolumeclaims_manage = 'persistentvolumeclaims-manage'
    persistentvolumeclaims_view = 'persistentvolumeclaims-view'
    project_member = 'project-member'
    project_monitoring_readonly = 'project-monitoring-readonly'
    project_owner = 'project-owner'
    projectcatalogs_manage = 'projectcatalogs-manage'
    projectcatalogs_view = 'projectcatalogs-view'
    projectroletemplatebindings_manage = 'projectroletemplatebindings-manage'
    projectroletemplatebindings_view = 'projectroletemplatebindings-view'
    projects_create = 'projects-create'
    projects_view = 'projects-view'
    read_only = 'read-only'
    secrets_manage = 'secrets-manage'
    secrets_view = 'secrets-view'
    serviceaccounts_manage = 'serviceaccounts-manage'
    serviceaccounts_view = 'serviceaccounts-view'
    services_manage = 'services-manage'
    services_view = 'services-view'
    storage_manage = 'storage-manage'
    view = 'view'
    workloads_manage = 'workloads-manage'
    workloads_view = 'workloads-view'


LONGHORN_NAME = 'longhorn'


LONGHORN_NAMESPACE = 'longhorn-system'
