# Generated by Django 4.2.18 on 2025-02-11 15:16

import re

import django.contrib.auth.models
import django.core.validators
from django.db import migrations, models

import waldur_core.core.managers
import waldur_core.core.validators


def lowercase_usernames(apps, schema_editor):
    User = apps.get_model("core", "User")
    for user in User.objects.all():
        username = user.username
        user.username = username.lower()
        user.save(update_fields=["username"])


class Migration(migrations.Migration):
    replaces = [
        ("core", "0002_alter_user_username"),
        ("core", "0003_add_common_email_footer"),
        ("core", "0004_add_uuid_to_common_footer"),
        ("core", "0005_delete_commonmailfooter"),
        ("core", "0006_alter_user_managers"),
        ("core", "0007_impersonateduser"),
        ("core", "0008_remove_user_competence"),
        ("core", "0009_rename_fingerprint_sshpublickey_fingerprint_md5_and_more"),
        ("core", "0010_generate_missing_fingerprint"),
        ("core", "0011_user_identity_source_alter_user_registration_method"),
        ("core", "0012_user_slug"),
        ("core", "0013_alter_user_phone_number"),
    ]

    dependencies = [
        ("core", "0001_squashed_0029"),
    ]

    operations = [
        migrations.RunPython(
            code=lowercase_usernames,
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                help_text="Required. 128 characters or fewer. Lowercase letters, numbers and @/./+/-/_ characters",
                max_length=128,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        re.compile("^[0-9a-z_.@+-]+$"),
                        "Enter a valid username.",
                        "invalid",
                    )
                ],
                verbose_name="username",
            ),
        ),
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", waldur_core.core.managers.UserActiveManager()),
                ("all_objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name="user",
            name="competence",
        ),
        migrations.AddField(
            model_name="sshpublickey",
            name="fingerprint_sha256",
            field=models.CharField(blank=True, max_length=51),
        ),
        migrations.AddField(
            model_name="sshpublickey",
            name="fingerprint_sha512",
            field=models.CharField(blank=True, max_length=94),
        ),
        migrations.CreateModel(
            name="ImpersonatedUser",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("core.user",),
            managers=[
                ("objects", waldur_core.core.managers.UserActiveManager()),
                ("all_objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name="user",
            name="identity_source",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Indicates what identity provider was used.",
                max_length=50,
                verbose_name="source of identity",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="registration_method",
            field=models.CharField(
                blank=True,
                default="default",
                help_text="Indicates what registration method was used.",
                max_length=50,
                verbose_name="registration method",
            ),
        ),
        migrations.RenameField(
            model_name="sshpublickey",
            old_name="fingerprint",
            new_name="fingerprint_md5",
        ),
        migrations.AddField(
            model_name="user",
            name="slug",
            field=models.SlugField(),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(
                blank=True,
                max_length=255,
                validators=[waldur_core.core.validators.validate_phone_number],
                verbose_name="phone number",
            ),
        ),
    ]
