# Generated by Django 4.2.8 on 2024-01-04 10:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_alter_user_username"),
    ]

    operations = [
        migrations.CreateModel(
            name="CommonMailFooter",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("html_content", models.TextField(blank=True)),
                ("text_content", models.TextField(blank=True)),
            ],
        ),
    ]
