# Generated by Django 4.2.8 on 2024-01-09 23:00
import uuid

from django.db import migrations

import waldur_core.core.fields


def gen_uuid(apps, schema_editor):
    CommonMailFooter = apps.get_model("core", "CommonMailFooter")
    for row in CommonMailFooter.objects.all():
        row.uuid = uuid.uuid4().hex
        row.save(update_fields=["uuid"])


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_add_common_email_footer"),
    ]

    operations = [
        migrations.AddField(
            model_name="commonmailfooter",
            name="uuid",
            field=waldur_core.core.fields.UUIDField(null=True),
        ),
        migrations.RunPython(gen_uuid, elidable=True),
        migrations.AlterField(
            model_name="commonmailfooter",
            name="uuid",
            field=waldur_core.core.fields.UUIDField(),
        ),
    ]
