# Generated by Django 4.2.8 on 2024-01-17 10:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_add_uuid_to_common_footer"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CommonMailFooter",
        ),
    ]
