# Generated by Django 4.2.8 on 2024-03-12 13:58

import django.contrib.auth.models
from django.db import migrations

import waldur_core.core.managers


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_delete_commonmailfooter"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", waldur_core.core.managers.UserActiveManager()),
                ("all_objects", django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
