# Generated by Django 4.2.10 on 2024-05-24 12:36

import django.contrib.auth.models
from django.db import migrations

import waldur_core.core.managers


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_alter_user_managers"),
    ]

    operations = [
        migrations.CreateModel(
            name="ImpersonatedUser",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("core.user",),
            managers=[
                ("objects", waldur_core.core.managers.UserActiveManager()),
                ("all_objects", django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
