# Generated by Django 4.2.10 on 2024-07-17 10:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_impersonateduser"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="competence",
        ),
    ]
