# Generated by Django 6.0.8 on 2026-08-28 12:01

import django.utils.timezone
import model_utils.fields
from django.db import migrations, models

import waldur_core.core.validators


class Migration(migrations.Migration):
    replaces = [
        ("core", "0014_sshpublickey_created_sshpublickey_modified"),
        ("core", "0015_user_modified"),
        ("core", "0016_notifications_cleanup"),
        ("core", "0017_remove_duplicate_notification_templates"),
        ("core", "0018_alter_notification_description_and_more"),
        ("core", "0019_user_birth_date"),
        ("core", "0020_user_country_of_residence_user_eduperson_assurance_and_more"),
        ("core", "0021_daily_table_size_history"),
        ("core", "0022_user_organization_registry_code"),
        ("core", "0023_user_identity_bridge_fields"),
        ("core", "0024_remove_constance_site_logo"),
    ]

    dependencies = [
        ("core", "0013_alter_user_phone_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="sshpublickey",
            name="created",
            field=model_utils.fields.AutoCreatedField(
                default=django.utils.timezone.now,
                editable=False,
                verbose_name="created",
            ),
        ),
        migrations.AddField(
            model_name="sshpublickey",
            name="modified",
            field=model_utils.fields.AutoLastModifiedField(
                default=django.utils.timezone.now,
                editable=False,
                verbose_name="modified",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="active_isds",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of ISDs that have asserted this user exists. User is deactivated when this becomes empty.",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="attribute_sources",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Per-attribute source and freshness tracking. Format: {'field_name': {'source': 'isd:<name>', 'timestamp': 'ISO8601'}}.",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="birth_date",
            field=models.DateField(blank=True, null=True, verbose_name="birth date"),
        ),
        migrations.AddField(
            model_name="user",
            name="country_of_residence",
            field=models.CharField(
                blank=True,
                max_length=2,
                validators=[waldur_core.core.validators.ISO3166Alpha2Validator()],
                verbose_name="country of residence",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="eduperson_assurance",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="REFEDS assurance profile URIs from identity provider",
                validators=[waldur_core.core.validators.validate_refeds_assurance_list],
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="gender",
            field=models.PositiveSmallIntegerField(
                blank=True,
                choices=[
                    (0, "Not known"),
                    (1, "Male"),
                    (2, "Female"),
                    (9, "Not applicable"),
                ],
                help_text="ISO 5218 gender code",
                null=True,
                verbose_name="gender",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="managed_isds",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of ISD source identifiers this user can manage via Identity Bridge. E.g., ['isd:puhuri', 'isd:fenix']. Non-empty list implies identity manager role.",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="modified",
            field=model_utils.fields.AutoLastModifiedField(
                default=django.utils.timezone.now,
                editable=False,
                verbose_name="modified",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="nationalities",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of all citizenships (ISO 3166-1 alpha-2 codes)",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="nationality",
            field=models.CharField(
                blank=True,
                help_text="Primary citizenship (ISO 3166-1 alpha-2 code)",
                max_length=2,
                validators=[waldur_core.core.validators.ISO3166Alpha2Validator()],
                verbose_name="nationality",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="organization_country",
            field=models.CharField(
                blank=True,
                max_length=2,
                validators=[waldur_core.core.validators.ISO3166Alpha2Validator()],
                verbose_name="organization country",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="organization_registry_code",
            field=models.CharField(
                blank=True,
                help_text="Company registration code of the user's organization, if known",
                max_length=255,
                verbose_name="organization registry code",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="organization_type",
            field=models.CharField(
                blank=True,
                help_text="SCHAC URN (e.g., urn:schac:homeOrganizationType:int:university)",
                max_length=255,
                validators=[
                    waldur_core.core.validators.validate_schac_organization_type
                ],
                verbose_name="organization type",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="personal_title",
            field=models.CharField(
                blank=True,
                help_text="Honorific title (Mr, Ms, Dr, Prof, etc.)",
                max_length=50,
                verbose_name="personal title",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="place_of_birth",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="place of birth"
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="description",
            field=models.CharField(
                blank=True, max_length=4096, verbose_name="description"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="description",
            field=models.CharField(
                blank=True, max_length=4096, verbose_name="description"
            ),
        ),
        migrations.CreateModel(
            name="DailyTableSizeHistory",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("table_name", models.CharField(db_index=True, max_length=150)),
                ("date", models.DateField(db_index=True)),
                (
                    "total_size",
                    models.BigIntegerField(
                        help_text="Total size including indexes in bytes"
                    ),
                ),
                (
                    "data_size",
                    models.BigIntegerField(help_text="Data-only size in bytes"),
                ),
                (
                    "row_estimate",
                    models.BigIntegerField(help_text="Estimated row count", null=True),
                ),
            ],
            options={
                "verbose_name": "Daily table size history",
                "verbose_name_plural": "Daily table size history",
                "ordering": ["-date", "table_name"],
                "unique_together": {("table_name", "date")},
            },
        ),
    ]
