# Generated by Django 5.2.11 on 2026-03-01 15:13

import logging

import django.utils.timezone
import model_utils.fields
from django.db import migrations, models

import waldur_core.core.validators
from waldur_core.core.utils import get_valid_notification_keys, get_valid_template_paths

logger = logging.getLogger(__name__)


# --- Data migration functions (copied from individual migrations) ---


def delete_unregistered_notifications_and_templates(apps, schema_editor):
    Notification = apps.get_model("core", "Notification")
    NotificationTemplate = apps.get_model("core", "NotificationTemplate")

    valid_keys = get_valid_notification_keys()
    valid_paths = get_valid_template_paths()

    for notification in Notification.objects.all():
        if notification.key not in valid_keys:
            logger.info(f"Deleting unregistered notification: {notification.key}")
            notification.delete()

    for template in NotificationTemplate.objects.all():
        if template.path not in valid_paths:
            logger.info(f"Deleting unregistered notification template: {template.path}")
            template.delete()


def remove_duplicate_notification_templates(apps, schema_editor):
    NotificationTemplate = apps.get_model("core", "NotificationTemplate")
    duplicate_paths = []
    all_paths = NotificationTemplate.objects.values_list("path", flat=True).distinct()

    for path in all_paths:
        path_count = NotificationTemplate.objects.filter(path=path).count()
        if path_count > 1:
            duplicate_paths.append(path)

    deleted_count = 0
    for path in duplicate_paths:
        templates_with_path = NotificationTemplate.objects.filter(path=path).order_by(
            "id"
        )
        if templates_with_path.count() > 1:
            templates_to_delete = templates_with_path[1:]
            for template in templates_to_delete:
                template.delete()
                deleted_count += 1


def remove_site_logo_setting(apps, schema_editor):
    schema_editor.execute("DELETE FROM constance_constance WHERE key = 'SITE_LOGO'")


class Migration(migrations.Migration):
    replaces = [
        ("core", "0014_sshpublickey_created_sshpublickey_modified"),
        ("core", "0015_user_modified"),
        ("core", "0016_notifications_cleanup"),
        ("core", "0017_remove_duplicate_notification_templates"),
        ("core", "0018_alter_notification_description_and_more"),
        ("core", "0019_user_birth_date"),
        ("core", "0020_user_country_of_residence_user_eduperson_assurance_and_more"),
        ("core", "0021_daily_table_size_history"),
        ("core", "0022_user_organization_registry_code"),
        ("core", "0023_user_identity_bridge_fields"),
        ("core", "0024_remove_constance_site_logo"),
    ]

    dependencies = [
        ("core", "0002_alter_user_username_squashed_0013_alter_user_phone_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="sshpublickey",
            name="created",
            field=model_utils.fields.AutoCreatedField(
                default=django.utils.timezone.now,
                editable=False,
                verbose_name="created",
            ),
        ),
        migrations.AddField(
            model_name="sshpublickey",
            name="modified",
            field=model_utils.fields.AutoLastModifiedField(
                default=django.utils.timezone.now,
                editable=False,
                verbose_name="modified",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="modified",
            field=model_utils.fields.AutoLastModifiedField(
                default=django.utils.timezone.now,
                editable=False,
                verbose_name="modified",
            ),
        ),
        migrations.RunPython(
            code=delete_unregistered_notifications_and_templates,
        ),
        migrations.RunPython(
            code=remove_duplicate_notification_templates,
            hints={"NotificationTemplate": "core.NotificationTemplate"},
        ),
        migrations.AlterField(
            model_name="notification",
            name="description",
            field=models.CharField(
                blank=True, max_length=4096, verbose_name="description"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="description",
            field=models.CharField(
                blank=True, max_length=4096, verbose_name="description"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="birth_date",
            field=models.DateField(blank=True, null=True, verbose_name="birth date"),
        ),
        migrations.AddField(
            model_name="user",
            name="country_of_residence",
            field=models.CharField(
                blank=True,
                max_length=2,
                validators=[waldur_core.core.validators.ISO3166Alpha2Validator()],
                verbose_name="country of residence",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="eduperson_assurance",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="REFEDS assurance profile URIs from identity provider",
                validators=[waldur_core.core.validators.validate_refeds_assurance_list],
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="gender",
            field=models.PositiveSmallIntegerField(
                blank=True,
                choices=[
                    (0, "Not known"),
                    (1, "Male"),
                    (2, "Female"),
                    (9, "Not applicable"),
                ],
                help_text="ISO 5218 gender code",
                null=True,
                verbose_name="gender",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="nationalities",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of all citizenships (ISO 3166-1 alpha-2 codes)",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="nationality",
            field=models.CharField(
                blank=True,
                help_text="Primary citizenship (ISO 3166-1 alpha-2 code)",
                max_length=2,
                validators=[waldur_core.core.validators.ISO3166Alpha2Validator()],
                verbose_name="nationality",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="organization_country",
            field=models.CharField(
                blank=True,
                max_length=2,
                validators=[waldur_core.core.validators.ISO3166Alpha2Validator()],
                verbose_name="organization country",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="organization_type",
            field=models.CharField(
                blank=True,
                help_text="SCHAC URN (e.g., urn:schac:homeOrganizationType:int:university)",
                max_length=255,
                validators=[
                    waldur_core.core.validators.validate_schac_organization_type
                ],
                verbose_name="organization type",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="personal_title",
            field=models.CharField(
                blank=True,
                help_text="Honorific title (Mr, Ms, Dr, Prof, etc.)",
                max_length=50,
                verbose_name="personal title",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="place_of_birth",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="place of birth"
            ),
        ),
        migrations.CreateModel(
            name="DailyTableSizeHistory",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("table_name", models.CharField(db_index=True, max_length=150)),
                ("date", models.DateField(db_index=True)),
                (
                    "total_size",
                    models.BigIntegerField(
                        help_text="Total size including indexes in bytes"
                    ),
                ),
                (
                    "data_size",
                    models.BigIntegerField(help_text="Data-only size in bytes"),
                ),
                (
                    "row_estimate",
                    models.BigIntegerField(help_text="Estimated row count", null=True),
                ),
            ],
            options={
                "verbose_name": "Daily table size history",
                "verbose_name_plural": "Daily table size history",
                "ordering": ["-date", "table_name"],
                "unique_together": {("table_name", "date")},
            },
        ),
        migrations.AddField(
            model_name="user",
            name="organization_registry_code",
            field=models.CharField(
                blank=True,
                help_text="Company registration code of the user's organization, if known",
                max_length=255,
                verbose_name="organization registry code",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="active_isds",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of ISDs that have asserted this user exists. User is deactivated when this becomes empty.",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="attribute_sources",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Per-attribute source and freshness tracking. Format: {'field_name': {'source': 'isd:<name>', 'timestamp': 'ISO8601'}}.",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="managed_isds",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of ISD source identifiers this user can manage via Identity Bridge. E.g., ['isd:puhuri', 'isd:fenix']. Non-empty list implies identity manager role.",
            ),
        ),
        migrations.RunPython(
            code=remove_site_logo_setting,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
