# Generated by Django 2.2.19 on 2021-03-25 08:07

from django.db import migrations, models


def split_full_name(apps, schema_editor):
    User = apps.get_model('core', 'User')

    for user in User.objects.all():
        if user.full_name:
            names = user.full_name.split()
            user.first_name = ' '.join(names[:1])
            user.last_name = ' '.join(names[1:])
            user.save()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_user_affiliations'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='first_name',
            field=models.CharField(
                blank=True, max_length=100, verbose_name='first name'
            ),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(
                blank=True, max_length=100, verbose_name='last name'
            ),
        ),
        migrations.RunPython(split_full_name),
        migrations.RemoveField(
            model_name='user',
            name='full_name',
        ),
    ]
