# Generated by Django 4.2.20 on 2025-05-27 10:22
import logging

from django.db import migrations

from waldur_core.core.utils import get_valid_notification_keys, get_valid_template_paths

logger = logging.getLogger(__name__)


def delete_unregistered_notifications_and_templates(apps, schema_editor):
    Notification = apps.get_model("core", "Notification")
    NotificationTemplate = apps.get_model("core", "NotificationTemplate")

    valid_keys = get_valid_notification_keys()
    valid_paths = get_valid_template_paths()

    for notification in Notification.objects.all():
        if notification.key not in valid_keys:
            logger.info(f"Deleting unregistered notification: {notification.key}")
            notification.delete()

    for template in NotificationTemplate.objects.all():
        if template.path not in valid_paths:
            logger.info(f"Deleting unregistered notification template: {template.path}")
            template.delete()


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0015_user_modified"),
    ]

    operations = [
        migrations.RunPython(
            delete_unregistered_notifications_and_templates,
        ),
    ]
