# Generated by Django 2.2.19 on 2021-04-02 10:50

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_clean_affiliations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='affiliations',
            field=django.contrib.postgres.fields.jsonb.JSONField(
                blank=True,
                default=list,
                help_text="Person's affiliation within organization such as student, faculty, staff.",
            ),
        ),
    ]
