# Generated by Django 2.2.24 on 2021-10-05 11:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0020_feature'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_sync',
            field=models.DateTimeField(
                default=django.utils.timezone.now, editable=False
            ),
        ),
    ]
