# Generated by Django 4.2.24 on 2026-01-26 12:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0020_user_country_of_residence_user_eduperson_assurance_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyTableSizeHistory",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("table_name", models.CharField(db_index=True, max_length=150)),
                ("date", models.DateField(db_index=True)),
                (
                    "total_size",
                    models.BigIntegerField(
                        help_text="Total size including indexes in bytes"
                    ),
                ),
                (
                    "data_size",
                    models.BigIntegerField(help_text="Data-only size in bytes"),
                ),
                (
                    "row_estimate",
                    models.BigIntegerField(help_text="Estimated row count", null=True),
                ),
            ],
            options={
                "verbose_name": "Daily table size history",
                "verbose_name_plural": "Daily table size history",
                "ordering": ["-date", "table_name"],
                "unique_together": {("table_name", "date")},
            },
        ),
    ]
