# Generated by Django 4.2.27 on 2026-02-07 22:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0021_daily_table_size_history"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="organization_registry_code",
            field=models.CharField(
                blank=True,
                help_text="Company registration code of the user's organization, if known",
                max_length=255,
                verbose_name="organization registry code",
            ),
        ),
    ]
