# Generated by Django 4.2.27 on 2026-02-05 14:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0022_user_organization_registry_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="active_isds",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of ISDs that have asserted this user exists. User is deactivated when this becomes empty.",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="attribute_sources",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Per-attribute source and freshness tracking. Format: {'field_name': {'source': 'isd:<name>', 'timestamp': 'ISO8601'}}.",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="managed_isds",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of ISD source identifiers this user can manage via Identity Bridge. E.g., ['isd:puhuri', 'isd:fenix']. Non-empty list implies identity manager role.",
            ),
        ),
    ]
