# Generated by Django 2.2.25 on 2021-12-16 13:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0024_query_field_fix'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='notifications_enabled',
            field=models.BooleanField(
                default=True,
                help_text='Designates whether the user is allowed to receive email notifications.',
            ),
        ),
    ]
