# Generated by Django 6.0.3 on 2026-03-30 19:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0026_add_personal_title_and_nationalities_validators"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="enabled",
            field=models.BooleanField(
                default=False,
                help_text="Indicates if notification is enabled or disabled",
            ),
        ),
    ]
