# Generated by Django 6.0.3 on 2026-04-03 14:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0027_notification_default_disabled"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="deactivation_reason",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Reason why the user was deactivated. Visible to staff and support.",
                max_length=512,
            ),
        ),
    ]
