# Generated by Django 6.0.3 on 2026-04-08 16:19

from django.db import migrations, models

import waldur_core.core.validators


def clear_legacy_gender_values(apps, schema_editor):
    User = apps.get_model("core", "User")
    User.objects.exclude(gender=None).update(gender=None)


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0029_personal_access_token"),
    ]

    operations = [
        migrations.RunPython(
            clear_legacy_gender_values,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name="user",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[
                    ("male", "Male"),
                    ("female", "Female"),
                    ("unknown", "Unknown"),
                ],
                help_text="User's gender (male, female, or unknown)",
                max_length=10,
                null=True,
                validators=[waldur_core.core.validators.validate_gender],
                verbose_name="gender",
            ),
        ),
    ]
