# Generated by Django 6.0.5 on 2026-05-12 14:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0031_add_address_to_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="personalaccesstoken",
            name="allowed_scopes",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
