# Generated by Django 6.0.6 on 2026-06-10 09:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0034_user_can_use_personal_access_tokens"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_admin_deactivated",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Designates that the user was deactivated by an administrator and must not be reactivated automatically by the role-sync task. Visible to staff and support.",
            ),
        ),
    ]
