# Generated by Django 6.0.6 on 2026-06-22 20:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0035_user_is_admin_deactivated"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="organization_vat_code",
            field=models.CharField(
                blank=True,
                help_text="VAT code of the user's organization",
                max_length=20,
                verbose_name="organization VAT code",
            ),
        ),
    ]
