# Generated by Django 6.0.6 on 2026-06-25 11:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0036_user_organization_vat_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="organization_address",
            field=models.CharField(
                blank=True,
                help_text="Postal address of the user's organization",
                max_length=255,
                verbose_name="organization address",
            ),
        ),
    ]
