# Generated by Django 6.0.7 on 2026-07-20 11:33

from django.db import migrations, models

import waldur_core.core.validators


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0039_user_primary_gid_user_uid_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="personalaccesstoken",
            name="allowed_networks",
            field=models.JSONField(
                blank=True,
                default=list,
                validators=[waldur_core.core.validators.normalize_network_acl],
            ),
        ),
    ]
