# Generated by Django 6.0.8 on 2026-08-20 13:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0042_call_and_proposal_invitation_notifications"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="notificationtemplate",
            options={"ordering": ["name", "path", "id"]},
        ),
        migrations.AlterModelOptions(
            name="personalaccesstoken",
            options={"ordering": ["-created", "id"]},
        ),
        migrations.AlterModelOptions(
            name="sshpublickey",
            options={
                "ordering": ["name", "id"],
                "verbose_name": "SSH public key",
                "verbose_name_plural": "SSH public keys",
            },
        ),
    ]
