# Generated by Django 6.0.8 on 2026-09-03 15:35

from importlib import import_module

from django.db import migrations

import waldur_core.core.migration_operations


def _original(name):
    """A replaced migration's module: its data code runs from there, unchanged."""
    return import_module(__name__.rpartition(".")[0] + "." + name)


class Migration(migrations.Migration):
    replaces = [
        ("marketplace_openstack", "0001_initial"),
        ("marketplace_openstack", "0002_prefix_storage"),
        ("marketplace_openstack", "0003_set_storage_mode"),
        ("marketplace_openstack", "0004_set_parent_offering"),
        ("marketplace_openstack", "0005_change_private_offerings_customers"),
        ("marketplace_openstack", "0006_change_billing_type_for_volumes"),
        ("marketplace_openstack", "0007_change_billing_type_for_volumes_of_tenants"),
        ("marketplace_openstack", "0008_drop_package_tables"),
        ("marketplace_openstack", "0009_fill_project"),
        ("marketplace_openstack", "0010_split_invoice_items"),
        ("marketplace_openstack", "0011_limit_components"),
        ("marketplace_openstack", "0012_drop_offering_components"),
        ("marketplace_openstack", "0013_rename_offering_type"),
        ("marketplace_openstack", "0014_update_router_metadata"),
        ("marketplace_openstack", "0015_fix_limits"),
        ("marketplace_openstack", "0016_add_limit_period_to_vpc"),
        ("marketplace_openstack", "0017_rename_internal_ips_set"),
        ("marketplace_openstack", "0018_populate_volume_metadata"),
        ("marketplace_openstack", "0019_expose_instance_flavor_and_image"),
    ]

    dependencies = [
        ("marketplace", "0001_squashed_0076"),
        ("marketplace", "0237_resourcelimitchangerequest"),
        (
            "marketplace",
            "0280_category_description_mk_category_description_sq_and_more",
        ),
        ("openstack", "0073_instance_config_drive"),
        ("openstack", "0082_instance_metadata"),
    ]

    operations = [
        migrations.RunPython(
            code=_original("0015_fix_limits").fix_limits,
        ),
        waldur_core.core.migration_operations.FlushDeferredSql(),
        migrations.RunPython(
            code=_original(
                "0016_add_limit_period_to_vpc"
            ).fill_openstack_component_limit_period,
        ),
        waldur_core.core.migration_operations.FlushDeferredSql(),
        migrations.RunPython(
            code=_original("0017_rename_internal_ips_set").rename_internal_ips_set,
        ),
        waldur_core.core.migration_operations.FlushDeferredSql(),
        migrations.RunPython(
            code=_original("0018_populate_volume_metadata").populate_volume_metadata,
        ),
        waldur_core.core.migration_operations.FlushDeferredSql(),
        migrations.RunPython(
            code=_original(
                "0019_expose_instance_flavor_and_image"
            ).backfill_instance_metadata,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
