from enum import Enum


class RoleEnum(str, Enum):
    CUSTOMER_OWNER = 'CUSTOMER.OWNER'
    CUSTOMER_SUPPORT = 'CUSTOMER.SUPPORT'
    CUSTOMER_MANAGER = 'CUSTOMER.MANAGER'

    PROJECT_ADMIN = 'PROJECT.ADMIN'
    PROJECT_MANAGER = 'PROJECT.MANAGER'
    PROJECT_MEMBER = 'PROJECT.MEMBER'

    OFFERING_MANAGER = 'OFFERING.MANAGER'


SYSTEM_CUSTOMER_ROLES = (
    RoleEnum.CUSTOMER_MANAGER,
    RoleEnum.CUSTOMER_OWNER,
    RoleEnum.CUSTOMER_SUPPORT,
)

SYSTEM_PROJECT_ROLES = (
    RoleEnum.PROJECT_ADMIN,
    RoleEnum.PROJECT_MANAGER,
    RoleEnum.PROJECT_MEMBER,
)

ALL_SYSTEM_ROLES = (
    SYSTEM_CUSTOMER_ROLES + SYSTEM_PROJECT_ROLES + (RoleEnum.OFFERING_MANAGER,)
)


TYPE_MAP = {
    'customer': ('structure', 'customer'),
    'project': ('structure', 'project'),
    'offering': ('marketplace', 'offering'),
}


class PermissionEnum(str, Enum):
    REGISTER_SERVICE_PROVIDER = 'SERVICE_PROVIDER.REGISTER'

    CREATE_OFFERING = 'OFFERING.CREATE'
    DELETE_OFFERING = 'OFFERING.DELETE'
    UPDATE_OFFERING_THUMBNAIL = 'OFFERING.UPDATE_THUMBNAIL'
    UPDATE_OFFERING = 'OFFERING.UPDATE'
    UPDATE_OFFERING_ATTRIBUTES = 'OFFERING.UPDATE_ATTRIBUTES'
    UPDATE_OFFERING_LOCATION = 'OFFERING.UPDATE_LOCATION'
    UPDATE_OFFERING_DESCRIPTION = 'OFFERING.UPDATE_DESCRIPTION'
    UPDATE_OFFERING_OVERVIEW = 'OFFERING.UPDATE_OVERVIEW'
    UPDATE_OFFERING_OPTIONS = 'OFFERING.UPDATE_OPTIONS'
    UPDATE_OFFERING_SECRET_OPTIONS = 'OFFERING.UPDATE_SECRET_OPTIONS'
    ADD_OFFERING_ENDPOINT = 'OFFERING.ADD_ENDPOINT'
    DELETE_OFFERING_ENDPOINT = 'OFFERING.DELETE_ENDPOINT'
    UPDATE_OFFERING_COMPONENTS = 'OFFERING.UPDATE_COMPONENTS'
    PAUSE_OFFERING = 'OFFERING.PAUSE'
    UNPAUSE_OFFERING = 'OFFERING.UNPAUSE'
    ARCHIVE_OFFERING = 'OFFERING.ARCHIVE'
    DRY_RUN_OFFERING_SCRIPT = 'OFFERING.DRY_RUN_SCRIPT'
    MANAGE_CAMPAIGN = 'OFFERING.MANAGE_CAMPAIGN'
    MANAGE_OFFERING_USER_GROUP = 'OFFERING.MANAGE_USER_GROUP'
    CREATE_OFFERING_PLAN = 'OFFERING.CREATE_PLAN'
    UPDATE_OFFERING_PLAN = 'OFFERING.UPDATE_PLAN'
    ARCHIVE_OFFERING_PLAN = 'OFFERING.ARCHIVE_PLAN'
    CREATE_OFFERING_SCREENSHOT = 'OFFERING.CREATE_SCREENSHOT'
    UPDATE_OFFERING_SCREENSHOT = 'OFFERING.UPDATE_SCREENSHOT'
    DELETE_OFFERING_SCREENSHOT = 'OFFERING.DELETE_SCREENSHOT'
    CREATE_OFFERING_USER = 'OFFERING.CREATE_USER'
    CREATE_RESOURCE_ROBOT_ACCOUNT = 'RESOURCE.CREATE_ROBOT_ACCOUNT'
    UPDATE_RESOURCE_ROBOT_ACCOUNT = 'RESOURCE.UPDATE_ROBOT_ACCOUNT'
    DELETE_RESOURCE_ROBOT_ACCOUNT = 'RESOURCE.DELETE_ROBOT_ACCOUNT'

    APPROVE_ORDER = 'ORDER.APPROVE'
    APPROVE_PRIVATE_ORDER = 'ORDER.APPROVE_PRIVATE'
    REJECT_ORDER = 'ORDER.REJECT'

    APPROVE_ORDER_ITEM = 'ORDER_ITEM.APPROVE'
    REJECT_ORDER_ITEM = 'ORDER_ITEM.REJECT'
    DESTROY_ORDER_ITEM = 'ORDER_ITEM.DESTROY'
    TERMINATE_ORDER_ITEM = 'ORDER_ITEM.TERMINATE'

    TERMINATE_RESOURCE = 'RESOURCE.TERMINATE'
    LIST_IMPORTABLE_RESOURCES = 'RESOURCE.LIST_IMPORTABLE'
    SET_RESOURCE_END_DATE = 'RESOURCE.SET_END_DATE'
    SET_RESOURCE_USAGE = 'RESOURCE.SET_USAGE'
    SWITCH_RESOURCE_PLAN = 'RESOURCE.SET_PLAN'
    UPDATE_RESOURCE_LIMITS = 'RESOURCE.SET_LIMITS'
    SET_RESOURCE_BACKEND_ID = 'RESOURCE.SET_BACKEND_ID'
    SUBMIT_RESOURCE_REPORT = 'RESOURCE.SUBMIT_REPORT'
    LIST_RESOURCE_USERS = 'RESOURCE.LIST_USERS'
    COMPLETE_RESOURCE_DOWNSCALING = 'RESOURCE.COMPLETE_DOWNSCALING'
    ACCEPT_BOOKING_REQUEST = 'RESOURCE.ACCEPT_BOOKING_REQUEST'
    REJECT_BOOKING_REQUEST = 'RESOURCE.REJECT_BOOKING_REQUEST'

    CREATE_PROJECT_PERMISSION = 'PROJECT.CREATE_PERMISSION'
    CREATE_CUSTOMER_PERMISSION = 'CUSTOMER.CREATE_PERMISSION'
    CREATE_OFFERING_PERMISSION = 'OFFERING.CREATE_PERMISSION'

    UPDATE_PROJECT_PERMISSION = 'PROJECT.UPDATE_PERMISSION'
    UPDATE_CUSTOMER_PERMISSION = 'CUSTOMER.UPDATE_PERMISSION'
    UPDATE_OFFERING_PERMISSION = 'OFFERING.UPDATE_PERMISSION'

    DELETE_PROJECT_PERMISSION = 'PROJECT.DELETE_PERMISSION'
    DELETE_CUSTOMER_PERMISSION = 'CUSTOMER.DELETE_PERMISSION'
    DELETE_OFFERING_PERMISSION = 'OFFERING.DELETE_PERMISSION'

    CREATE_LEXIS_LINK_PERMISSION = 'LEXIS_LINK.CREATE_PERMISSION'
    DELETE_LEXIS_LINK_PERMISSION = 'LEXIS_LINK.DELETE_PERMISSION'
