# Generated by Django 4.2.18 on 2025-02-11 15:23

import django.core.validators
import django.utils.timezone
import django_fsm
import model_utils.fields
from django.conf import settings
from django.core.exceptions import ObjectDoesNotExist
from django.db import migrations, models

import waldur_core.core.fields
import waldur_core.core.validators
import waldur_core.media.mixins


def create_call_role(apps, schema_editor):
    Call = apps.get_model("proposal", "Call")
    ContentType = apps.get_model("contenttypes", "ContentType")
    Role = apps.get_model("permissions", "Role")

    Role.objects.create(
        name="CALL.REVIEWER",
        description="Call reviewer",
        content_type=ContentType.objects.get_for_model(Call),
        is_system_role=True,
    )


def drop_fsm(apps, schema_editor):
    Call = apps.get_model("proposal", "Call")
    RequestedOffering = apps.get_model("proposal", "RequestedOffering")
    Round = apps.get_model("proposal", "Round")
    Proposal = apps.get_model("proposal", "Proposal")
    Review = apps.get_model("proposal", "Review")

    for call in Call.objects.all():
        call.state = ["draft", "active", "archived"][int(call.state) - 1]
        call.save()

    for offering in RequestedOffering.objects.all():
        offering.state = ["requested", "accepted", "canceled"][int(offering.state) - 1]
        offering.save()

    for round in Round.objects.all():
        round.review_strategy = ["after_round", "after_proposal"][
            int(round.review_strategy) - 1
        ]
        round.deciding_entity = ["by_call_manager", "automatic"][
            int(round.deciding_entity) - 1
        ]
        round.allocation_time = ["on_decision", "fixed_date"][
            int(round.allocation_time) - 1
        ]
        round.save()

    for proposal in Proposal.objects.all():
        proposal.state = [
            "draft",
            "submitted",
            "in_review",
            "in_revision",
            "accepted",
            "rejected",
            "canceled",
        ][int(proposal.state) - 1]
        proposal.save()

    for review in Review.objects.all():
        review.state = ["created", "in_review", "submitted", "rejected"][
            int(review.state) - 1
        ]
        review.save()


def create_projects(apps, schema_editor):
    Proposal = apps.get_model("proposal", "Proposal")
    Project = apps.get_model("structure", "Project")

    for proposal in Proposal.objects.all():
        if not proposal.project:
            project = Project.objects.create(
                customer=proposal.round.call.manager.customer,
                name=proposal.project_summary
                if proposal.project_summary
                else proposal.created_by.username + " | " + proposal.round.call.name,
            )
            proposal.project = project
            proposal.save()


def create_role_call_manager(apps, schema_editor):
    Call = apps.get_model("proposal", "Call")
    ContentType = apps.get_model("contenttypes", "ContentType")
    Role = apps.get_model("permissions", "Role")

    Role.objects.create(
        name="CALL.MANAGER",
        description="Call manager",
        content_type=ContentType.objects.get_for_model(Call),
        is_system_role=True,
    )


def create_role_proposal_member(apps, schema_editor):
    Proposal = apps.get_model("proposal", "Proposal")
    ContentType = apps.get_model("contenttypes", "ContentType")
    Role = apps.get_model("permissions", "Role")

    Role.objects.create(
        name="PROPOSAL.MEMBER",
        description="Proposal member",
        content_type=ContentType.objects.get_for_model(Proposal),
        is_system_role=True,
    )


def create_role_proposal_manager(apps, schema_editor):
    Proposal = apps.get_model("proposal", "Proposal")
    ContentType = apps.get_model("contenttypes", "ContentType")
    Role = apps.get_model("permissions", "Role")

    Role.objects.create(
        name="PROPOSAL.MANAGER",
        description="Proposal manager",
        content_type=ContentType.objects.get_for_model(Proposal),
        is_system_role=True,
    )


def upgrade_role(apps, schema_editor):
    Role = apps.get_model("permissions", "Role")
    UserRole = apps.get_model("permissions", "UserRole")
    ContentType = apps.get_model("contenttypes", "ContentType")
    Customer = apps.get_model("structure", "Customer")
    CallManagingOrganisation = apps.get_model("proposal", "CallManagingOrganisation")

    CustomerContentType = ContentType.objects.get_for_model(Customer)
    CallManagingOrganisationContentType = ContentType.objects.get_for_model(
        CallManagingOrganisation
    )

    Role.objects.filter(name="CUSTOMER.CALL_ORGANIZER").update(
        content_type=CallManagingOrganisationContentType
    )

    for user_role in UserRole.objects.filter(
        role__name="CUSTOMER.CALL_ORGANIZER", content_type=CustomerContentType
    ):
        try:
            service_provider = CallManagingOrganisation.objects.get(
                customer_id=user_role.object_id
            )
        except ObjectDoesNotExist:
            print(
                f"CallManagingOrganisation for customer {user_role.object_id} not found"
            )
            continue
        user_role.content_type = CallManagingOrganisationContentType
        user_role.object_id = service_provider.id
        user_role.save(update_fields=["content_type", "object_id"])


class Migration(migrations.Migration):
    replaces = [
        ("proposal", "0001_initial"),
        ("proposal", "0002_callmanager"),
        ("proposal", "0003_requested_offering"),
        ("proposal", "0004_proposal"),
        ("proposal", "0005_proposal_state"),
        ("proposal", "0006_add_reviewer"),
        ("proposal", "0007_drop_start_end_time_from_call"),
        ("proposal", "0008_drop_round_strategy_from_call"),
        ("proposal", "0009_move_review_strategy_from_call_to_round"),
        ("proposal", "0010_move_allocation_strategy_from_call_to_round"),
        ("proposal", "0011_alter_round_endtime_to_cutofftime"),
        ("proposal", "0012_add_extra_fields_to_proposal"),
        ("proposal", "0013_add_documents_to_call"),
        ("proposal", "0014_remove_call_reviewers_alter_review_reviewer_and_more"),
        ("proposal", "0015_call_backend_id"),
        ("proposal", "0016_requestedoffering_description"),
        ("proposal", "0017_call_role"),
        ("proposal", "0018_requestedresource_proposal_resources"),
        ("proposal", "0019_requestedoffering_plan"),
        ("proposal", "0020_drop_fsm"),
        ("proposal", "0021_proposal_description"),
        ("proposal", "0022_add_fields_to_review"),
        ("proposal", "0023_remove_proposal_supporting_documentation"),
        ("proposal", "0024_proposal_allocation_comment"),
        ("proposal", "0025_remove_round_max_allocations"),
        ("proposal", "0026_alter_proposal_project"),
        ("proposal", "0027_call_manager_role"),
        ("proposal", "0027_proposal_member_role"),
        ("proposal", "0028_call_default_project_role"),
        ("proposal", "0029_user_on_delete_set_null"),
        ("proposal", "0030_proposal_manager_role"),
        ("proposal", "0031_calldocument_description"),
        ("proposal", "0032_call_external_url"),
        ("proposal", "0033_call_organizer"),
    ]

    dependencies = [
        ("structure", "0040_useragreement_uuid"),
        ("marketplace", "0128_alter_plan_unit_price"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("marketplace", "0129_rename_divisions_to_organization_groups"),
        ("marketplace", "0104_translations"),
        ("permissions", "0015_customer_manager"),
        ("structure", "0043_rename_divisions_to_organization_groups"),
        ("permissions", "0014_unify_log"),
    ]

    operations = [
        migrations.CreateModel(
            name="Call",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=2000, verbose_name="description"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=150,
                        validators=[waldur_core.core.validators.validate_name],
                        verbose_name="name",
                    ),
                ),
                ("uuid", waldur_core.core.fields.UUIDField()),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField()),
                (
                    "round_strategy",
                    django_fsm.FSMIntegerField(
                        choices=[(1, "One-time"), (2, "Regular")], default=2
                    ),
                ),
                (
                    "review_strategy",
                    django_fsm.FSMIntegerField(
                        choices=[
                            (1, "After round is closed"),
                            (2, "After proposal submission"),
                        ],
                        default=1,
                    ),
                ),
                (
                    "allocation_strategy",
                    django_fsm.FSMIntegerField(
                        choices=[
                            (1, "By call manager"),
                            (2, "Automatic based on review scoring"),
                        ],
                        default=2,
                    ),
                ),
                (
                    "state",
                    django_fsm.FSMIntegerField(
                        choices=[(1, "Draft"), (2, "Active"), (3, "Archived")],
                        default=1,
                    ),
                ),
                ("offerings", models.ManyToManyField(to="marketplace.offering")),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Proposal",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=150,
                        validators=[waldur_core.core.validators.validate_name],
                        verbose_name="name",
                    ),
                ),
                ("uuid", waldur_core.core.fields.UUIDField()),
                (
                    "state",
                    django_fsm.FSMIntegerField(
                        choices=[(1, "Draft"), (2, "Active"), (3, "Cancelled")],
                        default=1,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="structure.project",
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "duration_in_days",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Duration in days after provisioning of resources.",
                        null=True,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("uuid", waldur_core.core.fields.UUIDField()),
                (
                    "state",
                    django_fsm.FSMIntegerField(
                        choices=[
                            (1, "Created"),
                            (2, "In review"),
                            (3, "Submitted"),
                            (4, "Rejected"),
                        ],
                        default=1,
                    ),
                ),
                (
                    "proposal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="proposal.proposal",
                    ),
                ),
                ("summary_private_comment", models.TextField(blank=True)),
                ("summary_public_comment", models.TextField(blank=True)),
                (
                    "summary_score",
                    models.PositiveSmallIntegerField(blank=True, default=0),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Round",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("uuid", waldur_core.core.fields.UUIDField()),
                ("start_time", models.DateTimeField()),
                ("cutoff_time", models.DateTimeField()),
                (
                    "call",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="proposal.call"
                    ),
                ),
                (
                    "minimum_number_of_reviewers",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "review_duration_in_days",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "review_strategy",
                    django_fsm.FSMIntegerField(
                        choices=[
                            (1, "After round is closed"),
                            (2, "After proposal submission"),
                        ],
                        default=1,
                    ),
                ),
                ("allocation_date", models.DateTimeField(blank=True, null=True)),
                (
                    "allocation_time",
                    django_fsm.FSMIntegerField(
                        choices=[(1, "On decision"), (2, "Fixed date")], default=1
                    ),
                ),
                (
                    "deciding_entity",
                    django_fsm.FSMIntegerField(
                        choices=[
                            (1, "By call manager"),
                            (2, "Automatic based on review scoring"),
                        ],
                        default=2,
                    ),
                ),
                ("max_allocations", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "minimal_average_scoring",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=5,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ReviewComment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("uuid", waldur_core.core.fields.UUIDField()),
                ("message", models.CharField(max_length=255)),
                (
                    "review",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="proposal.review",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ResourceAllocator",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=150,
                        validators=[waldur_core.core.validators.validate_name],
                        verbose_name="name",
                    ),
                ),
                ("uuid", waldur_core.core.fields.UUIDField()),
                (
                    "call",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="proposal.call"
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="structure.project",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CallManagingOrganisation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=waldur_core.media.mixins.get_upload_path,
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=2000, verbose_name="description"
                    ),
                ),
                ("uuid", waldur_core.core.fields.UUIDField()),
                (
                    "customer",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="structure.customer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Call managing organisation",
            },
        ),
        migrations.AddField(
            model_name="call",
            name="manager",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.PROTECT,
                to="proposal.callmanagingorganisation",
            ),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="RequestedOffering",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("uuid", waldur_core.core.fields.UUIDField()),
                ("attributes", models.JSONField(blank=True, default=dict)),
                (
                    "state",
                    django_fsm.FSMIntegerField(
                        choices=[(1, "Requested"), (2, "Accepted"), (3, "Canceled")],
                        default=1,
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "call",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="proposal.call"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "offering",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="marketplace.offering",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=2000, verbose_name="description"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.RemoveField(
            model_name="call",
            name="offerings",
        ),
        migrations.AddField(
            model_name="call",
            name="offerings",
            field=models.ManyToManyField(
                through="proposal.RequestedOffering", to="marketplace.offering"
            ),
        ),
        migrations.AddField(
            model_name="proposal",
            name="round",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="proposal.round"
            ),
        ),
        migrations.AlterField(
            model_name="proposal",
            name="state",
            field=django_fsm.FSMIntegerField(
                choices=[
                    (1, "Draft"),
                    (2, "Submitted"),
                    (3, "In review"),
                    (4, "In revision"),
                    (5, "Accepted"),
                    (6, "Rejected"),
                    (7, "Canceled"),
                ],
                default=1,
            ),
        ),
        migrations.AlterField(
            model_name="call",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.RemoveField(
            model_name="call",
            name="end_time",
        ),
        migrations.RemoveField(
            model_name="call",
            name="start_time",
        ),
        migrations.RemoveField(
            model_name="call",
            name="round_strategy",
        ),
        migrations.RemoveField(
            model_name="call",
            name="review_strategy",
        ),
        migrations.RemoveField(
            model_name="call",
            name="allocation_strategy",
        ),
        migrations.AddField(
            model_name="proposal",
            name="oecd_fos_2007_code",
            field=models.CharField(
                blank=True,
                choices=[
                    ("1.1", "Mathematics"),
                    ("1.2", "Computer and information sciences"),
                    ("1.3", "Physical sciences"),
                    ("1.4", "Chemical sciences"),
                    ("1.5", "Earth and related environmental sciences"),
                    ("1.6", "Biological sciences"),
                    ("1.7", "Other natural sciences"),
                    ("2.1", "Civil engineering"),
                    (
                        "2.2",
                        "Electrical engineering, electronic engineering, information engineering",
                    ),
                    ("2.3", "Mechanical engineering"),
                    ("2.4", "Chemical engineering"),
                    ("2.5", "Materials engineering"),
                    ("2.6", "Medical engineering"),
                    ("2.7", "Environmental engineering"),
                    ("2.8", "Systems engineering"),
                    ("2.9", "Environmental biotechnology"),
                    ("2.10", "Industrial biotechnology"),
                    ("2.11", "Nano technology"),
                    ("2.12", "Other engineering and technologies"),
                    ("3.1", "Basic medicine"),
                    ("3.2", "Clinical medicine"),
                    ("3.3", "Health sciences"),
                    ("3.4", "Health biotechnology"),
                    ("3.5", "Other medical sciences"),
                    ("4.1", "Agriculture, forestry, and fisheries"),
                    ("4.2", "Animal and dairy science"),
                    ("4.3", "Veterinary science"),
                    ("4.4", "Agricultural biotechnology"),
                    ("4.5", "Other agricultural sciences"),
                    ("5.1", "Psychology"),
                    ("5.2", "Economics and business"),
                    ("5.3", "Educational sciences"),
                    ("5.4", "Sociology"),
                    ("5.5", "Law"),
                    ("5.6", "Political science"),
                    ("5.7", "Social and economic geography"),
                    ("5.8", "Media and communications"),
                    ("5.9", "Other social sciences"),
                    ("6.1", "History and archaeology"),
                    ("6.2", "Languages and literature"),
                    ("6.3", "Philosophy, ethics and religion"),
                    ("6.4", "Arts (arts, history of arts, performing arts, music)"),
                    ("6.5", "Other humanities"),
                ],
                max_length=80,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="proposal",
            name="project_duration",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="proposal",
            name="project_has_civilian_purpose",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="proposal",
            name="project_is_confidential",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="proposal",
            name="project_summary",
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name="ProposalDocumentation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("uuid", waldur_core.core.fields.UUIDField()),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        help_text="Upload supporting documentation in PDF format.",
                        null=True,
                        upload_to="proposal_project_supporting_documentation",
                    ),
                ),
                (
                    "proposal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="proposal.proposal",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="proposal",
            name="supporting_documentation",
            field=models.ManyToManyField(
                related_name="supporting_documentation_set",
                to="proposal.proposaldocumentation",
            ),
        ),
        migrations.CreateModel(
            name="CallDocument",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("uuid", waldur_core.core.fields.UUIDField()),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        help_text="Documentation for call for proposals.",
                        null=True,
                        upload_to="call_documents",
                    ),
                ),
                (
                    "call",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="proposal.call"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="call",
            name="documents",
            field=models.ManyToManyField(
                related_name="call_documents", to="proposal.calldocument"
            ),
        ),
        migrations.AddField(
            model_name="call",
            name="backend_id",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.RunPython(
            code=create_call_role,
        ),
        migrations.CreateModel(
            name="RequestedResource",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=2000, verbose_name="description"
                    ),
                ),
                ("uuid", waldur_core.core.fields.UUIDField()),
                ("attributes", models.JSONField(blank=True, default=dict)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "proposal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="proposal.proposal",
                    ),
                ),
                (
                    "requested_offering",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="proposal.requestedoffering",
                    ),
                ),
                (
                    "resource",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="marketplace.resource",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="proposal",
            name="resources",
            field=models.ManyToManyField(
                through="proposal.RequestedResource", to="proposal.requestedoffering"
            ),
        ),
        migrations.AddField(
            model_name="requestedoffering",
            name="plan",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="marketplace.plan",
            ),
        ),
        migrations.AlterField(
            model_name="call",
            name="state",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("active", "Active"),
                    ("archived", "Archived"),
                ],
                db_index=True,
                default="draft",
            ),
        ),
        migrations.AlterField(
            model_name="proposal",
            name="state",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("team_verification", "Team verification"),
                    ("submitted", "Submitted"),
                    ("in_review", "In review"),
                    ("in_revision", "In revision"),
                    ("accepted", "Accepted"),
                    ("rejected", "Rejected"),
                    ("canceled", "Canceled"),
                ],
                db_index=True,
                default="draft",
            ),
        ),
        migrations.AlterField(
            model_name="requestedoffering",
            name="state",
            field=models.CharField(
                choices=[
                    ("requested", "Requested"),
                    ("accepted", "Accepted"),
                    ("canceled", "Canceled"),
                ],
                db_index=True,
                default="requested",
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="state",
            field=models.CharField(
                choices=[
                    ("created", "Created"),
                    ("in_review", "In review"),
                    ("submitted", "Submitted"),
                    ("rejected", "Rejected"),
                ],
                db_index=True,
                default="created",
            ),
        ),
        migrations.AlterField(
            model_name="round",
            name="allocation_time",
            field=models.CharField(
                choices=[("on_decision", "On decision"), ("fixed_date", "Fixed date")],
                db_index=True,
                default="on_decision",
            ),
        ),
        migrations.AlterField(
            model_name="round",
            name="deciding_entity",
            field=models.CharField(
                choices=[
                    ("by_call_manager", "By call manager"),
                    ("automatic", "Automatic based on review scoring"),
                ],
                db_index=True,
                default="automatic",
            ),
        ),
        migrations.AlterField(
            model_name="round",
            name="review_strategy",
            field=models.CharField(
                choices=[
                    ("after_round", "After round is closed"),
                    ("after_proposal", "After proposal submission"),
                ],
                db_index=True,
                default="after_round",
            ),
        ),
        migrations.RunPython(
            code=drop_fsm,
        ),
        migrations.AddField(
            model_name="proposal",
            name="description",
            field=models.CharField(
                blank=True, max_length=2000, verbose_name="description"
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="comment_project_description",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="review",
            name="comment_project_duration",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="review",
            name="comment_project_has_civilian_purpose",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="review",
            name="comment_project_is_confidential",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="review",
            name="comment_project_summary",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="review",
            name="comment_project_supporting_documentation",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="review",
            name="comment_project_title",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="review",
            name="comment_resource_requests",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="review",
            name="comment_team",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.RemoveField(
            model_name="proposal",
            name="supporting_documentation",
        ),
        migrations.AddField(
            model_name="proposal",
            name="allocation_comment",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.RunPython(
            code=create_projects,
        ),
        migrations.AddField(
            model_name="requestedresource",
            name="limits",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.RemoveField(
            model_name="round",
            name="max_allocations",
        ),
        migrations.AlterField(
            model_name="proposal",
            name="project",
            field=models.ForeignKey(
                default=1,
                editable=False,
                on_delete=django.db.models.deletion.PROTECT,
                to="structure.project",
            ),
            preserve_default=False,
        ),
        migrations.AlterModelOptions(
            name="proposal",
            options={"ordering": ["round__start_time"]},
        ),
        migrations.RunPython(
            code=create_role_call_manager,
        ),
        migrations.RunPython(
            code=create_role_proposal_member,
        ),
        migrations.AddField(
            model_name="call",
            name="default_project_role",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="permissions.role",
            ),
        ),
        migrations.AlterField(
            model_name="call",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="proposal",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="proposal",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="requestedoffering",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="requestedoffering",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.RunPython(
            code=create_role_proposal_manager,
        ),
        migrations.AddField(
            model_name="calldocument",
            name="description",
            field=models.CharField(
                blank=True, max_length=2000, verbose_name="description"
            ),
        ),
        migrations.AddField(
            model_name="call",
            name="external_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.RunPython(
            code=upgrade_role,
        ),
    ]
