# Generated by Django 4.2.8 on 2024-01-08 09:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("proposal", "0006_add_reviewer"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="call",
            name="end_time",
        ),
        migrations.RemoveField(
            model_name="call",
            name="start_time",
        ),
    ]
