# Generated by Django 4.2.10 on 2024-03-13 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("marketplace", "0129_rename_divisions_to_organization_groups"),
        ("proposal", "0018_requestedresource_proposal_resources"),
    ]

    operations = [
        migrations.AddField(
            model_name="requestedoffering",
            name="plan",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="marketplace.plan",
            ),
        ),
    ]
