# Generated by Django 4.2.10 on 2024-03-18 13:33

from django.db import migrations, models


def drop_fsm(apps, schema_editor):
    Call = apps.get_model("proposal", "Call")
    RequestedOffering = apps.get_model("proposal", "RequestedOffering")
    Round = apps.get_model("proposal", "Round")
    Proposal = apps.get_model("proposal", "Proposal")
    Review = apps.get_model("proposal", "Review")

    for call in Call.objects.all():
        call.state = ["draft", "active", "archived"][int(call.state) - 1]
        call.save()

    for offering in RequestedOffering.objects.all():
        offering.state = ["requested", "accepted", "canceled"][int(offering.state) - 1]
        offering.save()

    for round in Round.objects.all():
        round.review_strategy = ["after_round", "after_proposal"][
            int(round.review_strategy) - 1
        ]
        round.deciding_entity = ["by_call_manager", "automatic"][
            int(round.deciding_entity) - 1
        ]
        round.allocation_time = ["on_decision", "fixed_date"][
            int(round.allocation_time) - 1
        ]
        round.save()

    for proposal in Proposal.objects.all():
        proposal.state = [
            "draft",
            "submitted",
            "in_review",
            "in_revision",
            "accepted",
            "rejected",
            "canceled",
        ][int(proposal.state) - 1]
        proposal.save()

    for review in Review.objects.all():
        review.state = ["created", "in_review", "submitted", "rejected"][
            int(review.state) - 1
        ]
        review.save()


class Migration(migrations.Migration):
    dependencies = [
        ("proposal", "0019_requestedoffering_plan"),
    ]

    operations = [
        migrations.AlterField(
            model_name="call",
            name="state",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("active", "Active"),
                    ("archived", "Archived"),
                ],
                db_index=True,
                default="draft",
            ),
        ),
        migrations.AlterField(
            model_name="proposal",
            name="state",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("submitted", "Submitted"),
                    ("in_review", "In review"),
                    ("in_revision", "In revision"),
                    ("accepted", "Accepted"),
                    ("rejected", "Rejected"),
                    ("canceled", "Canceled"),
                ],
                db_index=True,
                default="draft",
            ),
        ),
        migrations.AlterField(
            model_name="requestedoffering",
            name="state",
            field=models.CharField(
                choices=[
                    ("requested", "Requested"),
                    ("accepted", "Accepted"),
                    ("canceled", "Canceled"),
                ],
                db_index=True,
                default="requested",
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="state",
            field=models.CharField(
                choices=[
                    ("created", "Created"),
                    ("in_review", "In review"),
                    ("submitted", "Submitted"),
                    ("rejected", "Rejected"),
                ],
                db_index=True,
                default="created",
            ),
        ),
        migrations.AlterField(
            model_name="round",
            name="allocation_time",
            field=models.CharField(
                choices=[("on_decision", "On decision"), ("fixed_date", "Fixed date")],
                db_index=True,
                default="on_decision",
            ),
        ),
        migrations.AlterField(
            model_name="round",
            name="deciding_entity",
            field=models.CharField(
                choices=[
                    ("by_call_manager", "By call manager"),
                    ("automatic", "Automatic based on review scoring"),
                ],
                db_index=True,
                default="automatic",
            ),
        ),
        migrations.AlterField(
            model_name="round",
            name="review_strategy",
            field=models.CharField(
                choices=[
                    ("after_round", "After round is closed"),
                    ("after_proposal", "After proposal submission"),
                ],
                db_index=True,
                default="after_round",
            ),
        ),
        migrations.RunPython(drop_fsm),
    ]
