# Generated by Django 4.2.10 on 2024-03-20 09:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("proposal", "0021_proposal_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="comment_project_description",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="review",
            name="comment_project_duration",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="review",
            name="comment_project_has_civilian_purpose",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="review",
            name="comment_project_is_confidential",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="review",
            name="comment_project_summary",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="review",
            name="comment_project_supporting_documentation",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="review",
            name="comment_project_title",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="review",
            name="comment_resource_requests",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="review",
            name="comment_team",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
