# Generated by Django 4.2.10 on 2024-03-22 08:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("proposal", "0024_proposal_allocation_comment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="round",
            name="max_allocations",
        ),
    ]
