# Generated by Django 4.2.18 on 2025-02-25 10:35

import django.db.models.deletion
from django.db import migrations, models


def remove_team_verification_state(apps, schema_editor):
    Proposal = apps.get_model("proposal", "Proposal")

    Proposal.objects.filter(state="team_verification").update(state="draft")


def fill_in_slug(apps, schema_editor):
    from django.template.defaultfilters import slugify

    Call = apps.get_model("proposal", "Call")

    for call in Call.objects.all():
        base_slug = slugify(call.name)[:8]
        existing_slugs = Call.objects.filter(slug__startswith=base_slug).values_list(
            "slug", flat=True
        )

        # Find maximum suffix
        max_num = 0
        for slug in existing_slugs:
            try:
                num = int(slug.split("-")[-1])
                if num > max_num:
                    max_num = num
            except ValueError:
                pass

        call.slug = f"{base_slug}-{max_num + 1}"
        call.save()


class Migration(migrations.Migration):
    dependencies = [
        ("proposal", "0001_initial_squashed_0033_call_organizer"),
    ]

    operations = [
        migrations.RunPython(
            code=remove_team_verification_state,
        ),
        migrations.AlterField(
            model_name="proposal",
            name="state",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("submitted", "Submitted"),
                    ("in_review", "In review"),
                    ("in_revision", "In revision"),
                    ("accepted", "Accepted"),
                    ("rejected", "Rejected"),
                    ("canceled", "Canceled"),
                ],
                db_index=True,
                default="draft",
            ),
        ),
        migrations.AlterField(
            model_name="proposal",
            name="project",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="structure.project",
            ),
        ),
        migrations.AddField(
            model_name="call",
            name="slug",
            field=models.SlugField(default=""),
            preserve_default=False,
        ),
        migrations.RunPython(
            code=fill_in_slug,
        ),
        migrations.AlterField(
            model_name="call",
            name="slug",
            field=models.SlugField(),
        ),
    ]
