# Generated by Django 6.0.4 on 2026-04-29 09:52

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import waldur_core.core.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("proposal", "0036_sciencedomain_sciencesubdomain"),
    ]

    operations = [
        migrations.CreateModel(
            name="CallApplicantVisibilityConfig",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("uuid", waldur_core.core.fields.UUIDField()),
                ("expose_full_name", models.BooleanField(default=True)),
                ("expose_organization", models.BooleanField(default=False)),
                ("expose_organization_country", models.BooleanField(default=False)),
                ("expose_email", models.BooleanField(default=True)),
                ("expose_affiliations", models.BooleanField(default=False)),
                ("expose_organization_type", models.BooleanField(default=False)),
                ("expose_nationality", models.BooleanField(default=False)),
                ("expose_nationalities", models.BooleanField(default=False)),
                ("expose_country_of_residence", models.BooleanField(default=False)),
                ("expose_eduperson_assurance", models.BooleanField(default=False)),
                ("expose_identity_source", models.BooleanField(default=False)),
                ("expose_username", models.BooleanField(default=True)),
                ("expose_registration_method", models.BooleanField(default=True)),
                ("expose_phone_number", models.BooleanField(default=False)),
                ("expose_job_title", models.BooleanField(default=False)),
                ("expose_gender", models.BooleanField(default=False)),
                ("expose_personal_title", models.BooleanField(default=False)),
                ("expose_place_of_birth", models.BooleanField(default=False)),
                ("expose_address", models.BooleanField(default=False)),
                (
                    "expose_organization_registry_code",
                    models.BooleanField(default=False),
                ),
                ("expose_civil_number", models.BooleanField(default=False)),
                ("expose_birth_date", models.BooleanField(default=False)),
                ("expose_active_isds", models.BooleanField(default=False)),
                (
                    "call",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applicant_visibility_config",
                        to="proposal.call",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
