# Generated by Django 4.2.20 on 2025-05-30 14:56

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.conf import settings
from django.db import migrations, models

import waldur_core.core.fields


class Migration(migrations.Migration):
    dependencies = [
        ("marketplace", "0164_customerserviceaccount_preferred_identifier"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("proposal", "0036_call_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="call",
            name="fixed_duration_in_days",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Fixed duration in days that applies to all proposals in this call",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="requestedoffering",
            name="offering",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="marketplace.offering"
            ),
        ),
        migrations.CreateModel(
            name="CallResourceTemplate",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=2000, verbose_name="description"
                    ),
                ),
                ("uuid", waldur_core.core.fields.UUIDField()),
                ("name", models.CharField(max_length=255)),
                ("attributes", models.JSONField(blank=True, default=dict)),
                ("limits", models.JSONField(blank=True, default=dict)),
                (
                    "is_required",
                    models.BooleanField(
                        default=False,
                        help_text="If True, every proposal must include this resource type",
                    ),
                ),
                (
                    "call",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resource_templates",
                        to="proposal.call",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "requested_offering",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="proposal.requestedoffering",
                    ),
                ),
            ],
            options={
                "verbose_name": "Call resource template",
                "verbose_name_plural": "Call resource templates",
                "unique_together": {("call", "name")},
            },
        ),
        migrations.AddField(
            model_name="requestedresource",
            name="call_resource_template",
            field=models.ForeignKey(
                blank=True,
                help_text="Resource template this request is based on",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="proposal.callresourcetemplate",
            ),
        ),
    ]
