# Generated by Django 4.2.23 on 2025-07-11 07:58

import django.db.models.deletion
from django.db import migrations, models

import waldur_core.core.fields


class Migration(migrations.Migration):
    dependencies = [
        ("permissions", "0016_userrole_modified_alter_userrole_created"),
        ("proposal", "0038_call_reviewer_identity_visible_to_submitters_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProposalProjectRoleMapping",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uuid", waldur_core.core.fields.UUIDField()),
                (
                    "call",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="proposal.call"
                    ),
                ),
                (
                    "project_role",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="project_role_mappings",
                        to="permissions.role",
                    ),
                ),
                (
                    "proposal_role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="proposal_role_mappings",
                        to="permissions.role",
                    ),
                ),
            ],
            options={
                "unique_together": {("call", "proposal_role")},
            },
        ),
    ]
