# Generated by Django 4.2.23 on 2025-08-07 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("checklist", "0001_initial"),
        ("proposal", "0041_remove_call_default_project_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="call",
            name="compliance_checklist",
            field=models.ForeignKey(
                blank=True,
                help_text="Compliance checklist that proposals must complete before submission",
                limit_choices_to={"checklist_type": "proposal_compliance"},
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="checklist.checklist",
            ),
        ),
    ]
