# Generated by Django 4.2.24 on 2025-09-12 20:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("proposal", "0042_call_compliance_checklist"),
    ]

    operations = [
        migrations.AlterField(
            model_name="call",
            name="state",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("active", "Active"),
                    ("archived", "Archived"),
                ],
                db_index=True,
                default="draft",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="proposal",
            name="state",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("submitted", "Submitted"),
                    ("in_review", "In review"),
                    ("accepted", "Accepted"),
                    ("rejected", "Rejected"),
                    ("canceled", "Canceled"),
                ],
                db_index=True,
                default="draft",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="requestedoffering",
            name="state",
            field=models.CharField(
                choices=[
                    ("requested", "Requested"),
                    ("accepted", "Accepted"),
                    ("canceled", "Canceled"),
                ],
                db_index=True,
                default="requested",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="state",
            field=models.CharField(
                choices=[
                    ("created", "Created"),
                    ("in_review", "In review"),
                    ("submitted", "Submitted"),
                    ("rejected", "Rejected"),
                ],
                db_index=True,
                default="created",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="round",
            name="allocation_time",
            field=models.CharField(
                choices=[("on_decision", "On decision"), ("fixed_date", "Fixed date")],
                db_index=True,
                default="on_decision",
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="round",
            name="deciding_entity",
            field=models.CharField(
                choices=[
                    ("by_call_manager", "By call manager"),
                    ("automatic", "Automatic based on review scoring"),
                ],
                db_index=True,
                default="automatic",
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="round",
            name="review_strategy",
            field=models.CharField(
                choices=[
                    ("after_round", "After round is closed"),
                    ("after_proposal", "After proposal submission"),
                ],
                db_index=True,
                default="after_round",
                max_length=15,
            ),
        ),
    ]
