# Generated by Django 4.2.24 on 2025-10-20 10:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("proposal", "0045_add_proposal_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="call",
            name="description",
            field=models.CharField(
                blank=True, max_length=4096, verbose_name="description"
            ),
        ),
        migrations.AlterField(
            model_name="calldocument",
            name="description",
            field=models.CharField(
                blank=True, max_length=4096, verbose_name="description"
            ),
        ),
        migrations.AlterField(
            model_name="callmanagingorganisation",
            name="description",
            field=models.CharField(
                blank=True, max_length=4096, verbose_name="description"
            ),
        ),
        migrations.AlterField(
            model_name="callresourcetemplate",
            name="description",
            field=models.CharField(
                blank=True, max_length=4096, verbose_name="description"
            ),
        ),
        migrations.AlterField(
            model_name="proposal",
            name="description",
            field=models.CharField(
                blank=True, max_length=4096, verbose_name="description"
            ),
        ),
        migrations.AlterField(
            model_name="requestedoffering",
            name="description",
            field=models.CharField(
                blank=True, max_length=4096, verbose_name="description"
            ),
        ),
        migrations.AlterField(
            model_name="requestedresource",
            name="description",
            field=models.CharField(
                blank=True, max_length=4096, verbose_name="description"
            ),
        ),
    ]
