# Generated by Django 4.2.24 on 2026-01-10 16:25

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.conf import settings
from django.db import migrations, models

import waldur_core.core.fields
import waldur_core.core.validators
import waldur_core.permissions.mixins
import waldur_core.structure.models
import waldur_mastermind.proposal.models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("structure", "0070_add_useragreement_language"),
        ("proposal", "0047_call_proposal_slug_template"),
    ]

    operations = [
        migrations.CreateModel(
            name="AssignmentBatch",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("uuid", waldur_core.core.fields.UUIDField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft - pending approval"),
                            ("sent", "Sent to reviewer"),
                            ("responded", "Reviewer responded"),
                            ("expired", "Invitation expired"),
                            ("cancelled", "Cancelled by manager"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "sent_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the invitation was sent to the reviewer.",
                        null=True,
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True, help_text="When the invitation expires.", null=True
                    ),
                ),
                (
                    "responded_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the reviewer completed their response.",
                        null=True,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("algorithm", "Algorithm-generated"),
                            ("manual", "Manually assigned"),
                        ],
                        default="algorithm",
                        max_length=20,
                    ),
                ),
                (
                    "invitation_token",
                    models.CharField(blank=True, max_length=64, unique=True),
                ),
                (
                    "manager_notes",
                    models.TextField(
                        blank=True,
                        help_text="Optional notes from call manager to reviewer.",
                    ),
                ),
                (
                    "reminder_sent",
                    models.BooleanField(
                        default=False,
                        help_text="Whether expiry reminder has been sent to reviewer.",
                    ),
                ),
                (
                    "manager_notified",
                    models.BooleanField(
                        default=False,
                        help_text="Whether manager has been notified of expiration.",
                    ),
                ),
            ],
            options={
                "verbose_name": "Assignment batch",
                "verbose_name_plural": "Assignment batches",
                "ordering": ["-created"],
            },
            bases=(models.Model, waldur_core.permissions.mixins.PermissionMixin),
        ),
        migrations.CreateModel(
            name="ExpertiseCategory",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=4096, verbose_name="description"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=150,
                        validators=[waldur_core.core.validators.validate_name],
                        verbose_name="name",
                    ),
                ),
                ("uuid", waldur_core.core.fields.UUIDField()),
                ("code", models.CharField(max_length=20, unique=True)),
                (
                    "level",
                    models.PositiveSmallIntegerField(
                        default=0, help_text="Depth in hierarchy (0 = root)"
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="proposal.expertisecategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Expertise category",
                "verbose_name_plural": "Expertise categories",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="ReviewerProfile",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=4096, verbose_name="description"
                    ),
                ),
                ("uuid", waldur_core.core.fields.UUIDField()),
                (
                    "orcid_id",
                    models.CharField(
                        blank=True,
                        help_text="ORCID identifier (format: 0000-0000-0000-0000)",
                        max_length=19,
                        null=True,
                        unique=True,
                        validators=[
                            waldur_mastermind.proposal.models.validate_orcid_format
                        ],
                    ),
                ),
                (
                    "biography",
                    models.TextField(
                        blank=True, help_text="Professional biography / summary"
                    ),
                ),
                (
                    "alternative_names",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of name variants used in publications",
                    ),
                ),
                ("orcid_access_token", models.CharField(blank=True, max_length=255)),
                ("orcid_refresh_token", models.CharField(blank=True, max_length=255)),
                ("orcid_last_sync", models.DateTimeField(blank=True, null=True)),
                (
                    "is_published",
                    models.BooleanField(
                        default=False,
                        help_text="Whether profile is discoverable by call managers",
                    ),
                ),
                (
                    "published_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the profile was published",
                        null=True,
                    ),
                ),
                (
                    "available_for_reviews",
                    models.BooleanField(
                        default=True,
                        help_text="Whether reviewer is currently accepting review requests",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviewer_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Reviewer profile",
                "verbose_name_plural": "Reviewer profiles",
            },
            bases=(models.Model, waldur_core.permissions.mixins.PermissionMixin),
        ),
        migrations.AlterField(
            model_name="call",
            name="reviewer_identity_visible_to_submitters",
            field=models.BooleanField(
                default=False,
                help_text="Whether proposal applicants can see reviewer identities. If False, reviewers appear as 'Reviewer 1', 'Reviewer 2', etc.",
            ),
        ),
        migrations.AlterField(
            model_name="call",
            name="reviews_visible_to_submitters",
            field=models.BooleanField(
                default=True,
                help_text="Whether proposal applicants can see review comments and scores. If False, applicants only see final approval/rejection status.",
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="state",
            field=models.CharField(
                choices=[
                    ("in_review", "In review"),
                    ("submitted", "Submitted"),
                    ("rejected", "Rejected"),
                ],
                db_index=True,
                default="in_review",
                max_length=10,
            ),
        ),
        migrations.CreateModel(
            name="ReviewerStats",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("uuid", waldur_core.core.fields.UUIDField()),
                ("total_reviews_completed", models.PositiveIntegerField(default=0)),
                ("total_reviews_declined", models.PositiveIntegerField(default=0)),
                ("total_reviews_timeout", models.PositiveIntegerField(default=0)),
                ("average_review_time_days", models.FloatField(blank=True, null=True)),
                ("average_score_given", models.FloatField(blank=True, null=True)),
                ("last_review_date", models.DateField(blank=True, null=True)),
                (
                    "quality_rating",
                    models.FloatField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(1.0)],
                    ),
                ),
                ("quality_rating_count", models.PositiveIntegerField(default=0)),
                (
                    "reviewer_profile",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stats",
                        to="proposal.reviewerprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Reviewer statistics",
                "verbose_name_plural": "Reviewer statistics",
            },
        ),
        migrations.CreateModel(
            name="MatchingConfiguration",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("uuid", waldur_core.core.fields.UUIDField()),
                (
                    "affinity_method",
                    models.CharField(
                        choices=[
                            ("keyword", "Keyword matching only"),
                            ("tfidf", "TF-IDF text similarity"),
                            ("combined", "Combined keyword + text"),
                        ],
                        default="combined",
                        max_length=20,
                    ),
                ),
                (
                    "keyword_weight",
                    models.FloatField(
                        default=0.4,
                        validators=[django.core.validators.MinValueValidator(0.0)],
                    ),
                ),
                (
                    "text_weight",
                    models.FloatField(
                        default=0.6,
                        validators=[django.core.validators.MinValueValidator(0.0)],
                    ),
                ),
                ("min_reviewers_per_proposal", models.PositiveIntegerField(default=3)),
                ("max_reviewers_per_proposal", models.PositiveIntegerField(default=5)),
                ("min_proposals_per_reviewer", models.PositiveIntegerField(default=3)),
                ("max_proposals_per_reviewer", models.PositiveIntegerField(default=10)),
                (
                    "algorithm",
                    models.CharField(
                        choices=[
                            ("minmax", "MinMax (balanced load)"),
                            ("fairflow", "FairFlow (quality threshold)"),
                            ("hungarian", "Hungarian (global optimum)"),
                        ],
                        default="minmax",
                        max_length=20,
                    ),
                ),
                (
                    "min_affinity_threshold",
                    models.FloatField(
                        default=0.1,
                        help_text="Minimum affinity score for FairFlow algorithm",
                        validators=[django.core.validators.MinValueValidator(0.0)],
                    ),
                ),
                ("use_reviewer_bids", models.BooleanField(default=True)),
                (
                    "bid_weight",
                    models.FloatField(
                        default=0.3,
                        validators=[django.core.validators.MinValueValidator(0.0)],
                    ),
                ),
                (
                    "call",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matching_configuration",
                        to="proposal.call",
                    ),
                ),
            ],
            options={
                "verbose_name": "Matching configuration",
                "verbose_name_plural": "Matching configurations",
            },
        ),
        migrations.CreateModel(
            name="ConflictOfInterest",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("uuid", waldur_core.core.fields.UUIDField()),
                (
                    "coi_type",
                    models.CharField(
                        choices=[
                            ("INST_SAME", "Same institution"),
                            ("FIN_DIRECT", "Direct financial interest"),
                            ("REL_FAMILY", "Family relationship"),
                            ("ROLE_NAMED", "Named on proposal"),
                            ("COLLAB_ACTIVE", "Active collaboration"),
                            ("REL_MENTOR", "Mentor/mentee relationship"),
                            ("REL_SUPERVISOR", "Supervisor relationship"),
                            ("COAUTH_RECENT", "Recent co-authorship"),
                            ("INST_DEPT", "Same department"),
                            ("INST_FORMER", "Former institution"),
                            ("ROLE_CONF", "Conference organizer"),
                            ("COLLAB_GRANT", "Grant collaboration"),
                            ("REL_EDITORIAL", "Editorial relationship"),
                            ("COMPET", "Competitor"),
                            ("COAUTH_OLD", "Distant co-authorship"),
                            ("INST_CONSORT", "Consortium membership"),
                            ("CONF_ATTEND", "Conference participation"),
                            ("SOC_MEMBER", "Professional society"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("real", "Real conflict - must recuse"),
                            ("apparent", "Apparent conflict - requires management"),
                            ("potential", "Potential conflict - disclosure only"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "detection_method",
                    models.CharField(
                        choices=[
                            ("automated", "Automated detection"),
                            ("self_disclosed", "Self-disclosed by reviewer"),
                            ("reported", "Reported by third party"),
                            ("manager_identified", "Identified by call manager"),
                        ],
                        max_length=20,
                    ),
                ),
                ("detected_at", models.DateTimeField(auto_now_add=True)),
                ("evidence_description", models.TextField()),
                (
                    "evidence_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='Structured evidence: {"papers": [...], "affiliation_overlap": {...}}',
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending review"),
                            ("dismissed", "Dismissed - not a conflict"),
                            ("waived", "Waived with management plan"),
                            ("recused", "Reviewer recused"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("review_notes", models.TextField(blank=True)),
                (
                    "management_plan",
                    models.TextField(
                        blank=True, help_text="If waived, how is it managed"
                    ),
                ),
                (
                    "call",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conflicts",
                        to="proposal.call",
                    ),
                ),
                (
                    "conflicting_organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="structure.customer",
                    ),
                ),
                (
                    "conflicting_user",
                    models.ForeignKey(
                        blank=True,
                        help_text="Specific person causing conflict",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "proposal",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conflicts",
                        to="proposal.proposal",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="coi_reviews_performed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conflicts",
                        to="proposal.reviewerprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Conflict of interest",
                "verbose_name_plural": "Conflicts of interest",
                "ordering": ["-detected_at"],
            },
            bases=(
                models.Model,
                waldur_core.structure.models.StructureLoggableMixin,
                waldur_core.permissions.mixins.PermissionMixin,
            ),
        ),
        migrations.CreateModel(
            name="COIDisclosureForm",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("uuid", waldur_core.core.fields.UUIDField()),
                ("certified", models.BooleanField(default=False)),
                ("certification_date", models.DateTimeField(blank=True, null=True)),
                (
                    "certification_statement",
                    models.TextField(blank=True, help_text="Legal text they agreed to"),
                ),
                ("has_financial_interests", models.BooleanField(default=False)),
                ("has_personal_relationships", models.BooleanField(default=False)),
                ("personal_relationships", models.JSONField(blank=True, default=list)),
                ("has_other_conflicts", models.BooleanField(default=False)),
                ("other_conflicts_description", models.TextField(blank=True)),
                (
                    "valid_until",
                    models.DateField(help_text="Typically 1 year from certification"),
                ),
                ("is_current", models.BooleanField(default=True)),
                (
                    "call",
                    models.ForeignKey(
                        blank=True,
                        help_text="Null for general annual disclosure",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="disclosure_forms",
                        to="proposal.call",
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="disclosure_forms",
                        to="proposal.reviewerprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "COI disclosure form",
                "verbose_name_plural": "COI disclosure forms",
                "ordering": ["-certification_date"],
            },
        ),
        migrations.CreateModel(
            name="COIDisclosureFinancialInterest",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("uuid", waldur_core.core.fields.UUIDField()),
                ("entity_name", models.CharField(max_length=255)),
                (
                    "entity_type",
                    models.CharField(
                        choices=[
                            ("company", "Company"),
                            ("startup", "Startup"),
                            ("nonprofit", "Non-profit organization"),
                            ("government", "Government entity"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "relationship_type",
                    models.CharField(
                        choices=[
                            ("employment", "Employment"),
                            ("consulting", "Consulting"),
                            ("equity", "Equity/stock ownership"),
                            ("board", "Board membership"),
                            ("royalties", "Royalties/licensing"),
                            ("gifts", "Gifts/honoraria"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "amount_range",
                    models.CharField(
                        choices=[
                            ("none", "None"),
                            ("under_5k", "Under $5,000"),
                            ("5k_10k", "$5,000 - $10,000"),
                            ("10k_50k", "$10,000 - $50,000"),
                            ("over_50k", "Over $50,000"),
                        ],
                        max_length=20,
                    ),
                ),
                ("is_ongoing", models.BooleanField(default=True)),
                ("description", models.TextField(blank=True)),
                (
                    "disclosure_form",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="financial_interests",
                        to="proposal.coidisclosureform",
                    ),
                ),
            ],
            options={
                "verbose_name": "Financial interest disclosure",
                "verbose_name_plural": "Financial interest disclosures",
            },
        ),
        migrations.CreateModel(
            name="COIDetectionJob",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("uuid", waldur_core.core.fields.UUIDField()),
                (
                    "job_type",
                    models.CharField(
                        choices=[
                            ("full_call", "Full call detection"),
                            ("incremental", "Incremental detection"),
                            ("single_pair", "Single pair detection"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("total_pairs", models.PositiveIntegerField(default=0)),
                ("processed_pairs", models.PositiveIntegerField(default=0)),
                ("conflicts_found", models.PositiveIntegerField(default=0)),
                (
                    "celery_task_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True)),
                ("config_snapshot", models.JSONField(blank=True, default=dict)),
                (
                    "call",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="coi_jobs",
                        to="proposal.call",
                    ),
                ),
            ],
            options={
                "verbose_name": "COI detection job",
                "verbose_name_plural": "COI detection jobs",
                "ordering": ["-created"],
            },
        ),
        migrations.CreateModel(
            name="CallReviewerPool",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("uuid", waldur_core.core.fields.UUIDField()),
                (
                    "invited_email",
                    models.EmailField(
                        blank=True,
                        help_text="Email address for direct invitations",
                        max_length=254,
                    ),
                ),
                ("invited_at", models.DateTimeField(auto_now_add=True)),
                (
                    "invitation_status",
                    models.CharField(
                        choices=[
                            ("pending", "Invitation pending"),
                            ("accepted", "Accepted"),
                            ("declined", "Declined"),
                            ("expired", "Invitation expired"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("response_date", models.DateTimeField(blank=True, null=True)),
                ("decline_reason", models.TextField(blank=True)),
                ("max_assignments", models.PositiveIntegerField(default=5)),
                ("current_assignments", models.PositiveIntegerField(default=0)),
                (
                    "expertise_match_score",
                    models.FloatField(
                        blank=True,
                        help_text="Calculated affinity to call topics (0-1)",
                        null=True,
                    ),
                ),
                (
                    "invitation_token",
                    models.CharField(blank=True, max_length=64, unique=True),
                ),
                ("invitation_expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "call",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviewer_pool",
                        to="proposal.call",
                    ),
                ),
                (
                    "invited_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "invited_user",
                    models.ForeignKey(
                        blank=True,
                        help_text="Waldur user if email matches existing account",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewer_invitations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pool_memberships",
                        to="proposal.reviewerprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Call reviewer pool member",
                "verbose_name_plural": "Call reviewer pool members",
                "ordering": ["-invited_at"],
            },
            bases=(models.Model, waldur_core.permissions.mixins.PermissionMixin),
        ),
        migrations.CreateModel(
            name="CallCOIConfiguration",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("uuid", waldur_core.core.fields.UUIDField()),
                (
                    "coauthorship_lookback_years",
                    models.PositiveIntegerField(
                        default=3,
                        help_text="Years to look back for co-authorship detection",
                    ),
                ),
                (
                    "coauthorship_threshold_papers",
                    models.PositiveIntegerField(
                        default=1, help_text="Minimum shared papers to trigger COI"
                    ),
                ),
                (
                    "institutional_lookback_years",
                    models.PositiveIntegerField(
                        default=2,
                        help_text="Years to look back for former institution detection",
                    ),
                ),
                (
                    "include_same_department",
                    models.BooleanField(
                        default=True, help_text="Detect same-department as COI"
                    ),
                ),
                (
                    "include_same_institution",
                    models.BooleanField(
                        default=True, help_text="Detect same-institution as COI"
                    ),
                ),
                (
                    "recusal_required_types",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="COI types requiring automatic recusal",
                    ),
                ),
                (
                    "management_allowed_types",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="COI types allowing management plan",
                    ),
                ),
                (
                    "disclosure_only_types",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="COI types requiring disclosure only",
                    ),
                ),
                (
                    "auto_detect_coauthorship",
                    models.BooleanField(
                        default=True,
                        help_text="Enable automated co-authorship detection",
                    ),
                ),
                (
                    "auto_detect_institutional",
                    models.BooleanField(
                        default=True,
                        help_text="Enable automated institutional affiliation detection",
                    ),
                ),
                (
                    "auto_detect_named_personnel",
                    models.BooleanField(
                        default=True,
                        help_text="Enable detection of reviewer named in proposals",
                    ),
                ),
                (
                    "invitation_proposal_disclosure",
                    models.CharField(
                        choices=[
                            ("titles_only", "Titles only"),
                            ("titles_and_summaries", "Titles and summaries"),
                            ("full_details", "Full proposal details"),
                        ],
                        default="titles_only",
                        help_text="Level of proposal information disclosed in reviewer invitations",
                        max_length=30,
                    ),
                ),
                (
                    "call",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="coi_configuration",
                        to="proposal.call",
                    ),
                ),
            ],
            options={
                "verbose_name": "Call COI configuration",
                "verbose_name_plural": "Call COI configurations",
            },
        ),
        migrations.CreateModel(
            name="CallAssignmentConfiguration",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("uuid", waldur_core.core.fields.UUIDField()),
                (
                    "auto_reassign_on_decline",
                    models.BooleanField(
                        default=False,
                        help_text="Automatically assign next-best reviewer when someone declines. If False, manager must manually approve reassignments.",
                    ),
                ),
                (
                    "max_auto_reassign_attempts",
                    models.PositiveIntegerField(
                        default=3,
                        help_text="Maximum automatic reassignment attempts before requiring manual intervention.",
                    ),
                ),
                (
                    "assignment_expiration_days",
                    models.PositiveIntegerField(
                        default=7,
                        help_text="Days until assignment invitation expires if not responded to.",
                    ),
                ),
                (
                    "send_reminder_before_expiry_days",
                    models.PositiveIntegerField(
                        default=2,
                        help_text="Days before expiry to send reminder notification.",
                    ),
                ),
                (
                    "call",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignment_configuration",
                        to="proposal.call",
                    ),
                ),
            ],
            options={
                "verbose_name": "Call assignment configuration",
                "verbose_name_plural": "Call assignment configurations",
            },
        ),
        migrations.CreateModel(
            name="AssignmentItem",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("uuid", waldur_core.core.fields.UUIDField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Awaiting response"),
                            ("accepted", "Accepted"),
                            ("declined", "Declined"),
                            ("coi_blocked", "Blocked due to COI"),
                            ("expired", "Expired without response"),
                            ("reassigned", "Reassigned to another reviewer"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "affinity_score",
                    models.FloatField(
                        blank=True,
                        help_text="Affinity score used for assignment (0-1).",
                        null=True,
                    ),
                ),
                (
                    "has_coi",
                    models.BooleanField(
                        default=False,
                        help_text="Whether COI was detected during pre-check.",
                    ),
                ),
                ("responded_at", models.DateTimeField(blank=True, null=True)),
                (
                    "decline_reason",
                    models.TextField(
                        blank=True,
                        help_text="Reason provided by reviewer for declining.",
                    ),
                ),
                (
                    "reassign_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Number of times this proposal has been reassigned.",
                    ),
                ),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="proposal.assignmentbatch",
                    ),
                ),
                (
                    "coi_records",
                    models.ManyToManyField(
                        blank=True,
                        help_text="COI records that block this assignment.",
                        related_name="blocked_assignments",
                        to="proposal.conflictofinterest",
                    ),
                ),
                (
                    "proposal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignment_items",
                        to="proposal.proposal",
                    ),
                ),
                (
                    "reassigned_from",
                    models.ForeignKey(
                        blank=True,
                        help_text="If this is a reassignment, the original item.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reassigned_to_items",
                        to="proposal.assignmentitem",
                    ),
                ),
                (
                    "review",
                    models.OneToOneField(
                        blank=True,
                        help_text="The Review record created when this assignment was accepted.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assignment_item",
                        to="proposal.review",
                    ),
                ),
            ],
            options={
                "verbose_name": "Assignment item",
                "verbose_name_plural": "Assignment items",
                "ordering": ["-affinity_score"],
            },
            bases=(models.Model, waldur_core.permissions.mixins.PermissionMixin),
        ),
        migrations.AddField(
            model_name="assignmentbatch",
            name="call",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assignment_batches",
                to="proposal.call",
            ),
        ),
        migrations.AddField(
            model_name="assignmentbatch",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created/approved this batch.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="assignmentbatch",
            name="reviewer_pool_entry",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assignment_batches",
                to="proposal.callreviewerpool",
            ),
        ),
        migrations.CreateModel(
            name="ReviewerSuggestion",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("uuid", waldur_core.core.fields.UUIDField()),
                (
                    "affinity_score",
                    models.FloatField(help_text="Combined affinity score (0-1)"),
                ),
                (
                    "keyword_score",
                    models.FloatField(
                        blank=True, help_text="Keyword matching score", null=True
                    ),
                ),
                (
                    "text_score",
                    models.FloatField(
                        blank=True, help_text="TF-IDF text similarity score", null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Awaiting manager review"),
                            ("confirmed", "Manager approved"),
                            ("rejected", "Manager rejected"),
                            ("invited", "Invitation sent"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("rejection_reason", models.TextField(blank=True)),
                (
                    "matched_keywords",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Keywords from reviewer's expertise that matched the source text",
                    ),
                ),
                (
                    "top_matching_proposals",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Top proposals with highest affinity: [{uuid, name, slug, affinity}, ...]",
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("call_description", "Call description"),
                            ("all_proposals", "All proposals"),
                            ("selected_proposals", "Selected proposals"),
                            ("custom_keywords", "Custom keywords"),
                        ],
                        default="all_proposals",
                        help_text="What content was used to generate this suggestion",
                        max_length=30,
                    ),
                ),
                (
                    "call",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviewer_suggestions",
                        to="proposal.call",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="suggestions",
                        to="proposal.reviewerprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Reviewer suggestion",
                "verbose_name_plural": "Reviewer suggestions",
                "ordering": ["-affinity_score"],
                "indexes": [
                    models.Index(
                        fields=["status"], name="proposal_re_status_d52565_idx"
                    )
                ],
                "unique_together": {("call", "reviewer")},
            },
        ),
        migrations.CreateModel(
            name="ReviewerPublication",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("uuid", waldur_core.core.fields.UUIDField()),
                ("title", models.CharField(max_length=500)),
                (
                    "doi",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Digital Object Identifier",
                        max_length=100,
                        null=True,
                    ),
                ),
                ("publication_year", models.PositiveIntegerField()),
                (
                    "venue",
                    models.CharField(
                        help_text="Journal or conference name", max_length=255
                    ),
                ),
                (
                    "venue_type",
                    models.CharField(
                        choices=[
                            ("journal", "Journal article"),
                            ("conference", "Conference paper"),
                            ("preprint", "Preprint"),
                            ("book", "Book or book chapter"),
                            ("thesis", "Thesis or dissertation"),
                            ("report", "Technical report"),
                            ("other", "Other"),
                        ],
                        default="journal",
                        max_length=20,
                    ),
                ),
                ("abstract", models.TextField(blank=True)),
                (
                    "coauthors",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of co-author names and identifiers",
                    ),
                ),
                (
                    "external_ids",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='External identifiers: {"semantic_scholar": "...", "pubmed": "..."}',
                    ),
                ),
                (
                    "is_excluded_from_matching",
                    models.BooleanField(
                        default=False,
                        help_text="User can exclude old papers from expertise matching",
                    ),
                ),
                (
                    "reviewer_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="publications",
                        to="proposal.reviewerprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Reviewer publication",
                "verbose_name_plural": "Reviewer publications",
                "ordering": ["-publication_year"],
                "indexes": [
                    models.Index(fields=["doi"], name="proposal_re_doi_4174b2_idx"),
                    models.Index(
                        fields=["publication_year"],
                        name="proposal_re_publica_f170a3_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ReviewerProposalAffinity",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("uuid", waldur_core.core.fields.UUIDField()),
                (
                    "affinity_score",
                    models.FloatField(help_text="Combined affinity score (0-1)"),
                ),
                (
                    "keyword_score",
                    models.FloatField(
                        blank=True, help_text="Keyword-based affinity score", null=True
                    ),
                ),
                (
                    "text_score",
                    models.FloatField(
                        blank=True,
                        help_text="Text-based (TF-IDF) affinity score",
                        null=True,
                    ),
                ),
                (
                    "call",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="affinities",
                        to="proposal.call",
                    ),
                ),
                (
                    "proposal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="affinities",
                        to="proposal.proposal",
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="affinities",
                        to="proposal.reviewerprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Reviewer proposal affinity",
                "verbose_name_plural": "Reviewer proposal affinities",
                "indexes": [
                    models.Index(
                        fields=["call", "affinity_score"],
                        name="proposal_re_call_id_672d5d_idx",
                    )
                ],
                "unique_together": {("call", "reviewer", "proposal")},
            },
        ),
        migrations.CreateModel(
            name="ReviewerExpertise",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("uuid", waldur_core.core.fields.UUIDField()),
                (
                    "expertise_keyword",
                    models.CharField(help_text="Free-text keyword", max_length=100),
                ),
                (
                    "proficiency_level",
                    models.CharField(
                        choices=[
                            ("expert", "Expert - Can review independently"),
                            ("familiar", "Familiar - Can review with guidance"),
                            ("basic", "Basic - General understanding only"),
                        ],
                        default="familiar",
                        max_length=20,
                    ),
                ),
                (
                    "years_experience",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "last_active_date",
                    models.DateField(
                        blank=True, help_text="When last worked in this area", null=True
                    ),
                ),
                (
                    "expertise_category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="proposal.expertisecategory",
                    ),
                ),
                (
                    "reviewer_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expertise_set",
                        to="proposal.reviewerprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Reviewer expertise",
                "verbose_name_plural": "Reviewer expertise",
                "indexes": [
                    models.Index(
                        fields=["expertise_keyword"],
                        name="proposal_re_experti_cb9c26_idx",
                    ),
                    models.Index(
                        fields=["proficiency_level"],
                        name="proposal_re_profici_596a12_idx",
                    ),
                ],
                "unique_together": {("reviewer_profile", "expertise_keyword")},
            },
        ),
        migrations.CreateModel(
            name="ReviewerBid",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("uuid", waldur_core.core.fields.UUIDField()),
                (
                    "bid",
                    models.CharField(
                        choices=[
                            ("eager", "Eager to review"),
                            ("willing", "Willing to review"),
                            ("not_willing", "Not willing to review"),
                            ("conflict", "Has conflict of interest"),
                        ],
                        help_text="Reviewer's preference for reviewing this proposal",
                        max_length=20,
                    ),
                ),
                (
                    "comment",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Optional comment explaining the bid",
                    ),
                ),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "call",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviewer_bids",
                        to="proposal.call",
                    ),
                ),
                (
                    "proposal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviewer_bids",
                        to="proposal.proposal",
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bids",
                        to="proposal.reviewerprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Reviewer bid",
                "verbose_name_plural": "Reviewer bids",
                "ordering": ["-submitted_at"],
                "unique_together": {("call", "reviewer", "proposal")},
            },
        ),
        migrations.CreateModel(
            name="ReviewerAffiliation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("uuid", waldur_core.core.fields.UUIDField()),
                (
                    "organization_name",
                    models.CharField(
                        help_text="Organization name (used when not linked to Waldur org)",
                        max_length=255,
                    ),
                ),
                (
                    "organization_identifier",
                    models.CharField(
                        blank=True,
                        help_text="ROR, GRID, or other external identifier",
                        max_length=100,
                    ),
                ),
                ("department", models.CharField(blank=True, max_length=255)),
                ("position_title", models.CharField(blank=True, max_length=255)),
                ("start_date", models.DateField(blank=True, null=True)),
                (
                    "end_date",
                    models.DateField(
                        blank=True,
                        help_text="Leave empty for current affiliation",
                        null=True,
                    ),
                ),
                ("is_primary", models.BooleanField(default=False)),
                (
                    "affiliation_type",
                    models.CharField(
                        choices=[
                            ("employment", "Employment"),
                            ("education", "Education"),
                            ("visiting", "Visiting position"),
                            ("honorary", "Honorary position"),
                            ("consulting", "Consulting"),
                        ],
                        default="employment",
                        max_length=20,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        help_text="Link to Waldur organization if applicable",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="structure.customer",
                    ),
                ),
                (
                    "reviewer_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="affiliations",
                        to="proposal.reviewerprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Reviewer affiliation",
                "verbose_name_plural": "Reviewer affiliations",
                "ordering": ["-start_date"],
                "indexes": [
                    models.Index(
                        fields=["organization"], name="proposal_re_organiz_a60166_idx"
                    ),
                    models.Index(
                        fields=["organization_name"],
                        name="proposal_re_organiz_0c08a8_idx",
                    ),
                    models.Index(
                        fields=["end_date"], name="proposal_re_end_dat_8866d8_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ProposedAssignment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("uuid", waldur_core.core.fields.UUIDField()),
                ("affinity_score", models.FloatField()),
                (
                    "algorithm_used",
                    models.CharField(
                        choices=[
                            ("minmax", "MinMax (balanced load)"),
                            ("fairflow", "FairFlow (quality threshold)"),
                            ("hungarian", "Hungarian (global optimum)"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "rank",
                    models.PositiveIntegerField(
                        default=0, help_text="Assignment rank (1 = best match)"
                    ),
                ),
                ("is_deployed", models.BooleanField(default=False)),
                ("deployed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "call",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="proposed_assignments",
                        to="proposal.call",
                    ),
                ),
                (
                    "deployed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "proposal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="proposed_assignments",
                        to="proposal.proposal",
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="proposed_assignments",
                        to="proposal.reviewerprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Proposed assignment",
                "verbose_name_plural": "Proposed assignments",
                "ordering": ["proposal", "rank"],
                "unique_together": {("call", "reviewer", "proposal")},
            },
        ),
        migrations.AddIndex(
            model_name="conflictofinterest",
            index=models.Index(
                fields=["call", "status"], name="proposal_co_call_id_d9eae5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="conflictofinterest",
            index=models.Index(
                fields=["reviewer", "proposal"], name="proposal_co_reviewe_2dc381_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="conflictofinterest",
            index=models.Index(
                fields=["coi_type", "severity"], name="proposal_co_coi_typ_2d142e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="coidisclosureform",
            index=models.Index(
                fields=["reviewer", "call"], name="proposal_co_reviewe_7de133_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="coidisclosureform",
            index=models.Index(
                fields=["is_current", "valid_until"],
                name="proposal_co_is_curr_407519_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="callreviewerpool",
            index=models.Index(
                fields=["invitation_status"], name="proposal_ca_invitat_04122b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="callreviewerpool",
            index=models.Index(
                fields=["invitation_token"], name="proposal_ca_invitat_61f0fd_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="callreviewerpool",
            constraint=models.UniqueConstraint(
                condition=models.Q(("reviewer__isnull", False)),
                fields=("call", "reviewer"),
                name="unique_call_reviewer",
            ),
        ),
        migrations.AddConstraint(
            model_name="callreviewerpool",
            constraint=models.UniqueConstraint(
                condition=models.Q(("invited_email__gt", "")),
                fields=("call", "invited_email"),
                name="unique_call_invited_email",
            ),
        ),
        migrations.AddConstraint(
            model_name="callreviewerpool",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("reviewer__isnull", False),
                    ("invited_email__gt", ""),
                    _connector="OR",
                ),
                name="reviewer_or_email_required",
            ),
        ),
        migrations.AddIndex(
            model_name="assignmentitem",
            index=models.Index(fields=["status"], name="proposal_as_status_efe0c6_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="assignmentitem",
            unique_together={("batch", "proposal")},
        ),
        migrations.AddIndex(
            model_name="assignmentbatch",
            index=models.Index(fields=["status"], name="proposal_as_status_720203_idx"),
        ),
        migrations.AddIndex(
            model_name="assignmentbatch",
            index=models.Index(
                fields=["invitation_token"], name="proposal_as_invitat_302a6f_idx"
            ),
        ),
    ]
