# Generated by Django 6.0.4 on 2026-05-04 11:06

from django.db import migrations, models

DEFAULT_RESPONSIBLE_ROLES = {
    "administrative_check": "call_manager",
    "technical_assessment": "offering_manager",
    "expert_review": "reviewer",
    "panel_review": "panel_member",
    "allocation_decision": "call_manager",
    "award_response": "applicant",
}


def backfill_responsible_role(apps, schema_editor):
    CallWorkflowStep = apps.get_model("proposal", "CallWorkflowStep")
    for step_id, role in DEFAULT_RESPONSIBLE_ROLES.items():
        CallWorkflowStep.objects.filter(
            step=step_id, responsible_role__isnull=True
        ).update(responsible_role=role)


def reverse_backfill(apps, schema_editor):
    CallWorkflowStep = apps.get_model("proposal", "CallWorkflowStep")
    CallWorkflowStep.objects.update(responsible_role=None)


class Migration(migrations.Migration):
    dependencies = [
        ("proposal", "0051_merge_20260430_0901"),
    ]

    operations = [
        migrations.AddField(
            model_name="callworkflowstep",
            name="responsible_role",
            field=models.CharField(
                blank=True,
                choices=[
                    ("call_manager", "Call manager"),
                    ("offering_manager", "Offering manager"),
                    ("reviewer", "Reviewer"),
                    ("panel_member", "Panel member"),
                    ("applicant", "Applicant"),
                ],
                help_text="Role expected to act on this step.",
                max_length=32,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="callworkflowstep",
            name="transition_mode",
            field=models.CharField(
                choices=[
                    (
                        "automatic_on_completion",
                        "Advance automatically when step completes",
                    ),
                ],
                default="automatic_on_completion",
                help_text="How this step advances to the next.",
                max_length=32,
            ),
        ),
        migrations.RunPython(backfill_responsible_role, reverse_backfill),
    ]
