# Generated by Django 6.0.4 on 2026-05-05 07:47

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import waldur_core.core.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("proposal", "0052_callworkflowstep_responsible_role_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="callworkflowstep",
            name="display_order",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Optional override of catalog ordering.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="callworkflowstep",
            name="include_award_response",
            field=models.BooleanField(
                default=False,
                help_text="Allocation decision: require applicant award response after decision.",
            ),
        ),
        migrations.CreateModel(
            name="WorkflowCriterion",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("uuid", waldur_core.core.fields.UUIDField()),
                ("name", models.CharField(max_length=255)),
                ("order", models.PositiveSmallIntegerField(default=0)),
                (
                    "workflow_step",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="criteria",
                        to="proposal.callworkflowstep",
                    ),
                ),
            ],
            options={
                "verbose_name": "Workflow criterion",
                "verbose_name_plural": "Workflow criteria",
                "ordering": ["order", "id"],
                "unique_together": {("workflow_step", "name")},
            },
        ),
    ]
