# Generated by Django 6.0.5 on 2026-05-25 06:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("proposal", "0056_backfill_allocation_decision_step"),
    ]

    operations = [
        migrations.AddField(
            model_name="proposalworkflowstepinstance",
            name="internal_notes",
            field=models.TextField(
                blank=True,
                help_text="Notes captured by the call-management team when completing or rejecting the step. Never shown to the applicant. Visible in API responses to staff and to any user who holds an active role on the proposal's call (see permissions.user_can_view_internal_notes).",
            ),
        ),
    ]
