# Generated by Django 6.0.6 on 2026-07-09 17:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("proposal", "0062_move_allocation_time_to_workflow_step"),
    ]

    operations = [
        migrations.AlterField(
            model_name="callworkflowstep",
            name="min_score_threshold",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Minimum average score required before this step can complete (a completion gate; it does not auto-reject lower scores).",
                max_digits=5,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="callworkflowstep",
            name="transition_mode",
            field=models.CharField(
                choices=[
                    (
                        "automatic_on_completion",
                        "Advance to the next step as soon as this one is completed",
                    ),
                    ("manual", "Hold for a separate manual advance after completion"),
                ],
                default="automatic_on_completion",
                help_text="How this step advances once a human completes it. 'Automatic' advances to the next step immediately; 'Manual' waits for a separate advance action. Neither auto-decides from review scores.",
                max_length=32,
            ),
        ),
    ]
