# Generated by Django 6.0.6 on 2026-07-10 13:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("proposal", "0064_backfill_stranded_workflow_instances"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="coi_confirmed",
            field=models.BooleanField(
                default=False,
                help_text="Reviewer confirmed absence of conflict of interest with this proposal.",
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="coi_confirmed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
