# Generated by Django 6.0.6 on 2026-07-10 13:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("proposal", "0065_review_coi_confirmed_review_coi_confirmed_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="callworkflowstep",
            name="checklist_required",
            field=models.BooleanField(
                default=True,
                help_text="When the step has a checklist, block completion until its required questions are answered. Set False to make the checklist advisory.",
            ),
        ),
    ]
