# Generated by Django 6.0.8 on 2026-08-20 07:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("proposal", "0068_requestedoffering_require_purchase_order_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="call",
            options={"ordering": ["-created", "id"]},
        ),
        migrations.AlterModelOptions(
            name="callassignmentconfiguration",
            options={
                "ordering": ["-created", "id"],
                "verbose_name": "Call assignment configuration",
                "verbose_name_plural": "Call assignment configurations",
            },
        ),
        migrations.AlterModelOptions(
            name="review",
            options={"ordering": ["-created", "id"]},
        ),
        migrations.AlterModelOptions(
            name="reviewerexpertise",
            options={
                "ordering": ["-created", "id"],
                "verbose_name": "Reviewer expertise",
                "verbose_name_plural": "Reviewer expertise",
            },
        ),
    ]
