# Generated by Django 6.0.8 on 2026-08-20 13:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("proposal", "0069_alter_call_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="requestedresource",
            options={"ordering": ["-created", "id"]},
        ),
        migrations.AlterModelOptions(
            name="round",
            options={"ordering": ["-created", "id"]},
        ),
    ]
