# Generated by Django 6.0.8 on 2026-08-21 06:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("proposal", "0071_alter_assignmentbatch_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="callworkflowstep",
            options={
                "ordering": ["created", "id"],
                "verbose_name": "Workflow step",
                "verbose_name_plural": "Workflow steps",
            },
        ),
        migrations.AlterModelOptions(
            name="proposalworkflowstepinstance",
            options={
                "ordering": ["created", "id"],
                "verbose_name": "Proposal workflow step",
                "verbose_name_plural": "Proposal workflow steps",
            },
        ),
        migrations.AlterModelOptions(
            name="proposedassignment",
            options={
                "ordering": ["proposal", "rank", "id"],
                "verbose_name": "Proposed assignment",
                "verbose_name_plural": "Proposed assignments",
            },
        ),
    ]
