# Generated by Django 6.0.8 on 2026-08-25 22:16

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models

import waldur_core.core.fields


class Migration(migrations.Migration):
    dependencies = [
        ("proposal", "0073_remove_proposal_project_has_civilian_purpose_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CallProposalFieldConfig",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("uuid", waldur_core.core.fields.UUIDField()),
                (
                    "field_project_summary",
                    models.CharField(
                        choices=[
                            ("hidden", "Hidden"),
                            ("optional", "Optional"),
                            ("required", "Required"),
                        ],
                        default="required",
                        max_length=10,
                    ),
                ),
                (
                    "field_description",
                    models.CharField(
                        choices=[
                            ("hidden", "Hidden"),
                            ("optional", "Optional"),
                            ("required", "Required"),
                        ],
                        default="optional",
                        max_length=10,
                    ),
                ),
                (
                    "field_science_sub_domain",
                    models.CharField(
                        choices=[
                            ("hidden", "Hidden"),
                            ("optional", "Optional"),
                            ("required", "Required"),
                        ],
                        default="optional",
                        max_length=10,
                    ),
                ),
                (
                    "field_supporting_documentation",
                    models.CharField(
                        choices=[
                            ("hidden", "Hidden"),
                            ("optional", "Optional"),
                            ("required", "Required"),
                        ],
                        default="optional",
                        max_length=10,
                    ),
                ),
                (
                    "call",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="proposal_field_config",
                        to="proposal.call",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
