# Generated by Django 6.0.8 on 2026-08-28 21:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("proposal", "0074_callproposalfieldconfig"),
    ]

    operations = [
        migrations.AlterField(
            model_name="proposal",
            name="duration_in_days",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Legacy: recorded on proposals created before the length was derived from the requested resources; not written any more.",
                null=True,
            ),
        ),
    ]
