# Generated by Django 6.0.8 on 2026-08-29 04:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("proposal", "0075_alter_proposal_duration_in_days"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="proposal",
            name="duration_in_days",
        ),
    ]
