# Generated by Django 6.0.8 on 2026-08-29 14:13

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.conf import settings
from django.db import migrations, models

import waldur_core.core.fields


class Migration(migrations.Migration):
    dependencies = [
        ("proposal", "0076_remove_proposal_duration_in_days"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="call",
            name="panel_chair",
            field=models.ForeignKey(
                blank=True,
                help_text="Panel member who chairs this call's review panel. Must hold the panel member role on the call; cleared automatically when that role is revoked. Addressable by notification rules as panel_chair.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="proposalworkflowstepinstance",
            name="sent_notifications",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text='Ledger of notification-rule events already dispatched for this instance ("<trigger>" or "deadline_approaching:<days>"), so a reminder is never sent twice.',
            ),
        ),
        migrations.CreateModel(
            name="CallWorkflowStepNotificationRule",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("uuid", waldur_core.core.fields.UUIDField()),
                (
                    "trigger",
                    models.CharField(
                        choices=[
                            ("step_started", "Step started"),
                            ("step_completed", "Step completed"),
                            ("step_rejected", "Step rejected"),
                            ("step_expired", "Step expired"),
                            ("deadline_approaching", "Deadline approaching"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "recipient",
                    models.CharField(
                        choices=[
                            ("applicant", "Applicant"),
                            ("responsible_role", "Responsible role"),
                            ("assigned_reviewers", "Assigned reviewers"),
                            ("call_managers", "Call managers"),
                            ("all_pool_reviewers", "All pool reviewers"),
                            ("panel_chair", "Panel chair"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "days_before",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Only for deadline_approaching: how many days before the step's deadline the reminder is sent.",
                        null=True,
                    ),
                ),
                ("is_enabled", models.BooleanField(default=True)),
                (
                    "workflow_step",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_rules",
                        to="proposal.callworkflowstep",
                    ),
                ),
            ],
            options={
                "verbose_name": "Workflow step notification rule",
                "verbose_name_plural": "Workflow step notification rules",
                "ordering": ["created", "id"],
                "unique_together": {("workflow_step", "trigger", "recipient")},
            },
        ),
    ]
