# Generated by Django 6.0.8 on 2026-09-15 18:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("proposal", "0079_backfill_system_role_descriptions"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="call",
            name="support_ticket_caller",
            field=models.CharField(
                choices=[
                    ("applicant", "Proposal applicant"),
                    ("project_manager", "Project manager"),
                    ("call_manager", "Call manager"),
                    ("specific_user", "Named contact"),
                ],
                default="applicant",
                help_text="Who helpdesk tickets for granted resources are raised for. They receive the helpdesk's replies; reading the ticket in Waldur also needs a role on the project. If that person has no email address, the project's roles decide instead.",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="call",
            name="support_ticket_caller_user",
            field=models.ForeignKey(
                blank=True,
                help_text="The person tickets go to when the caller is set to a named contact. Useful for routing a whole call to a shared mailbox. Must hold a role on this call or on the organisation managing it.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
