# Generated by Django 6.0.8 on 2026-09-29 07:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("proposal", "0082_reviewer_pool_invitation_token_default"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="proposal",
            name="project_duration",
        ),
        migrations.RemoveField(
            model_name="review",
            name="comment_project_duration",
        ),
    ]
