# Generated by Django 6.0.8 on 2026-09-29 10:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("proposal", "0084_call_evaluation_start"),
    ]

    operations = [
        migrations.AddField(
            model_name="proposal",
            name="submitted_at",
            field=models.DateTimeField(
                blank=True,
                editable=False,
                help_text="When the proposal left draft. Null for proposals submitted before this field existed: their submission was never recorded and the only proxy, the first workflow step instance, was backfilled by migration for the oldest of them — so it is left empty rather than filled with a date that reads as fact.",
                null=True,
            ),
        ),
    ]
