# -*- coding: utf-8; indent-tabs-mode: nil; tab-width: 2; -*-

---
- name: Start VM instances
  connection: local
  hosts: localhost
  tasks:
    - name: Start VM instances
      waldur_os_add_instance:
        access_token: "{{ access_token }}"
        api_url: "{{ api_url }}"
        data_volume_size: 1
        flavor: m1.little
        floating_ip: auto
        image: CentOS
        name: Waldur
        project: "{{ project_uuid }}"
        provider: "{{ provider_uuid }}"
        security_groups:
          - default
          - ping
          - ssh
          - web
        ssh_key: "{{ public_key_uuid }}"
        subnet: "{{ subnet_uuid }}"
        system_volume_size: 30
        tags: "{{ tags }}"
        wait: true
      register: vm_instance

    - name: Set instance facts
      set_fact:
        public_ip: "{{ vm_instance.instance.external_ips.0 }}"
      when: not ansible_check_mode

    - name: Add instance to dynamic inventory
      add_host:
        ansible_ssh_private_key_file: "{{ private_key_path }}"
        ansible_ssh_user: centos
        groups: created_vm_instances
        hostname: "{{ public_ip }}"
      when: not ansible_check_mode

    - name: Get SSH public key data
      uri:
        headers:
          Authorization: "Token {{ access_token }}"
        url: "{{ api_url }}keys/{{ user_key_uuid }}/"
      register: key_data
      when: not ansible_check_mode

    - name: Set SSH public key fact
      set_fact:
        public_key: "{{ key_data.json.public_key }}"
      when: not ansible_check_mode

    - name: Wait for instance to respond to SSH
      wait_for:
        delay: 10
        host: "{{ public_ip }}"
        port: 22
      when: not ansible_check_mode


- name: Add SSH public key to instance authorized keys
  become: yes
  hosts: created_vm_instances
  tasks:
    - name: Add SSH public key to instance authorized keys
      authorized_key:
        key: "{{ hostvars.localhost.public_key }}"
        state: present
        user: centos


- name: Install and configure ownCloud
  hosts: created_vm_instances
  tasks:
    - name: Enable package repositories
      get_url:
        dest: /etc/yum.repos.d/ce:stable.repo
        mode: 0644
        url: http://download.owncloud.org/download/repositories/stable/CentOS_7/ce:stable.repo

    - name: Add ownCloud package repository keys
      rpm_key:
        key: https://download.owncloud.org/download/repositories/stable/CentOS_7/repodata/repomd.xml.key

    - name: Install packages
      package:
        name: owncloud

    - name: Configure Apache HTTPd
      copy:
        dest: /etc/httpd/conf.d/owncloud.conf
        remote_src: yes
        src: /usr/share/lib/owncloud-files-9.1.6/owncloud-config-apache.conf.default
      notify: httpd_restart

    - name: Enable and start services
      service:
        enabled: yes
        name: httpd
        state: started

  handlers:
    - name: httpd_restart
      service:
        name: httpd
        state: restarted
