# Generated by Django 4.2.23 on 2025-08-28 07:51

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import django_fsm
import model_utils.fields
from django.conf import settings
from django.db import migrations, models

import waldur_core.core.fields
import waldur_core.core.models
import waldur_core.core.validators
import waldur_core.logging.mixins
import waldur_core.structure.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("structure", "0001_squashed_0036"),
    ]

    operations = [
        migrations.CreateModel(
            name="Allocation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=2000, verbose_name="description"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=150,
                        validators=[waldur_core.core.validators.validate_name],
                        verbose_name="name",
                    ),
                ),
                ("uuid", waldur_core.core.fields.UUIDField()),
                ("error_message", models.TextField(blank=True)),
                (
                    "state",
                    django_fsm.FSMIntegerField(
                        choices=[
                            (5, "CREATION_SCHEDULED"),
                            (6, "CREATING"),
                            (1, "UPDATE_SCHEDULED"),
                            (2, "UPDATING"),
                            (7, "DELETION_SCHEDULED"),
                            (8, "DELETING"),
                            (3, "OK"),
                            (4, "ERRED"),
                        ],
                        default=5,
                    ),
                ),
                ("backend_id", models.CharField(blank=True, max_length=255)),
                ("node_limit", models.BigIntegerField(default=0)),
                (
                    "node_usage",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("error_traceback", models.TextField(blank=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="structure.project",
                    ),
                ),
                (
                    "service_settings",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="structure.servicesettings",
                    ),
                ),
                ("groupname", models.TextField(blank=True, max_length=64, null=True)),
                ("is_added", models.BooleanField(default=False)),
            ],
            options={
                "abstract": False,
            },
            bases=(
                waldur_core.core.models.DescendantMixin,
                waldur_core.core.models.BackendModelMixin,
                waldur_core.logging.mixins.LoggableMixin,
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="Association",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uuid", waldur_core.core.fields.UUIDField()),
                ("username", models.CharField(blank=True, max_length=64, null=True)),
                (
                    "allocation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="op-associations-allocation+",
                        to="waldur_openportal.allocation",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="op-associations-user+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "useridentifier",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                ("groupname", models.CharField(blank=True, max_length=64, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="UserInfo",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "shortname",
                    models.CharField(
                        help_text="A short, unique name for you. It will be used to form your local username on any systems. Should only contain lower-case letters and digits and must start with a letter.",
                        max_length=32,
                        null=True,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Must start with a letter and only contain numbers and letters.",
                                regex="^[a-z][a-z0-9]+$",
                            ),
                            django.core.validators.RegexValidator(
                                inverse_match=True, regex="(admin)|(root)$"
                            ),
                            django.core.validators.MinLengthValidator(4),
                            django.core.validators.MaxLengthValidator(32),
                        ],
                        verbose_name="shortname",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="op-userinfo-user+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProjectInfo",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "shortname",
                    models.CharField(
                        help_text="A short, unique name for the project. It will be used to form the local username of any users in the project on any systems. Should only contain lower-case letters and digits and must start with a letter.",
                        max_length=30,
                        null=True,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                regex="^[a-z0-9\\-_]+$"
                            ),
                            django.core.validators.RegexValidator(
                                inverse_match=True, regex="(-admin)|(-root)$"
                            ),
                            django.core.validators.MinLengthValidator(3),
                            django.core.validators.MaxLengthValidator(30),
                        ],
                        verbose_name="shortname",
                    ),
                ),
                (
                    "allowed_destinations",
                    models.TextField(
                        blank=True,
                        help_text="A comma-separated list of allowable destinations of instances that              can be attached to this project. For example, a project may only allow              'brics.aip1.*', meaning that only instances that start with 'brics.aip1.'              can be attached to this project.",
                        max_length=1024,
                        null=True,
                        verbose_name="allowed destinations",
                    ),
                ),
                (
                    "project",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="op-projectinfo-project+",
                        to="structure.project",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AllocationUserUsage",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=64)),
                (
                    "node_usage",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="op-allocationuser-user+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "allocation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="op-allocationuser-allocation+",
                        to="waldur_openportal.allocation",
                    ),
                ),
                (
                    "month",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(12),
                        ]
                    ),
                ),
                ("year", models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="HistoricalAllocation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "node_usage",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                ("year", models.PositiveSmallIntegerField()),
                (
                    "month",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(12),
                        ]
                    ),
                ),
                ("is_complete", models.BooleanField(default=False)),
                (
                    "allocation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="op-historicalallocation+",
                        to="waldur_openportal.allocation",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ProjectNotification",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "frequency",
                    models.PositiveSmallIntegerField(
                        default=14,
                        help_text="How many days between notifications (0 = no notifications).",
                        verbose_name="frequency",
                    ),
                ),
                (
                    "last_notification",
                    models.DateField(
                        blank=True,
                        help_text="When was the last notification sent?",
                        null=True,
                        verbose_name="last notification",
                    ),
                ),
                (
                    "project",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="op-projectnotification-project+",
                        to="structure.project",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProjectShortNameGenerator",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "shortname",
                    models.CharField(
                        help_text="The key / descriptor used to identify this generator.",
                        max_length=30,
                        unique=True,
                        verbose_name="shortname",
                    ),
                ),
                (
                    "count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="The number of projects created with this shortname.",
                        verbose_name="count",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "job_id",
                    models.CharField(
                        db_index=True, max_length=36, unique=True, verbose_name="ID"
                    ),
                ),
                (
                    "job_data",
                    models.TextField(
                        blank=True,
                        help_text="JSON representation of the job",
                        null=True,
                        verbose_name="job data",
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("communicated", "Communicated"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        help_text="The current status of the job.",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "created",
                    models.DateField(
                        auto_now_add=True,
                        default=django.utils.timezone.now,
                        help_text="The date when this job was created.",
                        verbose_name="created",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProjectTemplate",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True, max_length=128, verbose_name="name"
                    ),
                ),
                (
                    "portal",
                    models.CharField(
                        db_index=True, max_length=32, verbose_name="portal"
                    ),
                ),
                (
                    "shortname",
                    models.CharField(
                        blank=True, max_length=30, null=True, verbose_name="shortname"
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        help_text="The organisation that this project class belongs to.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="op-projectclass-organisation+",
                        to="structure.customer",
                        verbose_name="organisation",
                    ),
                ),
                (
                    "offerings",
                    models.ManyToManyField(
                        help_text="The list of MarketPlace Offerings that should be created automatically for projects created in this class by the specified portal.",
                        related_name="op-projectclass-offerings+",
                        to="marketplace.offering",
                        verbose_name="offerings",
                    ),
                ),
                (
                    "approval_limit",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="The credit limit beyond which requests need to be approved by a local admin. If this is None, then no local approval is required. If this is set to 0, then all requests (including creating the project) need to be approved.",
                        max_digits=20,
                        null=True,
                        verbose_name="approval limit",
                    ),
                ),
                (
                    "max_credit_limit",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="The maximum credit limit for any projects created in this class. Any requests beyond this limit are automatically rejected. If this is None, then no maximum limit is set. If this is set to 0, then no projects can be created in this class.",
                        max_digits=20,
                        null=True,
                        verbose_name="maximum credit limit",
                    ),
                ),
                (
                    "role_mapping",
                    models.JSONField(
                        default=dict,
                        help_text="The mapping of role names from the remote portal to role information in this portal for users in projects created in this class.",
                        verbose_name="role mapping",
                    ),
                ),
                ("uuid", waldur_core.core.fields.UUIDField()),
                (
                    "provider",
                    models.ForeignKey(
                        blank=True,
                        help_text="The organisation that owns this project class.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="op-projectclass-provider+",
                        to="structure.customer",
                        verbose_name="provider",
                    ),
                ),
                (
                    "allocation_units_mapping",
                    models.JSONField(
                        default=dict,
                        help_text="The mapping of credits to allocation units, i.e. how many allocation units to award per credit allocated.",
                        verbose_name="allocation units mapping",
                    ),
                ),
            ],
            options={
                "verbose_name": "Project Class",
                "verbose_name_plural": "Project Classes",
                "unique_together": {("name", "portal")},
            },
        ),
        migrations.CreateModel(
            name="OnceTask",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "task_name",
                    models.CharField(
                        db_index=True,
                        max_length=128,
                        unique=True,
                        verbose_name="task name",
                    ),
                ),
                (
                    "last_run",
                    models.DateTimeField(
                        blank=True,
                        help_text="The date when this task was started.",
                        null=True,
                        verbose_name="run date",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RemoteAllocation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=2000, verbose_name="description"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=150,
                        validators=[waldur_core.core.validators.validate_name],
                        verbose_name="name",
                    ),
                ),
                ("uuid", waldur_core.core.fields.UUIDField()),
                ("error_message", models.TextField(blank=True)),
                ("error_traceback", models.TextField(blank=True)),
                (
                    "state",
                    django_fsm.FSMIntegerField(
                        choices=[
                            (5, "CREATION_SCHEDULED"),
                            (6, "CREATING"),
                            (1, "UPDATE_SCHEDULED"),
                            (2, "UPDATING"),
                            (7, "DELETION_SCHEDULED"),
                            (8, "DELETING"),
                            (3, "OK"),
                            (4, "ERRED"),
                        ],
                        default=5,
                    ),
                ),
                ("backend_id", models.CharField(blank=True, max_length=255)),
                (
                    "node_usage",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("node_limit", models.BigIntegerField(default=0)),
                (
                    "remote_project_identifier",
                    models.CharField(
                        blank=True,
                        help_text="The identifier of the project in the remote OpenPortal instance.",
                        max_length=64,
                        null=True,
                        verbose_name="remote project identifier",
                    ),
                ),
                ("is_added", models.BooleanField(default=False)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="structure.project",
                    ),
                ),
                (
                    "service_settings",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="structure.servicesettings",
                    ),
                ),
                (
                    "local_version",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="The local version of the remote project. This is used to track changes to the project.",
                        verbose_name="local version",
                    ),
                ),
                (
                    "remote_version",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="The last successful updated version of the remote project. This is used to track changes to the project.",
                        verbose_name="remote version",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(
                waldur_core.core.models.DescendantMixin,
                waldur_core.core.models.BackendModelMixin,
                waldur_core.structure.models.StructureLoggableMixin,
                models.Model,
                django_fsm.ConcurrentTransitionMixin,
            ),
        ),
        migrations.CreateModel(
            name="RemoteAssociation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uuid", waldur_core.core.fields.UUIDField()),
                (
                    "allocation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="op-remote_associations-remote_allocation+",
                        to="waldur_openportal.remoteallocation",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="op-remote_associations-user+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="HistoricalRemoteAllocation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "node_usage",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                ("year", models.PositiveSmallIntegerField()),
                (
                    "month",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(12),
                        ]
                    ),
                ),
                ("is_complete", models.BooleanField(default=False)),
                (
                    "allocation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="op-remote-historicalallocation+",
                        to="waldur_openportal.remoteallocation",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ManagedProject",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "identifier",
                    models.CharField(
                        db_index=True, max_length=64, unique=True, verbose_name="ID"
                    ),
                ),
                (
                    "details",
                    models.JSONField(
                        blank=True,
                        help_text="JSON representation of the project",
                        null=True,
                        verbose_name="project data",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="op-managedproject-project+",
                        to="structure.project",
                        verbose_name="project",
                    ),
                ),
                (
                    "local_identifier",
                    models.CharField(
                        blank=True,
                        help_text="The local project identifier in this portal.",
                        max_length=64,
                        null=True,
                        verbose_name="local ID",
                    ),
                ),
                (
                    "project_template",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="op-managedproject-projectclass+",
                        to="waldur_openportal.projecttemplate",
                        verbose_name="project class",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("review_comment", models.TextField(blank=True, null=True)),
                (
                    "reviewed_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "state",
                    django_fsm.FSMIntegerField(
                        choices=[
                            (1, "draft"),
                            (2, "pending"),
                            (3, "approved"),
                            (4, "rejected"),
                            (5, "canceled"),
                        ],
                        default=1,
                    ),
                ),
                (
                    "destination",
                    models.CharField(
                        blank=True,
                        help_text="The destination used to send instructions from the remote portal.",
                        max_length=256,
                        null=True,
                        verbose_name="destination",
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="job",
            name="created",
            field=models.DateField(
                auto_now_add=True,
                help_text="The date when this job was created.",
                verbose_name="created",
            ),
        ),
    ]
