# Generated by Django 6.0.8 on 2026-08-28 11:41

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import django_fsm
import model_utils.fields
from django.conf import settings
from django.db import migrations, models

import waldur_core.core.fields
import waldur_core.core.models
import waldur_core.core.validators
import waldur_core.structure.models


class Migration(migrations.Migration):
    replaces = [
        ("waldur_openportal", "0001_squashed_0028_delete_remoteallocationuserusage"),
        ("waldur_openportal", "0029_alter_managedproject_options_and_more"),
        ("waldur_openportal", "0030_alter_projecttemplate_options_and_more"),
        ("waldur_openportal", "0031_alter_projecttemplate_unique_together_and_more"),
        ("waldur_openportal", "0032_alter_managedproject_review_comment_and_more"),
        ("waldur_openportal", "0033_alter_allocation_description_and_more"),
        ("waldur_openportal", "0034_allocation_can_be_managed_and_more"),
        ("waldur_openportal", "0035_add_cached_reports_and_available_mixin"),
        ("waldur_openportal", "0036_remote_projects"),
        ("waldur_openportal", "0037_alter_allocation_options_and_more"),
        ("waldur_openportal", "0038_alter_managedprojectauditentry_options_and_more"),
        ("waldur_openportal", "0039_alter_remoteprojectattachment_options"),
    ]

    dependencies = [
        ("core", "__first__"),
        ("structure", "0001_squashed_0036"),
        ("structure", "0078_alter_servicesettings_certificate"),
    ]

    operations = [
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "job_id",
                    models.CharField(
                        db_index=True, max_length=36, unique=True, verbose_name="ID"
                    ),
                ),
                (
                    "job_data",
                    models.TextField(
                        blank=True,
                        help_text="JSON representation of the job",
                        null=True,
                        verbose_name="job data",
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("communicated", "Communicated"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        help_text="The current status of the job.",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "created",
                    models.DateField(
                        auto_now_add=True,
                        help_text="The date when this job was created.",
                        verbose_name="created",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OnceTask",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "task_name",
                    models.CharField(
                        db_index=True,
                        max_length=128,
                        unique=True,
                        verbose_name="task name",
                    ),
                ),
                (
                    "last_run",
                    models.DateTimeField(
                        blank=True,
                        help_text="The date when this task was started.",
                        null=True,
                        verbose_name="run date",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProjectShortNameGenerator",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "shortname",
                    models.CharField(
                        help_text="The key / descriptor used to identify this generator.",
                        max_length=30,
                        unique=True,
                        verbose_name="shortname",
                    ),
                ),
                (
                    "count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="The number of projects created with this shortname.",
                        verbose_name="count",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Allocation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=4096, verbose_name="description"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=150,
                        validators=[waldur_core.core.validators.validate_name],
                        verbose_name="name",
                    ),
                ),
                ("uuid", waldur_core.core.fields.UUIDField()),
                ("error_message", models.TextField(blank=True)),
                ("error_traceback", models.TextField(blank=True)),
                (
                    "state",
                    django_fsm.FSMIntegerField(
                        choices=[
                            (5, "CREATION_SCHEDULED"),
                            (6, "CREATING"),
                            (1, "UPDATE_SCHEDULED"),
                            (2, "UPDATING"),
                            (7, "DELETION_SCHEDULED"),
                            (8, "DELETING"),
                            (3, "OK"),
                            (4, "ERRED"),
                        ],
                        default=5,
                    ),
                ),
                ("can_be_managed", models.BooleanField(default=True)),
                ("backend_id", models.CharField(blank=True, max_length=255)),
                (
                    "node_usage",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("node_limit", models.BigIntegerField(default=0)),
                ("groupname", models.TextField(blank=True, max_length=64, null=True)),
                ("is_added", models.BooleanField(default=False)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="structure.project",
                    ),
                ),
                (
                    "service_settings",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="structure.servicesettings",
                    ),
                ),
            ],
            options={
                "ordering": ["-created", "id"],
                "abstract": False,
            },
            bases=(
                waldur_core.core.models.DescendantMixin,
                waldur_core.core.models.BackendModelMixin,
                waldur_core.structure.models.StructureLoggableMixin,
                models.Model,
                django_fsm.ConcurrentTransitionMixin,
            ),
        ),
        migrations.CreateModel(
            name="AllocationUserUsage",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "node_usage",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                ("year", models.PositiveSmallIntegerField()),
                (
                    "month",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(12),
                        ]
                    ),
                ),
                ("username", models.CharField(max_length=64)),
                (
                    "allocation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="op-allocationuser-allocation+",
                        to="waldur_openportal.allocation",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="op-allocationuser-user+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Association",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uuid", waldur_core.core.fields.UUIDField()),
                ("username", models.CharField(blank=True, max_length=64, null=True)),
                ("groupname", models.CharField(blank=True, max_length=64, null=True)),
                (
                    "useridentifier",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                (
                    "allocation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="op-associations-allocation+",
                        to="waldur_openportal.allocation",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="op-associations-user+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CachedProjectStorageReport",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.PositiveSmallIntegerField()),
                (
                    "month",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(12),
                        ]
                    ),
                ),
                ("project_identifier", models.CharField(max_length=64)),
                ("resource", models.CharField(max_length=256)),
                ("report", models.JSONField()),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["project_identifier"],
                        name="waldur_open_project_077226_idx",
                    )
                ],
                "unique_together": {
                    ("year", "month", "project_identifier", "resource")
                },
            },
        ),
        migrations.CreateModel(
            name="CachedProjectUsageReport",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.PositiveSmallIntegerField()),
                (
                    "month",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(12),
                        ]
                    ),
                ),
                ("project_identifier", models.CharField(max_length=64)),
                ("resource", models.CharField(max_length=256)),
                ("is_complete", models.BooleanField(default=False)),
                ("report", models.JSONField()),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["project_identifier"],
                        name="waldur_open_project_c1652b_idx",
                    )
                ],
                "unique_together": {
                    ("year", "month", "project_identifier", "resource")
                },
            },
        ),
        migrations.CreateModel(
            name="HistoricalAllocation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "node_usage",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                ("year", models.PositiveSmallIntegerField()),
                (
                    "month",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(12),
                        ]
                    ),
                ),
                ("is_complete", models.BooleanField(default=False)),
                (
                    "allocation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="op-historicalallocation+",
                        to="waldur_openportal.allocation",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ManagedProject",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "state",
                    django_fsm.FSMIntegerField(
                        choices=[
                            (1, "draft"),
                            (2, "pending"),
                            (3, "approved"),
                            (4, "rejected"),
                            (5, "canceled"),
                        ],
                        default=1,
                    ),
                ),
                (
                    "reviewed_at",
                    models.DateTimeField(
                        blank=True,
                        editable=False,
                        help_text="Timestamp when the review was completed",
                        null=True,
                    ),
                ),
                (
                    "review_comment",
                    models.TextField(
                        blank=True,
                        help_text="Optional comment provided during review",
                        null=True,
                    ),
                ),
                (
                    "destination",
                    models.CharField(
                        help_text="The destination used to send instructions from the remote portal.",
                        max_length=256,
                        verbose_name="destination",
                    ),
                ),
                ("identifier", models.CharField(max_length=64, verbose_name="ID")),
                (
                    "details",
                    models.JSONField(
                        blank=True,
                        help_text="JSON representation of the project",
                        null=True,
                        verbose_name="project data",
                    ),
                ),
                (
                    "local_identifier",
                    models.CharField(
                        blank=True,
                        help_text="The local project identifier in this portal.",
                        max_length=64,
                        null=True,
                        verbose_name="local ID",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="op-managedproject-project+",
                        to="structure.project",
                        verbose_name="project",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who performed the review",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Managed Project",
                "verbose_name_plural": "Managed Projects",
            },
        ),
        migrations.CreateModel(
            name="ManagedProjectAuditEntry",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "identifier",
                    models.CharField(
                        help_text="Project identifier copied from ManagedProject at record time.",
                        max_length=64,
                        verbose_name="identifier",
                    ),
                ),
                (
                    "destination",
                    models.CharField(
                        help_text="Destination copied from ManagedProject at record time.",
                        max_length=256,
                        verbose_name="destination",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="timestamp"
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("created", "Project request received"),
                            ("approved", "Project request approved"),
                            ("rejected", "Project request rejected"),
                            ("deleted", "ManagedProject deleted"),
                            ("note_added", "Note added"),
                            ("details_updated", "Award details updated"),
                            ("project_attached", "Waldur project attached"),
                            ("project_detached", "Waldur project detached"),
                        ],
                        db_index=True,
                        max_length=32,
                        verbose_name="event type",
                    ),
                ),
                (
                    "previous_details",
                    models.JSONField(
                        blank=True,
                        help_text="Project details before this event.  Null for creation events.",
                        null=True,
                        verbose_name="previous details",
                    ),
                ),
                (
                    "new_details",
                    models.JSONField(
                        blank=True,
                        help_text="Project details after this event.  Null for events that do not change the details.",
                        null=True,
                        verbose_name="new details",
                    ),
                ),
                (
                    "note",
                    models.TextField(
                        blank=True,
                        help_text="Optional free-text comment about this event.",
                        verbose_name="note",
                    ),
                ),
                (
                    "managed_project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_log",
                        to="waldur_openportal.managedproject",
                        verbose_name="managed project",
                    ),
                ),
                (
                    "performed_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="The user who triggered this event, if it was a human action.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="performed by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Managed Project Audit Entry",
                "verbose_name_plural": "Managed Project Audit Entries",
                "ordering": ["-timestamp", "id"],
            },
        ),
        migrations.CreateModel(
            name="ProjectInfo",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "shortname",
                    models.CharField(
                        help_text="A short, unique name for the project. It will be used to form the local username of any users in the project on any systems. Should only contain lower-case letters and digits and must start with a letter.",
                        max_length=30,
                        null=True,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                regex="^[a-z0-9\\-_]+$"
                            ),
                            django.core.validators.RegexValidator(
                                inverse_match=True, regex="(-admin)|(-root)$"
                            ),
                            django.core.validators.MinLengthValidator(3),
                            django.core.validators.MaxLengthValidator(30),
                        ],
                        verbose_name="shortname",
                    ),
                ),
                (
                    "allowed_destinations",
                    models.TextField(
                        blank=True,
                        help_text="A comma-separated list of allowable destinations of instances that              can be attached to this project. For example, a project may only allow              'brics.aip1.*', meaning that only instances that start with 'brics.aip1.'              can be attached to this project.",
                        max_length=1024,
                        null=True,
                        verbose_name="allowed destinations",
                    ),
                ),
                (
                    "project",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="op-projectinfo-project+",
                        to="structure.project",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProjectNotification",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "frequency",
                    models.PositiveSmallIntegerField(
                        default=14,
                        help_text="How many days between notifications (0 = no notifications).",
                        verbose_name="frequency",
                    ),
                ),
                (
                    "last_notification",
                    models.DateField(
                        blank=True,
                        help_text="When was the last notification sent?",
                        null=True,
                        verbose_name="last notification",
                    ),
                ),
                (
                    "project",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="op-projectnotification-project+",
                        to="structure.project",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProjectTemplate",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uuid", waldur_core.core.fields.UUIDField()),
                ("name", models.CharField(max_length=128, verbose_name="name")),
                (
                    "offering",
                    models.CharField(
                        blank=True,
                        help_text="The offering for which this template applies.",
                        max_length=256,
                        null=True,
                        verbose_name="offering",
                    ),
                ),
                ("portal", models.CharField(max_length=32, verbose_name="portal")),
                (
                    "key",
                    models.CharField(
                        blank=True,
                        help_text="The key that is used to authenticate requests for this class.",
                        max_length=256,
                        null=True,
                        verbose_name="key",
                    ),
                ),
                (
                    "shortname",
                    models.CharField(
                        blank=True, max_length=30, null=True, verbose_name="shortname"
                    ),
                ),
                (
                    "approval_limit",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="The credit limit beyond which requests need to be approved by a local admin. If this is None, then no local approval is required. If this is set to 0, then all requests (including creating the project) need to be approved.",
                        max_digits=20,
                        null=True,
                        verbose_name="approval limit",
                    ),
                ),
                (
                    "max_credit_limit",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="The maximum credit limit for any projects created in this class. Any requests beyond this limit are automatically rejected. If this is None, then no maximum limit is set. If this is set to 0, then no projects can be created in this class.",
                        max_digits=20,
                        null=True,
                        verbose_name="maximum credit limit",
                    ),
                ),
                (
                    "role_mapping",
                    models.JSONField(
                        default=dict,
                        help_text="The mapping of role names from the remote portal to role information in this portal for users in projects created in this class.",
                        verbose_name="role mapping",
                    ),
                ),
                (
                    "allocation_units_mapping",
                    models.JSONField(
                        default=dict,
                        help_text="The mapping of credits to allocation units, i.e. how many allocation units to award per credit allocated.",
                        verbose_name="allocation units mapping",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        help_text="The organisation that this project class belongs to.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="op-projectclass-organisation+",
                        to="structure.customer",
                        verbose_name="organisation",
                    ),
                ),
                (
                    "offerings",
                    models.ManyToManyField(
                        help_text="The list of MarketPlace Offerings that should be created automatically for projects created in this class by the specified portal.",
                        related_name="op-projectclass-offerings+",
                        to="marketplace.offering",
                        verbose_name="offerings",
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        blank=True,
                        help_text="The organisation that owns this project class.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="op-projectclass-provider+",
                        to="structure.customer",
                        verbose_name="provider",
                    ),
                ),
            ],
            options={
                "verbose_name": "Project class",
                "verbose_name_plural": "Project classes",
                "ordering": ["name", "id"],
                "unique_together": {("name", "offering", "portal")},
            },
        ),
        migrations.AddField(
            model_name="managedproject",
            name="project_template",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="op-managedproject-projectclass+",
                to="waldur_openportal.projecttemplate",
                verbose_name="project class",
            ),
        ),
        migrations.CreateModel(
            name="RemoteAllocation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=4096, verbose_name="description"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=150,
                        validators=[waldur_core.core.validators.validate_name],
                        verbose_name="name",
                    ),
                ),
                ("uuid", waldur_core.core.fields.UUIDField()),
                ("error_message", models.TextField(blank=True)),
                ("error_traceback", models.TextField(blank=True)),
                (
                    "state",
                    django_fsm.FSMIntegerField(
                        choices=[
                            (5, "CREATION_SCHEDULED"),
                            (6, "CREATING"),
                            (1, "UPDATE_SCHEDULED"),
                            (2, "UPDATING"),
                            (7, "DELETION_SCHEDULED"),
                            (8, "DELETING"),
                            (3, "OK"),
                            (4, "ERRED"),
                        ],
                        default=5,
                    ),
                ),
                ("can_be_managed", models.BooleanField(default=True)),
                ("backend_id", models.CharField(blank=True, max_length=255)),
                (
                    "node_usage",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("node_limit", models.BigIntegerField(default=0)),
                (
                    "remote_project_identifier",
                    models.CharField(
                        blank=True,
                        help_text="The identifier of the project in the remote OpenPortal instance.",
                        max_length=64,
                        null=True,
                        verbose_name="remote project identifier",
                    ),
                ),
                ("is_added", models.BooleanField(default=False)),
                (
                    "local_version",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="The local version of the remote project. This is used to track changes to the project.",
                        verbose_name="local version",
                    ),
                ),
                (
                    "remote_version",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="The last successful updated version of the remote project. This is used to track changes to the project.",
                        verbose_name="remote version",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="structure.project",
                    ),
                ),
                (
                    "service_settings",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="structure.servicesettings",
                    ),
                ),
            ],
            options={
                "ordering": ["-created", "id"],
                "abstract": False,
            },
            bases=(
                waldur_core.core.models.DescendantMixin,
                waldur_core.core.models.BackendModelMixin,
                waldur_core.structure.models.StructureLoggableMixin,
                models.Model,
                django_fsm.ConcurrentTransitionMixin,
            ),
        ),
        migrations.CreateModel(
            name="HistoricalRemoteAllocation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "node_usage",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                ("year", models.PositiveSmallIntegerField()),
                (
                    "month",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(12),
                        ]
                    ),
                ),
                ("is_complete", models.BooleanField(default=False)),
                (
                    "allocation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="op-remote-historicalallocation+",
                        to="waldur_openportal.remoteallocation",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="RemoteAssociation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uuid", waldur_core.core.fields.UUIDField()),
                (
                    "allocation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="op-remote_associations-remote_allocation+",
                        to="waldur_openportal.remoteallocation",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="op-remote_associations-user+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="RemoteProject",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uuid", waldur_core.core.fields.UUIDField()),
                (
                    "destination",
                    models.CharField(
                        help_text="Routing path from the local portal to the remote resource, e.g. 'airr.brics.isambard-ai'.  Never changes after creation.",
                        max_length=256,
                        verbose_name="destination",
                    ),
                ),
                (
                    "identifier",
                    models.CharField(
                        blank=True,
                        help_text="Stable remote project identifier, e.g. 'u6ac.brics'.  Uniquely identifies the project on the remote portal and never changes.  Null while the project is pending first approval.",
                        max_length=64,
                        null=True,
                        verbose_name="identifier",
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("active", "Active"),
                            ("stale", "Stale"),
                            ("error", "Error"),
                            ("deleted", "Deleted"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=16,
                        verbose_name="state",
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="The most recent rejection or error message received from the remote portal.  Cleared when the state transitions to ACTIVE.",
                        verbose_name="error message",
                    ),
                ),
                (
                    "last_sent_details",
                    models.JSONField(
                        blank=True,
                        help_text="The AwardDetails most recently sent to the remote portal (create_award or update_award).  May not yet be confirmed.",
                        null=True,
                        verbose_name="last sent award details",
                    ),
                ),
                (
                    "last_confirmed_details",
                    models.JSONField(
                        blank=True,
                        help_text="The AwardDetails most recently confirmed by the remote portal.  Reflects what is actually live on the remote portal.",
                        null=True,
                        verbose_name="last confirmed award details",
                    ),
                ),
                (
                    "pending_details",
                    models.JSONField(
                        blank=True,
                        help_text="AwardDetails that have been submitted to the remote portal but are awaiting human review or confirmation (e.g. an allocation increase that requires manual approval).  Null when nothing is pending.",
                        null=True,
                        verbose_name="pending award details",
                    ),
                ),
                (
                    "pending_since",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the currently pending change was submitted.",
                        null=True,
                        verbose_name="pending since",
                    ),
                ),
                (
                    "current_allocation",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Latest confirmed allocation (credits) for this project.  Updated whenever a RemoteProjectAllocationEntry is confirmed.",
                        max_digits=20,
                        verbose_name="current allocation",
                    ),
                ),
                (
                    "pending_allocation",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Allocation value currently under review on the remote portal.  Null when no allocation change is pending.",
                        max_digits=20,
                        null=True,
                        verbose_name="pending allocation",
                    ),
                ),
                (
                    "last_contact_time",
                    models.DateTimeField(
                        blank=True,
                        help_text="The most recent time the remote portal acknowledged anything about this project (confirmation, usage report, get_award response, etc.).  Used to detect connectivity issues and to trigger a transition to the STALE state.",
                        null=True,
                        verbose_name="last contact time",
                    ),
                ),
                (
                    "notes",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Append-only list of timestamped notes {timestamp, author, text}. Kept in sync with the full merged set from award_details() — includes both locally-authored notes and any notes added by the remote portal.",
                        verbose_name="notes",
                    ),
                ),
                (
                    "earliest_approve",
                    models.DateTimeField(
                        blank=True,
                        help_text="Earliest UTC time the remote portal may approve this award. Gives the sender a window to make corrections before provisioning begins.",
                        null=True,
                        verbose_name="earliest approve",
                    ),
                ),
                (
                    "membership_control",
                    models.CharField(
                        blank=True,
                        choices=[
                            (
                                "open",
                                "Open — receiving portal manages membership freely",
                            ),
                            ("members_only", "Members only — roles are authoritative"),
                            ("roles_only", "Roles only — membership is authoritative"),
                            (
                                "locked",
                                "Locked — both membership and roles are authoritative",
                            ),
                        ],
                        help_text="Policy controlling whether the remote portal may independently modify project membership or roles.",
                        max_length=16,
                        null=True,
                        verbose_name="membership control",
                    ),
                ),
                (
                    "allowed_domains",
                    models.JSONField(
                        blank=True,
                        default=None,
                        help_text="List of email domain glob patterns allowed to join the project on the remote portal, e.g. ['*.ac.uk']. None means all domains are allowed.",
                        null=True,
                        verbose_name="allowed domains",
                    ),
                ),
                (
                    "breakdown",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Free-form allocation breakdown sent to the remote portal, e.g. {'gpu_hours': '500 GPUHR', 'storage': '5 TB'}.",
                        verbose_name="allocation breakdown",
                    ),
                ),
                (
                    "link_award",
                    models.JSONField(
                        blank=True,
                        help_text="Link to the award record on the funder's system.",
                        null=True,
                        verbose_name="award link",
                    ),
                ),
                (
                    "link_call",
                    models.JSONField(
                        blank=True,
                        help_text="Link to the funding call this award came from.",
                        null=True,
                        verbose_name="call link",
                    ),
                ),
                (
                    "link_project",
                    models.JSONField(
                        blank=True,
                        help_text="Link to the project page on the awarding portal.",
                        null=True,
                        verbose_name="project page link",
                    ),
                ),
                (
                    "link_renewal",
                    models.JSONField(
                        blank=True,
                        help_text="Link to where renewal or more time can be requested.",
                        null=True,
                        verbose_name="renewal link",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                (
                    "current_project",
                    models.ForeignKey(
                        blank=True,
                        help_text="The local Waldur project currently holding this award.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="current_remote_projects",
                        to="structure.project",
                        verbose_name="current project",
                    ),
                ),
                (
                    "remote_allocation",
                    models.OneToOneField(
                        blank=True,
                        help_text="The current RemoteAllocation that drives this project.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="remote_project",
                        to="waldur_openportal.remoteallocation",
                        verbose_name="remote allocation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Remote Project",
                "verbose_name_plural": "Remote Projects",
            },
        ),
        migrations.CreateModel(
            name="RemoteProjectAttachment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "attached_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="attached at"),
                ),
                (
                    "detached_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Null while this is the current attachment.",
                        null=True,
                        verbose_name="detached at",
                    ),
                ),
                (
                    "note",
                    models.TextField(
                        blank=True,
                        help_text="Optional comment recorded when the award was attached or moved.",
                        verbose_name="note",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="remote_project_attachments",
                        to="structure.project",
                        verbose_name="project",
                    ),
                ),
                (
                    "remote_project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="waldur_openportal.remoteproject",
                        verbose_name="remote project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Remote Project Attachment",
                "verbose_name_plural": "Remote Project Attachments",
                "ordering": ["-attached_at", "id"],
            },
        ),
        migrations.CreateModel(
            name="RemoteProjectAllocationEntry",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "allocation",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="New total allocation (credits) after this change.",
                        max_digits=20,
                        verbose_name="allocation",
                    ),
                ),
                (
                    "previous_allocation",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Total allocation before this change.  Null for the first entry.",
                        max_digits=20,
                        null=True,
                        verbose_name="previous allocation",
                    ),
                ),
                (
                    "submitted_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="submitted at"
                    ),
                ),
                (
                    "confirmed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the remote portal confirmed this allocation.  Null if pending.",
                        null=True,
                        verbose_name="confirmed at",
                    ),
                ),
                (
                    "note",
                    models.TextField(
                        blank=True,
                        help_text="Optional comment, e.g. 'carrying over 20 unused credits from previous award'.",
                        verbose_name="note",
                    ),
                ),
                (
                    "remote_project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="allocation_history",
                        to="waldur_openportal.remoteproject",
                        verbose_name="remote project",
                    ),
                ),
                (
                    "source_project",
                    models.ForeignKey(
                        blank=True,
                        help_text="The local project/award that triggered this allocation change.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="remote_allocation_entries",
                        to="structure.project",
                        verbose_name="source project",
                    ),
                ),
                (
                    "attachment",
                    models.ForeignKey(
                        blank=True,
                        help_text="The award attachment period during which this change was made.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="allocation_entries",
                        to="waldur_openportal.remoteprojectattachment",
                        verbose_name="attachment",
                    ),
                ),
            ],
            options={
                "verbose_name": "Remote Project Allocation Entry",
                "verbose_name_plural": "Remote Project Allocation Entries",
                "ordering": ["-submitted_at", "id"],
            },
        ),
        migrations.CreateModel(
            name="RemoteProjectAuditEntry",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="timestamp"
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            (
                                "award_attempted",
                                "Award creation attempted but not yet confirmed (pending approval or error)",
                            ),
                            (
                                "award_rejected",
                                "Award creation explicitly rejected by remote portal",
                            ),
                            ("award_created", "Award created (create_award sent)"),
                            ("award_updated", "Award updated (update_award sent)"),
                            (
                                "award_update_confirmed",
                                "Award update confirmed by remote portal",
                            ),
                            (
                                "award_update_rejected",
                                "Award update rejected by remote portal",
                            ),
                            ("state_changed", "State changed"),
                            ("resource_deleted", "Local resource deleted"),
                        ],
                        db_index=True,
                        max_length=32,
                        verbose_name="event type",
                    ),
                ),
                (
                    "previous_details",
                    models.JSONField(
                        blank=True,
                        help_text="AwardDetails before this event.  Null for creation events.",
                        null=True,
                        verbose_name="previous award details",
                    ),
                ),
                (
                    "new_details",
                    models.JSONField(
                        blank=True,
                        help_text="AwardDetails after this event, or the details being requested.  Null for events that do not change the details.",
                        null=True,
                        verbose_name="new award details",
                    ),
                ),
                (
                    "remote_response",
                    models.JSONField(
                        blank=True,
                        help_text="Raw response received from the remote portal, if applicable.",
                        null=True,
                        verbose_name="remote response",
                    ),
                ),
                (
                    "note",
                    models.TextField(
                        blank=True,
                        help_text="Optional free-text comment about this event.",
                        verbose_name="note",
                    ),
                ),
                (
                    "allocation_entry",
                    models.ForeignKey(
                        blank=True,
                        help_text="The allocation ledger entry associated with this event, if applicable.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_entries",
                        to="waldur_openportal.remoteprojectallocationentry",
                        verbose_name="allocation entry",
                    ),
                ),
                (
                    "performed_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="The user who triggered this event, if it was a human action.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="performed by",
                    ),
                ),
                (
                    "remote_project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_log",
                        to="waldur_openportal.remoteproject",
                        verbose_name="remote project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Remote Project Audit Entry",
                "verbose_name_plural": "Remote Project Audit Entries",
                "ordering": ["-timestamp", "id"],
            },
        ),
        migrations.CreateModel(
            name="UserInfo",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "shortname",
                    models.CharField(
                        help_text="A short, unique name for you. It will be used to form your local username on any systems. Should only contain lower-case letters and digits and must start with a letter.",
                        max_length=32,
                        null=True,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Must start with a letter and only contain numbers and letters.",
                                regex="^[a-z][a-z0-9]+$",
                            ),
                            django.core.validators.RegexValidator(
                                inverse_match=True, regex="(admin)|(root)$"
                            ),
                            django.core.validators.MinLengthValidator(4),
                            django.core.validators.MaxLengthValidator(32),
                        ],
                        verbose_name="shortname",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="op-userinfo-user+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AlterUniqueTogether(
            name="managedproject",
            unique_together={("destination", "identifier")},
        ),
        migrations.AddConstraint(
            model_name="remoteproject",
            constraint=models.UniqueConstraint(
                condition=models.Q(("identifier__isnull", False)),
                fields=("destination", "identifier"),
                name="unique_remote_project_destination_identifier",
            ),
        ),
        migrations.AddConstraint(
            model_name="remoteproject",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("current_project__isnull", False), ("identifier__isnull", True)
                ),
                fields=("destination", "current_project"),
                name="unique_pending_remote_project_destination_project",
            ),
        ),
    ]
