# Generated by Django 4.2.24 on 2025-09-24 08:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("waldur_openportal", "0001_squashed_0028_delete_remoteallocationuserusage"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="managedproject",
            options={
                "verbose_name": "Managed Project",
                "verbose_name_plural": "Managed Projects",
            },
        ),
        migrations.AlterField(
            model_name="managedproject",
            name="destination",
            field=models.CharField(
                help_text="The destination used to send instructions from the remote portal.",
                max_length=256,
                verbose_name="destination",
            ),
        ),
        migrations.AlterField(
            model_name="managedproject",
            name="identifier",
            field=models.CharField(max_length=64, verbose_name="ID"),
        ),
        migrations.AlterUniqueTogether(
            name="managedproject",
            unique_together={("destination", "identifier")},
        ),
    ]
