# Generated by Django 4.2.24 on 2025-12-07 19:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("waldur_openportal", "0033_alter_allocation_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="allocation",
            name="can_be_managed",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="remoteallocation",
            name="can_be_managed",
            field=models.BooleanField(default=True),
        ),
    ]
