# Generated by Django 6.0.3 on 2026-04-06 08:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("waldur_openportal", "0034_allocation_can_be_managed_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CachedProjectStorageReport",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.PositiveSmallIntegerField()),
                (
                    "month",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(12),
                        ]
                    ),
                ),
                ("project_identifier", models.CharField(max_length=64)),
                ("resource", models.CharField(max_length=256)),
                ("report", models.JSONField()),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["project_identifier"],
                        name="waldur_open_project_077226_idx",
                    )
                ],
                "unique_together": {
                    ("year", "month", "project_identifier", "resource")
                },
            },
        ),
        migrations.CreateModel(
            name="CachedProjectUsageReport",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.PositiveSmallIntegerField()),
                (
                    "month",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(12),
                        ]
                    ),
                ),
                ("project_identifier", models.CharField(max_length=64)),
                ("resource", models.CharField(max_length=256)),
                ("is_complete", models.BooleanField(default=False)),
                ("report", models.JSONField()),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["project_identifier"],
                        name="waldur_open_project_c1652b_idx",
                    )
                ],
                "unique_together": {
                    ("year", "month", "project_identifier", "resource")
                },
            },
        ),
    ]
