# Generated by Django 6.0.7 on 2026-08-05 15:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import waldur_core.core.fields


class Migration(migrations.Migration):
    dependencies = [
        ("structure", "0078_alter_servicesettings_certificate"),
        ("waldur_openportal", "0035_add_cached_reports_and_available_mixin"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RemoteProject",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uuid", waldur_core.core.fields.UUIDField()),
                (
                    "destination",
                    models.CharField(
                        help_text="Routing path from the local portal to the remote resource, e.g. 'airr.brics.isambard-ai'.  Never changes after creation.",
                        max_length=256,
                        verbose_name="destination",
                    ),
                ),
                (
                    "identifier",
                    models.CharField(
                        blank=True,
                        help_text="Stable remote project identifier, e.g. 'u6ac.brics'.  Uniquely identifies the project on the remote portal and never changes.  Null while the project is pending first approval.",
                        max_length=64,
                        null=True,
                        verbose_name="identifier",
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("active", "Active"),
                            ("stale", "Stale"),
                            ("error", "Error"),
                            ("deleted", "Deleted"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=16,
                        verbose_name="state",
                    ),
                ),
                (
                    "last_sent_details",
                    models.JSONField(
                        blank=True,
                        help_text="The AwardDetails most recently sent to the remote portal (create_award or update_award).  May not yet be confirmed.",
                        null=True,
                        verbose_name="last sent award details",
                    ),
                ),
                (
                    "last_confirmed_details",
                    models.JSONField(
                        blank=True,
                        help_text="The AwardDetails most recently confirmed by the remote portal.  Reflects what is actually live on the remote portal.",
                        null=True,
                        verbose_name="last confirmed award details",
                    ),
                ),
                (
                    "pending_details",
                    models.JSONField(
                        blank=True,
                        help_text="AwardDetails that have been submitted to the remote portal but are awaiting human review or confirmation (e.g. an allocation increase that requires manual approval).  Null when nothing is pending.",
                        null=True,
                        verbose_name="pending award details",
                    ),
                ),
                (
                    "pending_since",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the currently pending change was submitted.",
                        null=True,
                        verbose_name="pending since",
                    ),
                ),
                (
                    "current_allocation",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Latest confirmed allocation (credits) for this project.  Updated whenever a RemoteProjectAllocationEntry is confirmed.",
                        max_digits=20,
                        verbose_name="current allocation",
                    ),
                ),
                (
                    "pending_allocation",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Allocation value currently under review on the remote portal.  Null when no allocation change is pending.",
                        max_digits=20,
                        null=True,
                        verbose_name="pending allocation",
                    ),
                ),
                (
                    "last_contact_time",
                    models.DateTimeField(
                        blank=True,
                        help_text="The most recent time the remote portal acknowledged anything about this project (confirmation, usage report, get_award response, etc.).  Used to detect connectivity issues and to trigger a transition to the STALE state.",
                        null=True,
                        verbose_name="last contact time",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                (
                    "current_project",
                    models.ForeignKey(
                        blank=True,
                        help_text="The local Waldur project currently holding this award.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="current_remote_projects",
                        to="structure.project",
                        verbose_name="current project",
                    ),
                ),
                (
                    "remote_allocation",
                    models.OneToOneField(
                        blank=True,
                        help_text="The current RemoteAllocation that drives this project.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="remote_project",
                        to="waldur_openportal.remoteallocation",
                        verbose_name="remote allocation",
                    ),
                ),
                (
                    "allowed_domains",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of email domain glob patterns allowed to join the project on the remote portal, e.g. ['*.ac.uk'].",
                        verbose_name="allowed domains",
                    ),
                ),
                (
                    "breakdown",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Free-form allocation breakdown sent to the remote portal, e.g. {'gpu_hours': '500 GPUHR', 'storage': '5 TB'}.",
                        verbose_name="allocation breakdown",
                    ),
                ),
                (
                    "earliest_approve",
                    models.DateTimeField(
                        blank=True,
                        help_text="Earliest UTC time the remote portal may approve this award. Gives the sender a window to make corrections before provisioning begins.",
                        null=True,
                        verbose_name="earliest approve",
                    ),
                ),
                (
                    "link_award",
                    models.JSONField(
                        blank=True,
                        help_text="Link to the award record on the funder's system.",
                        null=True,
                        verbose_name="award link",
                    ),
                ),
                (
                    "link_call",
                    models.JSONField(
                        blank=True,
                        help_text="Link to the funding call this award came from.",
                        null=True,
                        verbose_name="call link",
                    ),
                ),
                (
                    "link_project",
                    models.JSONField(
                        blank=True,
                        help_text="Link to the project page on the awarding portal.",
                        null=True,
                        verbose_name="project page link",
                    ),
                ),
                (
                    "link_renewal",
                    models.JSONField(
                        blank=True,
                        help_text="Link to where renewal or more time can be requested.",
                        null=True,
                        verbose_name="renewal link",
                    ),
                ),
                (
                    "membership_control",
                    models.CharField(
                        blank=True,
                        choices=[
                            (
                                "open",
                                "Open — receiving portal manages membership freely",
                            ),
                            ("members_only", "Members only — roles are authoritative"),
                            ("roles_only", "Roles only — membership is authoritative"),
                            (
                                "locked",
                                "Locked — both membership and roles are authoritative",
                            ),
                        ],
                        help_text="Policy controlling whether the remote portal may independently modify project membership or roles.",
                        max_length=16,
                        null=True,
                        verbose_name="membership control",
                    ),
                ),
                (
                    "notes",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Append-only list of timestamped notes {timestamp, author, text} communicated to the remote portal.",
                        verbose_name="notes",
                    ),
                ),
            ],
            options={
                "verbose_name": "Remote Project",
                "verbose_name_plural": "Remote Projects",
                "unique_together": set(),
            },
        ),
        migrations.CreateModel(
            name="RemoteProjectAllocationEntry",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "allocation",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="New total allocation (credits) after this change.",
                        max_digits=20,
                        verbose_name="allocation",
                    ),
                ),
                (
                    "previous_allocation",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Total allocation before this change.  Null for the first entry.",
                        max_digits=20,
                        null=True,
                        verbose_name="previous allocation",
                    ),
                ),
                (
                    "submitted_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="submitted at"
                    ),
                ),
                (
                    "confirmed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the remote portal confirmed this allocation.  Null if pending.",
                        null=True,
                        verbose_name="confirmed at",
                    ),
                ),
                (
                    "note",
                    models.TextField(
                        blank=True,
                        help_text="Optional comment, e.g. 'carrying over 20 unused credits from previous award'.",
                        verbose_name="note",
                    ),
                ),
            ],
            options={
                "verbose_name": "Remote Project Allocation Entry",
                "verbose_name_plural": "Remote Project Allocation Entries",
                "ordering": ["-submitted_at"],
            },
        ),
        migrations.CreateModel(
            name="RemoteProjectAuditEntry",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="timestamp"
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("award_created", "Award created (create_award sent)"),
                            (
                                "award_confirmed",
                                "Award creation confirmed by remote portal",
                            ),
                            ("award_updated", "Award updated (update_award sent)"),
                            (
                                "award_update_confirmed",
                                "Award update confirmed by remote portal",
                            ),
                            (
                                "award_update_rejected",
                                "Award update rejected by remote portal",
                            ),
                            (
                                "award_fetched",
                                "Award details fetched from remote portal (get_award)",
                            ),
                            ("allocation_changed", "Allocation changed"),
                            ("allocation_confirmed", "Allocation change confirmed"),
                            ("allocation_rejected", "Allocation change rejected"),
                            (
                                "project_attached",
                                "Remote project attached to a local project",
                            ),
                            (
                                "project_detached",
                                "Remote project detached from a local project",
                            ),
                            ("state_changed", "State changed"),
                            ("resource_deleted", "Local resource deleted"),
                            (
                                "resource_restored",
                                "Local resource restored / reconnected",
                            ),
                        ],
                        db_index=True,
                        max_length=32,
                        verbose_name="event type",
                    ),
                ),
                (
                    "previous_details",
                    models.JSONField(
                        blank=True,
                        help_text="AwardDetails before this event.  Null for creation events.",
                        null=True,
                        verbose_name="previous award details",
                    ),
                ),
                (
                    "new_details",
                    models.JSONField(
                        blank=True,
                        help_text="AwardDetails after this event, or the details being requested.  Null for events that do not change the details.",
                        null=True,
                        verbose_name="new award details",
                    ),
                ),
                (
                    "remote_response",
                    models.JSONField(
                        blank=True,
                        help_text="Raw response received from the remote portal, if applicable.",
                        null=True,
                        verbose_name="remote response",
                    ),
                ),
                (
                    "note",
                    models.TextField(
                        blank=True,
                        help_text="Optional free-text comment about this event.",
                        verbose_name="note",
                    ),
                ),
                (
                    "allocation_entry",
                    models.ForeignKey(
                        blank=True,
                        help_text="The allocation ledger entry associated with this event, if applicable.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_entries",
                        to="waldur_openportal.remoteprojectallocationentry",
                        verbose_name="allocation entry",
                    ),
                ),
                (
                    "performed_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="The user who triggered this event, if it was a human action.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="performed by",
                    ),
                ),
                (
                    "remote_project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_log",
                        to="waldur_openportal.remoteproject",
                        verbose_name="remote project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Remote Project Audit Entry",
                "verbose_name_plural": "Remote Project Audit Entries",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="RemoteProjectAttachment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "attached_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="attached at"),
                ),
                (
                    "detached_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Null while this is the current attachment.",
                        null=True,
                        verbose_name="detached at",
                    ),
                ),
                (
                    "note",
                    models.TextField(
                        blank=True,
                        help_text="Optional comment recorded when the award was attached or moved.",
                        verbose_name="note",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="remote_project_attachments",
                        to="structure.project",
                        verbose_name="project",
                    ),
                ),
                (
                    "remote_project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="waldur_openportal.remoteproject",
                        verbose_name="remote project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Remote Project Attachment",
                "verbose_name_plural": "Remote Project Attachments",
                "ordering": ["-attached_at"],
            },
        ),
        migrations.AddField(
            model_name="remoteprojectallocationentry",
            name="attachment",
            field=models.ForeignKey(
                blank=True,
                help_text="The award attachment period during which this change was made.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="allocation_entries",
                to="waldur_openportal.remoteprojectattachment",
                verbose_name="attachment",
            ),
        ),
        migrations.AddField(
            model_name="remoteprojectallocationentry",
            name="remote_project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="allocation_history",
                to="waldur_openportal.remoteproject",
                verbose_name="remote project",
            ),
        ),
        migrations.AddField(
            model_name="remoteprojectallocationentry",
            name="source_project",
            field=models.ForeignKey(
                blank=True,
                help_text="The local project/award that triggered this allocation change.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="remote_allocation_entries",
                to="structure.project",
                verbose_name="source project",
            ),
        ),
        migrations.AddConstraint(
            model_name="remoteproject",
            constraint=models.UniqueConstraint(
                condition=models.Q(("identifier__isnull", False)),
                fields=("destination", "identifier"),
                name="unique_remote_project_destination_identifier",
            ),
        ),
        migrations.AddConstraint(
            model_name="remoteproject",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("current_project__isnull", False), ("identifier__isnull", True)
                ),
                fields=("destination", "current_project"),
                name="unique_pending_remote_project_destination_project",
            ),
        ),
        migrations.CreateModel(
            name="ManagedProjectAuditEntry",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "identifier",
                    models.CharField(
                        help_text="Project identifier copied from ManagedProject at record time.",
                        max_length=64,
                        verbose_name="identifier",
                    ),
                ),
                (
                    "destination",
                    models.CharField(
                        help_text="Destination copied from ManagedProject at record time.",
                        max_length=256,
                        verbose_name="destination",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="timestamp"
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("created", "Project request received"),
                            ("approved", "Project request approved"),
                            ("rejected", "Project request rejected"),
                            ("deleted", "ManagedProject deleted"),
                            ("note_added", "Note added"),
                            ("details_updated", "Award details updated"),
                            ("project_attached", "Waldur project attached"),
                            ("project_detached", "Waldur project detached"),
                        ],
                        db_index=True,
                        max_length=32,
                        verbose_name="event type",
                    ),
                ),
                (
                    "previous_details",
                    models.JSONField(
                        blank=True,
                        help_text="Project details before this event.  Null for creation events.",
                        null=True,
                        verbose_name="previous details",
                    ),
                ),
                (
                    "new_details",
                    models.JSONField(
                        blank=True,
                        help_text="Project details after this event.  Null for events that do not change the details.",
                        null=True,
                        verbose_name="new details",
                    ),
                ),
                (
                    "note",
                    models.TextField(
                        blank=True,
                        help_text="Optional free-text comment about this event.",
                        verbose_name="note",
                    ),
                ),
                (
                    "managed_project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_log",
                        to="waldur_openportal.managedproject",
                        verbose_name="managed project",
                    ),
                ),
                (
                    "performed_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="The user who triggered this event, if it was a human action.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="performed by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Managed Project Audit Entry",
                "verbose_name_plural": "Managed Project Audit Entries",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.AddField(
            model_name="remoteproject",
            name="error_message",
            field=models.TextField(
                blank=True,
                default="",
                help_text="The most recent rejection or error message received from the remote portal.  Cleared when the state transitions to ACTIVE.",
                verbose_name="error message",
            ),
        ),
        migrations.AlterField(
            model_name="remoteprojectauditentry",
            name="event_type",
            field=models.CharField(
                choices=[
                    (
                        "award_attempted",
                        "Award creation attempted but not yet confirmed (pending approval or error)",
                    ),
                    (
                        "award_rejected",
                        "Award creation explicitly rejected by remote portal",
                    ),
                    ("award_created", "Award created (create_award sent)"),
                    ("award_updated", "Award updated (update_award sent)"),
                    (
                        "award_update_confirmed",
                        "Award update confirmed by remote portal",
                    ),
                    ("award_update_rejected", "Award update rejected by remote portal"),
                    ("state_changed", "State changed"),
                    ("resource_deleted", "Local resource deleted"),
                ],
                db_index=True,
                max_length=32,
                verbose_name="event type",
            ),
        ),
        migrations.AlterField(
            model_name="remoteproject",
            name="notes",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Append-only list of timestamped notes {timestamp, author, text}. Kept in sync with the full merged set from award_details() — includes both locally-authored notes and any notes added by the remote portal.",
                verbose_name="notes",
            ),
        ),
        migrations.AlterField(
            model_name="remoteproject",
            name="allowed_domains",
            field=models.JSONField(
                blank=True,
                default=None,
                help_text="List of email domain glob patterns allowed to join the project on the remote portal, e.g. ['*.ac.uk']. None means all domains are allowed.",
                null=True,
                verbose_name="allowed domains",
            ),
        ),
    ]
