# Generated by Django 6.0.8 on 2026-08-20 13:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("waldur_openportal", "0037_alter_allocation_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="managedprojectauditentry",
            options={
                "ordering": ["-timestamp", "id"],
                "verbose_name": "Managed Project Audit Entry",
                "verbose_name_plural": "Managed Project Audit Entries",
            },
        ),
        migrations.AlterModelOptions(
            name="projecttemplate",
            options={
                "ordering": ["name", "id"],
                "verbose_name": "Project class",
                "verbose_name_plural": "Project classes",
            },
        ),
        migrations.AlterModelOptions(
            name="remoteprojectallocationentry",
            options={
                "ordering": ["-submitted_at", "id"],
                "verbose_name": "Remote Project Allocation Entry",
                "verbose_name_plural": "Remote Project Allocation Entries",
            },
        ),
        migrations.AlterModelOptions(
            name="remoteprojectauditentry",
            options={
                "ordering": ["-timestamp", "id"],
                "verbose_name": "Remote Project Audit Entry",
                "verbose_name_plural": "Remote Project Audit Entries",
            },
        ),
    ]
