# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-03 17:02
from __future__ import unicode_literals

from django.db import migrations
import waldur_core.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('experts', '0013_expertcontract__file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expertrequest',
            name='extra',
            field=waldur_core.core.fields.JSONField(default=dict),
        ),
    ]
