# Generated by Django 6.0.8 on 2026-09-03 15:38

from importlib import import_module

import django.db.models.deletion
import django.utils.timezone
import django_fsm
import model_utils.fields
from django.conf import settings
from django.db import migrations, models

import waldur_core.core.fields
import waldur_core.core.migration_operations


def _original(name):
    """A replaced migration's module: its data code runs from there, unchanged."""
    return import_module(__name__.rpartition(".")[0] + "." + name)


class Migration(migrations.Migration):
    replaces = [
        ("waldur_keycloak", "0001_initial"),
        ("waldur_keycloak", "0002_initial"),
        ("waldur_keycloak", "0003_change_scope_id_to_charfield"),
        ("waldur_keycloak", "0004_alter_offeringkeycloakgroup_role"),
        ("waldur_keycloak", "0005_delete_models"),
    ]

    dependencies = [
        ("core", "__first__"),
        ("marketplace", "0208_order_rejection_comments"),
        ("permissions", "0021_alter_role_name_roleavailability"),
        ("structure", "0001_squashed_0036"),
    ]

    operations = [
        _original("0002_initial").CreateModelIfTableNotExists(
            name="OfferingKeycloakGroup",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uuid", waldur_core.core.fields.UUIDField()),
                ("backend_id", models.CharField(blank=True, max_length=255)),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="Group name"
                    ),
                ),
                (
                    "scope_id",
                    models.UUIDField(
                        blank=True,
                        help_text="Sub-entity UUID within a resource, e.g. Rancher Project UUID within a Cluster.",
                        null=True,
                    ),
                ),
                (
                    "offering",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="keycloak_groups",
                        to="marketplace.offering",
                    ),
                ),
                (
                    "resource",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="keycloak_groups",
                        to="marketplace.resource",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="keycloak_groups",
                        to="marketplace.offeringuserrole",
                    ),
                ),
            ],
            options={
                "ordering": ["-created"],
                "unique_together": {("offering", "role", "resource", "scope_id")},
            },
        ),
        waldur_core.core.migration_operations.FlushDeferredSql(),
        _original("0002_initial").CreateModelIfTableNotExists(
            name="OfferingKeycloakMembership",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uuid", waldur_core.core.fields.UUIDField()),
                ("error_message", models.TextField(blank=True)),
                ("error_traceback", models.TextField(blank=True)),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        help_text="Keycloak user username", max_length=255
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="User's email for notifications", max_length=254
                    ),
                ),
                ("first_name", models.CharField(blank=True, max_length=100)),
                ("last_name", models.CharField(blank=True, max_length=100)),
                (
                    "state",
                    django_fsm.FSMField(
                        choices=[("pending", "pending"), ("active", "active")],
                        default="pending",
                        max_length=50,
                    ),
                ),
                ("last_checked", models.DateTimeField(auto_now=True)),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="waldur_keycloak.offeringkeycloakgroup",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created"],
                "unique_together": {("username", "group")},
            },
        ),
        migrations.DeleteModel(
            name="OfferingKeycloakGroup",
        ),
        migrations.DeleteModel(
            name="OfferingKeycloakMembership",
        ),
    ]
