# Generated by Django 6.0.4 on 2026-04-26 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("permissions", "0021_alter_role_name_roleavailability"),
        ("waldur_keycloak", "0003_change_scope_id_to_charfield"),
    ]

    operations = [
        migrations.AlterField(
            model_name="offeringkeycloakgroup",
            name="role",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="keycloak_groups",
                to="permissions.role",
            ),
        ),
    ]
