# Generated by Django 6.0.8 on 2026-08-20 13:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("waldur_auth_saml2", "0002_immutable_default_json"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="identityprovider",
            options={"ordering": ["name", "id"]},
        ),
    ]
