# Generated by Django 6.0.8 on 2026-08-19 21:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("waldur_aws", "0007_alter_instance_description_alter_volume_description"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="instance",
            options={"ordering": ["-created", "id"]},
        ),
        migrations.AlterModelOptions(
            name="volume",
            options={"ordering": ["-created", "id"]},
        ),
    ]
