# Generated by Django 4.2.14 on 2024-09-30 17:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("waldur_jira", "0001_squashed_0024_drop_spl"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="task_id",
            field=models.CharField(blank=True, max_length=155, null=True),
        ),
    ]
