# Generated by Django 4.2.27 on 2026-02-15 08:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("waldur_arrow", "0006_add_plan_to_vendor_offering_mapping"),
    ]

    operations = [
        migrations.AddField(
            model_name="arrowsettings",
            name="invoice_item_prefix",
            field=models.CharField(
                blank=True,
                default="Arrow consumption",
                help_text="Prefix for invoice item names (e.g. 'Arrow consumption')",
                max_length=100,
            ),
        ),
    ]
