# Generated by Django 2.2.9 on 2020-02-24 13:15

from decimal import Decimal

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slurm_invoices', '0002_add_name_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slurmpackage',
            name='cpu_price',
            field=models.DecimalField(
                decimal_places=10,
                default=0,
                max_digits=22,
                validators=[django.core.validators.MinValueValidator(Decimal('0'))],
                verbose_name='Price for CPU hour',
            ),
        ),
        migrations.AlterField(
            model_name='slurmpackage',
            name='gpu_price',
            field=models.DecimalField(
                decimal_places=10,
                default=0,
                max_digits=22,
                validators=[django.core.validators.MinValueValidator(Decimal('0'))],
                verbose_name='Price for GPU hour',
            ),
        ),
        migrations.AlterField(
            model_name='slurmpackage',
            name='ram_price',
            field=models.DecimalField(
                decimal_places=10,
                default=0,
                max_digits=22,
                validators=[django.core.validators.MinValueValidator(Decimal('0'))],
                verbose_name='Price for GB RAM',
            ),
        ),
    ]
