# Generated by Django 4.2.18 on 2025-02-11 16:02

import django.utils.timezone
import django_fsm
import model_utils.fields
from django.conf import settings
from django.db import migrations, models
from django.utils import timezone

import waldur_core.core.fields


def populate_with_current_time(apps, schema_editor):
    Policy = apps.get_model("policy", "ProjectEstimatedCostPolicy")
    Policy.objects.filter(has_fired=True).update(fired_datetime=timezone.now())


class Migration(migrations.Migration):
    replaces = [
        ("policy", "0001_initial"),
        ("policy", "0002_policy_project_not_unique"),
        ("policy", "0003_projectestimatedcostpolicy_fired_datetime"),
        ("policy", "0004_customerestimatedcostpolicy"),
        ("policy", "0005_rename_customer_customerestimatedcostpolicy_scope_and_more"),
        ("policy", "0006_offeringestimatedcostpolicy"),
        ("policy", "0007_offeringestimatedcostpolicy_period"),
        ("policy", "0008_offeringusagepolicy"),
        ("policy", "0009_estimated_cost_policy_period"),
        ("policy", "0010_customerestimatedcostpolicy_options_and_more"),
    ]

    dependencies = [
        ("structure", "0046_project_start_date"),
        ("structure", "0045_customer_slug_project_slug"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("structure", "0044_remove_customer_inet_accesssubnet"),
        ("marketplace", "0132_offering_slug_resource_slug"),
        ("marketplace", "0137_alter_order_state"),
        ("structure", "0039_project_end_date_requested_by"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectEstimatedCostPolicy",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("uuid", waldur_core.core.fields.UUIDField()),
                ("has_fired", models.BooleanField(default=False)),
                ("actions", models.CharField(max_length=255)),
                ("limit_cost", models.IntegerField()),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="structure.project",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "fired_datetime",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
            ],
            options={
                "verbose_name_plural": "Project estimated cost policies",
            },
        ),
        migrations.RunPython(
            code=populate_with_current_time,
        ),
        migrations.RenameField(
            model_name="projectestimatedcostpolicy",
            old_name="project",
            new_name="scope",
        ),
        migrations.CreateModel(
            name="OfferingComponentLimit",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("limit", models.IntegerField()),
                (
                    "component",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="marketplace.offeringcomponent",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OfferingUsagePolicy",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("uuid", waldur_core.core.fields.UUIDField()),
                ("has_fired", models.BooleanField(default=False)),
                (
                    "fired_datetime",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                ("actions", models.CharField(max_length=255)),
                (
                    "period",
                    django_fsm.FSMIntegerField(
                        choices=[
                            (1, "Total"),
                            (2, "1 month"),
                            (3, "3 month"),
                            (4, "12 month"),
                        ],
                        default=2,
                    ),
                ),
                (
                    "component_limit",
                    models.ManyToManyField(
                        through="policy.OfferingComponentLimit",
                        to="marketplace.offeringcomponent",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization_groups",
                    models.ManyToManyField(to="structure.organizationgroup"),
                ),
                (
                    "scope",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="marketplace.offering",
                    ),
                ),
                (
                    "options",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Fields for saving actions extra data. Keys are name of actions.",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="offeringcomponentlimit",
            name="policy",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="component_limits_set",
                to="policy.offeringusagepolicy",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="offeringcomponentlimit",
            unique_together={("policy", "component")},
        ),
        migrations.AddField(
            model_name="projectestimatedcostpolicy",
            name="period",
            field=django_fsm.FSMIntegerField(
                choices=[(1, "Total"), (2, "1 month"), (3, "3 month"), (4, "12 month")],
                default=2,
            ),
        ),
        migrations.CreateModel(
            name="CustomerEstimatedCostPolicy",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("uuid", waldur_core.core.fields.UUIDField()),
                ("has_fired", models.BooleanField(default=False)),
                (
                    "fired_datetime",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                ("actions", models.CharField(max_length=255)),
                ("limit_cost", models.IntegerField()),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "scope",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="structure.customer",
                    ),
                ),
                (
                    "period",
                    django_fsm.FSMIntegerField(
                        choices=[
                            (1, "Total"),
                            (2, "1 month"),
                            (3, "3 month"),
                            (4, "12 month"),
                        ],
                        default=2,
                    ),
                ),
                (
                    "options",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Fields for saving actions extra data. Keys are name of actions.",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Customer estimated cost policies",
            },
        ),
        migrations.CreateModel(
            name="OfferingEstimatedCostPolicy",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("uuid", waldur_core.core.fields.UUIDField()),
                ("has_fired", models.BooleanField(default=False)),
                (
                    "fired_datetime",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                ("limit_cost", models.IntegerField()),
                ("actions", models.CharField(max_length=255)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization_groups",
                    models.ManyToManyField(to="structure.organizationgroup"),
                ),
                (
                    "scope",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="marketplace.offering",
                    ),
                ),
                (
                    "period",
                    django_fsm.FSMIntegerField(
                        choices=[
                            (1, "Total"),
                            (2, "1 month"),
                            (3, "3 month"),
                            (4, "12 month"),
                        ],
                        default=2,
                    ),
                ),
                (
                    "options",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Fields for saving actions extra data. Keys are name of actions.",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Offering estimated cost policies",
            },
        ),
        migrations.AddField(
            model_name="projectestimatedcostpolicy",
            name="options",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Fields for saving actions extra data. Keys are name of actions.",
            ),
        ),
    ]
