# Generated by Django 4.2.14 on 2024-08-28 09:25

import django_fsm
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("policy", "0008_offeringusagepolicy"),
    ]

    operations = [
        migrations.AddField(
            model_name="customerestimatedcostpolicy",
            name="period",
            field=django_fsm.FSMIntegerField(
                choices=[(1, "Total"), (2, "1 month"), (3, "3 month"), (4, "12 month")],
                default=2,
            ),
        ),
        migrations.AddField(
            model_name="projectestimatedcostpolicy",
            name="period",
            field=django_fsm.FSMIntegerField(
                choices=[(1, "Total"), (2, "1 month"), (3, "3 month"), (4, "12 month")],
                default=2,
            ),
        ),
    ]
