# Generated by Django 4.2.16 on 2024-11-20 22:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("policy", "0009_estimated_cost_policy_period"),
    ]

    operations = [
        migrations.AddField(
            model_name="customerestimatedcostpolicy",
            name="options",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Fields for saving actions extra data. Keys are name of actions.",
            ),
        ),
        migrations.AddField(
            model_name="offeringestimatedcostpolicy",
            name="options",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Fields for saving actions extra data. Keys are name of actions.",
            ),
        ),
        migrations.AddField(
            model_name="offeringusagepolicy",
            name="options",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Fields for saving actions extra data. Keys are name of actions.",
            ),
        ),
        migrations.AddField(
            model_name="projectestimatedcostpolicy",
            name="options",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Fields for saving actions extra data. Keys are name of actions.",
            ),
        ),
    ]
