# Generated by Django 4.2.24 on 2026-01-12 16:21

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models

import waldur_core.core.fields


class Migration(migrations.Migration):
    dependencies = [
        ("marketplace", "0200_sync_resource_states_for_pending_orders"),
        ("policy", "0013_add_apply_to_all_field"),
    ]

    operations = [
        migrations.CreateModel(
            name="SlurmCommandHistory",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("uuid", waldur_core.core.fields.UUIDField()),
                (
                    "billing_period",
                    models.DateField(
                        help_text="First day of the billing period when command was executed"
                    ),
                ),
                (
                    "command_type",
                    models.CharField(
                        help_text="Type of command: fairshare, limits, qos, reset_usage",
                        max_length=50,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Human-readable description of what the command does"
                    ),
                ),
                (
                    "shell_command",
                    models.TextField(
                        help_text="Actual shell command that was/would be executed"
                    ),
                ),
                (
                    "parameters",
                    models.JSONField(
                        default=dict, help_text="Command parameters as key-value pairs"
                    ),
                ),
                ("executed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "execution_mode",
                    models.CharField(
                        choices=[
                            ("production", "Production"),
                            ("emulator", "Emulator"),
                        ],
                        default="production",
                        help_text="Whether command was executed in production or emulator mode",
                        max_length=20,
                    ),
                ),
                (
                    "success",
                    models.BooleanField(
                        default=True,
                        help_text="Whether the command execution was successful",
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True,
                        help_text="Error message if command execution failed",
                    ),
                ),
                (
                    "policy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="command_history",
                        to="policy.slurmperiodicusagepolicy",
                    ),
                ),
                (
                    "resource",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="slurm_command_history",
                        to="marketplace.resource",
                    ),
                ),
            ],
            options={
                "verbose_name": "SLURM Command History",
                "verbose_name_plural": "SLURM Command History",
                "ordering": ["-executed_at"],
                "indexes": [
                    models.Index(
                        fields=["resource", "billing_period"],
                        name="policy_slur_resourc_da8d09_idx",
                    ),
                    models.Index(
                        fields=["policy", "billing_period"],
                        name="policy_slur_policy__53fea0_idx",
                    ),
                ],
            },
        ),
    ]
