# Generated by Django 6.0.6 on 2026-07-09 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("marketplace", "0249_offeringuserattributeconfig_expose_primary_gid_and_more"),
        ("policy", "0016_sync_slurm_policy_period_with_component"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectestimatedcostpolicy",
            name="resource",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="marketplace.resource",
            ),
        ),
        migrations.AddField(
            model_name="projectestimatedcostpolicy",
            name="use_credit",
            field=models.BooleanField(default=True),
        ),
    ]
