# Generated by Django 6.0.8 on 2026-08-21 06:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("policy", "0017_projectestimatedcostpolicy_resource_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="slurmcommandhistory",
            options={
                "ordering": ["-executed_at", "id"],
                "verbose_name": "SLURM Command History",
                "verbose_name_plural": "SLURM Command History",
            },
        ),
        migrations.AlterModelOptions(
            name="slurmpolicyevaluationlog",
            options={
                "ordering": ["-evaluated_at", "id"],
                "verbose_name": "SLURM Policy Evaluation Log",
                "verbose_name_plural": "SLURM Policy Evaluation Logs",
            },
        ),
    ]
