# Generated by Django 3.2.16 on 2023-01-13 14:17

from django.db import migrations, models

import waldur_core.core.validators


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='name',
            field=models.CharField(
                default='Default',
                max_length=150,
                validators=[waldur_core.core.validators.validate_name],
                verbose_name='name',
            ),
            preserve_default=False,
        ),
    ]
