# Generated by Django 6.0.8 on 2026-09-03 15:35

from importlib import import_module

import django.contrib.postgres.fields
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.conf import settings
from django.db import migrations, models

import waldur_core.core.fields
import waldur_core.core.migration_operations
import waldur_core.core.utils
import waldur_core.logging.models


def _original(name):
    """A replaced migration's module: its data code runs from there, unchanged."""
    return import_module(__name__.rpartition(".")[0] + "." + name)


class Migration(migrations.Migration):
    replaces = [
        ("logging", "0001_squashed_0010"),
        ("logging", "0002_immutable_default_json"),
        ("logging", "0003_system_notification"),
        ("logging", "0004_json_field"),
        ("logging", "0005_report"),
        ("logging", "0006_event_feed"),
        ("logging", "0007_drop_alerts"),
        ("logging", "0008_drop_sec_group_rules_pulling_events"),
        ("logging", "0009_delete_pushhook"),
        ("logging", "0010_long_email"),
        ("logging", "0011_json_field"),
        ("logging", "0012_delete_report"),
        ("logging", "0013_alter_event_created"),
        ("logging", "0014_eventsubscription"),
        ("logging", "0015_event_index"),
        ("logging", "0016_emaillog"),
        ("logging", "0017_alter_emaillog_options"),
        ("logging", "0018_composite_indexes"),
        ("logging", "0019_alter_eventsubscription_description"),
        ("logging", "0020_add_user_data_access_log"),
        ("logging", "0021_eventsubscriptionqueue"),
        ("logging", "0022_systemlog"),
        ("logging", "0023_basehook_concrete"),
        ("logging", "0024_alter_webhook_destination_url"),
        ("logging", "0025_eventconsumer"),
        ("logging", "0026_alter_basehook_options_alter_emaillog_options_and_more"),
    ]

    dependencies = [
        ("contenttypes", "0001_initial"),
        ("contenttypes", "0002_remove_content_type_name"),
        ("core", "__first__"),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uuid", waldur_core.core.fields.UUIDField()),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("event_type", models.CharField(db_index=True, max_length=100)),
                ("message", models.TextField()),
                ("context", models.JSONField(blank=True)),
            ],
            options={
                "abstract": False,
                "ordering": ("-created",),
            },
        ),
        migrations.CreateModel(
            name="EmailHook",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("uuid", waldur_core.core.fields.UUIDField()),
                ("event_types", models.JSONField(verbose_name="List of event types")),
                (
                    "event_groups",
                    models.JSONField(default=list, verbose_name="List of event groups"),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "last_published",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("email", models.EmailField(max_length=320)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
                "ordering": ["-created"],
            },
        ),
        migrations.CreateModel(
            name="EventSubscription",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=2000, verbose_name="description"
                    ),
                ),
                ("uuid", waldur_core.core.fields.UUIDField()),
                (
                    "source_ip",
                    models.GenericIPAddressField(
                        blank=True, null=True, protocol="IPv4"
                    ),
                ),
                (
                    "observable_objects",
                    models.JSONField(
                        default=list, help_text="List of observable objects"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Feed",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("object_id", models.PositiveIntegerField(db_index=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="logging.event"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SystemNotification",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_types", models.JSONField(verbose_name="List of event types")),
                (
                    "event_groups",
                    models.JSONField(default=list, verbose_name="List of event groups"),
                ),
                ("name", models.CharField(max_length=150, verbose_name="name")),
                (
                    "roles",
                    waldur_core.core.fields.JSONField(
                        default=list, verbose_name="List of roles"
                    ),
                ),
                (
                    "hook_content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="WebHook",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("uuid", waldur_core.core.fields.UUIDField()),
                ("event_types", models.JSONField(verbose_name="List of event types")),
                (
                    "event_groups",
                    models.JSONField(default=list, verbose_name="List of event groups"),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "last_published",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("destination_url", models.URLField()),
                (
                    "content_type",
                    models.SmallIntegerField(
                        choices=[(1, "json"), (2, "form")], default=1
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
                "ordering": ["-created"],
            },
        ),
        waldur_core.core.migration_operations.FlushDeferredSql(),
        migrations.RunSQL(
            sql="CREATE INDEX log_event_org ON logging_event((context->>'customer_uuid'));",
        ),
        waldur_core.core.migration_operations.FlushDeferredSql(),
        migrations.RunSQL(
            sql="CREATE INDEX log_event_proj ON logging_event((context->>'project_uuid'));",
        ),
        waldur_core.core.migration_operations.FlushDeferredSql(),
        migrations.RunSQL(
            sql="CREATE INDEX log_event_user ON logging_event((context->>'user_uuid'));",
        ),
        migrations.CreateModel(
            name="BaseHook",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("uuid", waldur_core.core.fields.UUIDField()),
                ("event_types", models.JSONField(verbose_name="List of event types")),
                (
                    "event_groups",
                    models.JSONField(default=list, verbose_name="List of event groups"),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "last_published",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
            options={
                "ordering": ["-created"],
            },
        ),
        migrations.CreateModel(
            name="EmailLog",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uuid", waldur_core.core.fields.UUIDField()),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
                ("subject", models.CharField(max_length=255)),
                ("body", models.TextField()),
                (
                    "emails",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.EmailField(max_length=254)
                    ),
                ),
            ],
            options={
                "ordering": ["-sent_at"],
            },
        ),
        migrations.CreateModel(
            name="EventSubscriptionQueue",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("uuid", waldur_core.core.fields.UUIDField()),
                (
                    "offering_uuid",
                    models.UUIDField(
                        help_text="UUID of the offering this queue receives events for"
                    ),
                ),
                (
                    "object_type",
                    models.CharField(
                        help_text="Observable object type (e.g., 'resource', 'order')",
                        max_length=50,
                    ),
                ),
            ],
            options={
                "verbose_name": "Subscription queue",
                "ordering": ["-created"],
            },
        ),
        migrations.CreateModel(
            name="SystemLog",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("api", "API"),
                            ("worker", "Worker"),
                            ("beat", "Beat"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "instance",
                    models.CharField(
                        help_text="Pod name (K8s) or container name (Docker)",
                        max_length=255,
                    ),
                ),
                ("level", models.CharField(max_length=10)),
                ("level_number", models.PositiveSmallIntegerField()),
                ("logger_name", models.CharField(max_length=255)),
                ("message", models.TextField()),
                ("context", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ["-created"],
            },
        ),
        migrations.CreateModel(
            name="UserDataAccessLog",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uuid", waldur_core.core.fields.UUIDField()),
                (
                    "timestamp",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="When the access occurred",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, help_text="IP address of the accessor", null=True
                    ),
                ),
                (
                    "accessor_type",
                    models.CharField(
                        choices=[
                            ("staff", "Staff"),
                            ("support", "Support"),
                            ("organization_member", "Organization member"),
                            ("service_provider", "Service provider"),
                            ("self", "Self"),
                        ],
                        help_text="Type of accessor",
                        max_length=50,
                    ),
                ),
                (
                    "accessed_fields",
                    models.JSONField(
                        default=list,
                        help_text="List of user profile fields that were accessed",
                    ),
                ),
                (
                    "context",
                    models.JSONField(
                        default=dict,
                        help_text="Additional context (endpoint, offering UUID for providers, etc.)",
                    ),
                ),
            ],
            options={
                "verbose_name": "User data access log",
                "verbose_name_plural": "User data access logs",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.AlterField(
            model_name="eventsubscription",
            name="description",
            field=models.CharField(
                blank=True, max_length=4096, verbose_name="description"
            ),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(
                fields=["-created", "event_type"], name="logging_eve_created_ef381c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="feed",
            index=models.Index(
                fields=["content_type", "object_id"],
                name="logging_fee_content_eec3cf_idx",
            ),
        ),
        migrations.AddField(
            model_name="basehook",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="emailhook",
            name="basehook_ptr",
            field=models.OneToOneField(
                auto_created=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="logging.basehook",
            ),
        ),
        migrations.AddField(
            model_name="webhook",
            name="basehook_ptr",
            field=models.OneToOneField(
                auto_created=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="logging.basehook",
            ),
        ),
        migrations.AddField(
            model_name="eventsubscriptionqueue",
            name="event_subscription",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="queues",
                to="logging.eventsubscription",
            ),
        ),
        migrations.AddIndex(
            model_name="systemlog",
            index=models.Index(
                fields=["-created", "source"], name="logging_syslog_created_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="systemlog",
            index=models.Index(
                fields=["source", "instance", "-created"],
                name="logging_syslog_instance_idx",
            ),
        ),
        migrations.AddField(
            model_name="userdataaccesslog",
            name="accessor",
            field=models.ForeignKey(
                help_text="The user who accessed the data",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="performed_data_accesses",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="userdataaccesslog",
            name="target_user",
            field=models.ForeignKey(
                help_text="The user whose data was accessed",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="data_access_logs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="eventsubscriptionqueue",
            unique_together={("event_subscription", "offering_uuid", "object_type")},
        ),
        migrations.AddIndex(
            model_name="userdataaccesslog",
            index=models.Index(
                fields=["target_user", "-timestamp"],
                name="logging_use_target__c0fcb3_idx",
            ),
        ),
        waldur_core.core.migration_operations.FlushDeferredSql(),
        migrations.RunPython(
            code=_original("0023_basehook_concrete").migrate_data,
        ),
        migrations.AlterModelOptions(
            name="basehook",
            options={"ordering": ["-created", "id"]},
        ),
        migrations.AlterModelOptions(
            name="emailhook",
            options={},
        ),
        migrations.AlterModelOptions(
            name="emaillog",
            options={"ordering": ["-sent_at", "id"]},
        ),
        migrations.AlterModelOptions(
            name="event",
            options={"ordering": ["-created", "id"]},
        ),
        migrations.AlterModelOptions(
            name="eventsubscriptionqueue",
            options={
                "ordering": ["-created", "id"],
                "verbose_name": "Subscription queue",
            },
        ),
        migrations.AlterModelOptions(
            name="systemlog",
            options={"ordering": ["-created", "id"]},
        ),
        migrations.AlterModelOptions(
            name="userdataaccesslog",
            options={
                "ordering": ["-timestamp", "id"],
                "verbose_name": "User data access log",
                "verbose_name_plural": "User data access logs",
            },
        ),
        migrations.AlterModelOptions(
            name="webhook",
            options={},
        ),
        migrations.RemoveField(
            model_name="emailhook",
            name="created",
        ),
        migrations.RemoveField(
            model_name="emailhook",
            name="event_groups",
        ),
        migrations.RemoveField(
            model_name="emailhook",
            name="event_types",
        ),
        migrations.RemoveField(
            model_name="emailhook",
            name="id",
        ),
        migrations.RemoveField(
            model_name="emailhook",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="emailhook",
            name="last_published",
        ),
        migrations.RemoveField(
            model_name="emailhook",
            name="modified",
        ),
        migrations.RemoveField(
            model_name="emailhook",
            name="user",
        ),
        migrations.RemoveField(
            model_name="emailhook",
            name="uuid",
        ),
        migrations.RemoveField(
            model_name="webhook",
            name="created",
        ),
        migrations.RemoveField(
            model_name="webhook",
            name="event_groups",
        ),
        migrations.RemoveField(
            model_name="webhook",
            name="event_types",
        ),
        migrations.RemoveField(
            model_name="webhook",
            name="id",
        ),
        migrations.RemoveField(
            model_name="webhook",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="webhook",
            name="last_published",
        ),
        migrations.RemoveField(
            model_name="webhook",
            name="modified",
        ),
        migrations.RemoveField(
            model_name="webhook",
            name="user",
        ),
        migrations.RemoveField(
            model_name="webhook",
            name="uuid",
        ),
        migrations.AlterField(
            model_name="emailhook",
            name="basehook_ptr",
            field=models.OneToOneField(
                auto_created=True,
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                primary_key=True,
                serialize=False,
                to="logging.basehook",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="webhook",
            name="basehook_ptr",
            field=models.OneToOneField(
                auto_created=True,
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                primary_key=True,
                serialize=False,
                to="logging.basehook",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="webhook",
            name="destination_url",
            field=models.URLField(
                validators=[waldur_core.core.utils.validate_outbound_url]
            ),
        ),
        migrations.CreateModel(
            name="EventConsumer",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("uuid", waldur_core.core.fields.UUIDField()),
                (
                    "rmq_username",
                    models.CharField(
                        blank=True,
                        help_text="RabbitMQ username (UUID hex) for the consumer queue.",
                        max_length=32,
                    ),
                ),
                ("queue_created", models.BooleanField(default=False)),
                (
                    "object_types",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of observable object types this consumer receives. Empty list means all types.",
                        validators=[
                            waldur_core.logging.models.validate_observable_object_types
                        ],
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="Owner/registrant; the RabbitMQ vhost is the user UUID hex.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_consumers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EventConsumerScope",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("object_id", models.PositiveIntegerField(db_index=True)),
                (
                    "consumer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scopes",
                        to="logging.eventconsumer",
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["content_type", "object_id"],
                        name="logging_eve_content_1ebe33_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("consumer", "content_type", "object_id"),
                        name="unique_event_consumer_scope",
                    )
                ],
            },
        ),
    ]
