# Generated by Django 4.2.18 on 2025-02-11 15:20

import django.contrib.postgres.fields.jsonb
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.conf import settings
from django.db import migrations, models

import waldur_core.core.fields


class Migration(migrations.Migration):
    replaces = [
        ("logging", "0002_immutable_default_json"),
        ("logging", "0003_system_notification"),
        ("logging", "0004_json_field"),
        ("logging", "0005_report"),
        ("logging", "0006_event_feed"),
        ("logging", "0007_drop_alerts"),
        ("logging", "0008_drop_sec_group_rules_pulling_events"),
        ("logging", "0009_delete_pushhook"),
        ("logging", "0010_long_email"),
        ("logging", "0011_json_field"),
        ("logging", "0012_delete_report"),
        ("logging", "0013_alter_event_created"),
        ("logging", "0014_eventsubscription"),
        ("logging", "0015_event_index"),
    ]

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("logging", "0001_squashed_0010"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailhook",
            name="event_groups",
            field=waldur_core.core.fields.JSONField(
                default=list, verbose_name="List of event groups"
            ),
        ),
        migrations.AlterField(
            model_name="pushhook",
            name="event_groups",
            field=waldur_core.core.fields.JSONField(
                default=list, verbose_name="List of event groups"
            ),
        ),
        migrations.AlterField(
            model_name="systemnotification",
            name="event_groups",
            field=waldur_core.core.fields.JSONField(
                default=list, verbose_name="List of event groups"
            ),
        ),
        migrations.AlterField(
            model_name="webhook",
            name="event_groups",
            field=waldur_core.core.fields.JSONField(
                default=list, verbose_name="List of event groups"
            ),
        ),
        migrations.AddField(
            model_name="systemnotification",
            name="name",
            field=models.CharField(default="", max_length=150, verbose_name="name"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="systemnotification",
            name="roles",
            field=waldur_core.core.fields.JSONField(
                default=list, verbose_name="List of roles"
            ),
        ),
        migrations.AlterField(
            model_name="systemnotification",
            name="hook_content_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AlterField(
            model_name="emailhook",
            name="event_groups",
            field=django.contrib.postgres.fields.jsonb.JSONField(
                default=list, verbose_name="List of event groups"
            ),
        ),
        migrations.AlterField(
            model_name="emailhook",
            name="event_types",
            field=django.contrib.postgres.fields.jsonb.JSONField(
                verbose_name="List of event types"
            ),
        ),
        migrations.AlterField(
            model_name="pushhook",
            name="event_groups",
            field=django.contrib.postgres.fields.jsonb.JSONField(
                default=list, verbose_name="List of event groups"
            ),
        ),
        migrations.AlterField(
            model_name="pushhook",
            name="event_types",
            field=django.contrib.postgres.fields.jsonb.JSONField(
                verbose_name="List of event types"
            ),
        ),
        migrations.AlterField(
            model_name="systemnotification",
            name="event_groups",
            field=django.contrib.postgres.fields.jsonb.JSONField(
                default=list, verbose_name="List of event groups"
            ),
        ),
        migrations.AlterField(
            model_name="systemnotification",
            name="event_types",
            field=django.contrib.postgres.fields.jsonb.JSONField(
                verbose_name="List of event types"
            ),
        ),
        migrations.AlterField(
            model_name="webhook",
            name="event_groups",
            field=django.contrib.postgres.fields.jsonb.JSONField(
                default=list, verbose_name="List of event groups"
            ),
        ),
        migrations.AlterField(
            model_name="webhook",
            name="event_types",
            field=django.contrib.postgres.fields.jsonb.JSONField(
                verbose_name="List of event types"
            ),
        ),
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("uuid", waldur_core.core.fields.UUIDField()),
                ("file", models.FileField(upload_to="logging_reports")),
                ("file_size", models.PositiveIntegerField(null=True)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("done", "Done"),
                            ("erred", "Erred"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("error_message", models.TextField(blank=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uuid", waldur_core.core.fields.UUIDField()),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("event_type", models.CharField(db_index=True, max_length=100)),
                ("message", models.TextField()),
                ("context", models.JSONField(blank=True)),
            ],
            options={
                "abstract": False,
                "ordering": ("-created",),
            },
        ),
        migrations.CreateModel(
            name="Feed",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("object_id", models.PositiveIntegerField(db_index=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="logging.event"
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Alert",
        ),
        migrations.DeleteModel(
            name="PushHook",
        ),
        migrations.AlterField(
            model_name="emailhook",
            name="email",
            field=models.EmailField(max_length=320),
        ),
        migrations.AlterField(
            model_name="emailhook",
            name="event_groups",
            field=models.JSONField(default=list, verbose_name="List of event groups"),
        ),
        migrations.AlterField(
            model_name="emailhook",
            name="event_types",
            field=models.JSONField(verbose_name="List of event types"),
        ),
        migrations.AlterField(
            model_name="systemnotification",
            name="event_groups",
            field=models.JSONField(default=list, verbose_name="List of event groups"),
        ),
        migrations.AlterField(
            model_name="systemnotification",
            name="event_types",
            field=models.JSONField(verbose_name="List of event types"),
        ),
        migrations.AlterField(
            model_name="webhook",
            name="event_groups",
            field=models.JSONField(default=list, verbose_name="List of event groups"),
        ),
        migrations.AlterField(
            model_name="webhook",
            name="event_types",
            field=models.JSONField(verbose_name="List of event types"),
        ),
        migrations.DeleteModel(
            name="Report",
        ),
        migrations.CreateModel(
            name="EventSubscription",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=2000, verbose_name="description"
                    ),
                ),
                ("uuid", waldur_core.core.fields.UUIDField()),
                (
                    "source_ip",
                    models.GenericIPAddressField(
                        blank=True, null=True, protocol="IPv4"
                    ),
                ),
                (
                    "observable_objects",
                    models.JSONField(
                        default=list, help_text="List of observable objects"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.RunSQL(
            sql="CREATE INDEX log_event_org ON logging_event((context->>'customer_uuid'));",
        ),
        migrations.RunSQL(
            sql="CREATE INDEX log_event_proj ON logging_event((context->>'project_uuid'));",
        ),
        migrations.RunSQL(
            sql="CREATE INDEX log_event_user ON logging_event((context->>'user_uuid'));",
        ),
    ]
