# Generated by Django 2.2.24 on 2021-10-06 09:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("logging", "0009_delete_pushhook"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailhook",
            name="email",
            field=models.EmailField(max_length=320),
        ),
    ]
