# Generated by Django 4.2.16 on 2024-10-23 17:42

import django.utils.timezone
import model_utils.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("logging", "0012_delete_report"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="created",
            field=model_utils.fields.AutoCreatedField(
                db_index=True, default=django.utils.timezone.now, editable=False
            ),
        ),
    ]
