# Generated by Django 4.2.17 on 2025-01-13 10:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("logging", "0014_eventsubscription"),
    ]

    operations = [
        migrations.RunSQL(
            "CREATE INDEX log_event_org ON logging_event((context->>'customer_uuid'));"
        ),
        migrations.RunSQL(
            "CREATE INDEX log_event_proj ON logging_event((context->>'project_uuid'));"
        ),
        migrations.RunSQL(
            "CREATE INDEX log_event_user ON logging_event((context->>'user_uuid'));"
        ),
    ]
