# Generated by Django 4.2.24 on 2026-01-25 09:14

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models

import waldur_core.core.fields


class Migration(migrations.Migration):
    dependencies = [
        ("logging", "0020_add_user_data_access_log"),
    ]

    operations = [
        migrations.CreateModel(
            name="EventSubscriptionQueue",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("uuid", waldur_core.core.fields.UUIDField()),
                (
                    "offering_uuid",
                    models.UUIDField(
                        help_text="UUID of the offering this queue receives events for"
                    ),
                ),
                (
                    "object_type",
                    models.CharField(
                        help_text="Observable object type (e.g., 'resource', 'order')",
                        max_length=50,
                    ),
                ),
                (
                    "event_subscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="queues",
                        to="logging.eventsubscription",
                    ),
                ),
            ],
            options={
                "verbose_name": "Subscription queue",
                "ordering": ["-created"],
                "unique_together": {
                    ("event_subscription", "offering_uuid", "object_type")
                },
            },
        ),
    ]
