# Generated by Django on 2026-04-20 12:35

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.conf import settings
from django.db import migrations, models

import waldur_core.core.fields


def migrate_data(apps, schema_editor):
    BaseHook = apps.get_model("logging", "BaseHook")
    WebHook = apps.get_model("logging", "WebHook")
    EmailHook = apps.get_model("logging", "EmailHook")

    for hook in WebHook.objects.all():
        base = BaseHook.objects.create(
            created=hook.created,
            modified=hook.modified,
            uuid=hook.uuid,
            event_types=hook.event_types,
            event_groups=hook.event_groups,
            is_active=hook.is_active,
            last_published=hook.last_published,
            user_id=hook.user_id,
        )
        hook.basehook_ptr = base
        hook.save()

    for hook in EmailHook.objects.all():
        base = BaseHook.objects.create(
            created=hook.created,
            modified=hook.modified,
            uuid=hook.uuid,
            event_types=hook.event_types,
            event_groups=hook.event_groups,
            is_active=hook.is_active,
            last_published=hook.last_published,
            user_id=hook.user_id,
        )
        hook.basehook_ptr = base
        hook.save()


class Migration(migrations.Migration):
    dependencies = [
        ("logging", "0016_squashed_0016_0022"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BaseHook",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("uuid", waldur_core.core.fields.UUIDField()),
                ("event_types", models.JSONField(verbose_name="List of event types")),
                (
                    "event_groups",
                    models.JSONField(default=list, verbose_name="List of event groups"),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "last_published",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created"],
            },
        ),
        migrations.AddField(
            model_name="emailhook",
            name="basehook_ptr",
            field=models.OneToOneField(
                auto_created=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="logging.basehook",
            ),
        ),
        migrations.AddField(
            model_name="webhook",
            name="basehook_ptr",
            field=models.OneToOneField(
                auto_created=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="logging.basehook",
            ),
        ),
        migrations.RunPython(migrate_data),
        migrations.RemoveField(model_name="emailhook", name="created"),
        migrations.RemoveField(model_name="emailhook", name="event_groups"),
        migrations.RemoveField(model_name="emailhook", name="event_types"),
        migrations.RemoveField(model_name="emailhook", name="id"),
        migrations.RemoveField(model_name="emailhook", name="is_active"),
        migrations.RemoveField(model_name="emailhook", name="last_published"),
        migrations.RemoveField(model_name="emailhook", name="modified"),
        migrations.RemoveField(model_name="emailhook", name="user"),
        migrations.RemoveField(model_name="emailhook", name="uuid"),
        migrations.RemoveField(model_name="webhook", name="created"),
        migrations.RemoveField(model_name="webhook", name="event_groups"),
        migrations.RemoveField(model_name="webhook", name="event_types"),
        migrations.RemoveField(model_name="webhook", name="id"),
        migrations.RemoveField(model_name="webhook", name="is_active"),
        migrations.RemoveField(model_name="webhook", name="last_published"),
        migrations.RemoveField(model_name="webhook", name="modified"),
        migrations.RemoveField(model_name="webhook", name="user"),
        migrations.RemoveField(model_name="webhook", name="uuid"),
        migrations.AlterField(
            model_name="emailhook",
            name="basehook_ptr",
            field=models.OneToOneField(
                auto_created=True,
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                primary_key=True,
                serialize=False,
                to="logging.basehook",
            ),
        ),
        migrations.AlterField(
            model_name="webhook",
            name="basehook_ptr",
            field=models.OneToOneField(
                auto_created=True,
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                primary_key=True,
                serialize=False,
                to="logging.basehook",
            ),
        ),
        migrations.AlterModelOptions(
            name="emailhook",
            options={},
        ),
        migrations.AlterModelOptions(
            name="webhook",
            options={},
        ),
    ]
