# Generated by Django 6.0.5 on 2026-05-13 14:32

import waldur_core.core.utils
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("logging", "0023_basehook_concrete"),
    ]

    operations = [
        migrations.AlterField(
            model_name="webhook",
            name="destination_url",
            field=models.URLField(
                validators=[waldur_core.core.utils.validate_outbound_url]
            ),
        ),
    ]
