# Generated by Django 6.0.8 on 2026-08-31 14:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("logging", "0001_squashed_0026"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="emaillog",
            index=models.Index(
                fields=["-sent_at"], name="logging_ema_sent_at_66b0dd_idx"
            ),
        ),
    ]
