# Generated by Django 3.2.20 on 2023-10-30 09:39

from django.db import migrations, models

import waldur_core.core.validators


class Migration(migrations.Migration):
    dependencies = [
        ("marketplace_checklist", "0002_translations"),
    ]

    operations = [
        migrations.AddField(
            model_name="checklist",
            name="description_ar",
            field=models.CharField(
                blank=True, max_length=2000, null=True, verbose_name="description"
            ),
        ),
        migrations.AddField(
            model_name="checklist",
            name="name_ar",
            field=models.CharField(
                max_length=150,
                null=True,
                validators=[waldur_core.core.validators.validate_name],
                verbose_name="name",
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="description_ar",
            field=models.CharField(
                blank=True, max_length=2000, null=True, verbose_name="description"
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="solution_ar",
            field=models.TextField(
                blank=True,
                help_text="It is shown when incorrect or N/A answer is chosen",
                null=True,
            ),
        ),
    ]
