# Generated by Django 2.2.10 on 2020-05-26 13:30

from django.db import migrations, models

import waldur_core.core.validators


class Migration(migrations.Migration):
    dependencies = [
        ('marketplace_checklist', '0003_add_category_and_correct_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='description_en',
            field=models.CharField(
                blank=True, max_length=500, null=True, verbose_name='description'
            ),
        ),
        migrations.AddField(
            model_name='question',
            name='description_et',
            field=models.CharField(
                blank=True, max_length=500, null=True, verbose_name='description'
            ),
        ),
        migrations.AddField(
            model_name='question',
            name='solution_en',
            field=models.TextField(
                blank=True,
                help_text='It is shown when incorrect or N/A answer is chosen',
                null=True,
            ),
        ),
        migrations.AddField(
            model_name='question',
            name='solution_et',
            field=models.TextField(
                blank=True,
                help_text='It is shown when incorrect or N/A answer is chosen',
                null=True,
            ),
        ),
        migrations.AddField(
            model_name='checklist',
            name='description_en',
            field=models.CharField(
                blank=True, max_length=500, null=True, verbose_name='description'
            ),
        ),
        migrations.AddField(
            model_name='checklist',
            name='description_et',
            field=models.CharField(
                blank=True, max_length=500, null=True, verbose_name='description'
            ),
        ),
        migrations.AddField(
            model_name='checklist',
            name='name_en',
            field=models.CharField(
                max_length=150,
                null=True,
                validators=[waldur_core.core.validators.validate_name],
                verbose_name='name',
            ),
        ),
        migrations.AddField(
            model_name='checklist',
            name='name_et',
            field=models.CharField(
                max_length=150,
                null=True,
                validators=[waldur_core.core.validators.validate_name],
                verbose_name='name',
            ),
        ),
    ]
