# Generated by Django 2.2.13 on 2020-09-16 07:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace_checklist', '0005_extend_description_limits'),
    ]

    operations = [
        migrations.RemoveField(model_name='answer', name='project',),
        migrations.AlterField(
            model_name='answer',
            name='user',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
