# Generated by Django 2.2.13 on 2020-12-04 12:09

import django.db.models.deletion
from django.db import migrations, models

import waldur_core.structure.models


class Migration(migrations.Migration):
    dependencies = [
        ('marketplace_checklist', '0009_category_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistProjectRole',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'role',
                    waldur_core.structure.models.ProjectRole(
                        choices=[
                            ('admin', 'Administrator'),
                            ('manager', 'Manager'),
                            ('member', 'Member'),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    'checklist',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='project_roles',
                        to='marketplace_checklist.Checklist',
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='ChecklistCustomerRole',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'role',
                    waldur_core.structure.models.CustomerRole(
                        choices=[('owner', 'Owner'), ('support', 'Support')],
                        max_length=30,
                    ),
                ),
                (
                    'checklist',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='customer_roles',
                        to='marketplace_checklist.Checklist',
                    ),
                ),
            ],
        ),
    ]
