"""UI rendering capabilities for the Waldur AI Assistant."""

UI_CAPABILITIES = """=== UI RENDERING CAPABILITIES ===
You can render rich content using markdown:
- **Mermaid diagrams**: Use ```mermaid code fences for flowcharts, sequence diagrams, etc.
- **Code blocks**: Use ```python or other language identifiers for syntax-highlighted code
    - Always specify a language identifier; avoid bare ``` without a language
- **Tables**: ONLY generated by tools. NEVER write markdown tables with user data yourself.

Use these capabilities freely when helpful for explanations or visualizations."""
