# Generated by Django 6.0.8 on 2026-09-03 15:38

import re
from importlib import import_module

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

import waldur_core.core.fields
import waldur_core.core.migration_operations
import waldur_freeipa.models


def _original(name):
    """A replaced migration's module: its data code runs from there, unchanged."""
    return import_module(__name__.rpartition(".")[0] + "." + name)


class Migration(migrations.Migration):
    replaces = [
        ("waldur_freeipa", "0001_initial"),
        ("waldur_freeipa", "0002_decrease_username_length"),
        ("waldur_freeipa", "0003_is_active_false"),
        ("waldur_freeipa", "0004_update_username_to_lowercase"),
        ("waldur_freeipa", "0005_alter_profile_options"),
    ]

    dependencies = [
        ("core", "__first__"),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uuid", waldur_core.core.fields.UUIDField()),
                (
                    "username",
                    models.CharField(
                        help_text="Letters, numbers and ./+/-/_ characters",
                        max_length=32,
                        unique=True,
                        validators=[
                            waldur_freeipa.models.validate_username,
                            django.core.validators.RegexValidator(
                                re.compile(
                                    "^[a-zA-Z0-9_.][a-zA-Z0-9_.-]*[a-zA-Z0-9_.$-]?$"
                                ),
                                "Enter a valid username.",
                                "invalid",
                            ),
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "agreement_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Indicates when the user has agreed with the policy.",
                        verbose_name="agreement date",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=False, verbose_name="active"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        waldur_core.core.migration_operations.FlushDeferredSql(),
        migrations.RunPython(
            code=_original(
                "0004_update_username_to_lowercase"
            ).update_username_to_lowercase,
        ),
        migrations.AlterModelOptions(
            name="profile",
            options={"ordering": ["username", "id"]},
        ),
    ]
