# Generated by Django 6.0.8 on 2026-08-20 07:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("waldur_freeipa", "0004_update_username_to_lowercase"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="profile",
            options={"ordering": ["username", "id"]},
        ),
    ]
