# Generated by Django 6.0.8 on 2026-09-03 15:37

import django.db.models.deletion
import django.utils.timezone
import django_fsm
import model_utils.fields
from django.db import migrations, models

import waldur_core.core.fields
import waldur_core.core.models
import waldur_core.core.validators
import waldur_core.structure.models


class Migration(migrations.Migration):
    replaces = [
        ("waldur_digitalocean", "0001_initial"),
        ("waldur_digitalocean", "0002_extend_description_limits"),
        ("waldur_digitalocean", "0003_droplet_error_traceback"),
        ("waldur_digitalocean", "0004_drop_spl"),
        ("waldur_digitalocean", "0005_alter_droplet_state"),
        ("waldur_digitalocean", "0006_alter_droplet_description"),
        ("waldur_digitalocean", "0007_alter_droplet_options"),
        ("waldur_digitalocean", "0008_alter_region_options"),
    ]

    dependencies = [
        ("structure", "0001_squashed_0036"),
    ]

    operations = [
        migrations.CreateModel(
            name="Region",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=150,
                        validators=[waldur_core.core.validators.validate_name],
                        verbose_name="name",
                    ),
                ),
                ("uuid", waldur_core.core.fields.UUIDField()),
                ("backend_id", models.CharField(max_length=255, unique=True)),
            ],
            options={
                "ordering": ["name", "id"],
            },
            bases=(waldur_core.core.models.BackendModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name="Droplet",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=4096, verbose_name="description"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=150,
                        validators=[waldur_core.core.validators.validate_name],
                        verbose_name="name",
                    ),
                ),
                ("uuid", waldur_core.core.fields.UUIDField()),
                ("error_message", models.TextField(blank=True)),
                ("error_traceback", models.TextField(blank=True)),
                (
                    "runtime_state",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="runtime state"
                    ),
                ),
                (
                    "state",
                    django_fsm.FSMIntegerField(
                        choices=[
                            (5, "CREATION_SCHEDULED"),
                            (6, "CREATING"),
                            (1, "UPDATE_SCHEDULED"),
                            (2, "UPDATING"),
                            (7, "DELETION_SCHEDULED"),
                            (8, "DELETING"),
                            (3, "OK"),
                            (4, "ERRED"),
                        ],
                        default=5,
                    ),
                ),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
                ("backend_id", models.CharField(blank=True, max_length=255)),
                (
                    "cores",
                    models.PositiveSmallIntegerField(
                        default=0, help_text="Number of cores in a VM"
                    ),
                ),
                (
                    "ram",
                    models.PositiveIntegerField(
                        default=0, help_text="Memory size in MiB"
                    ),
                ),
                (
                    "disk",
                    models.PositiveIntegerField(
                        default=0, help_text="Disk size in MiB"
                    ),
                ),
                (
                    "min_ram",
                    models.PositiveIntegerField(
                        default=0, help_text="Minimum memory size in MiB"
                    ),
                ),
                (
                    "min_disk",
                    models.PositiveIntegerField(
                        default=0, help_text="Minimum disk size in MiB"
                    ),
                ),
                ("image_name", models.CharField(blank=True, max_length=150)),
                ("key_name", models.CharField(blank=True, max_length=50)),
                ("key_fingerprint", models.CharField(blank=True, max_length=47)),
                (
                    "user_data",
                    models.TextField(
                        blank=True,
                        help_text="Additional data that will be added to instance on provisioning",
                    ),
                ),
                ("start_time", models.DateTimeField(blank=True, null=True)),
                (
                    "transfer",
                    models.PositiveIntegerField(
                        default=0, help_text="Amount of transfer bandwidth in MiB"
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, protocol="IPv4"
                    ),
                ),
                ("region_name", models.CharField(blank=True, max_length=150)),
                ("size_name", models.CharField(blank=True, max_length=150)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="structure.project",
                    ),
                ),
                (
                    "service_settings",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="structure.servicesettings",
                    ),
                ),
            ],
            options={
                "ordering": ["-created", "id"],
                "abstract": False,
            },
            bases=(
                waldur_core.core.models.DescendantMixin,
                waldur_core.core.models.BackendModelMixin,
                waldur_core.structure.models.StructureLoggableMixin,
                models.Model,
                django_fsm.ConcurrentTransitionMixin,
            ),
        ),
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=150,
                        validators=[waldur_core.core.validators.validate_name],
                        verbose_name="name",
                    ),
                ),
                ("uuid", waldur_core.core.fields.UUIDField()),
                ("backend_id", models.CharField(max_length=255, unique=True)),
                ("distribution", models.CharField(max_length=100)),
                ("type", models.CharField(max_length=100)),
                (
                    "is_official",
                    models.BooleanField(
                        default=False, help_text="Is image provided by DigitalOcean"
                    ),
                ),
                (
                    "min_disk_size",
                    models.PositiveIntegerField(
                        help_text="Minimum disk required for a size to use this image",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(null=True)),
                ("regions", models.ManyToManyField(to="waldur_digitalocean.region")),
            ],
            options={
                "abstract": False,
            },
            bases=(waldur_core.core.models.BackendModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name="Size",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=150,
                        validators=[waldur_core.core.validators.validate_name],
                        verbose_name="name",
                    ),
                ),
                ("uuid", waldur_core.core.fields.UUIDField()),
                ("backend_id", models.CharField(max_length=255, unique=True)),
                (
                    "cores",
                    models.PositiveSmallIntegerField(
                        help_text="Number of cores in a VM"
                    ),
                ),
                ("ram", models.PositiveIntegerField(help_text="Memory size in MiB")),
                ("disk", models.PositiveIntegerField(help_text="Disk size in MiB")),
                (
                    "transfer",
                    models.PositiveIntegerField(
                        help_text="Amount of transfer bandwidth in MiB"
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=5,
                        default=0,
                        max_digits=11,
                        verbose_name="Hourly price rate",
                    ),
                ),
                ("regions", models.ManyToManyField(to="waldur_digitalocean.region")),
            ],
            options={
                "abstract": False,
            },
            bases=(waldur_core.core.models.BackendModelMixin, models.Model),
        ),
    ]
