# Generated by Django 6.0.8 on 2026-08-19 21:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("waldur_digitalocean", "0006_alter_droplet_description"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="droplet",
            options={"ordering": ["-created", "id"]},
        ),
    ]
