# Generated by Django 2.2.10 on 2020-04-23 06:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('structure', '0010_customer_geolocation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='agreement_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
