# Generated by Django 2.2.13 on 2020-09-08 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0013_extend_description_limits'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='type',
        ),
    ]
