# Generated by Django 2.2.13 on 2021-01-11 10:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('structure', '0017_remove_customer_is_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicesettings',
            name='is_active',
            field=models.BooleanField(
                default=True,
                help_text='Information about inactive service settings will not be updated in the background',
            ),
        ),
    ]
