# Generated by Django 3.2.12 on 2022-04-22 11:25

import netfields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0028_project_is_industry'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='inet',
            field=netfields.fields.CidrAddressField(
                blank=True, max_length=43, null=True
            ),
        ),
    ]
