# Generated by Django 2.2.24 on 2021-12-29 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0029_customer_inet'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
