# Generated by Django 3.2.13 on 2022-06-30 18:43

from django.db import migrations, models

import waldur_core.media.models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0030_customer_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=waldur_core.media.models.get_upload_path,
            ),
        ),
    ]
