# Generated by Django 3.2.14 on 2022-09-05 12:46

import django.utils.timezone
import model_utils.fields
from django.db import migrations, models

import waldur_core.logging.loggers


class Migration(migrations.Migration):
    dependencies = [
        ('structure', '0031_project_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAgreement',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'created',
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name='created',
                    ),
                ),
                (
                    'modified',
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name='modified',
                    ),
                ),
                ('content', models.TextField(blank=True)),
                (
                    'agreement_type',
                    models.CharField(
                        choices=[
                            ('TOS', 'Terms of services'),
                            ('PP', 'Privacy policy'),
                        ],
                        max_length=5,
                        unique=True,
                    ),
                ),
            ],
            options={
                'ordering': ['created'],
            },
            bases=(waldur_core.logging.loggers.LoggableMixin, models.Model),
        ),
    ]
