# Generated by Django 3.2.16 on 2022-12-07 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0036_remove_notification_and_notification_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='agreement_number',
            field=models.CharField(blank=True, default='', max_length=160),
        ),
    ]
