# Generated by Django 4.2.14 on 2024-08-06 09:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("structure", "0045_customer_slug_project_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="start_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
