# Generated by Django 6.0.2 on 2026-03-19 13:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("structure", "0045_projectenddatechangerequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectenddatechangerequest",
            name="comment",
            field=models.TextField(
                blank=True, help_text="Optional comment from the requester", null=True
            ),
        ),
    ]
