# Generated by Django 4.2.17 on 2025-01-08 14:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("structure", "0047_alter_customer_phone_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="organization_groups",
            field=models.ManyToManyField(
                blank=True, related_name="customers", to="structure.organizationgroup"
            ),
        ),
    ]
