# Generated by Django 4.2.23 on 2025-09-09 17:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("structure", "0058_project_kind"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="description",
            field=models.CharField(
                blank=True, max_length=2000, verbose_name="description"
            ),
        ),
    ]
