# Generated by Django 4.2.24 on 2025-10-07 08:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("structure", "0061_customer_notification_emails"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="display_billing_info_in_projects",
            field=models.BooleanField(default=True),
        ),
    ]
