# Generated by Django 4.2.24 on 2025-10-20 10:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("structure", "0062_customer_display_billing_info_in_projects"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accesssubnet",
            name="description",
            field=models.CharField(
                blank=True, max_length=4096, verbose_name="description"
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="description",
            field=models.CharField(
                blank=True, max_length=4096, verbose_name="description"
            ),
        ),
        migrations.AlterField(
            model_name="externallink",
            name="description",
            field=models.CharField(
                blank=True, max_length=4096, verbose_name="description"
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="description",
            field=models.CharField(
                blank=True, max_length=4096, verbose_name="description"
            ),
        ),
        migrations.AlterField(
            model_name="projecttype",
            name="description",
            field=models.CharField(
                blank=True, max_length=4096, verbose_name="description"
            ),
        ),
    ]
