# Generated by Django 4.2.24 on 2025-10-20 21:00

from django.db import migrations

import waldur_core.core.fields


class Migration(migrations.Migration):
    dependencies = [
        ("structure", "0063_alter_accesssubnet_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="termination_metadata",
            field=waldur_core.core.fields.JSONField(
                blank=True,
                help_text="Metadata captured at project termination for recovery purposes",
                null=True,
            ),
        ),
    ]
