# Generated by Django 4.2.24 on 2025-11-10 21:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("structure", "0066_alter_accesssubnet_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="grace_period_days",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Number of extra days after project end date before resources are terminated",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="grace_period_days",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Number of extra days after project end date before resources are terminated. Overrides customer-level setting.",
                null=True,
            ),
        ),
    ]
