# Generated by Django 4.2.24 on 2025-12-25 12:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("structure", "0068_add_user_restrictions"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="user_identity_sources",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of allowed identity sources (identity providers).",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="user_identity_sources",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of allowed identity sources (identity providers).",
            ),
        ),
    ]
