# Generated by Django 6.0.4 on 2026-04-10 21:58

import django.utils.timezone
import model_utils.fields
from django.db import migrations, models

import waldur_core.core.fields
import waldur_core.core.validators


class Migration(migrations.Migration):
    dependencies = [
        ("structure", "0048_customer_apartment_nr_customer_city_and_more"),
        ("structure", "0049_migrate_organization_groups"),
        ("structure", "0073_alter_projectdigestconfiguration_uuid"),
    ]

    operations = [
        migrations.CreateModel(
            name="AffiliatedOrganization",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=4096, verbose_name="description"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=150,
                        validators=[waldur_core.core.validators.validate_name],
                        verbose_name="name",
                    ),
                ),
                ("uuid", waldur_core.core.fields.UUIDField()),
                (
                    "code",
                    models.CharField(
                        help_text="Unique short identifier, e.g. CERN, EMBL.",
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("abbreviation", models.CharField(blank=True, max_length=12)),
                ("email", models.EmailField(blank=True, max_length=75)),
                ("homepage", models.URLField(blank=True, max_length=255)),
                ("country", models.CharField(blank=True, max_length=2)),
                ("address", models.CharField(blank=True, max_length=300)),
            ],
            options={
                "verbose_name": "affiliated organization",
                "ordering": ("name",),
            },
        ),
        migrations.AddField(
            model_name="project",
            name="affiliated_organizations",
            field=models.ManyToManyField(
                blank=True,
                related_name="projects",
                to="structure.affiliatedorganization",
            ),
        ),
    ]
