# Generated by Django 6.0.4 on 2026-04-20 08:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("structure", "0074_affiliatedorganization"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="project_slug_template",
            field=models.CharField(
                blank=True,
                help_text="Template for project slugs. Supports: {customer_slug}, {project_name}, {year}, {month}, {counter}, {counter_padded}. Default: slugified project name",
                max_length=255,
                null=True,
            ),
        ),
    ]
