# Generated by Django 6.0.4 on 2026-04-24 06:54

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import waldur_core.core.fields
import waldur_core.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("structure", "0075_customer_project_slug_template"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScienceDomain",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=150,
                        validators=[waldur_core.core.validators.validate_name],
                        verbose_name="name",
                    ),
                ),
                ("uuid", waldur_core.core.fields.UUIDField()),
                (
                    "code",
                    models.CharField(
                        blank=True,
                        help_text="Domain code (e.g. '1'). Auto-derived if left blank.",
                        max_length=20,
                        verbose_name="code",
                    ),
                ),
            ],
            options={
                "verbose_name": "science domain",
                "ordering": ("code", "name"),
            },
        ),
        migrations.CreateModel(
            name="ScienceSubDomain",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=150,
                        validators=[waldur_core.core.validators.validate_name],
                        verbose_name="name",
                    ),
                ),
                ("uuid", waldur_core.core.fields.UUIDField()),
                (
                    "code",
                    models.CharField(
                        blank=True,
                        help_text="Sub-domain code (e.g. '1.1'). Auto-derived from domain code if left blank.",
                        max_length=20,
                        verbose_name="code",
                    ),
                ),
                (
                    "domain",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subdomains",
                        to="structure.sciencedomain",
                    ),
                ),
            ],
            options={
                "verbose_name": "science sub-domain",
                "ordering": ("code", "name"),
            },
        ),
        migrations.AddField(
            model_name="project",
            name="science_sub_domain",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="projects",
                to="structure.sciencesubdomain",
                verbose_name="science sub-domain",
            ),
        ),
    ]
