# Generated by Django 6.0.8 on 2026-08-20 07:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("structure", "0082_project_display_credit_reports"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customerpermissionreview",
            options={"ordering": ["-created", "id"]},
        ),
        migrations.AlterModelOptions(
            name="projectpermissionreview",
            options={"ordering": ["-created", "id"]},
        ),
    ]
