# Generated by Django 6.0.8 on 2026-08-25 11:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("structure", "0084_alter_accesssubnet_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="display_credit_reports",
        ),
    ]
