- role: CUSTOMER.OWNER
  description: Organization owner
  scope: customer
  permissions:
    - OFFERING.CREATE
    - OFFERING.DELETE
    - OFFERING.UPDATE
    - OFFERING.UPDATE_THUMBNAIL
    - OFFERING.UPDATE_ATTRIBUTES
    - OFFERING.UPDATE_LOCATION
    - OFFERING.UPDATE_DESCRIPTION
    - OFFERING.UPDATE_OPTIONS
    - OFFERING.UPDATE_INTEGRATION
    - OFFERING.ADD_ENDPOINT
    - OFFERING.DELETE_ENDPOINT
    - OFFERING.UPDATE_COMPONENTS
    - OFFERING.PAUSE
    - OFFERING.UNPAUSE
    - OFFERING.ARCHIVE
    - OFFERING.DRY_RUN_SCRIPT
    - OFFERING.MANAGE_CAMPAIGN
    - OFFERING.MANAGE_USER_GROUP
    - OFFERING.CREATE_PLAN
    - OFFERING.UPDATE_PLAN
    - OFFERING.ARCHIVE_PLAN
    - OFFERING.CREATE_SCREENSHOT
    - OFFERING.UPDATE_SCREENSHOT
    - OFFERING.DELETE_SCREENSHOT
    - OFFERING.CREATE_USER
    - OFFERING.UPDATE_USER
    - OFFERING.DELETE_USER
    - OFFERING.MANAGE_USER_ROLE
    - POSIX_ID_POOL.MANAGE
    - RESOURCE.MANAGE_USERS
    - RESOURCE.CREATE_PERMISSION
    - RESOURCE.UPDATE_PERMISSION
    - RESOURCE.DELETE_PERMISSION
    - RESOURCE_PROJECT.CREATE_PERMISSION
    - RESOURCE_PROJECT.UPDATE_PERMISSION
    - RESOURCE_PROJECT.DELETE_PERMISSION
    - ORDER.LIST
    - ORDER.CREATE
    - ORDER.APPROVE
    - ORDER.APPROVE_PRIVATE
    - ORDER.REJECT
    - ORDER.DESTROY
    - ORDER.CANCEL
    - ORDER.SET_CONSUMER_INFO
    - CUSTOMER.CONTACT_UPDATE
    - RESOURCE.LIST
    - RESOURCE.UPDATE
    - RESOURCE.SET_END_DATE
    - RESOURCE.SET_USAGE
    - RESOURCE.SET_PLAN
    - RESOURCE.UPDATE_OPTIONS
    - RESOURCE.SET_LIMITS
    - RESOURCE.SET_BACKEND_ID
    - RESOURCE.SET_BACKEND_METADATA
    - RESOURCE.SET_STATE
    - RESOURCE.ACCEPT_BOOKING_REQUEST
    - RESOURCE.REJECT_BOOKING_REQUEST
    - RESOURCE.SUBMIT_REPORT
    - RESOURCE.TERMINATE
    - RESOURCE.LIST_IMPORTABLE
    - RESOURCE.CREATE_ROBOT_ACCOUNT
    - RESOURCE.UPDATE_ROBOT_ACCOUNT
    - RESOURCE.DELETE_ROBOT_ACCOUNT
    - OFFERING.MANAGE_BACKEND_RESOURCES
    - INVITATION.LIST
    - PROJECT.CREATE_PERMISSION
    - PROJECT.UPDATE_PERMISSION
    - PROJECT.DELETE_PERMISSION
    - PROJECT.COURSE_ACCOUNT_MANAGE
    - OFFERING.CREATE_PERMISSION
    - OFFERING.UPDATE_PERMISSION
    - OFFERING.DELETE_PERMISSION
    - PROJECT.LIST
    - PROJECT.CREATE
    - PROJECT.UPDATE
    - PROJECT.DELETE
    - OFFERING.ACCEPT_CALL_REQUEST
    - CUSTOMER.CREATE_PERMISSION
    - CUSTOMER.UPDATE_PERMISSION
    - CUSTOMER.DELETE_PERMISSION
    - CUSTOMER.LIST_PERMISSION_REVIEWS
    - CUSTOMER.LIST_USERS
    - CALL.APPROVE_AND_REJECT_PROPOSALS
    - CALL.CLOSE_ROUNDS
    - CALL.CREATE_PERMISSION
    - CALL.UPDATE_PERMISSION
    - CALL.DELETE_PERMISSION
    - ACCESS_SUBNET.CREATE
    - ACCESS_SUBNET.UPDATE
    - ACCESS_SUBNET.DELETE
    - RESOURCE_ACCESS_SUBNET.CREATE
    - RESOURCE_ACCESS_SUBNET.UPDATE
    - RESOURCE_ACCESS_SUBNET.DELETE
    - OFFERINGUSER.UPDATE_RESTRICTION
    - RESOURCE.CONSUMPTION_LIMITATION
    - SERVICE_PROVIDER.GET_API_SECRET_CODE
    - SERVICE_PROVIDER.GENERATE_API_SECRET_CODE
    - SERVICE_PROVIDER.LIST_CUSTOMERS
    - SERVICE_PROVIDER.LIST_CUSTOMER_PROJECTS
    - SERVICE_PROVIDER.LIST_PROJECTS
    - SERVICE_PROVIDER.LIST_PROJECT_PERMISSIONS
    - SERVICE_PROVIDER.LIST_KEYS
    - SERVICE_PROVIDER.LIST_USERS
    - SERVICE_PROVIDER.LIST_USER_CUSTOMERS
    - SERVICE_PROVIDER.LIST_SERVICE_ACCOUNTS
    - SERVICE_PROVIDER.LIST_COURSE_ACCOUNTS
    - SERVICE_PROVIDER.SET_OFFERINGS_USERNAME
    - SERVICE_PROVIDER.GET_STATISTICS
    - SERVICE_PROVIDER.GET_REVENUE
    - SERVICE_PROVIDER.GET_ROBOT_ACCOUNT_CUSTOMERS
    - SERVICE_PROVIDER.GET_ROBOT_ACCOUNT_PROJECTS
    - SERVICE_ACCOUNT.MANAGE
    - OPENSTACK_INSTANCE.CONSOLE_ACCESS
    - OPENSTACK_INSTANCE.MANAGE_POWER
    - OPENSTACK_INSTANCE.MANAGE

- role: CUSTOMER.MANAGER
  is_active: true
  scope: service_provider
  description: Service provider manager
  permissions:
    - RESOURCE.SET_END_DATE
    - RESOURCE.SET_BACKEND_ID
    - RESOURCE.SET_BACKEND_METADATA
    - RESOURCE.SET_STATE
    - RESOURCE.ACCEPT_BOOKING_REQUEST
    - RESOURCE.REJECT_BOOKING_REQUEST
    - RESOURCE.SUBMIT_REPORT
    - RESOURCE.CREATE_ROBOT_ACCOUNT
    - RESOURCE.UPDATE_ROBOT_ACCOUNT
    - RESOURCE.DELETE_ROBOT_ACCOUNT
    - OFFERING.MANAGE_BACKEND_RESOURCES
    - OFFERING.CREATE
    - OFFERING.DELETE
    - OFFERING.UPDATE_THUMBNAIL
    - OFFERING.UPDATE_ATTRIBUTES
    - OFFERING.UPDATE_LOCATION
    - OFFERING.UPDATE_DESCRIPTION
    - OFFERING.UPDATE
    - OFFERING.UPDATE_OPTIONS
    - OFFERING.UPDATE_INTEGRATION
    - OFFERING.ADD_ENDPOINT
    - OFFERING.DELETE_ENDPOINT
    - OFFERING.UPDATE_COMPONENTS
    - OFFERING.PAUSE
    - OFFERING.UNPAUSE
    - OFFERING.ARCHIVE
    - OFFERING.DRY_RUN_SCRIPT
    - OFFERING.MANAGE_CAMPAIGN
    - OFFERING.MANAGE_USER_GROUP
    - OFFERING.CREATE_PLAN
    - OFFERING.UPDATE_PLAN
    - OFFERING.ARCHIVE_PLAN
    - OFFERING.CREATE_SCREENSHOT
    - OFFERING.UPDATE_SCREENSHOT
    - OFFERING.DELETE_SCREENSHOT
    - OFFERING.CREATE_USER
    - OFFERING.UPDATE_USER
    - OFFERING.DELETE_USER
    - POSIX_ID_POOL.MANAGE
    - OFFERINGUSER.UPDATE_RESTRICTION
    - RESOURCE.CONSUMPTION_LIMITATION
    - SERVICE_PROVIDER.GET_API_SECRET_CODE
    - SERVICE_PROVIDER.GENERATE_API_SECRET_CODE
    - SERVICE_PROVIDER.LIST_CUSTOMERS
    - SERVICE_PROVIDER.LIST_CUSTOMER_PROJECTS
    - SERVICE_PROVIDER.LIST_PROJECTS
    - SERVICE_PROVIDER.LIST_PROJECT_PERMISSIONS
    - SERVICE_PROVIDER.LIST_KEYS
    - SERVICE_PROVIDER.LIST_USERS
    - SERVICE_PROVIDER.LIST_USER_CUSTOMERS
    - SERVICE_PROVIDER.LIST_SERVICE_ACCOUNTS
    - SERVICE_PROVIDER.LIST_COURSE_ACCOUNTS
    - SERVICE_PROVIDER.SET_OFFERINGS_USERNAME
    - SERVICE_PROVIDER.GET_STATISTICS
    - SERVICE_PROVIDER.GET_REVENUE
    - SERVICE_PROVIDER.GET_ROBOT_ACCOUNT_CUSTOMERS
    - SERVICE_PROVIDER.GET_ROBOT_ACCOUNT_PROJECTS
    - SERVICE_ACCOUNT.MANAGE
    - PROJECT.COURSE_ACCOUNT_MANAGE
    - SERVICE_PROVIDER.OPENSTACK_IMAGE_MANAGEMENT

- role: PROJECT.ADMIN
  description: Project administrator
  scope: project
  permissions:
    - PROJECT.LIST
    - INVITATION.LIST
    - ORDER.APPROVE_PRIVATE
    - ORDER.DESTROY
    - ORDER.CANCEL
    - ORDER.LIST
    - ORDER.CREATE
    - RESOURCE.LIST
    - RESOURCE.UPDATE
    - RESOURCE.TERMINATE
    - RESOURCE.LIST_IMPORTABLE
    - RESOURCE.SET_PLAN
    - RESOURCE.SET_LIMITS
    - RESOURCE.CREATE_PERMISSION
    - RESOURCE.UPDATE_PERMISSION
    - RESOURCE.DELETE_PERMISSION
    - RESOURCE_ACCESS_SUBNET.CREATE
    - RESOURCE_ACCESS_SUBNET.UPDATE
    - RESOURCE_ACCESS_SUBNET.DELETE
    - RESOURCE_PROJECT.CREATE_PERMISSION
    - RESOURCE_PROJECT.UPDATE_PERMISSION
    - RESOURCE_PROJECT.DELETE_PERMISSION
    - OPENSTACK_INSTANCE.CONSOLE_ACCESS
    - OPENSTACK_INSTANCE.MANAGE_POWER
    - OPENSTACK_INSTANCE.MANAGE

- role: PROJECT.MANAGER
  description: Project manager
  scope: project
  permissions:
    - PROJECT.LIST
    - INVITATION.LIST
    - ORDER.APPROVE_PRIVATE
    - ORDER.DESTROY
    - ORDER.CANCEL
    - ORDER.LIST
    - ORDER.CREATE
    - ORDER.SET_CONSUMER_INFO
    - RESOURCE.LIST
    - RESOURCE.UPDATE
    - RESOURCE.TERMINATE
    - RESOURCE.LIST_IMPORTABLE
    - RESOURCE.SET_PLAN
    - RESOURCE.SET_LIMITS
    - RESOURCE.CREATE_PERMISSION
    - RESOURCE.UPDATE_PERMISSION
    - RESOURCE.DELETE_PERMISSION
    - RESOURCE_ACCESS_SUBNET.CREATE
    - RESOURCE_ACCESS_SUBNET.UPDATE
    - RESOURCE_ACCESS_SUBNET.DELETE
    - RESOURCE_PROJECT.CREATE_PERMISSION
    - RESOURCE_PROJECT.UPDATE_PERMISSION
    - RESOURCE_PROJECT.DELETE_PERMISSION
    - PROJECT.CREATE_PERMISSION
    - PROJECT.UPDATE_PERMISSION
    - PROJECT.DELETE_PERMISSION
    - PROJECT.UPDATE
    - SERVICE_ACCOUNT.MANAGE
    - PROJECT.COURSE_ACCOUNT_MANAGE
    - PROJECT.REVIEW_MEMBERSHIP
    - OPENSTACK_INSTANCE.CONSOLE_ACCESS
    - OPENSTACK_INSTANCE.MANAGE_POWER
    - OPENSTACK_INSTANCE.MANAGE

- role: OFFERING.MANAGER
  description: Offering manager
  scope: offering
  permissions:
    - OFFERING.UPDATE
    - OFFERING.UPDATE_ATTRIBUTES
    - OFFERING.UPDATE_LOCATION
    - OFFERING.UPDATE_DESCRIPTION
    - OFFERING.UPDATE_OPTIONS
    - OFFERING.UPDATE_INTEGRATION
    - OFFERING.ADD_ENDPOINT
    - OFFERING.DELETE_ENDPOINT
    - OFFERING.UPDATE_COMPONENTS
    - OFFERING.PAUSE
    - OFFERING.UNPAUSE
    - OFFERING.ARCHIVE
    - OFFERING.DRY_RUN_SCRIPT
    - OFFERING.CREATE_USER
    - OFFERING.UPDATE_USER
    - OFFERING.DELETE_USER
    - ORDER.LIST
    - ORDER.APPROVE
    - RESOURCE.SET_USAGE
    - RESOURCE.SET_BACKEND_ID
    - RESOURCE.SET_BACKEND_METADATA
    - RESOURCE.SET_STATE
    - RESOURCE.ACCEPT_BOOKING_REQUEST
    - RESOURCE.REJECT_BOOKING_REQUEST
    - OFFERING.MANAGE_BACKEND_RESOURCES
    - OFFERING.ACCEPT_CALL_REQUEST

- role: CALL.REVIEWER
  description: Call reviewer
  scope: call
  permissions:
    - PROPOSAL.LIST

- role: CALL.PANEL_MEMBER
  description: Call panel member
  scope: call
  permissions:
    - PROPOSAL.LIST

- role: CUSTOMER.SUPPORT
  is_active: false
  description: Organization support
  scope: customer
  permissions:
    - CUSTOMER.LIST_USERS

- role: CALL.MANAGER
  description: Call manager
  scope: call
  permissions:
    - CALL.APPROVE_AND_REJECT_PROPOSALS
    - CALL.CLOSE_ROUNDS
    - CALL.CREATE_PERMISSION
    - CALL.UPDATE_PERMISSION
    - CALL.DELETE_PERMISSION
    - CALL.LIST
    - CALL.UPDATE
    - ROUND.LIST
    - PROPOSAL.LIST
    - PROPOSAL.MANAGE_REVIEW

- role: PROPOSAL.MANAGER
  description: Proposal manager
  scope: proposal
  permissions:
    - PROPOSAL.MANAGE

- role: PROPOSAL.MEMBER
  description: Proposal member
  scope: proposal
  permissions: []

- role: PROJECT.MEMBER
  description: Project member
  scope: project
  is_active: false
  permissions:
    - RESOURCE.LIST
    - PROJECT.LIST
    - ORDER.CREATE

- role: CUSTOMER.READER
  description: Organization reader
  scope: customer
  permissions: []

- role: CUSTOMER.CALL_ORGANIZER
  scope: call_organizer
  description: Organization call organizer
  permissions:
    - CALL.APPROVE_AND_REJECT_PROPOSALS
    - CALL.CLOSE_ROUNDS
    - CALL.CREATE_PERMISSION
    - CALL.UPDATE_PERMISSION
    - CALL.DELETE_PERMISSION
    - CALL.LIST
    - CALL.CREATE
    - CALL.UPDATE
    - ROUND.LIST
    - PROPOSAL.LIST
    - PROPOSAL.MANAGE_REVIEW
