# Generated by Django 6.0.8 on 2026-09-16 16:05

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models

import waldur_core.core.fields
import waldur_core.core.validators


class Migration(migrations.Migration):
    dependencies = [
        ("permissions", "0028_userrole_source"),
        ("waldur_sram", "0003_sramgroup_role"),
    ]

    operations = [
        migrations.CreateModel(
            name="SramProjectRule",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=150,
                        validators=[waldur_core.core.validators.validate_name],
                        verbose_name="name",
                    ),
                ),
                ("uuid", waldur_core.core.fields.UUIDField()),
                (
                    "source_kind",
                    models.CharField(
                        choices=[
                            ("co", "Collaboration"),
                            ("group", "Group"),
                            ("any", "Any"),
                        ],
                        default="co",
                        max_length=16,
                    ),
                ),
                (
                    "labels",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="The collaboration must carry one of these labels. A group is judged by its collaboration's labels. Empty matches any.",
                    ),
                ),
                (
                    "group_short_name_patterns",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Group short names to match; a trailing '*' matches by prefix. Empty matches any. Setting it restricts the rule to groups.",
                    ),
                ),
                (
                    "project_field",
                    models.CharField(
                        choices=[("backend_id", "Backend ID"), ("slug", "Slug")],
                        default="backend_id",
                        max_length=16,
                    ),
                ),
                (
                    "project_match",
                    models.CharField(
                        choices=[
                            ("exact", "Exact"),
                            ("prefix", "Prefix"),
                            ("regex", "Regular expression"),
                        ],
                        default="prefix",
                        max_length=16,
                    ),
                ),
                (
                    "project_pattern",
                    models.CharField(
                        default="{co_external_id}_",
                        help_text="Placeholders: {co_external_id}, {co_identifier}, {co_short_name}, {org_short_name}, {group_short_name}.",
                        max_length=255,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "project_role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="permissions.role",
                    ),
                ),
            ],
            options={
                "ordering": ["name", "id"],
            },
        ),
    ]
