from django.urls import re_path

from waldur_mastermind.marketplace import views


def register_in(router):
    router.register(
        r"marketplace-service-providers",
        views.ServiceProviderViewSet,
        basename="marketplace-service-provider",
    )
    router.register(
        r"marketplace-categories",
        views.CategoryViewSet,
        basename="marketplace-category",
    )
    router.register(
        r"marketplace-category-columns",
        views.CategoryColumnsViewSet,
        basename="marketplace-category-columns",
    )
    router.register(
        r"marketplace-category-groups",
        views.CategoryGroupViewSet,
        basename="marketplace-category-group",
    )
    router.register(
        r"marketplace-offering-groups",
        views.OfferingGroupViewSet,
        basename="marketplace-offering-group",
    )
    router.register(
        r"marketplace-posix-id-pools",
        views.PosixIdPoolViewSet,
        basename="marketplace-posix-id-pool",
    )
    router.register(
        r"marketplace-posix-identities",
        views.PosixIdentityViewSet,
        basename="marketplace-posix-identity",
    )
    router.register(
        r"marketplace-tags",
        views.TagViewSet,
        basename="marketplace-tag",
    )
    router.register(
        r"marketplace-provider-offerings",
        views.ProviderOfferingViewSet,
        basename="marketplace-provider-offering",
    )
    router.register(
        r"marketplace-offering-permissions",
        views.OfferingPermissionViewSet,
        basename="marketplace-offering-permission",
    )
    router.register(
        r"marketplace-offering-permissions-log",
        views.OfferingPermissionLogViewSet,
        basename="marketplace-offering-permission_log",
    )
    router.register(
        r"marketplace-plans", views.ProviderPlanViewSet, basename="marketplace-plan"
    )
    router.register(
        r"marketplace-plan-components",
        views.PlanComponentViewSet,
        basename="marketplace-plan-component",
    )
    router.register(
        r"marketplace-screenshots",
        views.ScreenshotViewSet,
        basename="marketplace-screenshot",
    )
    router.register(
        r"marketplace-orders",
        views.OrderViewSet,
        basename="marketplace-order",
    )
    router.register(
        r"marketplace-resources",
        views.ConsumerResourceViewSet,
        basename="marketplace-resource",
    )
    router.register(
        r"marketplace-provider-resources",
        views.ProviderResourceViewSet,
        basename="marketplace-provider-resource",
    )
    router.register(
        r"marketplace-category-component-usages",
        views.CategoryComponentUsageViewSet,
        basename="marketplace-category-component-usage",
    )
    router.register(
        r"marketplace-component-usages",
        views.ComponentUsageViewSet,
        basename="marketplace-component-usage",
    )
    router.register(
        r"marketplace-component-user-usages",
        views.ComponentUserUsageViewSet,
        basename="marketplace-component-user-usage",
    )
    router.register(
        r"marketplace-component-usage-monthly",
        views.ComponentUsageMonthlyViewSet,
        basename="marketplace-component-usage-monthly",
    )
    router.register(
        r"marketplace-public-api",
        views.MarketplaceAPIViewSet,
        basename="marketplace-public-api",
    )
    router.register(
        r"marketplace-offering-files",
        views.OfferingFileViewSet,
        basename="marketplace-offering-file",
    )
    router.register(
        r"marketplace-offering-referrals",
        views.OfferingReferralsViewSet,
        basename="marketplace-offering-referral",
    )
    router.register(
        r"marketplace-offering-users",
        views.OfferingUsersViewSet,
        basename="marketplace-offering-user",
    )
    router.register(
        r"marketplace-offering-user-checklist-completions",
        views.OfferingUserChecklistCompletionsViewSet,
        basename="marketplace-offering-user-checklist-completion",
    )
    router.register(
        r"marketplace-stats",
        views.StatsViewSet,
        basename="marketplace-stats",
    )
    router.register(
        r"marketplace-project-posix-groups",
        views.ProjectPosixGroupsViewSet,
        basename="marketplace-project-posix-group",
    )
    router.register(
        r"marketplace-customer-usage",
        views.MarketplaceCustomerUsageViewSet,
        basename="marketplace-customer-usage",
    )
    router.register(
        r"marketplace-project-usage",
        views.MarketplaceProjectUsageViewSet,
        basename="marketplace-project-usage",
    )
    router.register(
        r"provider-invoice-items",
        views.ProviderInvoiceItemsViewSet,
        basename="provider-invoice-items",
    )
    router.register(
        r"marketplace-public-offerings",
        views.PublicOfferingViewSet,
        basename="marketplace-public-offering",
    )
    router.register(
        r"marketplace-robot-accounts",
        views.RobotAccountViewSet,
        basename="marketplace-robot-account",
    )
    router.register(
        r"marketplace-project-service-accounts",
        views.ProjectServiceAccountViewSet,
        basename="marketplace-project-service-account",
    )
    router.register(
        r"marketplace-project-order-auto-approvals",
        views.ProjectOrderAutoApprovalViewSet,
        basename="marketplace-project-order-auto-approval",
    )
    router.register(
        r"marketplace-customer-service-accounts",
        views.CustomerServiceAccountViewSet,
        basename="marketplace-customer-service-account",
    )
    router.register(
        r"marketplace-sections",
        views.SectionViewSet,
        basename="marketplace-section",
    )
    router.register(
        r"marketplace-attributes",
        views.AttributeViewSet,
        basename="marketplace-attribute",
    )
    router.register(
        r"marketplace-attribute-options",
        views.AttributeOptionViewSet,
        basename="marketplace-attribute-option",
    )
    router.register(
        r"marketplace-category-help-articles",
        views.CategoryHelpArticleViewSet,
        basename="marketplace-category-help-articles",
    )
    router.register(
        r"marketplace-category-components",
        views.CategoryComponentViewSet,
        basename="marketplace-category-component",
    )
    router.register(
        r"marketplace-integration-statuses",
        views.IntegrationStatusViewSet,
        basename="marketplace-integration-status",
    )
    router.register(
        r"component-user-usage-limits",
        views.ComponentUserUsageLimitViewSet,
        basename="component-user-usage-limit",
    )
    router.register(
        r"backend-resources",
        views.BackendResourceViewSet,
        basename="backend-resource",
    )
    router.register(
        r"backend-resource-requests",
        views.BackendResourceRequestViewSet,
        basename="backend-resource-request",
    )
    router.register(
        r"maintenance-announcements",
        views.MaintenanceAnnouncementViewSet,
        basename="maintenance-announcement",
    )
    router.register(
        r"public-maintenance-announcements",
        views.PublicMaintenanceAnnouncementViewSet,
        basename="public-maintenance-announcement",
    )
    router.register(
        r"maintenance-announcement-offerings",
        views.MaintenanceAnnouncementOfferingViewSet,
        basename="maintenance-announcement-offering",
    )
    router.register(
        r"maintenance-announcements-template",
        views.MaintenanceAnnouncementTemplateViewSet,
        basename="maintenance-announcement-template",
    )
    router.register(
        r"maintenance-announcement-template-offerings",
        views.MaintenanceAnnouncementOfferingTemplateViewSet,
        basename="maintenance-announcement-template-offering",
    )
    router.register(
        r"marketplace-user-offering-consents",
        views.UserOfferingConsentViewSet,
        basename="marketplace-user-offering-consent",
    )
    router.register(
        r"marketplace-offering-terms-of-service",
        views.ProviderOfferingToSManagementViewset,
        basename="marketplace-offering-terms-of-service",
    )
    router.register(
        r"marketplace-course-accounts",
        views.CourseAccountViewSet,
        basename="marketplace-course-account",
    )
    router.register(
        r"marketplace-software-catalogs",
        views.SoftwareCatalogViewSet,
        basename="marketplace-software-catalog",
    )
    router.register(
        r"marketplace-software-packages",
        views.SoftwarePackageViewSet,
        basename="marketplace-software-package",
    )
    router.register(
        r"marketplace-software-versions",
        views.SoftwareVersionViewSet,
        basename="marketplace-software-version",
    )
    router.register(
        r"marketplace-software-targets",
        views.SoftwareTargetViewSet,
        basename="marketplace-software-target",
    )
    router.register(
        r"marketplace-demo-presets",
        views.DemoPresetViewSet,
        basename="marketplace-demo-preset",
    )
    router.register(
        r"marketplace-article-code-update",
        views.ArticleCodeUpdateViewSet,
        basename="marketplace-article-code-update",
    )

    # Resource projects (nested under resources)
    router.register(
        r"marketplace-resource-projects",
        views.ConsumerResourceProjectViewSet,
        basename="marketplace-resource-project",
    )
    router.register(
        r"marketplace-provider-resource-projects",
        views.ProviderResourceProjectViewSet,
        basename="marketplace-provider-resource-project",
    )
    router.register(
        r"marketplace-offering-roles",
        views.OfferingRoleViewSet,
        basename="marketplace-offering-role",
    )
    router.register(
        r"marketplace-offering-profiles",
        views.OfferingProfileViewSet,
        basename="marketplace-offering-profile",
    )
    router.register(
        r"marketplace-resource-limit-change-requests",
        views.ResourceLimitChangeRequestViewSet,
        basename="marketplace-resource-limit-change-request",
    )


urlpatterns = [
    re_path(r"^api/marketplace-plugins/$", views.PluginViewSet.as_view()),
    re_path(
        r"^api/marketplace-resource-offerings/(?P<category_uuid>[a-f0-9]+)/$",
        views.ResourceOfferingsViewSet.as_view(),
    ),
    re_path(
        r"^api/marketplace-runtime-states/$",
        views.RuntimeStatesViewSet.as_view(),
        name="marketplace-runtime-states-list",
    ),
    re_path(
        r"^api/marketplace-related-customers/(?P<customer_uuid>[a-f0-9]+)/$",
        views.RelatedCustomersViewSet.as_view(),
    ),
    re_path(
        r"^api/marketplace-public-offerings/(?P<uuid>[a-f0-9]+)/plans/(?P<plan_uuid>[a-f0-9]+)/$",
        views.PublicOfferingViewSet.as_view({"get": "plan_detail"}),
        name="marketplace-public-offering-plan-detail",
    ),
    re_path(
        r"^api/marketplace-provider-offerings/(?P<uuid>[a-f0-9]+)/orders/(?P<order_uuid>[a-f0-9]+)/$",
        views.ProviderOfferingViewSet.as_view({"get": "order_detail"}),
        name="marketplace-provider-offering-order-detail",
    ),
    re_path(
        r"^api/marketplace-global-categories/$",
        views.GlobalCategoriesViewSet.as_view(),
    ),
]
