# Generated by Django 6.0.8 on 2026-08-28 11:38

import django.db.models.deletion
import django.utils.timezone
import django_fsm
import model_utils.fields
from django.conf import settings
from django.db import migrations, models

import waldur_core.core.fields
import waldur_core.core.validators


class Migration(migrations.Migration):
    replaces = [
        ("users", "0001_squashed_0012"),
        ("users", "0002_invitation_extra_invitation_text"),
        ("users", "0003_alter_invitation_extra_invitation_text"),
        ("users", "0004_generic_invitation"),
        ("users", "0005_fill_data"),
        ("users", "0006_adjust_invitation_fields"),
        ("users", "0007_invitation_execution_state"),
        ("users", "0008_alter_invitation_state"),
        ("users", "0009_alter_invitation_phone_number"),
        ("users", "0010_clean_duplicate_profile_changed_logs"),
        ("users", "0011_alter_permissionrequest_created_by"),
        ("users", "0012_remove_invitation_tax_number"),
        ("users", "0013_groupinvitation_auto_create_project_and_more"),
        ("users", "0014_alter_invitation_extra_invitation_text"),
        ("users", "0015_alter_groupinvitation_project_name_template"),
        ("users", "0016_groupinvitation_user_affiliations_and_more"),
        ("users", "0017_alter_permissionrequest_review_comment_and_more"),
        ("users", "0018_add_is_public_to_group_invitation"),
        ("users", "0019_add_auto_approve_to_group_invitation"),
        ("users", "0020_add_user_identity_sources"),
        ("users", "0021_change_permission_request_invitation_to_cascade"),
        ("users", "0022_groupinvitation_user_assurance_levels_and_more"),
        ("users", "0023_add_group_invitation_custom_text"),
        ("users", "0024_alter_invitation_extra_invitation_text_max_length"),
        ("users", "0013_custom_project_and_multiple_requests"),
        ("users", "0025_disable_misconfigured_auto_create_project"),
    ]

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("core", "__first__"),
        ("permissions", "0013_alter_rolepermission_unique_together"),
        ("permissions", "0016_userrole_modified_alter_userrole_created"),
        ("structure", "0001_squashed_0036"),
    ]

    operations = [
        migrations.CreateModel(
            name="GroupInvitation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("uuid", waldur_core.core.fields.UUIDField()),
                ("user_affiliations", models.JSONField(blank=True, default=list)),
                ("user_email_patterns", models.JSONField(blank=True, default=list)),
                (
                    "user_identity_sources",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of allowed identity sources (identity providers).",
                    ),
                ),
                (
                    "user_nationalities",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of allowed nationality codes (ISO 3166-1 alpha-2). User must have one of these.",
                    ),
                ),
                (
                    "user_organization_types",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of allowed organization type URNs (SCHAC). User must match one.",
                    ),
                ),
                (
                    "user_assurance_levels",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of required assurance URIs. User must have ALL of these.",
                    ),
                ),
                ("object_id", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "project_name_template",
                    models.CharField(
                        blank=True,
                        help_text="Template for project name. Supports {username}, {email}, {full_name} variables",
                        max_length=255,
                        null=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "is_public",
                    models.BooleanField(
                        default=False,
                        help_text="Allow non-authenticated users to see and accept this invitation. Only staff can create public invitations.",
                    ),
                ),
                (
                    "auto_create_project",
                    models.BooleanField(
                        default=False,
                        help_text="Create project and grant project permissions instead of customer permissions",
                    ),
                ),
                (
                    "auto_approve",
                    models.BooleanField(
                        default=False,
                        help_text="Automatically approve permission requests from users matching email patterns or affiliations",
                    ),
                ),
                (
                    "custom_text",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Custom description text displayed to users viewing this invitation.",
                        max_length=500,
                    ),
                ),
                (
                    "allow_multiple_requests",
                    models.BooleanField(
                        default=False,
                        help_text="Allow users to submit multiple permission requests for this invitation.",
                    ),
                ),
                (
                    "allow_custom_project_details",
                    models.BooleanField(
                        default=False,
                        help_text="Allow users to provide custom project name and description when accepting the invitation. If disabled, the project name is auto-generated from the template.",
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="structure.customer",
                    ),
                ),
                (
                    "project_role",
                    models.ForeignKey(
                        blank=True,
                        help_text="Role to grant in the auto-created project. If not specified, uses invitation.role",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="group_project_invitations",
                        to="permissions.role",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="permissions.role",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Invitation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("uuid", waldur_core.core.fields.UUIDField()),
                ("error_message", models.TextField(blank=True)),
                ("error_traceback", models.TextField(blank=True)),
                (
                    "native_name",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="native name"
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        validators=[waldur_core.core.validators.validate_phone_number],
                        verbose_name="phone number",
                    ),
                ),
                (
                    "organization",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="organization"
                    ),
                ),
                (
                    "job_title",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="job title"
                    ),
                ),
                (
                    "affiliations",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Person's affiliation within organization such as student, faculty, staff.",
                    ),
                ),
                ("object_id", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("project", "Pending project"),
                            ("requested", "Requested"),
                            ("rejected", "Rejected"),
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("canceled", "Canceled"),
                            ("expired", "Expired"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                (
                    "execution_state",
                    django_fsm.FSMField(
                        choices=[
                            ("Scheduled", "Scheduled"),
                            ("Processing", "Processing"),
                            ("OK", "OK"),
                            ("Erred", "Erred"),
                        ],
                        default="Scheduled",
                        max_length=50,
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Invitation link will be sent to this email. Note that user can accept invitation with different email.",
                        max_length=254,
                    ),
                ),
                (
                    "civil_number",
                    models.CharField(
                        blank=True,
                        help_text="Civil number of invited user. If civil number is not defined any user can accept invitation.",
                        max_length=50,
                    ),
                ),
                (
                    "full_name",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="full name"
                    ),
                ),
                (
                    "extra_invitation_text",
                    models.TextField(blank=True, max_length=2000),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="structure.customer",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="permissions.role",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PermissionRequest",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("uuid", waldur_core.core.fields.UUIDField()),
                (
                    "state",
                    django_fsm.FSMIntegerField(
                        choices=[
                            (1, "draft"),
                            (2, "pending"),
                            (3, "approved"),
                            (4, "rejected"),
                            (5, "canceled"),
                        ],
                        default=1,
                    ),
                ),
                (
                    "reviewed_at",
                    models.DateTimeField(
                        blank=True,
                        editable=False,
                        help_text="Timestamp when the review was completed",
                        null=True,
                    ),
                ),
                (
                    "review_comment",
                    models.TextField(
                        blank=True,
                        help_text="Optional comment provided during review",
                        null=True,
                    ),
                ),
                (
                    "project_name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Custom project name provided by user during invitation acceptance.",
                        max_length=500,
                    ),
                ),
                (
                    "project_description",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Custom project description provided by user during invitation acceptance.",
                        max_length=2000,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "invitation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.groupinvitation",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who performed the review",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
