# Generated by Django 6.0.8 on 2026-09-03 15:37

from importlib import import_module

import django.db.models.deletion
import django.utils.timezone
import django_fsm
import model_utils.fields
from django.conf import settings
from django.db import migrations, models

import waldur_core.core.fields
import waldur_core.core.migration_operations
import waldur_core.core.validators


def _original(name):
    """A replaced migration's module: its data code runs from there, unchanged."""
    return import_module(__name__.rpartition(".")[0] + "." + name)


class Migration(migrations.Migration):
    replaces = [
        ("users", "0001_squashed_0012"),
        ("users", "0002_invitation_extra_invitation_text"),
        ("users", "0003_alter_invitation_extra_invitation_text"),
        ("users", "0004_generic_invitation"),
        ("users", "0005_fill_data"),
        ("users", "0006_adjust_invitation_fields"),
        ("users", "0007_invitation_execution_state"),
        ("users", "0008_alter_invitation_state"),
        ("users", "0009_alter_invitation_phone_number"),
        ("users", "0010_clean_duplicate_profile_changed_logs"),
        ("users", "0011_alter_permissionrequest_created_by"),
        ("users", "0012_remove_invitation_tax_number"),
        ("users", "0013_groupinvitation_auto_create_project_and_more"),
        ("users", "0014_alter_invitation_extra_invitation_text"),
        ("users", "0015_alter_groupinvitation_project_name_template"),
        ("users", "0016_groupinvitation_user_affiliations_and_more"),
        ("users", "0017_alter_permissionrequest_review_comment_and_more"),
        ("users", "0018_add_is_public_to_group_invitation"),
        ("users", "0019_add_auto_approve_to_group_invitation"),
        ("users", "0020_add_user_identity_sources"),
        ("users", "0021_change_permission_request_invitation_to_cascade"),
        ("users", "0022_groupinvitation_user_assurance_levels_and_more"),
        ("users", "0023_add_group_invitation_custom_text"),
        ("users", "0024_alter_invitation_extra_invitation_text_max_length"),
        ("users", "0013_custom_project_and_multiple_requests"),
        ("users", "0025_disable_misconfigured_auto_create_project"),
    ]

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("core", "__first__"),
        ("logging", "0028_split_openstack_resource_event_groups"),
        ("permissions", "0013_alter_rolepermission_unique_together"),
        ("permissions", "0016_userrole_modified_alter_userrole_created"),
        ("permissions", "0027_role_description_mk_role_description_sq"),
        ("structure", "0001_squashed_0036"),
    ]

    operations = [
        migrations.CreateModel(
            name="GroupInvitation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("uuid", waldur_core.core.fields.UUIDField()),
                (
                    "customer_role",
                    models.CharField(
                        blank=True,
                        max_length=30,
                        null=True,
                        verbose_name="organization role",
                    ),
                ),
                (
                    "project_role",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("object_id", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="structure.customer",
                        verbose_name="organization",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="structure.project",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="permissions.role",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Invitation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("uuid", waldur_core.core.fields.UUIDField()),
                ("error_message", models.TextField(blank=True)),
                (
                    "customer_role",
                    models.CharField(
                        blank=True,
                        max_length=30,
                        null=True,
                        verbose_name="organization role",
                    ),
                ),
                (
                    "project_role",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("requested", "Requested"),
                            ("rejected", "Rejected"),
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("canceled", "Canceled"),
                            ("expired", "Expired"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Invitation link will be sent to this email. Note that user can accept invitation with different email.",
                        max_length=254,
                    ),
                ),
                (
                    "civil_number",
                    models.CharField(
                        blank=True,
                        help_text="Civil number of invited user. If civil number is not defined any user can accept invitation.",
                        max_length=50,
                    ),
                ),
                (
                    "full_name",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="full name"
                    ),
                ),
                (
                    "job_title",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="job title"
                    ),
                ),
                (
                    "native_name",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="native name"
                    ),
                ),
                (
                    "organization",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="organization"
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="phone number"
                    ),
                ),
                (
                    "tax_number",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="tax number"
                    ),
                ),
                ("error_traceback", models.TextField(blank=True)),
                (
                    "affiliations",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Person's affiliation within organization such as student, faculty, staff.",
                    ),
                ),
                ("extra_invitation_text", models.TextField(blank=True)),
                ("object_id", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="structure.customer",
                        verbose_name="organization",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="structure.project",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="permissions.role",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PermissionRequest",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("uuid", waldur_core.core.fields.UUIDField()),
                (
                    "state",
                    django_fsm.FSMIntegerField(
                        choices=[
                            (1, "draft"),
                            (2, "pending"),
                            (3, "approved"),
                            (4, "rejected"),
                            (5, "canceled"),
                        ],
                        default=1,
                    ),
                ),
                (
                    "reviewed_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                ("review_comment", models.TextField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "invitation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="users.groupinvitation",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        waldur_core.core.migration_operations.FlushDeferredSql(),
        migrations.RunPython(
            code=_original("0005_fill_data").fill_data,
        ),
        migrations.RemoveField(
            model_name="groupinvitation",
            name="customer_role",
        ),
        migrations.RemoveField(
            model_name="groupinvitation",
            name="project",
        ),
        migrations.RemoveField(
            model_name="groupinvitation",
            name="project_role",
        ),
        migrations.RemoveField(
            model_name="invitation",
            name="customer_role",
        ),
        migrations.RemoveField(
            model_name="invitation",
            name="project",
        ),
        migrations.RemoveField(
            model_name="invitation",
            name="project_role",
        ),
        migrations.AddField(
            model_name="invitation",
            name="execution_state",
            field=django_fsm.FSMField(
                choices=[
                    ("Scheduled", "Scheduled"),
                    ("Processing", "Processing"),
                    ("OK", "OK"),
                    ("Erred", "Erred"),
                ],
                default="Scheduled",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="groupinvitation",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="structure.customer"
            ),
        ),
        migrations.AlterField(
            model_name="groupinvitation",
            name="role",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="permissions.role",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="invitation",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="structure.customer"
            ),
        ),
        migrations.AlterField(
            model_name="invitation",
            name="phone_number",
            field=models.CharField(
                blank=True,
                max_length=255,
                validators=[waldur_core.core.validators.validate_phone_number],
                verbose_name="phone number",
            ),
        ),
        migrations.AlterField(
            model_name="invitation",
            name="role",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="permissions.role",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="invitation",
            name="state",
            field=models.CharField(
                choices=[
                    ("project", "Pending project"),
                    ("requested", "Requested"),
                    ("rejected", "Rejected"),
                    ("pending", "Pending"),
                    ("accepted", "Accepted"),
                    ("canceled", "Canceled"),
                    ("expired", "Expired"),
                ],
                default="pending",
                max_length=10,
            ),
        ),
        waldur_core.core.migration_operations.FlushDeferredSql(),
        migrations.RunPython(
            code=_original(
                "0010_clean_duplicate_profile_changed_logs"
            ).clean_duplicate_profile_changed_logs,
        ),
        migrations.RemoveField(
            model_name="invitation",
            name="tax_number",
        ),
        migrations.AddField(
            model_name="groupinvitation",
            name="allow_custom_project_details",
            field=models.BooleanField(
                default=False,
                help_text="Allow users to provide custom project name and description when accepting the invitation. If disabled, the project name is auto-generated from the template.",
            ),
        ),
        migrations.AddField(
            model_name="groupinvitation",
            name="allow_multiple_requests",
            field=models.BooleanField(
                default=False,
                help_text="Allow users to submit multiple permission requests for this invitation.",
            ),
        ),
        migrations.AddField(
            model_name="groupinvitation",
            name="auto_approve",
            field=models.BooleanField(
                default=False,
                help_text="Automatically approve permission requests from users matching email patterns or affiliations",
            ),
        ),
        migrations.AddField(
            model_name="groupinvitation",
            name="auto_create_project",
            field=models.BooleanField(
                default=False,
                help_text="Create project and grant project permissions instead of customer permissions",
            ),
        ),
        migrations.AddField(
            model_name="groupinvitation",
            name="custom_text",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Custom description text displayed to users viewing this invitation.",
                max_length=500,
            ),
        ),
        migrations.AddField(
            model_name="groupinvitation",
            name="is_public",
            field=models.BooleanField(
                default=False,
                help_text="Allow non-authenticated users to see and accept this invitation. Only staff can create public invitations.",
            ),
        ),
        migrations.AddField(
            model_name="groupinvitation",
            name="project_name_template",
            field=models.CharField(
                blank=True,
                help_text="Template for project name. Supports {username}, {email}, {full_name} variables",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="groupinvitation",
            name="project_role",
            field=models.ForeignKey(
                blank=True,
                help_text="Role to grant in the auto-created project. If not specified, uses invitation.role",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="group_project_invitations",
                to="permissions.role",
            ),
        ),
        migrations.AddField(
            model_name="groupinvitation",
            name="user_affiliations",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="groupinvitation",
            name="user_assurance_levels",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of required assurance URIs. User must have ALL of these.",
            ),
        ),
        migrations.AddField(
            model_name="groupinvitation",
            name="user_email_patterns",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="groupinvitation",
            name="user_identity_sources",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of allowed identity sources (identity providers).",
            ),
        ),
        migrations.AddField(
            model_name="groupinvitation",
            name="user_nationalities",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of allowed nationality codes (ISO 3166-1 alpha-2). User must have one of these.",
            ),
        ),
        migrations.AddField(
            model_name="groupinvitation",
            name="user_organization_types",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of allowed organization type URNs (SCHAC). User must match one.",
            ),
        ),
        migrations.AddField(
            model_name="permissionrequest",
            name="project_description",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Custom project description provided by user during invitation acceptance.",
                max_length=2000,
            ),
        ),
        migrations.AddField(
            model_name="permissionrequest",
            name="project_name",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Custom project name provided by user during invitation acceptance.",
                max_length=500,
            ),
        ),
        migrations.AlterField(
            model_name="invitation",
            name="extra_invitation_text",
            field=models.TextField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name="permissionrequest",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="permissionrequest",
            name="invitation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="users.groupinvitation"
            ),
        ),
        migrations.AlterField(
            model_name="permissionrequest",
            name="review_comment",
            field=models.TextField(
                blank=True,
                help_text="Optional comment provided during review",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="permissionrequest",
            name="reviewed_at",
            field=models.DateTimeField(
                blank=True,
                editable=False,
                help_text="Timestamp when the review was completed",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="permissionrequest",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who performed the review",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        waldur_core.core.migration_operations.FlushDeferredSql(),
        migrations.RunPython(
            code=_original(
                "0025_disable_misconfigured_auto_create_project"
            ).disable_misconfigured_auto_create_project,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
