# Generated by Django 4.2.18 on 2025-02-11 15:43

import django.db.models.deletion
import django_fsm
from django.conf import settings
from django.db import migrations, models

import waldur_core.core.validators

ROLES_MAP = {
    "owner": "CUSTOMER.OWNER",
    "service_manager": "CUSTOMER.MANAGER",
    "manager": "PROJECT.MANAGER",
    "admin": "PROJECT.ADMIN",
    "member": "PROJECT.MEMBER",
}


def fill_data(apps, schema_editor):
    ContentType = apps.get_model("contenttypes", "ContentType")
    Role = apps.get_model("permissions", "Role")
    GroupInvitation = apps.get_model("users", "GroupInvitation")
    Invitation = apps.get_model("users", "Invitation")
    for model in (GroupInvitation, Invitation):
        for obj in model.objects.all():
            obj.content_type = ContentType.objects.get_for_model(
                obj.project or obj.customer
            )
            obj.object_id = obj.project_id or obj.customer_id
            obj.role = Role.objects.get(
                name=ROLES_MAP[obj.project_role or obj.customer_role]
            )
            obj.save()


def clean_duplicate_profile_changed_logs(apps, schema_editor):
    Event = apps.get_model("logging", "Event")
    events = Event.objects.filter(event_type="user_profile_changed")
    events.delete()


class Migration(migrations.Migration):
    replaces = [
        ("users", "0002_invitation_extra_invitation_text"),
        ("users", "0003_alter_invitation_extra_invitation_text"),
        ("users", "0004_generic_invitation"),
        ("users", "0005_fill_data"),
        ("users", "0006_adjust_invitation_fields"),
        ("users", "0007_invitation_execution_state"),
        ("users", "0008_alter_invitation_state"),
        ("users", "0009_alter_invitation_phone_number"),
        ("users", "0010_clean_duplicate_profile_changed_logs"),
        ("users", "0011_alter_permissionrequest_created_by"),
    ]

    dependencies = [
        ("users", "0001_squashed_0012"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("contenttypes", "0002_remove_content_type_name"),
        ("permissions", "0013_alter_rolepermission_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="invitation",
            name="extra_invitation_text",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="groupinvitation",
            name="content_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddField(
            model_name="groupinvitation",
            name="object_id",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="groupinvitation",
            name="role",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="permissions.role",
            ),
        ),
        migrations.AddField(
            model_name="invitation",
            name="content_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddField(
            model_name="invitation",
            name="object_id",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="invitation",
            name="role",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="permissions.role",
            ),
        ),
        migrations.RunPython(
            code=fill_data,
        ),
        migrations.AlterField(
            model_name="groupinvitation",
            name="role",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="permissions.role"
            ),
        ),
        migrations.AlterField(
            model_name="invitation",
            name="role",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="permissions.role"
            ),
        ),
        migrations.AlterField(
            model_name="groupinvitation",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="structure.customer"
            ),
        ),
        migrations.AlterField(
            model_name="invitation",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="structure.customer"
            ),
        ),
        migrations.RemoveField(
            model_name="groupinvitation",
            name="customer_role",
        ),
        migrations.RemoveField(
            model_name="groupinvitation",
            name="project",
        ),
        migrations.RemoveField(
            model_name="groupinvitation",
            name="project_role",
        ),
        migrations.RemoveField(
            model_name="invitation",
            name="customer_role",
        ),
        migrations.RemoveField(
            model_name="invitation",
            name="project",
        ),
        migrations.RemoveField(
            model_name="invitation",
            name="project_role",
        ),
        migrations.AddField(
            model_name="invitation",
            name="execution_state",
            field=django_fsm.FSMField(
                choices=[
                    ("Scheduled", "Scheduled"),
                    ("Processing", "Processing"),
                    ("OK", "OK"),
                    ("Erred", "Erred"),
                ],
                default="Scheduled",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="invitation",
            name="state",
            field=models.CharField(
                choices=[
                    ("project", "Pending project"),
                    ("requested", "Requested"),
                    ("rejected", "Rejected"),
                    ("pending", "Pending"),
                    ("accepted", "Accepted"),
                    ("canceled", "Canceled"),
                    ("expired", "Expired"),
                ],
                default="pending",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="invitation",
            name="phone_number",
            field=models.CharField(
                blank=True,
                max_length=255,
                validators=[waldur_core.core.validators.validate_phone_number],
                verbose_name="phone number",
            ),
        ),
        migrations.RunPython(
            code=clean_duplicate_profile_changed_logs,
        ),
        migrations.AlterField(
            model_name="permissionrequest",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
