# Generated by Django 3.2.18 on 2023-03-29 15:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_squashed_0012"),
    ]

    operations = [
        migrations.AddField(
            model_name="invitation",
            name="extra_invitation_text",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
