# Generated by Django 3.2.18 on 2023-05-04 12:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0002_invitation_extra_invitation_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='extra_invitation_text',
            field=models.TextField(blank=True),
        ),
    ]
