# Generated by Django 2.2.19 on 2021-04-01 07:17

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0005_remove_invitation_link_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='affiliations',
            field=django.contrib.postgres.fields.jsonb.JSONField(
                null=True,
                blank=True,
                help_text="Person's affiliation within organization such as student, faculty, staff.",
            ),
        ),
    ]
