# Generated by Django 4.2.14 on 2024-08-07 14:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0007_invitation_execution_state"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invitation",
            name="state",
            field=models.CharField(
                choices=[
                    ("project", "Pending project"),
                    ("requested", "Requested"),
                    ("rejected", "Rejected"),
                    ("pending", "Pending"),
                    ("accepted", "Accepted"),
                    ("canceled", "Canceled"),
                    ("expired", "Expired"),
                ],
                default="pending",
                max_length=10,
            ),
        ),
    ]
