# Generated by Django 4.2.19 on 2025-03-03 09:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0011_alter_permissionrequest_created_by"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="invitation",
            name="tax_number",
        ),
    ]
