# Generated by Django 6.0.3 on 2026-04-08 15:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0024_alter_invitation_extra_invitation_text_max_length"),
    ]

    operations = [
        migrations.AddField(
            model_name="groupinvitation",
            name="allow_custom_project_details",
            field=models.BooleanField(
                default=False,
                help_text="Allow users to provide custom project name and description when accepting the invitation. If disabled, the project name is auto-generated from the template.",
            ),
        ),
        migrations.AddField(
            model_name="groupinvitation",
            name="allow_multiple_requests",
            field=models.BooleanField(
                default=False,
                help_text="Allow users to submit multiple permission requests for this invitation.",
            ),
        ),
        migrations.AddField(
            model_name="permissionrequest",
            name="project_description",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Custom project description provided by user during invitation acceptance.",
                max_length=2000,
            ),
        ),
        migrations.AddField(
            model_name="permissionrequest",
            name="project_name",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Custom project name provided by user during invitation acceptance.",
                max_length=500,
            ),
        ),
    ]
