# Generated by Django 4.2.23 on 2025-08-23 08:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0017_alter_permissionrequest_review_comment_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="groupinvitation",
            name="is_public",
            field=models.BooleanField(
                default=False,
                help_text="Allow non-authenticated users to see and accept this invitation. Only staff can create public invitations.",
            ),
        ),
    ]
