# Generated by Django 4.2.24 on 2025-12-25 12:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0019_add_auto_approve_to_group_invitation"),
    ]

    operations = [
        migrations.AddField(
            model_name="groupinvitation",
            name="user_identity_sources",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of allowed identity sources (identity providers).",
            ),
        ),
    ]
