# Generated by Django 4.2.24 on 2025-12-30 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0020_add_user_identity_sources"),
    ]

    operations = [
        migrations.AlterField(
            model_name="permissionrequest",
            name="invitation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="users.groupinvitation"
            ),
        ),
    ]
