# Generated by Django 4.2.27 on 2026-02-08 07:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0022_groupinvitation_user_assurance_levels_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="groupinvitation",
            name="custom_text",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Custom description text displayed to users viewing this invitation.",
                max_length=500,
            ),
        ),
    ]
