# Generated by Django 5.2.11 on 2026-02-24 09:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0023_add_group_invitation_custom_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invitation",
            name="extra_invitation_text",
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
