# Generated by Django 6.0.8 on 2026-08-28 11:37

import django.contrib.postgres.fields
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import django_fsm
import model_utils.fields
from django.conf import settings
from django.db import migrations, models

import waldur_core.core.fields
import waldur_core.core.models
import waldur_core.core.validators
import waldur_core.structure.models
import waldur_openstack.models


class Migration(migrations.Migration):
    replaces = [
        ("waldur_rancher", "0001_squashed_0037_json_field"),
        ("waldur_rancher", "0038_alter_rancheruser_user"),
        ("waldur_rancher", "0039_cluster_tenant"),
        ("waldur_rancher", "0040_alter_application_state_alter_cluster_state_and_more"),
        ("waldur_rancher", "0041_remove_cluster_node_command"),
        ("waldur_rancher", "0042_keycloakgroup_keycloakusergroupmembership"),
        ("waldur_rancher", "0043_roletemplate_alter_keycloakgroup_role_and_more"),
        ("waldur_rancher", "0044_keycloakusergroupmembership_first_name_and_more"),
        ("waldur_rancher", "0045_add_new_role"),
        ("waldur_rancher", "0046_cluster_vm_project"),
        ("waldur_rancher", "0047_add_vm_field"),
        ("waldur_rancher", "0048_clustersecuritygroup_clustersecuritygrouprule"),
        ("waldur_rancher", "0049_clustersecuritygrouprule_uuid"),
        ("waldur_rancher", "0050_alter_clustersecuritygrouprule_group"),
        ("waldur_rancher", "0051_cluster_capacity_cluster_kubernetes_version_and_more"),
        ("waldur_rancher", "0052_alter_clustersecuritygrouprule_backend_id_and_more"),
        ("waldur_rancher", "0053_alter_application_description_and_more"),
        ("waldur_rancher", "0054_cluster_is_available"),
        ("waldur_rancher", "0055_alter_clustersecuritygrouprule_protocol"),
        (
            "waldur_rancher",
            "0056_alter_application_options_alter_cluster_options_and_more",
        ),
        ("waldur_rancher", "0057_alter_catalog_options"),
        (
            "waldur_rancher",
            "0058_alter_clustertemplate_options_alter_hpa_options_and_more",
        ),
    ]

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("core", "__first__"),
        ("openstack", "0001_squashed_0028"),
        ("openstack", "0039_remove_old_instance"),
        ("openstack", "0050_port_status"),
        ("openstack", "0052_router_ports"),
        ("structure", "0001_squashed_0036"),
        ("structure", "0052_accesssubnet_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClusterTemplate",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=4096, verbose_name="description"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=150,
                        validators=[waldur_core.core.validators.validate_name],
                        verbose_name="name",
                    ),
                ),
                ("uuid", waldur_core.core.fields.UUIDField()),
            ],
            options={
                "ordering": ["name", "id"],
            },
        ),
        migrations.CreateModel(
            name="KeycloakGroup",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("uuid", waldur_core.core.fields.UUIDField()),
                ("backend_id", models.CharField(blank=True, max_length=255)),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="Group name"
                    ),
                ),
                (
                    "scope_uuid",
                    models.UUIDField(help_text="UUID of the cluster or project"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Catalog",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=4096, verbose_name="description"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=150,
                        validators=[waldur_core.core.validators.validate_name],
                        verbose_name="name",
                    ),
                ),
                ("uuid", waldur_core.core.fields.UUIDField()),
                (
                    "runtime_state",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="runtime state"
                    ),
                ),
                ("backend_id", models.CharField(blank=True, max_length=255)),
                ("object_id", models.PositiveIntegerField(null=True)),
                ("catalog_url", models.URLField()),
                ("branch", models.CharField(max_length=255)),
                ("commit", models.CharField(blank=True, max_length=40)),
                ("username", models.CharField(blank=True, max_length=255)),
                ("password", models.CharField(blank=True, max_length=255)),
                (
                    "content_type",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "settings",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="structure.servicesettings",
                    ),
                ),
            ],
            options={
                "ordering": ["-created", "id"],
            },
        ),
        migrations.CreateModel(
            name="Cluster",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=4096, verbose_name="description"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=150,
                        validators=[waldur_core.core.validators.validate_name],
                        verbose_name="name",
                    ),
                ),
                ("uuid", waldur_core.core.fields.UUIDField()),
                ("error_message", models.TextField(blank=True)),
                ("error_traceback", models.TextField(blank=True)),
                (
                    "state",
                    django_fsm.FSMIntegerField(
                        choices=[
                            (5, "CREATION_SCHEDULED"),
                            (6, "CREATING"),
                            (1, "UPDATE_SCHEDULED"),
                            (2, "UPDATING"),
                            (7, "DELETION_SCHEDULED"),
                            (8, "DELETING"),
                            (3, "OK"),
                            (4, "ERRED"),
                        ],
                        default=5,
                    ),
                ),
                ("can_be_managed", models.BooleanField(default=True)),
                ("backend_id", models.CharField(blank=True, max_length=255)),
                ("runtime_state", models.CharField(blank=True, max_length=255)),
                (
                    "kubernetes_version",
                    models.CharField(
                        blank=True,
                        help_text="Kubernetes version used in the cluster.",
                        max_length=50,
                    ),
                ),
                (
                    "capacity",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Cluster capacity in the format {'cpu': '10', 'ram': '49125240Ki', 'pods': '330'}",
                    ),
                ),
                (
                    "requested",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Cluster requested resources in the format {'cpu': '1450m', 'memory': '884Mi', 'pods': '13'}",
                    ),
                ),
                (
                    "management_security_group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="openstack.securitygroup",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="structure.project",
                    ),
                ),
                (
                    "service_settings",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="structure.servicesettings",
                    ),
                ),
                (
                    "settings",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="structure.servicesettings",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="openstack.tenant",
                    ),
                ),
                (
                    "vm_project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="structure.project",
                    ),
                ),
            ],
            options={
                "ordering": ["-created", "id"],
                "abstract": False,
            },
            bases=(
                waldur_core.core.models.DescendantMixin,
                waldur_core.core.models.BackendModelMixin,
                waldur_core.structure.models.StructureLoggableMixin,
                models.Model,
                django_fsm.ConcurrentTransitionMixin,
            ),
        ),
        migrations.CreateModel(
            name="ClusterSecurityGroup",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=4096, verbose_name="description"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=150,
                        validators=[waldur_core.core.validators.validate_name],
                        verbose_name="name",
                    ),
                ),
                ("uuid", waldur_core.core.fields.UUIDField()),
                (
                    "cluster",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="waldur_rancher.cluster",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ClusterSecurityGroupRule",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=4096, verbose_name="description"
                    ),
                ),
                ("uuid", waldur_core.core.fields.UUIDField()),
                (
                    "protocol",
                    models.CharField(
                        blank=True,
                        help_text="Network protocol: 'tcp', 'udp', 'icmp', empty (any) or an IANA protocol number 0-255 (e.g. '112' for VRRP).",
                        max_length=40,
                        validators=[
                            waldur_openstack.models.validate_security_group_rule_protocol
                        ],
                    ),
                ),
                (
                    "from_port",
                    models.IntegerField(
                        help_text="Starting port number in the range (1-65535)",
                        null=True,
                        validators=[django.core.validators.MaxValueValidator(65535)],
                    ),
                ),
                (
                    "to_port",
                    models.IntegerField(
                        help_text="Ending port number in the range (1-65535)",
                        null=True,
                        validators=[django.core.validators.MaxValueValidator(65535)],
                    ),
                ),
                (
                    "cidr",
                    models.CharField(
                        blank=True,
                        help_text="CIDR notation for the source/destination network address range",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[("ingress", "ingress"), ("egress", "egress")],
                        default="ingress",
                        help_text="Traffic direction - either 'ingress' (incoming) or 'egress' (outgoing)",
                        max_length=8,
                    ),
                ),
                (
                    "ethertype",
                    models.CharField(
                        choices=[("IPv4", "IPv4"), ("IPv6", "IPv6")],
                        default="IPv4",
                        help_text="IP protocol version - either 'IPv4' or 'IPv6'",
                        max_length=40,
                    ),
                ),
                (
                    "backend_id",
                    models.CharField(
                        blank=True,
                        help_text="ID of the security group rule in the OpenStack backend",
                        max_length=36,
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rules",
                        to="waldur_rancher.clustersecuritygroup",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ClusterTemplateNode",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("agent", "agent"), ("server", "server")],
                        db_index=True,
                        max_length=10,
                    ),
                ),
                (
                    "min_vcpu",
                    models.PositiveSmallIntegerField(verbose_name="Min vCPU (cores)"),
                ),
                ("min_ram", models.PositiveIntegerField(verbose_name="Min RAM (GB)")),
                (
                    "system_volume_size",
                    models.PositiveIntegerField(verbose_name="System volume size (GB)"),
                ),
                ("preferred_volume_type", models.CharField(blank=True, max_length=150)),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nodes",
                        to="waldur_rancher.clustertemplate",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="KeycloakUserGroupMembership",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("uuid", waldur_core.core.fields.UUIDField()),
                ("error_message", models.TextField(blank=True)),
                ("error_traceback", models.TextField(blank=True)),
                (
                    "username",
                    models.CharField(
                        help_text="Keycloak user username", max_length=255
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="User's email for notifications", max_length=254
                    ),
                ),
                (
                    "state",
                    django_fsm.FSMField(
                        choices=[("pending", "pending"), ("active", "active")],
                        default="pending",
                        max_length=50,
                    ),
                ),
                ("last_checked", models.DateTimeField(auto_now=True)),
                ("first_name", models.CharField(blank=True, max_length=100)),
                ("last_name", models.CharField(blank=True, max_length=100)),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="waldur_rancher.keycloakgroup",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=4096, verbose_name="description"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=150,
                        validators=[waldur_core.core.validators.validate_name],
                        verbose_name="name",
                    ),
                ),
                ("uuid", waldur_core.core.fields.UUIDField()),
                (
                    "runtime_state",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="runtime state"
                    ),
                ),
                ("backend_id", models.CharField(blank=True, max_length=255)),
                (
                    "cluster",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="waldur_rancher.cluster",
                    ),
                ),
                (
                    "settings",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="structure.servicesettings",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Namespace",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=150,
                        validators=[waldur_core.core.validators.validate_name],
                        verbose_name="name",
                    ),
                ),
                ("uuid", waldur_core.core.fields.UUIDField()),
                (
                    "runtime_state",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="runtime state"
                    ),
                ),
                ("backend_id", models.CharField(blank=True, max_length=255)),
                (
                    "settings",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="structure.servicesettings",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="namespaces",
                        to="waldur_rancher.project",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Ingress",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=4096, verbose_name="description"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=150,
                        validators=[waldur_core.core.validators.validate_name],
                        verbose_name="name",
                    ),
                ),
                ("uuid", waldur_core.core.fields.UUIDField()),
                ("error_message", models.TextField(blank=True)),
                ("error_traceback", models.TextField(blank=True)),
                (
                    "runtime_state",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="runtime state"
                    ),
                ),
                (
                    "state",
                    django_fsm.FSMIntegerField(
                        choices=[
                            (5, "CREATION_SCHEDULED"),
                            (6, "CREATING"),
                            (1, "UPDATE_SCHEDULED"),
                            (2, "UPDATING"),
                            (7, "DELETION_SCHEDULED"),
                            (8, "DELETING"),
                            (3, "OK"),
                            (4, "ERRED"),
                        ],
                        default=5,
                    ),
                ),
                ("backend_id", models.CharField(blank=True, max_length=255)),
                ("rules", models.JSONField(blank=True, default=list)),
                (
                    "cluster",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="waldur_rancher.cluster",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="structure.project",
                    ),
                ),
                (
                    "service_settings",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="structure.servicesettings",
                    ),
                ),
                (
                    "settings",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="structure.servicesettings",
                    ),
                ),
                (
                    "namespace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="waldur_rancher.namespace",
                    ),
                ),
                (
                    "rancher_project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="waldur_rancher.project",
                    ),
                ),
            ],
            options={
                "ordering": ["-created", "id"],
                "abstract": False,
            },
            bases=(
                waldur_core.core.models.DescendantMixin,
                waldur_core.core.models.BackendModelMixin,
                waldur_core.structure.models.StructureLoggableMixin,
                models.Model,
                django_fsm.ConcurrentTransitionMixin,
            ),
        ),
        migrations.CreateModel(
            name="RancherUser",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uuid", waldur_core.core.fields.UUIDField()),
                ("backend_id", models.CharField(blank=True, max_length=255)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "settings",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="structure.servicesettings",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["user__username", "id"],
            },
            bases=(models.Model, waldur_core.structure.models.StructureLoggableMixin),
        ),
        migrations.CreateModel(
            name="RancherUserClusterLink",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("backend_id", models.CharField(blank=True, max_length=255)),
                (
                    "cluster",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="waldur_rancher.cluster",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="waldur_rancher.rancheruser",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="rancheruser",
            name="clusters",
            field=models.ManyToManyField(
                through="waldur_rancher.RancherUserClusterLink",
                to="waldur_rancher.cluster",
            ),
        ),
        migrations.CreateModel(
            name="RoleTemplate",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uuid", waldur_core.core.fields.UUIDField()),
                (
                    "scope_type",
                    models.CharField(
                        choices=[("cluster", "cluster"), ("project", "project")],
                        db_index=True,
                        max_length=10,
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Role internal name", max_length=50),
                ),
                (
                    "display_name",
                    models.CharField(help_text="Role public name", max_length=50),
                ),
                (
                    "settings",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="structure.servicesettings",
                    ),
                ),
            ],
            options={
                "unique_together": {("scope_type", "name", "settings")},
            },
        ),
        migrations.AddField(
            model_name="rancheruserclusterlink",
            name="role",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="waldur_rancher.roletemplate",
            ),
        ),
        migrations.AddField(
            model_name="keycloakgroup",
            name="role",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="waldur_rancher.roletemplate",
            ),
        ),
        migrations.CreateModel(
            name="Template",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=4096, verbose_name="description"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=150,
                        validators=[waldur_core.core.validators.validate_name],
                        verbose_name="name",
                    ),
                ),
                (
                    "icon_url",
                    models.URLField(
                        blank=True, max_length=500, verbose_name="icon url"
                    ),
                ),
                ("uuid", waldur_core.core.fields.UUIDField()),
                (
                    "runtime_state",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="runtime state"
                    ),
                ),
                ("backend_id", models.CharField(blank=True, max_length=255)),
                ("project_url", models.URLField(blank=True, max_length=500)),
                ("default_version", models.CharField(max_length=255)),
                (
                    "versions",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=255)
                    ),
                ),
                (
                    "icon",
                    models.FileField(blank=True, null=True, upload_to="rancher_icons"),
                ),
                (
                    "catalog",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="waldur_rancher.catalog",
                    ),
                ),
                (
                    "cluster",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="waldur_rancher.cluster",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="waldur_rancher.project",
                    ),
                ),
                (
                    "settings",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="structure.servicesettings",
                    ),
                ),
            ],
            options={
                "ordering": ["name", "id"],
            },
        ),
        migrations.CreateModel(
            name="Application",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=4096, verbose_name="description"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=150,
                        validators=[waldur_core.core.validators.validate_name],
                        verbose_name="name",
                    ),
                ),
                ("uuid", waldur_core.core.fields.UUIDField()),
                ("error_message", models.TextField(blank=True)),
                ("error_traceback", models.TextField(blank=True)),
                (
                    "runtime_state",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="runtime state"
                    ),
                ),
                (
                    "state",
                    django_fsm.FSMIntegerField(
                        choices=[
                            (5, "CREATION_SCHEDULED"),
                            (6, "CREATING"),
                            (1, "UPDATE_SCHEDULED"),
                            (2, "UPDATING"),
                            (7, "DELETION_SCHEDULED"),
                            (8, "DELETING"),
                            (3, "OK"),
                            (4, "ERRED"),
                        ],
                        default=5,
                    ),
                ),
                ("backend_id", models.CharField(blank=True, max_length=255)),
                ("version", models.CharField(max_length=100)),
                ("answers", models.JSONField(blank=True, default=dict)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="structure.project",
                    ),
                ),
                (
                    "service_settings",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="structure.servicesettings",
                    ),
                ),
                (
                    "settings",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="structure.servicesettings",
                    ),
                ),
                (
                    "cluster",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="waldur_rancher.cluster",
                    ),
                ),
                (
                    "namespace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="waldur_rancher.namespace",
                    ),
                ),
                (
                    "rancher_project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="waldur_rancher.project",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="waldur_rancher.template",
                    ),
                ),
            ],
            options={
                "ordering": ["-created", "id"],
                "abstract": False,
            },
            bases=(
                waldur_core.core.models.DescendantMixin,
                waldur_core.core.models.BackendModelMixin,
                waldur_core.structure.models.StructureLoggableMixin,
                models.Model,
                django_fsm.ConcurrentTransitionMixin,
            ),
        ),
        migrations.CreateModel(
            name="Workload",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=150,
                        validators=[waldur_core.core.validators.validate_name],
                        verbose_name="name",
                    ),
                ),
                ("uuid", waldur_core.core.fields.UUIDField()),
                (
                    "runtime_state",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="runtime state"
                    ),
                ),
                ("backend_id", models.CharField(blank=True, max_length=255)),
                ("scale", models.PositiveSmallIntegerField()),
                (
                    "cluster",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="waldur_rancher.cluster",
                    ),
                ),
                (
                    "namespace",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="waldur_rancher.namespace",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="waldur_rancher.project",
                    ),
                ),
                (
                    "settings",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="structure.servicesettings",
                    ),
                ),
            ],
            options={
                "ordering": ["name", "id"],
            },
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=4096, verbose_name="description"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=150,
                        validators=[waldur_core.core.validators.validate_name],
                        verbose_name="name",
                    ),
                ),
                ("uuid", waldur_core.core.fields.UUIDField()),
                ("error_message", models.TextField(blank=True)),
                ("error_traceback", models.TextField(blank=True)),
                (
                    "runtime_state",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="runtime state"
                    ),
                ),
                (
                    "state",
                    django_fsm.FSMIntegerField(
                        choices=[
                            (5, "CREATION_SCHEDULED"),
                            (6, "CREATING"),
                            (1, "UPDATE_SCHEDULED"),
                            (2, "UPDATING"),
                            (7, "DELETION_SCHEDULED"),
                            (8, "DELETING"),
                            (3, "OK"),
                            (4, "ERRED"),
                        ],
                        default=5,
                    ),
                ),
                ("backend_id", models.CharField(blank=True, max_length=255)),
                (
                    "cluster_ip",
                    models.GenericIPAddressField(
                        blank=True, null=True, protocol="IPv4"
                    ),
                ),
                ("selector", models.JSONField(blank=True, null=True)),
                (
                    "namespace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="waldur_rancher.namespace",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="structure.project",
                    ),
                ),
                (
                    "service_settings",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="structure.servicesettings",
                    ),
                ),
                (
                    "settings",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="structure.servicesettings",
                    ),
                ),
                (
                    "target_workloads",
                    models.ManyToManyField(to="waldur_rancher.workload"),
                ),
            ],
            options={
                "ordering": ["-created", "id"],
                "abstract": False,
            },
            bases=(
                waldur_core.core.models.DescendantMixin,
                waldur_core.core.models.BackendModelMixin,
                waldur_core.structure.models.StructureLoggableMixin,
                models.Model,
                django_fsm.ConcurrentTransitionMixin,
            ),
        ),
        migrations.CreateModel(
            name="HPA",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=4096, verbose_name="description"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=150,
                        validators=[waldur_core.core.validators.validate_name],
                        verbose_name="name",
                    ),
                ),
                ("uuid", waldur_core.core.fields.UUIDField()),
                ("error_message", models.TextField(blank=True)),
                ("error_traceback", models.TextField(blank=True)),
                (
                    "runtime_state",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="runtime state"
                    ),
                ),
                (
                    "state",
                    django_fsm.FSMIntegerField(
                        choices=[
                            (5, "CREATION_SCHEDULED"),
                            (6, "CREATING"),
                            (1, "UPDATE_SCHEDULED"),
                            (2, "UPDATING"),
                            (7, "DELETION_SCHEDULED"),
                            (8, "DELETING"),
                            (3, "OK"),
                            (4, "ERRED"),
                        ],
                        default=5,
                    ),
                ),
                ("backend_id", models.CharField(blank=True, max_length=255)),
                ("current_replicas", models.PositiveSmallIntegerField(default=0)),
                ("desired_replicas", models.PositiveSmallIntegerField(default=0)),
                ("min_replicas", models.PositiveSmallIntegerField(default=0)),
                ("max_replicas", models.PositiveSmallIntegerField(default=0)),
                ("metrics", models.JSONField()),
                (
                    "cluster",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="waldur_rancher.cluster",
                    ),
                ),
                (
                    "settings",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="structure.servicesettings",
                    ),
                ),
                (
                    "namespace",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="waldur_rancher.namespace",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="waldur_rancher.project",
                    ),
                ),
                (
                    "workload",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="waldur_rancher.workload",
                    ),
                ),
            ],
            options={
                "ordering": ["name", "id"],
            },
            bases=(models.Model, django_fsm.ConcurrentTransitionMixin),
        ),
        migrations.CreateModel(
            name="ClusterPublicIP",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("uuid", waldur_core.core.fields.UUIDField()),
                (
                    "cluster",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="public_ips",
                        to="waldur_rancher.cluster",
                    ),
                ),
                (
                    "floating_ip",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="openstack.floatingip",
                    ),
                ),
            ],
            options={
                "unique_together": {("cluster", "floating_ip")},
            },
        ),
        migrations.CreateModel(
            name="Node",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=150,
                        validators=[waldur_core.core.validators.validate_name],
                        verbose_name="name",
                    ),
                ),
                ("uuid", waldur_core.core.fields.UUIDField()),
                ("error_message", models.TextField(blank=True)),
                ("error_traceback", models.TextField(blank=True)),
                (
                    "state",
                    django_fsm.FSMIntegerField(
                        choices=[
                            (5, "CREATION_SCHEDULED"),
                            (6, "CREATING"),
                            (1, "UPDATE_SCHEDULED"),
                            (2, "UPDATING"),
                            (7, "DELETION_SCHEDULED"),
                            (8, "DELETING"),
                            (3, "OK"),
                            (4, "ERRED"),
                        ],
                        default=5,
                    ),
                ),
                ("backend_id", models.CharField(blank=True, max_length=255)),
                (
                    "role",
                    models.CharField(
                        choices=[("agent", "agent"), ("server", "server")],
                        db_index=True,
                        max_length=10,
                    ),
                ),
                (
                    "initial_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Initial data for instance creating.",
                    ),
                ),
                ("runtime_state", models.CharField(blank=True, max_length=255)),
                ("k8s_version", models.CharField(blank=True, max_length=255)),
                ("docker_version", models.CharField(blank=True, max_length=255)),
                ("cpu_allocated", models.FloatField(blank=True, null=True)),
                ("cpu_total", models.IntegerField(blank=True, null=True)),
                (
                    "ram_allocated",
                    models.IntegerField(
                        blank=True, help_text="Allocated RAM in Mi.", null=True
                    ),
                ),
                (
                    "ram_total",
                    models.IntegerField(
                        blank=True, help_text="Total RAM in Mi.", null=True
                    ),
                ),
                ("pods_allocated", models.IntegerField(blank=True, null=True)),
                ("pods_total", models.IntegerField(blank=True, null=True)),
                ("labels", models.JSONField(blank=True, default=dict)),
                ("annotations", models.JSONField(blank=True, default=dict)),
                (
                    "cluster",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="waldur_rancher.cluster",
                    ),
                ),
                (
                    "instance",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="openstack.instance",
                    ),
                ),
            ],
            options={
                "ordering": ["name", "id"],
                "unique_together": {("cluster", "name")},
            },
            bases=(
                waldur_core.structure.models.StructureLoggableMixin,
                models.Model,
                django_fsm.ConcurrentTransitionMixin,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="rancheruser",
            unique_together={("user", "settings")},
        ),
        migrations.CreateModel(
            name="RancherUserProjectLink",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("backend_id", models.CharField(blank=True, max_length=255)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="waldur_rancher.project",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="waldur_rancher.rancheruser",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="waldur_rancher.roletemplate",
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "project", "role")},
            },
        ),
        migrations.AlterUniqueTogether(
            name="rancheruserclusterlink",
            unique_together={("user", "cluster", "role")},
        ),
        migrations.AlterUniqueTogether(
            name="keycloakgroup",
            unique_together={("scope_uuid", "role")},
        ),
    ]
