# Generated by Django 2.2.9 on 2020-02-24 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('waldur_rancher', '0012_cluster_initial_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cluster',
            name='initial_data',
        ),
    ]
