# Generated by Django 2.2.13 on 2020-06-17 14:46

import django_fsm
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waldur_rancher', '0024_hpa'),
    ]

    operations = [
        migrations.AddField(
            model_name='hpa', name='error_message', field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='hpa',
            name='state',
            field=django_fsm.FSMIntegerField(
                choices=[
                    (5, 'Creation Scheduled'),
                    (6, 'Creating'),
                    (1, 'Update Scheduled'),
                    (2, 'Updating'),
                    (7, 'Deletion Scheduled'),
                    (8, 'Deleting'),
                    (3, 'OK'),
                    (4, 'Erred'),
                ],
                default=5,
            ),
        ),
    ]
