# Generated by Django 2.2.13 on 2020-06-19 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waldur_rancher', '0025_hpa_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='hpa',
            name='description',
            field=models.CharField(
                blank=True, max_length=500, verbose_name='description'
            ),
        ),
    ]
