# Generated by Django 2.2.13 on 2020-10-07 11:12

from django.db import migrations


def delete_catalogs(apps, schema_editor):
    Catalog = apps.get_model('waldur_rancher', 'Catalog')
    for catalog in Catalog.objects.all():
        if not catalog.scope:
            catalog.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('waldur_rancher', '0033_error_traceback'),
    ]

    operations = [
        migrations.RunPython(delete_catalogs),
    ]
