# Generated by Django 3.2 on 2022-01-31 14:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('waldur_rancher', '0036_cluster_management_security_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='answers',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='hpa',
            name='metrics',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='ingress',
            name='rules',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='node',
            name='annotations',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='node',
            name='initial_data',
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text='Initial data for instance creating.',
            ),
        ),
        migrations.AlterField(
            model_name='node',
            name='labels',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='service',
            name='selector',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
