# Generated by Django 4.2.20 on 2025-04-02 12:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("waldur_rancher", "0040_alter_application_state_alter_cluster_state_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cluster",
            name="node_command",
        ),
    ]
