# Generated by Django 4.2.20 on 2025-04-15 08:27

import django.db.models.deletion
import django.utils.timezone
import django_fsm
import model_utils.fields
from django.db import migrations, models

import waldur_core.core.fields


class Migration(migrations.Migration):
    dependencies = [
        ("waldur_rancher", "0041_remove_cluster_node_command"),
    ]

    operations = [
        migrations.CreateModel(
            name="KeycloakGroup",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("uuid", waldur_core.core.fields.UUIDField()),
                ("backend_id", models.CharField(blank=True, max_length=255)),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="Group name"
                    ),
                ),
                (
                    "scope_type",
                    models.CharField(
                        choices=[("cluster", "cluster"), ("project", "project")],
                        db_index=True,
                        max_length=10,
                    ),
                ),
                (
                    "scope_uuid",
                    models.UUIDField(help_text="UUID of the cluster or project"),
                ),
                ("role", models.CharField(max_length=100)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="KeycloakUserGroupMembership",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("uuid", waldur_core.core.fields.UUIDField()),
                ("error_message", models.TextField(blank=True)),
                ("error_traceback", models.TextField(blank=True)),
                (
                    "username",
                    models.CharField(
                        help_text="Keycloak user username", max_length=255
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="User's email for notifications", max_length=254
                    ),
                ),
                (
                    "state",
                    django_fsm.FSMField(
                        choices=[("pending", "pending"), ("active", "active")],
                        default="pending",
                        max_length=50,
                    ),
                ),
                ("last_checked", models.DateTimeField(auto_now=True)),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="waldur_rancher.keycloakgroup",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
