# Generated by Django 4.2.20 on 2025-04-17 17:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("waldur_rancher", "0043_roletemplate_alter_keycloakgroup_role_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="keycloakusergroupmembership",
            name="first_name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="keycloakusergroupmembership",
            name="last_name",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
