# Generated by Django 4.2.23 on 2025-08-22 07:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("waldur_rancher", "0051_cluster_capacity_cluster_kubernetes_version_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clustersecuritygrouprule",
            name="backend_id",
            field=models.CharField(
                blank=True,
                help_text="ID of the security group rule in the OpenStack backend",
                max_length=36,
            ),
        ),
        migrations.AlterField(
            model_name="clustersecuritygrouprule",
            name="cidr",
            field=models.CharField(
                blank=True,
                help_text="CIDR notation for the source/destination network address range",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="clustersecuritygrouprule",
            name="direction",
            field=models.CharField(
                choices=[("ingress", "ingress"), ("egress", "egress")],
                default="ingress",
                help_text="Traffic direction - either 'ingress' (incoming) or 'egress' (outgoing)",
                max_length=8,
            ),
        ),
        migrations.AlterField(
            model_name="clustersecuritygrouprule",
            name="ethertype",
            field=models.CharField(
                choices=[("IPv4", "IPv4"), ("IPv6", "IPv6")],
                default="IPv4",
                help_text="IP protocol version - either 'IPv4' or 'IPv6'",
                max_length=40,
            ),
        ),
        migrations.AlterField(
            model_name="clustersecuritygrouprule",
            name="from_port",
            field=models.IntegerField(
                help_text="Starting port number in the range (1-65535)",
                null=True,
                validators=[django.core.validators.MaxValueValidator(65535)],
            ),
        ),
        migrations.AlterField(
            model_name="clustersecuritygrouprule",
            name="protocol",
            field=models.CharField(
                blank=True,
                choices=[("tcp", "tcp"), ("udp", "udp"), ("icmp", "icmp")],
                help_text="The network protocol (TCP, UDP, ICMP, or empty for any protocol)",
                max_length=40,
            ),
        ),
        migrations.AlterField(
            model_name="clustersecuritygrouprule",
            name="to_port",
            field=models.IntegerField(
                help_text="Ending port number in the range (1-65535)",
                null=True,
                validators=[django.core.validators.MaxValueValidator(65535)],
            ),
        ),
    ]
