# Generated by Django 4.2.23 on 2025-11-26 15:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("waldur_rancher", "0053_alter_application_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cluster",
            name="can_be_managed",
            field=models.BooleanField(default=True),
        ),
    ]
