# Generated by Django 6.0.8 on 2026-08-20 07:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "waldur_rancher",
            "0056_alter_application_options_alter_cluster_options_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="catalog",
            options={"ordering": ["-created", "id"]},
        ),
    ]
