# Generated by Django 4.2.16 on 2024-12-05 16:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("marketplace_remote", "0006_remotesynchronisation_remotelocalcategory"),
    ]

    operations = [
        migrations.AlterField(
            model_name="remotesynchronisation",
            name="last_output",
            field=models.TextField(editable=False),
        ),
    ]
