# Generated by Django 4.2.17 on 2024-12-12 15:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("marketplace_remote", "0007_alter_remotesynchronisation_last_output"),
    ]

    operations = [
        migrations.AddField(
            model_name="remotelocalcategory",
            name="remote_category_name",
            field=models.CharField(default="Unknown", max_length=255),
        ),
    ]
