# Generated by Django 4.2.23 on 2025-08-22 07:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("marketplace_remote", "0008_remotelocalcategory_remote_category_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectupdaterequest",
            name="review_comment",
            field=models.TextField(
                blank=True,
                help_text="Optional comment provided during review",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="projectupdaterequest",
            name="reviewed_at",
            field=models.DateTimeField(
                blank=True,
                editable=False,
                help_text="Timestamp when the review was completed",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="projectupdaterequest",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who performed the review",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
