# Generated by Django 4.2.24 on 2025-10-20 10:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "marketplace_remote",
            "0009_alter_projectupdaterequest_review_comment_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectupdaterequest",
            name="new_description",
            field=models.CharField(blank=True, max_length=4096),
        ),
        migrations.AlterField(
            model_name="projectupdaterequest",
            name="old_description",
            field=models.CharField(blank=True, max_length=4096),
        ),
    ]
