# Generated by Django 6.0.8 on 2026-08-20 13:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "marketplace_remote",
            "0010_alter_projectupdaterequest_new_description_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="projectupdaterequest",
            options={"ordering": ["created", "id"]},
        ),
    ]
