# Generated by Django 6.0.8 on 2026-09-03 15:34

import django.db.models.deletion
import django_fsm
from django.db import migrations, models


class Migration(migrations.Migration):
    replaces = [
        ("google", "0001_initial"),
        ("google", "0002_googlecalendar"),
        ("google", "0003_del_dev_credentials"),
        ("google", "0004_alter_googlecalendar_state"),
    ]

    dependencies = [
        ("marketplace", "0001_squashed_0076"),
    ]

    operations = [
        migrations.CreateModel(
            name="GoogleCalendar",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("error_message", models.TextField(blank=True)),
                ("error_traceback", models.TextField(blank=True)),
                (
                    "state",
                    django_fsm.FSMIntegerField(
                        choices=[
                            (5, "CREATION_SCHEDULED"),
                            (6, "CREATING"),
                            (1, "UPDATE_SCHEDULED"),
                            (2, "UPDATING"),
                            (7, "DELETION_SCHEDULED"),
                            (8, "DELETING"),
                            (3, "OK"),
                            (4, "ERRED"),
                        ],
                        default=5,
                    ),
                ),
                (
                    "backend_id",
                    models.CharField(
                        blank=True, db_index=True, max_length=255, null=True
                    ),
                ),
                ("public", models.BooleanField(default=False)),
                (
                    "offering",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="marketplace.offering",
                    ),
                ),
            ],
            options={
                "verbose_name": "Google calendar",
                "verbose_name_plural": "Google calendars",
            },
            bases=(models.Model, django_fsm.ConcurrentTransitionMixin),
        ),
        migrations.CreateModel(
            name="GoogleCredentials",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("calendar_token", models.CharField(blank=True, max_length=255)),
                (
                    "calendar_refresh_token",
                    models.CharField(blank=True, max_length=255),
                ),
                (
                    "service_provider",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="marketplace.serviceprovider",
                    ),
                ),
            ],
            options={
                "verbose_name": "Google credentials",
                "verbose_name_plural": "Google credentials",
            },
        ),
    ]
