# Generated by Django 4.2.19 on 2025-03-11 16:35

import django_fsm
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("google", "0003_del_dev_credentials"),
    ]

    operations = [
        migrations.AlterField(
            model_name="googlecalendar",
            name="state",
            field=django_fsm.FSMIntegerField(
                choices=[
                    (5, "CREATION_SCHEDULED"),
                    (6, "CREATING"),
                    (1, "UPDATE_SCHEDULED"),
                    (2, "UPDATING"),
                    (7, "DELETION_SCHEDULED"),
                    (8, "DELETING"),
                    (3, "OK"),
                    (4, "ERRED"),
                ],
                default=5,
            ),
        ),
    ]
