# Generated by Django 6.0.5 on 2026-06-04 07:00

import django.db.models.deletion
import django.utils.timezone
import django_fsm
import model_utils.fields
import waldur_core.core.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MatrixAppserviceTransaction",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "txn_id",
                    models.CharField(db_index=True, max_length=255, unique=True),
                ),
                ("processed_at", models.DateTimeField(auto_now_add=True)),
                ("event_count", models.IntegerField(default=0)),
            ],
            options={
                "ordering": ["-processed_at"],
            },
        ),
        migrations.CreateModel(
            name="MatrixRoom",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("uuid", waldur_core.core.fields.UUIDField()),
                (
                    "room_id",
                    models.CharField(
                        blank=True,
                        default=None,
                        help_text="Matrix room ID, e.g. !abc:domain",
                        max_length=255,
                        null=True,
                        unique=True,
                    ),
                ),
                ("room_name", models.CharField(blank=True, max_length=255)),
                (
                    "room_alias",
                    models.CharField(
                        blank=True,
                        help_text="Matrix room alias, e.g. #project-name:domain",
                        max_length=255,
                    ),
                ),
                (
                    "state",
                    django_fsm.FSMField(
                        choices=[
                            ("creating", "Creating"),
                            ("active", "Active"),
                            ("disabling", "Disabling"),
                            ("archived", "Archived"),
                            ("error", "Error"),
                        ],
                        default="creating",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True)),
                ("object_id", models.PositiveIntegerField()),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Matrix room",
                "verbose_name_plural": "Matrix rooms",
                "unique_together": {("content_type", "object_id")},
            },
        ),
        migrations.CreateModel(
            name="MatrixHistoryExport",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("uuid", waldur_core.core.fields.UUIDField()),
                (
                    "export_file",
                    models.FileField(
                        blank=True, null=True, upload_to="matrix_exports/%Y/%m/"
                    ),
                ),
                (
                    "media_file",
                    models.FileField(
                        blank=True,
                        help_text="ZIP archive containing downloaded media files",
                        null=True,
                        upload_to="matrix_exports/%Y/%m/media/",
                    ),
                ),
                ("media_count", models.IntegerField(default=0)),
                (
                    "export_type",
                    models.CharField(
                        choices=[
                            ("periodic", "Periodic"),
                            ("on_deletion", "On deletion"),
                            ("manual", "Manual"),
                        ],
                        default="manual",
                        max_length=20,
                    ),
                ),
                ("message_count", models.IntegerField(default=0)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("exporting", "Exporting"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exports",
                        to="matrix_chat.matrixroom",
                    ),
                ),
            ],
            options={
                "verbose_name": "Matrix history export",
                "verbose_name_plural": "Matrix history exports",
                "ordering": ["-created"],
            },
        ),
        migrations.CreateModel(
            name="MatrixUserProfile",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("uuid", waldur_core.core.fields.UUIDField()),
                (
                    "matrix_user_id",
                    models.CharField(
                        help_text="Full Matrix user ID, e.g. @user:domain",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "provisioned",
                    models.BooleanField(
                        default=False,
                        help_text="True after the user has been provisioned via Admin API",
                    ),
                ),
                ("provisioned_at", models.DateTimeField(blank=True, null=True)),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
                (
                    "access_token",
                    models.CharField(
                        blank=True,
                        help_text="Matrix access token obtained during registration",
                        max_length=512,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matrix_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Matrix user profile",
                "verbose_name_plural": "Matrix user profiles",
            },
        ),
        migrations.CreateModel(
            name="MatrixRoomMember",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("uuid", waldur_core.core.fields.UUIDField()),
                ("matrix_user_id", models.CharField(max_length=255)),
                ("power_level", models.IntegerField(default=0)),
                (
                    "membership_state",
                    models.CharField(
                        choices=[
                            ("invited", "Invited"),
                            ("joined", "Joined"),
                            ("left", "Left"),
                            ("banned", "Banned"),
                        ],
                        default="invited",
                        max_length=20,
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="matrix_chat.matrixroom",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Matrix room member",
                "verbose_name_plural": "Matrix room members",
                "unique_together": {("room", "user")},
            },
        ),
    ]
