# Generated by Django 6.0.8 on 2026-10-01 15:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("matrix_chat", "0003_alter_matrixappservicetransaction_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="matrixuserprofile",
            name="access_token",
        ),
    ]
