# Generated by Django 6.0.8 on 2026-10-06 15:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("matrix_chat", "0004_remove_matrixuserprofile_access_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="matrixuserprofile",
            name="last_web_session_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When Waldur last signed the user in on a web chat device. Cleared once none of those devices is left, so the daily prune only asks the homeserver about users who may still have one.",
                null=True,
            ),
        ),
    ]
