# Generated by Django 6.0.8 on 2026-10-02 18:16

from django.db import migrations, models


def mark_staff_memberships(apps, schema_editor):
    # Before this field, every staff and support user was spared by member sync,
    # since only the staff Join button put them in rooms without a role. Keep
    # existing ones in place; from now on only the button sets the flag.
    MatrixRoomMember = apps.get_model("matrix_chat", "MatrixRoomMember")
    MatrixRoomMember.objects.filter(
        models.Q(user__is_staff=True) | models.Q(user__is_support=True)
    ).update(manually_joined=True)


class Migration(migrations.Migration):
    dependencies = [
        ("matrix_chat", "0005_matrixuserprofile_last_web_session_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="matrixroommember",
            name="manually_joined",
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(mark_staff_memberships, migrations.RunPython.noop),
    ]
