# Generated by Django 6.0.8 on 2026-10-09 11:18

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models

import waldur_core.core.fields


class Migration(migrations.Migration):
    dependencies = [
        ("matrix_chat", "0008_crypto_temporary_password_until"),
    ]

    operations = [
        migrations.CreateModel(
            name="MatrixBotIdentity",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("user_id", models.CharField(max_length=255, unique=True)),
                ("device_id", models.CharField(max_length=64)),
                ("pickle_key", waldur_core.core.fields.EncryptedTextField()),
                (
                    "cross_signing_seeds",
                    waldur_core.core.fields.EncryptedTextField(blank=True, default=""),
                ),
                (
                    "access_token",
                    waldur_core.core.fields.EncryptedTextField(blank=True, default=""),
                ),
                (
                    "access_token_homeserver",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "lease_holder",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("lease_expires_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Matrix bot identity",
            },
        ),
        migrations.CreateModel(
            name="MatrixOutboxMessage",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("uuid", waldur_core.core.fields.UUIDField()),
                ("body", models.TextField()),
                (
                    "reply_to",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Event the message replies to; a command is answered once.",
                        max_length=255,
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("sent", "Sent"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("attempts", models.PositiveSmallIntegerField(default=0)),
                (
                    "next_attempt_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("error_message", models.TextField(blank=True)),
                ("event_id", models.CharField(blank=True, max_length=255)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outbox_messages",
                        to="matrix_chat.matrixroom",
                    ),
                ),
            ],
            options={
                "ordering": ["created", "id"],
                "indexes": [
                    models.Index(
                        fields=["state", "next_attempt_at"],
                        name="matrix_chat_state_5ebfc2_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("reply_to", ""), _negated=True),
                        fields=("room", "reply_to"),
                        name="matrix_outbox_one_reply_per_event",
                    )
                ],
            },
        ),
    ]
