# Generated by Django 6.0.8 on 2026-10-10 17:55

import django.db.models.deletion
from django.db import migrations, models

import waldur_core.core.fields


class Migration(migrations.Migration):
    dependencies = [
        ("matrix_chat", "0011_member_history_backfill"),
    ]

    operations = [
        migrations.AddField(
            model_name="matrixhistoryexport",
            name="data_key",
            field=waldur_core.core.fields.EncryptedTextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="matrixroom",
            name="closing_export",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="matrix_chat.matrixhistoryexport",
            ),
        ),
    ]
