# Generated by Django 6.0.8 on 2026-08-28 11:38

import uuid

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.conf import settings
from django.db import migrations, models

import waldur_core.core.fields
import waldur_core.core.validators


class Migration(migrations.Migration):
    replaces = [
        ("chat", "0001_initial"),
        ("chat", "0002_chatsession_threadsession_message_and_more"),
        ("chat", "0003_message_injection_categories_message_injection_score_and_more"),
        ("chat", "0004_remove_message_injection_score_message_action_taken_and_more"),
        ("chat", "0005_message_tool_calls"),
        ("chat", "0006_threadsession_cancel_requested_at_and_more"),
        ("chat", "0007_token_tracking_fields"),
        ("chat", "0008_message_blocks_warning"),
        ("chat", "0009_message_feedback_category_message_feedback_comment_and_more"),
        ("chat", "0008_systemprompt"),
        ("chat", "0010_merge_20260421_0810"),
        ("chat", "0011_anonymouschatclick_anonymouschatinteraction_and_more"),
        ("chat", "0012_alter_anonymouschatfeedback_llm_intent_category"),
        ("chat", "0013_anonymouschatinteraction_search_text_and_more"),
        ("chat", "0014_chat_search_gin_indexes"),
        ("chat", "0015_anonymouschatinteraction_input_tokens_and_more"),
        ("chat", "0016_anonymouschatinteraction_model_message_model"),
        ("chat", "0017_alter_anonymouschatfeedback_options_and_more"),
        ("chat", "0018_alter_message_options_alter_systemprompt_options"),
    ]

    dependencies = [
        ("core", "__first__"),
    ]

    operations = [
        migrations.CreateModel(
            name="AnonymousChatClick",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("offering_uuid", models.UUIDField()),
                (
                    "clicked_at",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
            ],
            options={
                "verbose_name": "Anonymous Chat Click",
                "verbose_name_plural": "Anonymous Chat Clicks",
            },
        ),
        migrations.CreateModel(
            name="AnonymousChatInteraction",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("offering_uuids", models.JSONField(default=list)),
                ("result_count", models.PositiveIntegerField(default=0)),
                (
                    "input_tokens",
                    models.PositiveIntegerField(blank=True, default=None, null=True),
                ),
                (
                    "output_tokens",
                    models.PositiveIntegerField(blank=True, default=None, null=True),
                ),
                (
                    "model",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=150
                    ),
                ),
                (
                    "user_slug",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=128
                    ),
                ),
                ("user_input", models.TextField(blank=True, default="")),
                ("assistant_blocks", models.JSONField(default=list)),
                ("search_text", models.TextField(blank=True, default="")),
                (
                    "search_vector",
                    models.GeneratedField(
                        db_persist=True,
                        expression=django.contrib.postgres.search.SearchVector(
                            "search_text", config="english"
                        ),
                        output_field=django.contrib.postgres.search.SearchVectorField(),
                    ),
                ),
                ("is_flagged", models.BooleanField(default=False)),
                ("severity", models.CharField(blank=True, default="", max_length=16)),
                ("injection_categories", models.JSONField(default=list)),
                ("pii_categories", models.JSONField(default=list)),
                (
                    "action_taken",
                    models.CharField(blank=True, default="", max_length=16),
                ),
                ("warning", models.TextField(blank=True, default="")),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("session_id", models.CharField(blank=True, max_length=64)),
                ("last_active_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
            ],
            options={
                "verbose_name": "Anonymous Chat Interaction",
                "verbose_name_plural": "Anonymous Chat Interactions",
                "ordering": ["-created", "id"],
            },
        ),
        migrations.CreateModel(
            name="ChatSession",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("uuid", waldur_core.core.fields.UUIDField()),
            ],
            options={
                "verbose_name": "Chat session",
            },
        ),
        migrations.CreateModel(
            name="GlobalAssistantBudget",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "pk_singleton",
                    models.PositiveSmallIntegerField(
                        default=1, primary_key=True, serialize=False
                    ),
                ),
                ("daily_token_usage", models.PositiveBigIntegerField(default=0)),
                (
                    "daily_reset_last_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("minute_request_usage", models.PositiveBigIntegerField(default=0)),
                (
                    "minute_reset_last_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
            options={
                "verbose_name": "Global Assistant Budget",
                "verbose_name_plural": "Global Assistant Budgets",
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("uuid", waldur_core.core.fields.UUIDField()),
                (
                    "role",
                    models.CharField(
                        choices=[("user", "User"), ("assistant", "Assistant")],
                        max_length=10,
                    ),
                ),
                ("blocks", models.JSONField(default=list)),
                ("search_text", models.TextField(blank=True, default="")),
                (
                    "search_vector",
                    models.GeneratedField(
                        db_persist=True,
                        expression=django.contrib.postgres.search.SearchVector(
                            "search_text", config="english"
                        ),
                        output_field=django.contrib.postgres.search.SearchVectorField(),
                    ),
                ),
                ("warning", models.TextField(blank=True, default="")),
                ("sequence_index", models.PositiveIntegerField()),
                (
                    "input_tokens",
                    models.PositiveIntegerField(blank=True, default=None, null=True),
                ),
                (
                    "output_tokens",
                    models.PositiveIntegerField(blank=True, default=None, null=True),
                ),
                (
                    "model",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=150
                    ),
                ),
                ("is_flagged", models.BooleanField(db_index=True, default=False)),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("none", "none"),
                            ("low", "low"),
                            ("medium", "medium"),
                            ("high", "high"),
                            ("critical", "critical"),
                        ],
                        db_index=True,
                        default="none",
                        max_length=10,
                    ),
                ),
                ("injection_categories", models.JSONField(blank=True, default=list)),
                ("pii_categories", models.JSONField(blank=True, default=list)),
                (
                    "action_taken",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("allow", "allow"),
                            ("flag", "flag"),
                            ("warn", "warn"),
                            ("redact", "redact"),
                            ("block", "block"),
                        ],
                        db_index=True,
                        default="allow",
                        max_length=10,
                    ),
                ),
                (
                    "feedback_score",
                    models.BooleanField(
                        blank=True,
                        default=None,
                        help_text="User feedback: True=thumbs up, False=thumbs down, None=no feedback.",
                        null=True,
                    ),
                ),
                (
                    "feedback_comment",
                    models.TextField(
                        blank=True,
                        default=None,
                        help_text="Optional user comment accompanying feedback.",
                        null=True,
                    ),
                ),
                (
                    "feedback_category",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("inaccurate", "Inaccurate"),
                            ("incomplete", "Incomplete"),
                            ("misunderstood", "Misunderstood"),
                            ("slow_or_failed", "Slow or failed"),
                            ("other", "Other"),
                        ],
                        default=None,
                        help_text="Category tag when feedback_score is False (thumbs down); null otherwise.",
                        max_length=32,
                        null=True,
                    ),
                ),
                (
                    "feedback_submitted_at",
                    models.DateTimeField(
                        blank=True,
                        default=None,
                        help_text="Timestamp of the most recent feedback submission; overwritten on resubmit.",
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Message",
                "ordering": ["sequence_index", "id"],
            },
        ),
        migrations.CreateModel(
            name="SessionBinding",
            fields=[
                (
                    "session_id",
                    models.CharField(max_length=64, primary_key=True, serialize=False),
                ),
                ("ip_address", models.GenericIPAddressField()),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("last_seen", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Session Binding",
                "verbose_name_plural": "Session Bindings",
            },
        ),
        migrations.CreateModel(
            name="SystemPrompt",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=4096, verbose_name="description"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=150,
                        validators=[waldur_core.core.validators.validate_name],
                        verbose_name="name",
                    ),
                ),
                ("uuid", waldur_core.core.fields.UUIDField()),
                (
                    "custom_instructions",
                    models.TextField(
                        blank=True,
                        help_text="Additional instructions injected into the system prompt. Use this for organisation-specific context, terminology, FAQ content, or behavioural guidelines. Supports {assistant_name} and {organization} placeholders.",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this prompt is currently used by the AI Assistant. Only one prompt can be active.",
                    ),
                ),
            ],
            options={
                "verbose_name": "System Prompt",
                "verbose_name_plural": "System Prompts",
                "ordering": ["-created", "id"],
            },
        ),
        migrations.CreateModel(
            name="ThreadSession",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("uuid", waldur_core.core.fields.UUIDField()),
                (
                    "name",
                    models.CharField(
                        default="New chat", max_length=150, verbose_name="name"
                    ),
                ),
                ("flags", models.JSONField(blank=True, default=dict)),
                ("is_archived", models.BooleanField(default=False)),
                (
                    "cancel_requested_at",
                    models.DateTimeField(
                        blank=True,
                        default=None,
                        help_text="Set when user requests stream cancellation; cleared after stream completes.",
                        null=True,
                    ),
                ),
                (
                    "title_gen_input_tokens",
                    models.PositiveIntegerField(
                        blank=True,
                        default=None,
                        help_text="Input tokens consumed by the title generation LLM call.",
                        null=True,
                    ),
                ),
                (
                    "title_gen_output_tokens",
                    models.PositiveIntegerField(
                        blank=True,
                        default=None,
                        help_text="Output tokens consumed by the title generation LLM call.",
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Thread session",
            },
        ),
        migrations.CreateModel(
            name="TokenQuota",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("uuid", waldur_core.core.fields.UUIDField()),
                (
                    "daily_limit",
                    models.IntegerField(
                        blank=True,
                        help_text="Daily token limit (non-negative integer). Null uses system default. -1 means unlimited.",
                        null=True,
                        validators=[django.core.validators.MinValueValidator(-1)],
                    ),
                ),
                (
                    "weekly_limit",
                    models.IntegerField(
                        blank=True,
                        help_text="Weekly token limit (non-negative integer). Null uses system default. -1 means unlimited.",
                        null=True,
                        validators=[django.core.validators.MinValueValidator(-1)],
                    ),
                ),
                (
                    "monthly_limit",
                    models.IntegerField(
                        blank=True,
                        help_text="Monthly token limit (non-negative integer). Null uses system default. -1 means unlimited.",
                        null=True,
                        validators=[django.core.validators.MinValueValidator(-1)],
                    ),
                ),
                ("daily_usage", models.PositiveIntegerField(default=0)),
                ("weekly_usage", models.PositiveIntegerField(default=0)),
                ("monthly_usage", models.PositiveIntegerField(default=0)),
                (
                    "daily_reset_last_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "weekly_reset_last_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "monthly_reset_last_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
            options={
                "verbose_name": "Token Quota",
                "verbose_name_plural": "Token Quotas",
            },
        ),
        migrations.CreateModel(
            name="AnonymousChatBudget",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(unique=True)),
                ("daily_token_usage", models.PositiveIntegerField(default=0)),
                ("weekly_token_usage", models.PositiveIntegerField(default=0)),
                ("monthly_token_usage", models.PositiveIntegerField(default=0)),
                ("daily_injection_strikes", models.PositiveIntegerField(default=0)),
                (
                    "daily_reset_last_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "weekly_reset_last_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "monthly_reset_last_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("is_blocked_until", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Anonymous Chat Budget",
                "verbose_name_plural": "Anonymous Chat Budgets",
                "indexes": [
                    models.Index(
                        fields=["ip_address"], name="chat_anonym_ip_addr_50ad9e_idx"
                    ),
                    models.Index(
                        fields=["daily_reset_last_at"],
                        name="chat_anonym_daily_r_165348_idx",
                    ),
                    models.Index(
                        fields=["weekly_reset_last_at"],
                        name="chat_anonym_weekly__b7eb17_idx",
                    ),
                    models.Index(
                        fields=["monthly_reset_last_at"],
                        name="chat_anonym_monthly_7d9e9f_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="AnonymousChatFeedback",
            fields=[
                (
                    "interaction",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="feedback",
                        serialize=False,
                        to="chat.anonymouschatinteraction",
                    ),
                ),
                ("score", models.SmallIntegerField(blank=True, null=True)),
                ("comment", models.TextField(blank=True, default="")),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("inaccurate", "Inaccurate"),
                            ("incomplete", "Incomplete"),
                            ("misunderstood", "Misunderstood"),
                            ("slow_or_failed", "Slow or failed"),
                            ("other", "Other"),
                        ],
                        default="",
                        max_length=32,
                    ),
                ),
                (
                    "submitted_from_ip",
                    models.GenericIPAddressField(blank=True, null=True),
                ),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "llm_resolution_score",
                    models.SmallIntegerField(blank=True, null=True),
                ),
                (
                    "llm_intent_category",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                ("llm_hallucination_detected", models.BooleanField(default=False)),
                ("llm_hallucination_details", models.TextField(blank=True, default="")),
                ("llm_summary", models.TextField(blank=True, default="")),
                ("llm_reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("llm_judge_input_tokens", models.PositiveIntegerField(default=0)),
                ("llm_judge_output_tokens", models.PositiveIntegerField(default=0)),
                (
                    "llm_judge_model",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "modified_at",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
            ],
            options={
                "verbose_name": "Anonymous Chat Feedback",
                "verbose_name_plural": "Anonymous Chat Feedbacks",
                "ordering": ["-interaction_id"],
            },
        ),
        migrations.AddIndex(
            model_name="anonymouschatinteraction",
            index=models.Index(
                fields=["created"], name="chat_anonym_created_3252d1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="anonymouschatinteraction",
            index=models.Index(
                fields=["session_id", "created"], name="chat_anonym_session_640021_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="anonymouschatinteraction",
            index=models.Index(
                fields=["user_slug", "created"], name="chat_anonym_user_sl_60722e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="anonymouschatinteraction",
            index=models.Index(fields=["uuid"], name="chat_anonym_uuid_a3507f_idx"),
        ),
        migrations.AddIndex(
            model_name="anonymouschatinteraction",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["search_vector"], name="anon_chat_search_gin"
            ),
        ),
        migrations.AddField(
            model_name="anonymouschatclick",
            name="interaction",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="clicks",
                to="chat.anonymouschatinteraction",
            ),
        ),
        migrations.AddField(
            model_name="chatsession",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chat_session",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="replaces",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="replaced_by",
                to="chat.message",
            ),
        ),
        migrations.AddIndex(
            model_name="sessionbinding",
            index=models.Index(
                fields=["created"], name="chat_sessio_created_50610d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sessionbinding",
            index=models.Index(
                fields=["last_seen"], name="chat_sessio_last_se_2f595a_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="systemprompt",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True)),
                fields=("is_active",),
                name="unique_active_system_prompt",
            ),
        ),
        migrations.AddField(
            model_name="threadsession",
            name="chat_session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="threads",
                to="chat.chatsession",
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="thread",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages",
                to="chat.threadsession",
            ),
        ),
        migrations.AddField(
            model_name="tokenquota",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="token_quota",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="anonymouschatfeedback",
            index=models.Index(fields=["score"], name="chat_anonym_score_fc4818_idx"),
        ),
        migrations.AddIndex(
            model_name="anonymouschatfeedback",
            index=models.Index(
                fields=["submitted_at"], name="chat_anonym_submitt_9b3297_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="anonymouschatfeedback",
            index=models.Index(
                fields=["llm_resolution_score"], name="chat_anonym_llm_res_6e2fa9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="anonymouschatfeedback",
            index=models.Index(
                fields=["llm_intent_category"], name="chat_anonym_llm_int_52f314_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="anonymouschatfeedback",
            index=models.Index(
                fields=["llm_hallucination_detected"],
                name="chat_anonym_llm_hal_48fe33_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="anonymouschatfeedback",
            index=models.Index(
                fields=["llm_reviewed_at"], name="chat_anonym_llm_rev_88b2d3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="anonymouschatclick",
            index=models.Index(
                fields=["offering_uuid", "clicked_at"],
                name="chat_anonym_offerin_941a45_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="anonymouschatclick",
            index=models.Index(
                fields=["clicked_at"], name="chat_anonym_clicked_b5d419_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="anonymouschatclick",
            index=models.Index(
                fields=["interaction"], name="chat_anonym_interac_ed198f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="threadsession",
            index=models.Index(
                fields=["chat_session"], name="chat_thread_chat_se_6c2505_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["thread"], name="chat_messag_thread__b199c2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["replaces"], name="chat_messag_replace_3cc074_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                condition=models.Q(("feedback_score__isnull", False)),
                fields=["feedback_score"],
                name="chat_msg_fb_score_partial_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["search_vector"], name="chat_msg_search_gin"
            ),
        ),
        migrations.AddConstraint(
            model_name="message",
            constraint=models.UniqueConstraint(
                condition=models.Q(("replaces__isnull", True)),
                fields=("thread", "sequence_index"),
                name="unique_active_message_sequence",
            ),
        ),
        migrations.AddIndex(
            model_name="tokenquota",
            index=models.Index(fields=["user"], name="chat_tokenq_user_id_1d24d4_idx"),
        ),
        migrations.AddIndex(
            model_name="tokenquota",
            index=models.Index(
                fields=["daily_reset_last_at"], name="chat_tokenq_daily_r_8eca0a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tokenquota",
            index=models.Index(
                fields=["weekly_reset_last_at"], name="chat_tokenq_weekly__00e972_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tokenquota",
            index=models.Index(
                fields=["monthly_reset_last_at"], name="chat_tokenq_monthly_0aecdf_idx"
            ),
        ),
    ]
