# Generated by Django 6.0.2 on 2026-03-09 14:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0004_remove_message_injection_score_message_action_taken_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="tool_calls",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
