# Generated by Django 6.0.3 on 2026-03-27 11:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0005_message_tool_calls"),
    ]

    operations = [
        migrations.AddField(
            model_name="threadsession",
            name="cancel_requested_at",
            field=models.DateTimeField(
                blank=True,
                default=None,
                help_text="Set when user requests stream cancellation; cleared after stream completes.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="content",
            field=models.TextField(blank=True),
        ),
    ]
