# Generated by Django 6.0.4 on 2026-04-21 08:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0008_systemprompt"),
        ("chat", "0009_message_feedback_category_message_feedback_comment_and_more"),
    ]

    operations = []
