# Generated by Django 6.0.7 on 2026-07-17 08:17

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations, models

from waldur_mastermind.chat.block_schemas import blocks_to_text


def _backfill(model, search_text_fn):
    # Populate search_text on pre-existing rows. search_vector is a stored
    # generated column, so Postgres recomputes it automatically from the new
    # search_text — no separate vector update needed.
    batch = []
    for row in model.objects.all().iterator(chunk_size=500):
        row.search_text = search_text_fn(row)
        batch.append(row)
        if len(batch) >= 500:
            model.objects.bulk_update(batch, ["search_text"])
            batch.clear()
    if batch:
        model.objects.bulk_update(batch, ["search_text"])


def backfill(apps, schema_editor):
    Message = apps.get_model("chat", "Message")
    Interaction = apps.get_model("chat", "AnonymousChatInteraction")
    _backfill(Message, lambda m: blocks_to_text(m.blocks))
    _backfill(
        Interaction,
        lambda i: "\n".join(
            p
            for p in [i.user_input or "", blocks_to_text(i.assistant_blocks or [])]
            if p
        ),
    )


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0012_alter_anonymouschatfeedback_llm_intent_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="anonymouschatinteraction",
            name="search_text",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="message",
            name="search_text",
            field=models.TextField(blank=True, default=""),
        ),
        # search_vector must be added before its GIN index references it.
        migrations.AddField(
            model_name="anonymouschatinteraction",
            name="search_vector",
            field=models.GeneratedField(
                db_persist=True,
                expression=django.contrib.postgres.search.SearchVector(
                    "search_text", config="english"
                ),
                output_field=django.contrib.postgres.search.SearchVectorField(),
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="search_vector",
            field=models.GeneratedField(
                db_persist=True,
                expression=django.contrib.postgres.search.SearchVector(
                    "search_text", config="english"
                ),
                output_field=django.contrib.postgres.search.SearchVectorField(),
            ),
        ),
        # Backfill existing rows' search_text before creating the GIN indexes so
        # each index is built once in a single bulk pass, instead of taking a
        # per-row incremental insert for every backfilled row. The generated
        # search_vector derives from search_text automatically.
        migrations.RunPython(backfill, noop),
        migrations.AddIndex(
            model_name="anonymouschatinteraction",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["search_vector"], name="anon_chat_search_gin"
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["search_vector"], name="chat_msg_search_gin"
            ),
        ),
    ]
