# Generated by Django 6.0.7 on 2026-07-20 10:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0014_chat_search_gin_indexes"),
    ]

    operations = [
        migrations.AddField(
            model_name="anonymouschatinteraction",
            name="input_tokens",
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="anonymouschatinteraction",
            name="output_tokens",
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
    ]
