# Generated by Django 6.0.8 on 2026-08-20 07:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0016_anonymouschatinteraction_model_message_model"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="anonymouschatfeedback",
            options={
                "ordering": ["-interaction_id"],
                "verbose_name": "Anonymous Chat Feedback",
                "verbose_name_plural": "Anonymous Chat Feedbacks",
            },
        ),
        migrations.AlterModelOptions(
            name="anonymouschatinteraction",
            options={
                "ordering": ["-created", "id"],
                "verbose_name": "Anonymous Chat Interaction",
                "verbose_name_plural": "Anonymous Chat Interactions",
            },
        ),
    ]
