# Generated by Django 4.2.24 on 2025-10-08 09:38

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.conf import settings
from django.db import migrations, models

import waldur_core.core.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("structure", "0061_customer_notification_emails"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OnboardingJustification",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("uuid", waldur_core.core.fields.UUIDField()),
                (
                    "user_justification",
                    models.TextField(
                        help_text="User's explanation for why they should be authorized"
                    ),
                ),
                ("validated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "validation_decision",
                    models.CharField(
                        choices=[
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("pending", "Pending Review"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "staff_notes",
                    models.TextField(
                        blank=True,
                        help_text="Administrator notes on the review decision",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="onboarding_justifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "validated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_justifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="OnboardingVerification",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("uuid", waldur_core.core.fields.UUIDField()),
                ("error_message", models.TextField(blank=True)),
                ("error_traceback", models.TextField(blank=True)),
                (
                    "country",
                    models.CharField(
                        help_text="ISO country code (e.g., 'EE' for Estonia)",
                        max_length=2,
                    ),
                ),
                (
                    "legal_person_identifier",
                    models.CharField(
                        help_text="Official company registration code", max_length=50
                    ),
                ),
                (
                    "legal_name",
                    models.CharField(
                        blank=True,
                        help_text="Claimed company name (optional, for reference)",
                        max_length=255,
                    ),
                ),
                (
                    "user_submitted_customer_metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional customer metadata submitted by user for manual verification cases. Should contain valid Customer model fields.",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("verified", "Verified"),
                            ("failed", "Failed"),
                            ("escalated", "Escalated for manual validation"),
                            ("expired", "Expired"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "validation_method",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("ariregister", "Estonian Business Register (ariregister)")
                        ],
                        help_text="Method used for validation",
                        max_length=50,
                    ),
                ),
                (
                    "verified_user_roles",
                    models.JSONField(
                        default=list, help_text="Roles the user has in the company"
                    ),
                ),
                (
                    "verified_company_data",
                    models.JSONField(
                        default=dict,
                        help_text="Company information retrieved during validation",
                    ),
                ),
                (
                    "raw_response",
                    models.JSONField(
                        default=dict,
                        help_text="Raw API response for debugging and auditing",
                    ),
                ),
                (
                    "validated_at",
                    models.DateTimeField(
                        blank=True, help_text="When validation was completed", null=True
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When this verification expires",
                        null=True,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        help_text="Customer created after successful validation",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="onboarding_verifications",
                        to="structure.customer",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User requesting company onboarding",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="onboarding_verifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created"],
            },
        ),
        migrations.CreateModel(
            name="OnboardingJustificationDocumentation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("uuid", waldur_core.core.fields.UUIDField()),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        help_text="Upload supporting documentation.",
                        null=True,
                        upload_to="onboarding_justification_documentation",
                    ),
                ),
                (
                    "justification",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="supporting_documentation",
                        to="onboarding.onboardingjustification",
                    ),
                ),
            ],
            options={
                "ordering": ["-created"],
            },
        ),
        migrations.AddField(
            model_name="onboardingjustification",
            name="verification",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="justifications",
                to="onboarding.onboardingverification",
            ),
        ),
    ]
