# Generated by Django 4.2.23 on 2025-10-29 11:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("onboarding", "0003_onboarding_checklists"),
    ]

    operations = [
        migrations.AlterField(
            model_name="onboardingverification",
            name="validation_method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ariregister", "Estonian Business Register (ariregister)"),
                    (
                        "wirtschaftscompass",
                        "Austrian Business Register (WirtschaftsCompass)",
                    ),
                ],
                help_text="Method used for validation",
                max_length=50,
            ),
        ),
    ]
