# Generated by Django 4.2.24 on 2025-11-12 14:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("onboarding", "0004_alter_onboardingverification_validation_method"),
    ]

    operations = [
        migrations.AlterField(
            model_name="onboardingverification",
            name="validation_method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ariregister", "Estonian Business Register (ariregister)"),
                    (
                        "wirtschaftscompass",
                        "Austrian Business Register (WirtschaftsCompass)",
                    ),
                    ("bolagsverket", "Swedish Business Register (Bolagsverket)"),
                ],
                help_text="Method used for validation",
                max_length=50,
            ),
        ),
    ]
