# Generated by Django 4.2.24 on 2026-01-12 08:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("onboarding", "0006_alter_onboardingverification_validation_method_norwegian"),
    ]

    operations = [
        migrations.AlterField(
            model_name="onboardingverification",
            name="country",
            field=models.CharField(
                blank=True,
                help_text="ISO country code (e.g., 'EE', 'AT') for context. Can be inferred from validation_method.",
                max_length=2,
            ),
        ),
        migrations.DeleteModel(
            name="OnboardingCountryChecklistConfiguration",
        ),
    ]
