# Generated by Django 6.0.8 on 2026-08-20 07:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("onboarding", "0008_alter_onboardingverification_validation_method_dnb"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="onboardingjustification",
            options={"ordering": ["-created", "id"]},
        ),
        migrations.AlterModelOptions(
            name="onboardingquestionmetadata",
            options={
                "ordering": ["-created", "id"],
                "verbose_name": "Onboarding Question Metadata",
                "verbose_name_plural": "Onboarding Question Metadata",
            },
        ),
    ]
