# Generated by Django 6.0.8 on 2026-08-20 13:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("onboarding", "0009_alter_onboardingjustification_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="onboardingverification",
            options={"ordering": ["-created", "id"]},
        ),
    ]
