# Generated by Django 6.0.8 on 2026-08-21 06:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("onboarding", "0010_alter_onboardingverification_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="onboardingjustificationdocumentation",
            options={"ordering": ["-created", "id"]},
        ),
    ]
