# Generated by Django 3.2.18 on 2023-06-01 13:30

import django.db.models.deletion
import django.utils.timezone
import django_fsm
import model_utils.fields
from django.db import migrations, models

import waldur_core.core.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("marketplace", "0088_usage_decimal"),
    ]

    operations = [
        migrations.CreateModel(
            name="DryRun",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("uuid", waldur_core.core.fields.UUIDField()),
                ("error_message", models.TextField(blank=True)),
                ("error_traceback", models.TextField(blank=True)),
                ("order_item_attributes", models.JSONField(blank=True, default=dict)),
                ("order_item_type", models.CharField(max_length=255)),
                (
                    "state",
                    django_fsm.FSMIntegerField(
                        choices=[
                            (1, "pending"),
                            (2, "executing"),
                            (3, "done"),
                            (4, "erred"),
                        ],
                        default=1,
                    ),
                ),
                ("output", models.TextField(blank=True)),
                (
                    "order",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="marketplace.order",
                    ),
                ),
                (
                    "order_item_offering",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="marketplace.offering",
                    ),
                ),
                (
                    "order_item_plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="marketplace.plan",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dry run",
                "ordering": ("created",),
            },
        ),
    ]
