# Generated by Django 3.2.20 on 2024-01-17 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("marketplace", "0122_add_missing_plan_periods"),
        ("marketplace_script", "0005_rename_order_item_to_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dryrun",
            name="order_plan",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="marketplace.plan",
            ),
        ),
    ]
