# Generated by Django 6.0.8 on 2026-08-20 13:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("marketplace_script", "0006_alter_dryrun_order_plan"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dryrun",
            options={"ordering": ["created", "id"], "verbose_name": "Dry run"},
        ),
    ]
