# Generated by Django 4.2.24 on 2025-12-07 09:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_actions", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="useraction",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="useractionexecution",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="useractionprovider",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
