# Generated by Django 4.2.24 on 2025-12-18 19:34

from django.db import migrations, models

import waldur_core.core.fields


class Migration(migrations.Migration):
    dependencies = [
        (
            "user_actions",
            "0002_alter_useraction_id_alter_useractionexecution_id_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="useraction",
            name="action_url",
        ),
        migrations.RemoveField(
            model_name="useraction",
            name="metadata",
        ),
        migrations.AddField(
            model_name="useraction",
            name="offering_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="useraction",
            name="offering_type",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="useraction",
            name="organization_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="useraction",
            name="organization_uuid",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="useraction",
            name="project_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="useraction",
            name="project_uuid",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="useraction",
            name="route_name",
            field=models.CharField(
                blank=True,
                help_text="UI-Router state name for navigation",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="useraction",
            name="route_params",
            field=waldur_core.core.fields.JSONField(
                blank=True, default=dict, help_text="Parameters for route navigation"
            ),
        ),
    ]
