# Generated by Django 4.2.27 on 2026-01-13 16:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_actions", "0003_remove_useraction_action_url_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="useraction",
            name="order_type",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="useraction",
            name="resource_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="useraction",
            name="resource_uuid",
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
