# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-21 20:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0007_screenshots'),
        ('marketplace', '0006_allow_svg_category_icon'),
    ]

    operations = [
    ]
