# Generated by Django 2.2.10 on 2020-03-19 10:37

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('marketplace', '0013_increase_limit_range'),
    ]

    operations = [
        migrations.AddField(
            model_name='offering',
            name='secret_options',
            field=django.contrib.postgres.fields.jsonb.JSONField(
                blank=True,
                default=dict,
                help_text='Private data used by specific plugin, such as credentials and hooks.',
            ),
        ),
        migrations.AlterField(
            model_name='offering',
            name='plugin_options',
            field=django.contrib.postgres.fields.jsonb.JSONField(
                blank=True,
                default=dict,
                help_text='Public data used by specific plugin, such as storage mode for OpenStack.',
            ),
        ),
    ]
