# Generated by Django 2.2.10 on 2020-04-28 09:44

from django.db import migrations

import waldur_core.core.fields


def update_default_referrals(apps, schema_editor):
    Offering = apps.get_model('marketplace', 'Offering')
    for offering in Offering.objects.all():
        if offering.referrals == {}:
            offering.referrals = []
            offering.save(update_fields=['referrals'])


class Migration(migrations.Migration):
    dependencies = [
        ('marketplace', '0017_change_default_disable_quotas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offering',
            name='referrals',
            field=waldur_core.core.fields.JSONField(
                blank=True, default=list, help_text='Referrals list for the current DOI'
            ),
        ),
        migrations.RunPython(update_default_referrals),
    ]
