# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-30 07:16
from __future__ import unicode_literals

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0028_offering_type_is_mandatory'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='state',
            field=django_fsm.FSMIntegerField(
                choices=[(1, 'pending'), (2, 'executing'), (3, 'done'), (4, 'erred'), (5, 'terminated')],
                default=1),
        ),
    ]
