# Generated by Django 2.2.13 on 2020-11-04 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0030_offering_data_to_invoice_item_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offering',
            name='type',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
