# Generated by Django 2.2.13 on 2020-11-04 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0032_fix_offering_uuid_in_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offering',
            name='type',
            field=models.CharField(max_length=100),
        ),
    ]
