# Generated by Django 2.2.13 on 2020-11-23 13:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('marketplace', '0033_mandatory_offering_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='offering',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='offering',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='offering',
            name='geolocations',
        ),
    ]
