# Generated by Django 2.2.13 on 2021-01-19 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0035_offeringpermission'),
    ]

    operations = [
        migrations.AddField(
            model_name='offeringcomponent',
            name='backend_id',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
