# Generated by Django 2.2.13 on 2021-02-26 11:42

from django.core.exceptions import ObjectDoesNotExist
from django.db import migrations, models


def set_default_tenant_flag_to_categories(apps, schema_editor):
    Category = apps.get_model('marketplace', 'Category')

    try:
        vm_category = Category.objects.get(title='VPC')
    except ObjectDoesNotExist:
        pass
    else:
        vm_category.default_tenant_category = True
        vm_category.save()


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0042_default_openstack_category_flags'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='default_tenant_category',
            field=models.BooleanField(
                default=False,
                help_text='Set to true if this category is for OpenStack Tenant. Only one category can have "true" value.',
            ),
        ),
        migrations.RunPython(set_default_tenant_flag_to_categories),
    ]
