# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-20 13:59
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0046_migrate_resource'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='limits',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='resource',
            name='limits',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='componentquota',
            name='resource',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quotas', to='marketplace.Resource'),
        ),
        migrations.AlterField(
            model_name='componentusage',
            name='resource',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='marketplace.Resource'),
        ),
        migrations.RemoveField(
            model_name='componentquota',
            name='order_item',
        ),
        migrations.AlterUniqueTogether(
            name='componentquota',
            unique_together=set([('resource', 'component')]),
        ),
        migrations.RemoveField(
            model_name='componentusage',
            name='order_item',
        ),
        migrations.AlterUniqueTogether(
            name='componentusage',
            unique_together=set([('resource', 'component', 'date')]),
        ),
    ]
