# Generated by Django 2.2.20 on 2021-04-12 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('structure', '0022_project_end_date'),
        ('marketplace', '0049_offeringuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='offering',
            name='project',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='+',
                to='structure.Project',
            ),
        ),
    ]
