# Generated by Django 2.2.20 on 2021-04-12 22:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('marketplace', '0050_offering_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offering',
            name='allowed_customers',
        ),
    ]
