# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-07 10:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0059_offering_backend_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='backend_id',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
