# Generated by Django 3.2.14 on 2022-08-23 12:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('marketplace', '0073_update_internal_name_validator'),
    ]

    operations = [
        migrations.AddField(
            model_name='offeringcomponent',
            name='max_available_limit',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
