# Generated by Django 3.2.16 on 2023-01-18 13:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def cleanup_component_usage_log(apps, schema_editor):
    step = 1000
    Event = apps.get_model('logging', 'Event')
    events_to_drop = Event.objects.filter(
        event_type__in=[
            'marketplace_component_usage_created',
            'marketplace_component_usage_updated',
        ]
    )

    while events_to_drop.count() > 0:
        event_subset = events_to_drop[:step]
        event_subset_ids = event_subset.values_list("id", flat=True)
        Event.objects.filter(id__in=event_subset_ids).delete()

        events_to_drop = Event.objects.filter(
            event_type__in=[
                'marketplace_component_usage_created',
                'marketplace_component_usage_updated',
            ]
        )


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('marketplace', '0078_alter_offering_parent'),
    ]

    operations = [
        migrations.RunPython(cleanup_component_usage_log),
        migrations.AddField(
            model_name='componentusage',
            name='modified_by',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='+',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
