# Generated by Django 3.2.18 on 2023-05-29 11:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('marketplace', '0087_robotaccount_backend_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='componentquota',
            name='limit',
            field=models.DecimalField(decimal_places=2, default=-1, max_digits=20),
        ),
        migrations.AlterField(
            model_name='componentquota',
            name='usage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='componentusage',
            name='usage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
