# Generated by Django 3.2.18 on 2023-06-26 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("marketplace", "0089_offeringusergroup"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resource",
            name="offering",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="marketplace.offering",
            ),
        ),
    ]
