# Generated by Django 3.2.20 on 2023-10-05 07:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('marketplace', '0098_robotaccount_responsible_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='offering',
            name='getting_started',
            field=models.TextField(blank=True),
        ),
    ]
