# Generated by Django 3.2.20 on 2023-10-25 12:49

from django.db import migrations

import waldur_core.core.fields


class Migration(migrations.Migration):
    dependencies = [
        ('marketplace', '0100_alter_resource_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorycomponent',
            name='uuid',
            field=waldur_core.core.fields.UUIDField(),
        ),
    ]
