# Generated by Django 6.0.8 on 2026-08-28 12:03

from decimal import Decimal

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import django_fsm
import model_utils.fields
from django.conf import settings
from django.db import migrations, models

import waldur_core.core.fields
import waldur_core.core.validators


class Migration(migrations.Migration):
    replaces = [
        ("marketplace", "0108_rename_orderitem_order"),
        ("marketplace", "0109_alter_order_options"),
        ("marketplace", "0110_provider_reviewed_by"),
        ("marketplace", "0111_consumer_reviewed_by"),
        ("marketplace", "0112_delete_offeringpermission"),
        ("marketplace", "0113_init_order_resource"),
        ("marketplace", "0114_alter_order_resource"),
        ("marketplace", "0115_consumer_reviewed_by"),
        ("marketplace", "0116_plancomponent_future_price"),
        ("marketplace", "0117_offering_resource_options_alter_offering_options"),
        ("marketplace", "0118_resource_options"),
        ("marketplace", "0119_clean_componentusage"),
        ("marketplace", "0120_componentusage_unique_together"),
        ("marketplace", "0121_clean_invalid_usage"),
        ("marketplace", "0122_add_missing_plan_periods"),
        ("marketplace", "0123_drop_druplicate_usage"),
        ("marketplace", "0124_update_resource_for_orders"),
        ("marketplace", "0125_offeringuserrole_resourceuser"),
        ("marketplace", "0126_offering_backend_metadata"),
        ("marketplace", "0127_integrationstatus"),
        ("marketplace", "0128_alter_plan_unit_price"),
        ("marketplace", "0129_rename_divisions_to_organization_groups"),
        ("marketplace", "0130_fix_limits_of_slurm_offering_components"),
        ("marketplace", "0131_delete_aggregateresourcecount"),
    ]

    dependencies = [
        ("core", "__first__"),
        ("marketplace", "0107_merge_order_item_with_order_step3"),
        ("permissions", "0002_import_data"),
        ("structure", "0040_useragreement_uuid"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="OrderItem",
            new_name="Order",
        ),
        migrations.CreateModel(
            name="IntegrationStatus",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uuid", waldur_core.core.fields.UUIDField()),
                (
                    "agent_type",
                    models.CharField(
                        choices=[
                            (1, "Order processing"),
                            (2, "Usage reporting"),
                            (3, "Glauth sync"),
                        ],
                        default=1,
                        max_length=15,
                    ),
                ),
                (
                    "status",
                    django_fsm.FSMIntegerField(
                        choices=[(1, "Unknown"), (2, "Active"), (3, "Disconnected")],
                        default=1,
                    ),
                ),
                (
                    "last_request_timestamp",
                    models.DateTimeField(
                        blank=True,
                        editable=False,
                        null=True,
                        verbose_name="time of latest backend request",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OfferingUserRole",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=150,
                        validators=[waldur_core.core.validators.validate_name],
                        verbose_name="name",
                    ),
                ),
                ("uuid", waldur_core.core.fields.UUIDField()),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ResourceUser",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("uuid", waldur_core.core.fields.UUIDField()),
            ],
            options={
                "ordering": ["created"],
            },
        ),
        migrations.AlterUniqueTogether(
            name="aggregateresourcecount",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="aggregateresourcecount",
            name="category",
        ),
        migrations.RemoveField(
            model_name="aggregateresourcecount",
            name="content_type",
        ),
        migrations.AlterUniqueTogether(
            name="offeringpermission",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="offeringpermission",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="offeringpermission",
            name="offering",
        ),
        migrations.RemoveField(
            model_name="offeringpermission",
            name="user",
        ),
        migrations.RenameField(
            model_name="offering",
            old_name="divisions",
            new_name="organization_groups",
        ),
        migrations.RenameField(
            model_name="order",
            old_name="approved_at",
            new_name="consumer_reviewed_at",
        ),
        migrations.RenameField(
            model_name="order",
            old_name="approved_by",
            new_name="consumer_reviewed_by",
        ),
        migrations.RenameField(
            model_name="order",
            old_name="reviewed_at",
            new_name="provider_reviewed_at",
        ),
        migrations.RenameField(
            model_name="order",
            old_name="reviewed_by",
            new_name="provider_reviewed_by",
        ),
        migrations.RenameField(
            model_name="plan",
            old_name="divisions",
            new_name="organization_groups",
        ),
        migrations.AlterUniqueTogether(
            name="componentusage",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="offering",
            name="backend_metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="offering",
            name="resource_options",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Fields describing resource report form.",
            ),
        ),
        migrations.AddField(
            model_name="plancomponent",
            name="future_price",
            field=models.DecimalField(
                decimal_places=10,
                max_digits=22,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                verbose_name="Price per unit for future month.",
            ),
        ),
        migrations.AddField(
            model_name="resource",
            name="options",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="offering",
            name="options",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Fields describing resource provision form.",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="resource",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="marketplace.resource",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="plan",
            name="unit_price",
            field=models.DecimalField(
                decimal_places=10,
                default=0,
                max_digits=22,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
            ),
        ),
        migrations.AddConstraint(
            model_name="componentusage",
            constraint=models.UniqueConstraint(
                fields=("resource", "component", "plan_period", "billing_period"),
                name="unique_with_optional",
            ),
        ),
        migrations.AddConstraint(
            model_name="componentusage",
            constraint=models.UniqueConstraint(
                condition=models.Q(("plan_period", None)),
                fields=("resource", "component", "billing_period"),
                name="unique_without_optional",
            ),
        ),
        migrations.AddField(
            model_name="integrationstatus",
            name="offering",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="marketplace.offering"
            ),
        ),
        migrations.AddField(
            model_name="offeringuserrole",
            name="offering",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="roles",
                to="marketplace.offering",
            ),
        ),
        migrations.AddField(
            model_name="resourceuser",
            name="resource",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="users",
                to="marketplace.resource",
            ),
        ),
        migrations.AddField(
            model_name="resourceuser",
            name="role",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="marketplace.offeringuserrole",
            ),
        ),
        migrations.AddField(
            model_name="resourceuser",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.DeleteModel(
            name="AggregateResourceCount",
        ),
        migrations.DeleteModel(
            name="OfferingPermission",
        ),
        migrations.AlterUniqueTogether(
            name="integrationstatus",
            unique_together={("offering", "agent_type")},
        ),
    ]
