# Generated by Django 3.2.20 on 2023-11-20 23:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('marketplace', '0109_alter_order_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='reviewed_at',
            new_name='provider_reviewed_at',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='reviewed_by',
            new_name='provider_reviewed_by',
        ),
    ]
