# Generated by Django 3.2.20 on 2023-12-15 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('marketplace', '0113_init_order_resource'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='resource',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to='marketplace.resource'
            ),
        ),
    ]
