# Generated by Django 4.2.8 on 2024-01-10 21:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("marketplace", "0119_clean_componentusage"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="componentusage",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="componentusage",
            constraint=models.UniqueConstraint(
                fields=("resource", "component", "plan_period", "billing_period"),
                name="unique_with_optional",
            ),
        ),
        migrations.AddConstraint(
            model_name="componentusage",
            constraint=models.UniqueConstraint(
                condition=models.Q(("plan_period", None)),
                fields=("resource", "component", "billing_period"),
                name="unique_without_optional",
            ),
        ),
    ]
