# Generated by Django 4.2.8 on 2024-01-31 10:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("marketplace", "0125_offeringuserrole_resourceuser"),
    ]

    operations = [
        migrations.AddField(
            model_name="offering",
            name="backend_metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
