# Generated by Django 4.2.10 on 2024-03-06 11:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("marketplace", "0128_alter_plan_unit_price"),
    ]

    operations = [
        migrations.RenameField(
            model_name="offering",
            old_name="divisions",
            new_name="organization_groups",
        ),
        migrations.RenameField(
            model_name="plan",
            old_name="divisions",
            new_name="organization_groups",
        ),
    ]
