# Generated by Django 4.2.10 on 2024-05-01 09:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("marketplace", "0130_fix_limits_of_slurm_offering_components"),
    ]

    operations = [
        migrations.DeleteModel(
            name="AggregateResourceCount",
        ),
    ]
