# Generated by Django 4.2.10 on 2024-07-29 09:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("marketplace", "0135_alter_offeringuser_uuid"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CartItem",
        ),
    ]
