# Generated by Django 4.2.17 on 2025-01-16 09:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "marketplace",
            "0147_offering_support_per_user_consumption_limitation_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="offering",
            name="access_url",
            field=models.URLField(
                blank=True, help_text="Publicly accessible offering access URL"
            ),
        ),
    ]
