# Generated by Django 4.2.17 on 2025-01-20 12:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("marketplace", "0148_offering_access_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="resource",
            name="last_sync",
            field=models.DateTimeField(
                default=django.utils.timezone.now, editable=False
            ),
        ),
    ]
