# Generated by Django 4.2.18 on 2025-02-03 12:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("marketplace", "0150_resource_last_sync"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="offering",
            name="rating",
        ),
    ]
