# Generated by Django 4.2.19 on 2025-03-03 12:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("marketplace", "0151_remove_offering_rating"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="completed_at",
            field=models.DateTimeField(
                blank=True, editable=False, null=True, verbose_name="completion time"
            ),
        ),
    ]
