# Generated by Django 4.2.19 on 2025-03-03 14:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("marketplace", "0152_order_completed_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="offering",
            name="native_description",
        ),
        migrations.RemoveField(
            model_name="offering",
            name="native_name",
        ),
    ]
