# Generated by Django 4.2.20 on 2025-03-26 11:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("marketplace", "0157_integrationstatus_service_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="offeringuser",
            name="propagation_date",
        ),
    ]
