# Generated by Django 4.2.21 on 2025-05-28 08:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("marketplace", "0163_remove_order_activated"),
    ]

    operations = [
        migrations.AddField(
            model_name="customerserviceaccount",
            name="preferred_identifier",
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name="projectserviceaccount",
            name="preferred_identifier",
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
