# Generated by Django 4.2.20 on 2025-07-07 08:57

import django.db.models.deletion
import django.utils.timezone
import django_fsm
import model_utils.fields
from django.db import migrations, models

import waldur_core.core.fields
import waldur_core.core.validators


class Migration(migrations.Migration):
    dependencies = [
        ("structure", "0053_customer_max_service_accounts_and_more"),
        ("marketplace", "0166_cleanup_noisy_resource_update_logs"),
    ]

    operations = [
        migrations.CreateModel(
            name="BackendResourceRequest",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("uuid", waldur_core.core.fields.UUIDField()),
                ("error_message", models.TextField(blank=True)),
                ("error_traceback", models.TextField(blank=True)),
                (
                    "started",
                    models.DateTimeField(
                        blank=True,
                        help_text="Time when request processing started",
                        null=True,
                    ),
                ),
                (
                    "finished",
                    models.DateTimeField(
                        blank=True,
                        help_text="Time when request processing finished",
                        null=True,
                    ),
                ),
                (
                    "state",
                    django_fsm.FSMField(
                        choices=[
                            ("Sent", "Sent"),
                            ("Processing", "Processing"),
                            ("Done", "Done"),
                            ("Erred", "Erred"),
                        ],
                        default="Sent",
                        max_length=50,
                    ),
                ),
                (
                    "offering",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="marketplace.offering",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="BackendResource",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=150,
                        validators=[waldur_core.core.validators.validate_name],
                        verbose_name="name",
                    ),
                ),
                ("uuid", waldur_core.core.fields.UUIDField()),
                ("backend_id", models.CharField(blank=True, max_length=255)),
                ("backend_metadata", models.JSONField(blank=True, default=dict)),
                (
                    "offering",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="marketplace.offering",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="structure.project",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
