# Generated by Django 4.2.23 on 2025-07-23 12:53

import django_fsm
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("marketplace", "0169_maintenanceannouncement_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="offeringuser",
            name="service_provider_comment",
            field=models.TextField(
                blank=True,
                help_text="Additional comment for pending states like validation or account linking",
            ),
        ),
        migrations.AddField(
            model_name="offeringuser",
            name="state",
            field=django_fsm.FSMIntegerField(
                choices=[
                    (1, "Requested"),
                    (2, "Creating"),
                    (3, "Pending account linking"),
                    (4, "Pending additional validation"),
                    (5, "OK"),
                    (6, "Requested deletion"),
                    (7, "Deleting"),
                    (8, "Deleted"),
                    (9, "Error"),
                ],
                default=1,
            ),
        ),
    ]
