# Generated by Django 4.2.23 on 2025-08-05 18:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("marketplace", "0170_offeringuser_state_and_service_provider_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="maintenanceannouncement",
            name="external_reference_url",
            field=models.URLField(
                blank=True,
                help_text="Optional reference to an external maintenance tracker",
            ),
        ),
    ]
