# Generated by Django 4.2.23 on 2025-08-25 11:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("marketplace", "0176_remove_offering_terms_of_service_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="maintenanceannouncement",
            name="backend_id",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
