# Generated by Django migrations

from django.db import migrations
from django.db.models import Q


def remove_incorrect_total_billing_2025(apps, schema_editor):
    """
    Remove incorrect TOTAL period invoice items from 2025.

    Find all invoice items that are:
    1. Connected to resources with offering components of billing_type=LIMIT and limit_period=TOTAL
    2. Do NOT have any connected orders for that resource created in the same month as the invoice
    3. Are from 2025 invoices

    These items should not exist since TOTAL period components should only be billed once
    during resource creation, not during monthly invoice generation.
    """
    InvoiceItem = apps.get_model("invoices", "InvoiceItem")
    OfferingComponent = apps.get_model("marketplace", "OfferingComponent")
    Order = apps.get_model("marketplace", "Order")

    # Import enums by value since apps.get_model doesn't provide enums
    BILLING_TYPE_LIMIT = "limit"  # BillingTypes.LIMIT
    LIMIT_PERIOD_TOTAL = "total"  # LimitPeriods.TOTAL
    REQUEST_TYPE_CREATE = 1  # RequestTypes.CREATE
    REQUEST_TYPE_UPDATE = 2  # RequestTypes.UPDATE
    ORDER_STATE_EXECUTING = 3  # OrderStates.EXECUTING
    ORDER_STATE_DONE = 4  # OrderStates.DONE

    print("=== Removing Incorrect TOTAL Period Invoice Items from 2025 ===")

    # Get all TOTAL period components with their offering and type info
    total_components = (
        OfferingComponent.objects.filter(
            billing_type=BILLING_TYPE_LIMIT, limit_period=LIMIT_PERIOD_TOTAL
        )
        .select_related("offering")
        .values("type", "offering__uuid", "offering__name")
    )

    total_components_list = list(total_components)
    print(f"🔍 Found {len(total_components_list)} TOTAL period components:")
    for comp in total_components_list:
        print(
            f"  - {comp['type']} (offering: {comp['offering__name']}, uuid: {comp['offering__uuid']})"
        )

    if not total_components_list:
        print("❌ No TOTAL period components found - migration complete")
        return

    # Find all invoice items for TOTAL period components in 2025
    # Use component type filtering (some items may not have offering_uuid in details)
    component_conditions = Q()
    total_component_types = set(comp["type"] for comp in total_components_list)
    for comp_type in total_component_types:
        component_conditions |= Q(details__offering_component_type=comp_type)

    total_invoice_items = (
        InvoiceItem.objects.filter(
            component_conditions,
            resource__isnull=False,
            quantity__gt=0,  # Skip items with zero quantity
            invoice__year=2025,  # Only 2025 items
        )
        .select_related("resource", "invoice", "resource__project__customer")
        .order_by("invoice__year", "invoice__month", "resource_id")
    )

    print(
        f"\n📋 Total invoice items for TOTAL period components in 2025: {total_invoice_items.count()}"
    )

    # Check each item for orders in the same month
    items_to_remove = []
    total_amount_to_remove = 0

    print("\n🔍 Checking each item for orders in the same month...")

    for item in total_invoice_items:
        invoice_year = item.invoice.year
        invoice_month = item.invoice.month
        resource = item.resource

        # Check if there are any orders for this resource in the same month
        same_month_orders = Order.objects.filter(
            resource=resource,
            type__in=[REQUEST_TYPE_CREATE, REQUEST_TYPE_UPDATE],
            state__in=[ORDER_STATE_EXECUTING, ORDER_STATE_DONE],
            created__year=invoice_year,
            created__month=invoice_month,
        )

        if not same_month_orders.exists():
            # This is problematic - TOTAL billing without orders in the same month
            items_to_remove.append(item)
            # Calculate price as unit_price * quantity since @property is not available in migrations
            item_price = item.unit_price * item.quantity
            total_amount_to_remove += item_price

            resource_name = resource.name or f"Resource_{resource.id}"
            customer_name = resource.project.customer.name or "Unknown"

            component_type = item.details.get("offering_component_type", "Unknown")
            offering_uuid = item.details.get("offering_uuid", "Unknown")

            print(
                f"  🚨 Item {item.id} ({invoice_year}-{invoice_month:02d}): {customer_name[:30]} | {resource_name[:25]} | {component_type} | {offering_uuid[:8]}... | {item_price:.2f}"
            )

    print(f"\n🚨 Found {len(items_to_remove)} problematic TOTAL period items to remove")
    print(f"💰 Total amount to be removed: {total_amount_to_remove:.2f}")

    if not items_to_remove:
        print("✅ No problematic items found - migration complete")
        return

    # Summary by customer before removal
    customer_summary = {}
    for item in items_to_remove:
        customer_name = item.resource.project.customer.name or "Unknown"

        if customer_name not in customer_summary:
            customer_summary[customer_name] = {"items": 0, "amount": 0}
        customer_summary[customer_name]["items"] += 1
        # Calculate price as unit_price * quantity since @property is not available in migrations
        customer_summary[customer_name]["amount"] += item.unit_price * item.quantity

    print("\n📊 REMOVAL SUMMARY BY CUSTOMER:")
    for customer, data in sorted(
        customer_summary.items(), key=lambda x: x[1]["amount"], reverse=True
    ):
        print(
            f"• {customer:<40} - {data['items']:>3} items, {data['amount']:>10.2f} total"
        )

    # Remove the items one by one to trigger Django signals
    print(f"\n🗑️  Removing {len(items_to_remove)} incorrect TOTAL period items...")

    deleted_count = 0
    for item in items_to_remove:
        # Delete one by one to trigger signals that update:
        # - Invoice.total_cost cache
        # - PriceEstimate for customer and project
        item.delete()
        deleted_count += 1
        if deleted_count % 10 == 0:
            print(f"   Deleted {deleted_count}/{len(items_to_remove)} items...")

    print(
        f"✅ Successfully removed {deleted_count} incorrect TOTAL period invoice items"
    )
    print(f"💰 Total amount removed: {total_amount_to_remove:.2f}")
    print(f"👥 Customers affected: {len(customer_summary)}")


class Migration(migrations.Migration):
    dependencies = [
        ("marketplace", "0179_courseaccount"),
    ]

    operations = [
        migrations.RunPython(
            remove_incorrect_total_billing_2025,
        ),
    ]
