# Generated by Django 6.0.8 on 2026-09-03 15:35

from importlib import import_module

import django.db.models.deletion
import django.utils.timezone
import django_fsm
import model_utils.fields
from django.conf import settings
from django.db import migrations, models

import waldur_core.core.fields
import waldur_core.core.migration_operations
import waldur_core.media.validators


def _original(name):
    """A replaced migration's module: its data code runs from there, unchanged."""
    return import_module(__name__.rpartition(".")[0] + "." + name)


class Migration(migrations.Migration):
    replaces = [
        ("marketplace", "0180_remove_incorrect_total_billing_2025"),
        ("marketplace", "0181_alter_offeringtermsofservice_is_active_and_more"),
        ("marketplace", "0182_order_attachment_order_request_comment"),
        ("marketplace", "0183_update_offering_user_state_with_username"),
        ("marketplace", "0184_add_model_indexes"),
        (
            "marketplace",
            "0185_category_description_bg_category_description_el_and_more",
        ),
        ("marketplace", "0186_offeringcomponent_is_prepaid_and_more"),
        ("marketplace", "0187_alter_categorycomponent_description_and_more"),
        ("marketplace", "0188_order_slug"),
        ("marketplace", "0189_populate_order_slug"),
        ("marketplace", "0190_alter_order_slug_required"),
        ("marketplace", "0191_plancomponent_discount_rate_and_more"),
        ("marketplace", "0192_order_start_date"),
        ("marketplace", "0193_alter_order_state"),
        (
            "marketplace",
            "0194_offeringpartition_softwarecatalog_softwarepackage_and_more",
        ),
        ("marketplace", "0195_offeringtermsofservice_grace_period_days"),
        ("marketplace", "0196_add_internal_notes_to_maintenance_announcement"),
        ("marketplace", "0197_alter_order_type"),
        ("marketplace", "0198_alter_softwarecatalog_options_and_more"),
        ("marketplace", "0199_alter_offering_state"),
        ("marketplace", "0200_sync_resource_states_for_pending_orders"),
        ("marketplace", "0201_tag_offering_tags"),
        ("marketplace", "0202_offeringuserattributeconfig"),
        ("marketplace", "0203_alter_order_consumer_reviewed_by_and_more"),
        ("marketplace", "0204_offeringuserattributeconfig_expose_registration_method"),
        ("marketplace", "0205_backfill_initial_revisions"),
        ("marketplace", "0206_order_provider_consumer_messages"),
        ("marketplace", "0207_offering_backend_id_rules"),
        ("marketplace", "0208_order_rejection_comments"),
        ("marketplace", "0209_offeringuserrole_scope_type"),
        ("marketplace", "0210_offeringuserrole_scope_type_label"),
        ("marketplace", "0211_offeringuserattributeconfig_expose_active_isds_and_more"),
        ("marketplace", "0212_deduplicate_component_usages"),
        ("marketplace", "0213_alter_resource_current_usages"),
        ("marketplace", "0214_softwarepackage_parent_softwares_m2m"),
        ("marketplace", "0215_migrate_parent_software_data"),
        ("marketplace", "0216_serviceprovider_allowed_domains"),
        ("marketplace", "0217_softwaretarget_gpu_architectures_offeringpartition_arch"),
        ("marketplace", "0218_backfill_gpu_architectures"),
        ("marketplace", "0219_courseaccount_pending_state"),
        ("marketplace", "0220_offering_helpdesk_url_documentation_url"),
        ("marketplace", "0221_add_uuid_to_attribute_and_attributeoption"),
        ("marketplace", "0222_offering_component_fields"),
        ("marketplace", "0223_order_error_updated_at_order_output_updated_at"),
        ("marketplace", "0224_componentusagemonthly"),
        ("marketplace", "0225_add_expose_address_to_offering_user_attribute_config"),
    ]

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("core", "__first__"),
        (
            "invoices",
            "0019_projectcredit_mark_unused_credit_as_spent_on_project_termination",
        ),
        ("marketplace", "0179_courseaccount"),
        ("reversion", "0001_squashed_0004_auto_20160611_1202"),
        ("reversion", "0002_add_index_on_version_for_content_type_and_db"),
    ]

    operations = [
        migrations.RunPython(
            code=_original(
                "0180_remove_incorrect_total_billing_2025"
            ).remove_incorrect_total_billing_2025,
        ),
        waldur_core.core.migration_operations.FlushDeferredSql(),
        migrations.RunPython(
            code=_original(
                "0181_alter_offeringtermsofservice_is_active_and_more"
            ).fix_multiple_active_tos,
        ),
        migrations.AddField(
            model_name="order",
            name="attachment",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="marketplace_order_attachments",
                validators=[
                    waldur_core.media.validators.FileTypeValidator(
                        allowed_types=["application/pdf"]
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="request_comment",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="offeringtermsofservice",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name="offeringtermsofservice",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True)),
                fields=("offering",),
                name="unique_active_terms_per_offering",
            ),
        ),
        waldur_core.core.migration_operations.FlushDeferredSql(),
        migrations.RunPython(
            code=_original(
                "0183_update_offering_user_state_with_username"
            ).update_offering_user_state_for_username,
        ),
        migrations.AddField(
            model_name="category",
            name="description_bg",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="category",
            name="description_el",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="category",
            name="description_sl",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="category",
            name="title_bg",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="category",
            name="title_el",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="category",
            name="title_sl",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="categorygroup",
            name="description_bg",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="categorygroup",
            name="description_el",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="categorygroup",
            name="description_sl",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="categorygroup",
            name="title_bg",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="categorygroup",
            name="title_el",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="categorygroup",
            name="title_sl",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="offeringcomponent",
            name="is_prepaid",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="offeringcomponent",
            name="max_prepaid_duration",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="offeringcomponent",
            name="min_prepaid_duration",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="offeringcomponent",
            name="overage_component",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="marketplace.offeringcomponent",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="slug",
            field=models.SlugField(blank=True, editable=False),
        ),
        migrations.AlterField(
            model_name="categorycomponent",
            name="description",
            field=models.CharField(
                blank=True, max_length=4096, verbose_name="description"
            ),
        ),
        migrations.AlterField(
            model_name="componentusage",
            name="description",
            field=models.CharField(
                blank=True, max_length=4096, verbose_name="description"
            ),
        ),
        migrations.AlterField(
            model_name="componentuserusage",
            name="description",
            field=models.CharField(
                blank=True, max_length=4096, verbose_name="description"
            ),
        ),
        migrations.AlterField(
            model_name="courseaccount",
            name="description",
            field=models.CharField(
                blank=True, max_length=4096, verbose_name="description"
            ),
        ),
        migrations.AlterField(
            model_name="offering",
            name="description",
            field=models.CharField(
                blank=True, max_length=4096, verbose_name="description"
            ),
        ),
        migrations.AlterField(
            model_name="offeringcomponent",
            name="description",
            field=models.CharField(
                blank=True, max_length=4096, verbose_name="description"
            ),
        ),
        migrations.AlterField(
            model_name="plan",
            name="description",
            field=models.CharField(
                blank=True, max_length=4096, verbose_name="description"
            ),
        ),
        migrations.AlterField(
            model_name="resource",
            name="description",
            field=models.CharField(
                blank=True, max_length=4096, verbose_name="description"
            ),
        ),
        migrations.AlterField(
            model_name="screenshot",
            name="description",
            field=models.CharField(
                blank=True, max_length=4096, verbose_name="description"
            ),
        ),
        migrations.AlterField(
            model_name="serviceprovider",
            name="description",
            field=models.CharField(
                blank=True, max_length=4096, verbose_name="description"
            ),
        ),
        migrations.AddIndex(
            model_name="componentusage",
            index=models.Index(
                fields=["resource", "-date"], name="mp_compusage_resource_date_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="offering",
            index=models.Index(
                fields=["customer", "state"], name="mp_offering_customer_state_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="offering",
            index=models.Index(fields=["name"], name="mp_offering_name_idx"),
        ),
        migrations.AddIndex(
            model_name="offeringuser",
            index=models.Index(
                fields=["offering", "user"], name="mp_offeringuser_offer_user_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["state", "-created"], name="mp_order_state_created_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="resource",
            index=models.Index(
                fields=["offering", "state"], name="mp_resource_offering_state_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="resource",
            index=models.Index(
                fields=["project", "state"], name="mp_resource_project_state_idx"
            ),
        ),
        waldur_core.core.migration_operations.FlushDeferredSql(),
        migrations.RunPython(
            code=_original("0189_populate_order_slug").fill_slug,
            reverse_code=_original("0189_populate_order_slug").clear_slug,
        ),
        migrations.CreateModel(
            name="SoftwareCatalog",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("uuid", waldur_core.core.fields.UUIDField()),
                (
                    "name",
                    models.CharField(
                        help_text="Catalog name (e.g., EESSI, Spack)", max_length=100
                    ),
                ),
                (
                    "version",
                    models.CharField(
                        help_text="Catalog version (e.g., 2023.06, 0.21.0)",
                        max_length=50,
                    ),
                ),
                (
                    "source_url",
                    models.URLField(blank=True, help_text="Catalog source URL"),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "auto_update_enabled",
                    models.BooleanField(
                        default=True,
                        help_text="Whether to automatically update this catalog via scheduled tasks",
                    ),
                ),
                (
                    "catalog_type",
                    models.CharField(
                        choices=[
                            ("binary_runtime", "Binary Runtime (EESSI)"),
                            ("source_package", "Source Package (Spack)"),
                            ("package_manager", "Package Manager (conda, pip)"),
                        ],
                        default="binary_runtime",
                        help_text="Type of software catalog",
                        max_length=50,
                    ),
                ),
                ("last_successful_update", models.DateTimeField(blank=True, null=True)),
                ("last_update_attempt", models.DateTimeField(blank=True, null=True)),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Catalog-specific metadata (architecture maps, API endpoints, etc.)",
                    ),
                ),
                ("update_errors", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["name", "catalog_type", "version"],
            },
        ),
        migrations.AddField(
            model_name="maintenanceannouncement",
            name="internal_notes",
            field=models.CharField(
                blank=True, max_length=2000, verbose_name="internal notes"
            ),
        ),
        migrations.AddField(
            model_name="offeringtermsofservice",
            name="grace_period_days",
            field=models.PositiveIntegerField(
                default=60,
                help_text="Number of days before outdated consents are automatically revoked. Only applies when requires_reconsent=True.",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="start_date",
            field=models.DateField(
                blank=True,
                help_text="Enables delayed processing of resource provisioning order.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="plancomponent",
            name="discount_rate",
            field=models.PositiveIntegerField(
                blank=True, help_text="Discount rate in percentage.", null=True
            ),
        ),
        migrations.AddField(
            model_name="plancomponent",
            name="discount_threshold",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Minimum amount to be eligible for discount.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="slug",
            field=models.SlugField(),
        ),
        migrations.AlterField(
            model_name="order",
            name="state",
            field=django_fsm.FSMIntegerField(
                choices=[
                    (1, "pending-consumer"),
                    (7, "pending-provider"),
                    (8, "pending-project"),
                    (9, "pending-start-date"),
                    (2, "executing"),
                    (3, "done"),
                    (4, "erred"),
                    (5, "canceled"),
                    (6, "rejected"),
                ],
                default=1,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="type",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "Create"),
                    (2, "Update"),
                    (3, "Terminate"),
                    (4, "Restore"),
                ],
                default=1,
            ),
        ),
        migrations.CreateModel(
            name="OfferingPartition",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("uuid", waldur_core.core.fields.UUIDField()),
                (
                    "partition_name",
                    models.CharField(
                        help_text="Name of the SLURM partition", max_length=255
                    ),
                ),
                (
                    "cpu_bind",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Default task binding policy (SLURM cpu_bind)",
                        null=True,
                    ),
                ),
                (
                    "def_cpu_per_gpu",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Default CPUs allocated per GPU",
                        null=True,
                    ),
                ),
                (
                    "max_cpus_per_node",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Maximum allocated CPUs per node",
                        null=True,
                    ),
                ),
                (
                    "max_cpus_per_socket",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Maximum allocated CPUs per socket",
                        null=True,
                    ),
                ),
                (
                    "def_mem_per_cpu",
                    models.PositiveBigIntegerField(
                        blank=True, help_text="Default memory per CPU in MB", null=True
                    ),
                ),
                (
                    "def_mem_per_gpu",
                    models.PositiveBigIntegerField(
                        blank=True, help_text="Default memory per GPU in MB", null=True
                    ),
                ),
                (
                    "def_mem_per_node",
                    models.PositiveBigIntegerField(
                        blank=True, help_text="Default memory per node in MB", null=True
                    ),
                ),
                (
                    "max_mem_per_cpu",
                    models.PositiveBigIntegerField(
                        blank=True, help_text="Maximum memory per CPU in MB", null=True
                    ),
                ),
                (
                    "max_mem_per_node",
                    models.PositiveBigIntegerField(
                        blank=True, help_text="Maximum memory per node in MB", null=True
                    ),
                ),
                (
                    "default_time",
                    models.PositiveIntegerField(
                        blank=True, help_text="Default time limit in minutes", null=True
                    ),
                ),
                (
                    "max_time",
                    models.PositiveIntegerField(
                        blank=True, help_text="Maximum time limit in minutes", null=True
                    ),
                ),
                (
                    "grace_time",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Preemption grace time in seconds",
                        null=True,
                    ),
                ),
                (
                    "max_nodes",
                    models.PositiveIntegerField(
                        blank=True, help_text="Maximum nodes per job", null=True
                    ),
                ),
                (
                    "min_nodes",
                    models.PositiveIntegerField(
                        blank=True, help_text="Minimum nodes per job", null=True
                    ),
                ),
                (
                    "exclusive_topo",
                    models.BooleanField(
                        default=False, help_text="Exclusive topology access required"
                    ),
                ),
                (
                    "exclusive_user",
                    models.BooleanField(
                        default=False, help_text="Exclusive user access required"
                    ),
                ),
                (
                    "priority_tier",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Priority tier for scheduling and preemption",
                        null=True,
                    ),
                ),
                (
                    "qos",
                    models.CharField(
                        blank=True,
                        help_text="Quality of Service (QOS) name",
                        max_length=255,
                    ),
                ),
                (
                    "req_resv",
                    models.BooleanField(
                        default=False,
                        help_text="Require reservation for job allocation",
                    ),
                ),
                (
                    "offering",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="partitions",
                        to="marketplace.offering",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OfferingSoftwareCatalog",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("uuid", waldur_core.core.fields.UUIDField()),
                (
                    "enabled_cpu_family",
                    models.JSONField(
                        default=list,
                        help_text="List of enabled CPU families: ['x86_64', 'aarch64']",
                    ),
                ),
                (
                    "enabled_cpu_microarchitectures",
                    models.JSONField(
                        default=list,
                        help_text="List of enabled CPU microarchitectures: ['generic', 'zen3']",
                    ),
                ),
                (
                    "offering",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="software_catalogs",
                        to="marketplace.offering",
                    ),
                ),
                (
                    "partition",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional SLURM partition this software catalog is associated with",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="software_catalogs",
                        to="marketplace.offeringpartition",
                    ),
                ),
                (
                    "catalog",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="offerings",
                        to="marketplace.softwarecatalog",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SoftwarePackage",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("uuid", waldur_core.core.fields.UUIDField()),
                ("name", models.CharField(db_index=True, max_length=200)),
                ("description", models.TextField(blank=True)),
                ("homepage", models.URLField(blank=True, null=True)),
                (
                    "categories",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Package categories (e.g., ['bio', 'hpc', 'build-tools'])",
                    ),
                ),
                (
                    "is_extension",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this package is an extension of another package",
                    ),
                ),
                (
                    "licenses",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Software licenses (e.g., ['GPL-3.0', 'MIT'])",
                    ),
                ),
                (
                    "maintainers",
                    models.JSONField(
                        blank=True, default=list, help_text="Package maintainers"
                    ),
                ),
                (
                    "catalog",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="packages",
                        to="marketplace.softwarecatalog",
                    ),
                ),
                (
                    "parent_software",
                    models.ForeignKey(
                        blank=True,
                        help_text="Parent package for extensions (e.g., Python package within Python)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="extensions",
                        to="marketplace.softwarepackage",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="SoftwareVersion",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("uuid", waldur_core.core.fields.UUIDField()),
                ("version", models.CharField(max_length=100)),
                ("release_date", models.DateField(blank=True, null=True)),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Version-specific metadata (toolchains, build info, modules, etc.)",
                    ),
                ),
                (
                    "dependencies",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Package dependencies (format varies by catalog type)",
                    ),
                ),
                (
                    "package",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="marketplace.softwarepackage",
                    ),
                ),
            ],
            options={
                "ordering": ["package", "version"],
            },
        ),
        migrations.CreateModel(
            name="SoftwareTarget",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("uuid", waldur_core.core.fields.UUIDField()),
                ("cpu_family", models.CharField(db_index=True, max_length=50)),
                (
                    "cpu_microarchitecture",
                    models.CharField(db_index=True, max_length=50),
                ),
                ("path", models.CharField(max_length=500)),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        help_text="Target location (CVMFS path, download URL, etc.)",
                        max_length=500,
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Target-specific metadata (build options, system requirements, etc.)",
                    ),
                ),
                (
                    "target_name",
                    models.CharField(
                        db_index=True,
                        default="generic",
                        help_text="Target identifier (x86_64/generic, linux, variant_name, etc.)",
                        max_length=100,
                    ),
                ),
                (
                    "target_subtype",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Target subtype (microarchitecture, distribution, etc.)",
                        max_length=50,
                    ),
                ),
                (
                    "target_type",
                    models.CharField(
                        db_index=True,
                        default="architecture",
                        help_text="Type of target (architecture, platform, variant, etc.)",
                        max_length=50,
                    ),
                ),
                (
                    "version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="targets",
                        to="marketplace.softwareversion",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="offeringpartition",
            index=models.Index(
                fields=["offering", "partition_name"],
                name="marketplace_offerin_d0e4fb_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="offeringpartition",
            index=models.Index(
                fields=["priority_tier"], name="marketplace_priorit_e4daf1_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="offeringpartition",
            unique_together={("offering", "partition_name")},
        ),
        migrations.AlterUniqueTogether(
            name="offeringsoftwarecatalog",
            unique_together={("offering", "catalog")},
        ),
        migrations.AddIndex(
            model_name="softwarepackage",
            index=models.Index(
                fields=["catalog", "name"], name="marketplace_catalog_60881d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="softwarepackage",
            index=models.Index(fields=["name"], name="marketplace_name_30beb0_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="softwarepackage",
            unique_together={("catalog", "name")},
        ),
        migrations.AlterUniqueTogether(
            name="softwareversion",
            unique_together={("package", "version")},
        ),
        waldur_core.core.migration_operations.FlushDeferredSql(),
        migrations.RunPython(
            code=_original(
                "0198_alter_softwarecatalog_options_and_more"
            ).remove_duplicate_software_targets,
            reverse_code=_original(
                "0198_alter_softwarecatalog_options_and_more"
            ).reverse_remove_duplicate_software_targets,
        ),
        migrations.AlterUniqueTogether(
            name="softwaretarget",
            unique_together={
                ("version", "target_type", "target_name", "target_subtype")
            },
        ),
        migrations.AlterField(
            model_name="offering",
            name="state",
            field=django_fsm.FSMIntegerField(
                choices=[
                    (1, "Draft"),
                    (2, "Active"),
                    (3, "Paused"),
                    (4, "Archived"),
                    (5, "Unavailable"),
                ],
                default=1,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="softwarecatalog",
            unique_together={("name", "version", "catalog_type")},
        ),
        migrations.AddIndex(
            model_name="softwarepackage",
            index=models.Index(
                fields=["is_extension"], name="marketplace_is_exte_b2a9ce_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="softwarepackage",
            index=models.Index(
                fields=["parent_software"], name="marketplace_parent__4bb7b4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="softwaretarget",
            index=models.Index(
                fields=["target_type", "target_name"],
                name="marketplace_target__1aec3f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="softwaretarget",
            index=models.Index(
                fields=["version", "target_type"], name="marketplace_version_694813_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="softwaretarget",
            index=models.Index(
                fields=["target_type", "target_subtype"],
                name="marketplace_target__98eb03_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="softwareversion",
            index=models.Index(
                fields=["package", "version"], name="marketplace_package_f89a61_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="softwareversion",
            index=models.Index(
                fields=["version"], name="marketplace_version_4924ad_idx"
            ),
        ),
        migrations.RemoveField(
            model_name="softwaretarget",
            name="cpu_family",
        ),
        migrations.RemoveField(
            model_name="softwaretarget",
            name="cpu_microarchitecture",
        ),
        migrations.RemoveField(
            model_name="softwaretarget",
            name="path",
        ),
        waldur_core.core.migration_operations.FlushDeferredSql(),
        migrations.RunPython(
            code=_original(
                "0200_sync_resource_states_for_pending_orders"
            ).sync_resource_states,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name="order",
            name="consumer_reviewed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="provider_reviewed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="OfferingUserAttributeConfig",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("uuid", waldur_core.core.fields.UUIDField()),
                ("expose_username", models.BooleanField(default=True)),
                ("expose_full_name", models.BooleanField(default=True)),
                ("expose_email", models.BooleanField(default=True)),
                ("expose_phone_number", models.BooleanField(default=False)),
                ("expose_organization", models.BooleanField(default=False)),
                ("expose_job_title", models.BooleanField(default=False)),
                ("expose_affiliations", models.BooleanField(default=False)),
                ("expose_gender", models.BooleanField(default=False)),
                ("expose_personal_title", models.BooleanField(default=False)),
                ("expose_place_of_birth", models.BooleanField(default=False)),
                ("expose_country_of_residence", models.BooleanField(default=False)),
                ("expose_nationality", models.BooleanField(default=False)),
                ("expose_nationalities", models.BooleanField(default=False)),
                ("expose_organization_country", models.BooleanField(default=False)),
                ("expose_organization_type", models.BooleanField(default=False)),
                ("expose_eduperson_assurance", models.BooleanField(default=False)),
                ("expose_civil_number", models.BooleanField(default=False)),
                ("expose_birth_date", models.BooleanField(default=False)),
                ("expose_identity_source", models.BooleanField(default=False)),
                ("expose_registration_method", models.BooleanField(default=True)),
                (
                    "offering",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_attribute_config",
                        to="marketplace.offering",
                    ),
                ),
            ],
            options={
                "verbose_name": "Offering user attribute config",
                "verbose_name_plural": "Offering user attribute configs",
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("uuid", waldur_core.core.fields.UUIDField()),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Tag",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="offering",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="offerings", to="marketplace.tag"
            ),
        ),
        waldur_core.core.migration_operations.FlushDeferredSql(),
        migrations.RunPython(
            code=_original(
                "0205_backfill_initial_revisions"
            ).backfill_initial_revisions,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AddField(
            model_name="offering",
            name="backend_id_rules",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Validation rules for resource backend_id: format regex and uniqueness scope.",
            ),
        ),
        migrations.AddField(
            model_name="offeringuserattributeconfig",
            name="expose_active_isds",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="offeringuserattributeconfig",
            name="expose_organization_registry_code",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="offeringuserrole",
            name="scope_type",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Level this role applies at, e.g. 'cluster', 'project'. Empty means offering-wide.",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="offeringuserrole",
            name="scope_type_label",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Human-readable label for scope_type shown to end users, e.g. 'Rancher Project', 'Cluster Namespace'. Falls back to capitalized scope_type if empty.",
                max_length=150,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="consumer_message",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="order",
            name="consumer_message_attachment",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="marketplace_order_consumer_attachments",
                validators=[
                    waldur_core.media.validators.FileTypeValidator(
                        allowed_types=["application/pdf"]
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="consumer_rejection_comment",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="order",
            name="provider_message",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="order",
            name="provider_message_attachment",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="marketplace_order_provider_attachments",
                validators=[
                    waldur_core.media.validators.FileTypeValidator(
                        allowed_types=["application/pdf"]
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="provider_message_url",
            field=models.URLField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="order",
            name="provider_rejection_comment",
            field=models.TextField(blank=True, default=""),
        ),
        waldur_core.core.migration_operations.FlushDeferredSql(),
        migrations.RunPython(
            code=_original(
                "0212_deduplicate_component_usages"
            ).deduplicate_component_usages,
        ),
        migrations.RemoveIndex(
            model_name="softwarepackage",
            name="marketplace_parent__4bb7b4_idx",
        ),
        migrations.AddField(
            model_name="softwarepackage",
            name="parent_softwares",
            field=models.ManyToManyField(
                blank=True,
                help_text="Parent packages for extensions (e.g., Python package within Python)",
                related_name="extensions",
                to="marketplace.softwarepackage",
            ),
        ),
        migrations.AlterField(
            model_name="resource",
            name="current_usages",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Dictionary mapping component types to their current usage amounts. For usage-based and limit-based components, it stores the most recent reported amounts or consumed quotas. Populated by backend synchronization tasks or explicit usage reports.",
            ),
        ),
        migrations.AlterField(
            model_name="softwarepackage",
            name="parent_software",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="extensions_old",
                to="marketplace.softwarepackage",
            ),
        ),
        waldur_core.core.migration_operations.FlushDeferredSql(),
        migrations.RunPython(
            code=_original(
                "0215_migrate_parent_software_data"
            ).copy_parent_software_to_m2m,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.RemoveField(
            model_name="softwarepackage",
            name="parent_software",
        ),
        migrations.AddField(
            model_name="offeringpartition",
            name="cpu_arch",
            field=models.CharField(
                blank=True,
                help_text="CPU architecture of the partition (e.g., x86_64/amd/zen3)",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="offeringpartition",
            name="gpu_arch",
            field=models.CharField(
                blank=True,
                help_text="GPU architecture of the partition (e.g., nvidia/cc90, amd/gfx90a)",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="serviceprovider",
            name="allowed_domains",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of allowed domains for offering endpoints. Only staff can modify this field. ",
            ),
        ),
        migrations.AddField(
            model_name="softwaretarget",
            name="gpu_architectures",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of GPU architectures this target supports (e.g., ['nvidia/cc70', 'nvidia/cc90'])",
            ),
        ),
        waldur_core.core.migration_operations.FlushDeferredSql(),
        migrations.RunPython(
            code=_original(
                "0218_backfill_gpu_architectures"
            ).backfill_gpu_architectures,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AddField(
            model_name="attribute",
            name="uuid",
            field=models.UUIDField(null=True),
        ),
        migrations.AddField(
            model_name="offering",
            name="documentation_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="offering",
            name="helpdesk_url",
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name="courseaccount",
            name="state",
            field=django_fsm.FSMIntegerField(
                choices=[(1, "OK"), (2, "Closed"), (3, "Erred"), (4, "Pending")],
                default=1,
            ),
        ),
        waldur_core.core.migration_operations.FlushDeferredSql(),
        migrations.RunPython(
            code=_original(
                "0221_add_uuid_to_attribute_and_attributeoption"
            ).gen_attribute_uuids,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name="attribute",
            name="uuid",
            field=waldur_core.core.fields.UUIDField(),
        ),
        migrations.AddField(
            model_name="attributeoption",
            name="uuid",
            field=models.UUIDField(null=True),
        ),
        waldur_core.core.migration_operations.FlushDeferredSql(),
        migrations.RunPython(
            code=_original(
                "0221_add_uuid_to_attribute_and_attributeoption"
            ).gen_attributeoption_uuids,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name="attributeoption",
            name="uuid",
            field=waldur_core.core.fields.UUIDField(),
        ),
        migrations.AddField(
            model_name="offeringcomponent",
            name="prepaid_duration_step",
            field=models.PositiveIntegerField(
                blank=True,
                default=None,
                help_text="Step size in months for the initial prepaid duration at order creation. If set, only multiples of this value (starting from min_prepaid_duration) are valid. Defaults to 1 (any value between min and max).",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="offeringcomponent",
            name="max_renewal_duration",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Maximum number of months allowed for a renewal.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="offeringcomponent",
            name="min_renewal_duration",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Minimum number of months allowed for a renewal.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="offeringcomponent",
            name="renewal_duration_step",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Step size in months for renewal. Only multiples of this value (starting from min_renewal_duration) are valid. Defaults to 1.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="error_updated_at",
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="output_updated_at",
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.CreateModel(
            name="ComponentUsageMonthly",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "billing_period",
                    models.DateField(
                        help_text="Always the first day of the month (e.g., 2023-10-01)"
                    ),
                ),
                (
                    "total_consumed",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                (
                    "total_allocated",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                (
                    "usage_percent",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "component",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="monthly_summaries",
                        to="marketplace.offeringcomponent",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["billing_period", "component"],
                        name="marketplace_billing_36b7ff_idx",
                    )
                ],
                "unique_together": {("component", "billing_period")},
            },
        ),
        migrations.AddField(
            model_name="offeringuserattributeconfig",
            name="expose_address",
            field=models.BooleanField(default=False),
        ),
    ]
