# Generated by Django 4.2.24 on 2025-10-01 14:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("marketplace", "0183_update_offering_user_state_with_username"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="componentusage",
            index=models.Index(
                fields=["resource", "-date"], name="mp_compusage_resource_date_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="offering",
            index=models.Index(
                fields=["customer", "state"], name="mp_offering_customer_state_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="offering",
            index=models.Index(fields=["name"], name="mp_offering_name_idx"),
        ),
        migrations.AddIndex(
            model_name="offeringuser",
            index=models.Index(
                fields=["offering", "user"], name="mp_offeringuser_offer_user_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["state", "-created"], name="mp_order_state_created_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="resource",
            index=models.Index(
                fields=["offering", "state"], name="mp_resource_offering_state_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="resource",
            index=models.Index(
                fields=["project", "state"], name="mp_resource_project_state_idx"
            ),
        ),
    ]
