# Generated by Django 4.2.24 on 2025-10-21 18:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("marketplace", "0190_alter_order_slug_required"),
    ]

    operations = [
        migrations.AddField(
            model_name="plancomponent",
            name="discount_rate",
            field=models.PositiveIntegerField(
                blank=True, help_text="Discount rate in percentage.", null=True
            ),
        ),
        migrations.AddField(
            model_name="plancomponent",
            name="discount_threshold",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Minimum amount to be eligible for discount.",
                null=True,
            ),
        ),
    ]
