# Generated by Django 4.2.24 on 2025-10-23 21:21

import django_fsm
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("marketplace", "0192_order_start_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="state",
            field=django_fsm.FSMIntegerField(
                choices=[
                    (1, "pending-consumer"),
                    (7, "pending-provider"),
                    (8, "pending-project"),
                    (9, "pending-start-date"),
                    (2, "executing"),
                    (3, "done"),
                    (4, "erred"),
                    (5, "canceled"),
                    (6, "rejected"),
                ],
                default=1,
            ),
        ),
    ]
