# Generated by Django 4.2.24 on 2025-11-29 17:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("marketplace", "0196_add_internal_notes_to_maintenance_announcement"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="type",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "Create"),
                    (2, "Update"),
                    (3, "Terminate"),
                    (4, "Restore"),
                ],
                default=1,
            ),
        ),
    ]
