# Generated by Django 4.2.23 on 2025-11-26 14:52

import django_fsm
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("marketplace", "0198_alter_softwarecatalog_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="offering",
            name="state",
            field=django_fsm.FSMIntegerField(
                choices=[
                    (1, "Draft"),
                    (2, "Active"),
                    (3, "Paused"),
                    (4, "Archived"),
                    (5, "Unavailable"),
                ],
                default=1,
            ),
        ),
    ]
