# Generated by Django 5.2.11 on 2026-02-19 12:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("marketplace", "0210_offeringuserrole_scope_type_label"),
    ]

    operations = [
        migrations.AddField(
            model_name="offeringuserattributeconfig",
            name="expose_active_isds",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="offeringuserattributeconfig",
            name="expose_organization_registry_code",
            field=models.BooleanField(default=False),
        ),
    ]
