# Generated by Django 6.0.2 on 2026-03-04 19:00

from django.db import migrations


def backfill_gpu_architectures(apps, schema_editor):
    SoftwareTarget = apps.get_model("marketplace", "SoftwareTarget")
    targets = SoftwareTarget.objects.exclude(metadata__gpu_arch={})
    for target in targets.iterator():
        gpu_arch_map = target.metadata.get("gpu_arch", {})
        all_gpu_archs = set()
        for archs in gpu_arch_map.values():
            all_gpu_archs.update(archs)
        if all_gpu_archs:
            target.gpu_architectures = sorted(all_gpu_archs)
            target.save(update_fields=["gpu_architectures"])


class Migration(migrations.Migration):
    dependencies = [
        ("marketplace", "0217_softwaretarget_gpu_architectures_offeringpartition_arch"),
    ]

    operations = [
        migrations.RunPython(backfill_gpu_architectures, migrations.RunPython.noop),
    ]
