# Generated by Django 6.0.3 on 2026-03-25 12:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("marketplace", "0221_add_uuid_to_attribute_and_attributeoption"),
    ]

    operations = [
        migrations.AddField(
            model_name="offeringcomponent",
            name="prepaid_duration_step",
            field=models.PositiveIntegerField(
                blank=True,
                default=None,
                help_text="Step size in months for the initial prepaid duration at order creation. If set, only multiples of this value (starting from min_prepaid_duration) are valid. Defaults to 1 (any value between min and max).",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="offeringcomponent",
            name="max_renewal_duration",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Maximum number of months allowed for a renewal.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="offeringcomponent",
            name="min_renewal_duration",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Minimum number of months allowed for a renewal.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="offeringcomponent",
            name="renewal_duration_step",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Step size in months for renewal. Only multiples of this value (starting from min_renewal_duration) are valid. Defaults to 1.",
                null=True,
            ),
        ),
    ]
