# Generated by Django 6.0.3 on 2026-04-08 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("marketplace", "0223_order_error_updated_at_order_output_updated_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="ComponentUsageMonthly",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "billing_period",
                    models.DateField(
                        help_text="Always the first day of the month (e.g., 2023-10-01)"
                    ),
                ),
                (
                    "total_consumed",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                (
                    "total_allocated",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                (
                    "usage_percent",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "component",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="monthly_summaries",
                        to="marketplace.offeringcomponent",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["billing_period", "component"],
                        name="marketplace_billing_36b7ff_idx",
                    )
                ],
                "unique_together": {("component", "billing_period")},
            },
        ),
    ]
