# Generated by Django 6.0.4 on 2026-04-13 14:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("marketplace", "0224_componentusagemonthly"),
    ]

    operations = [
        migrations.AddField(
            model_name="offeringuserattributeconfig",
            name="expose_address",
            field=models.BooleanField(default=False),
        ),
    ]
