# Generated by Django 6.0.8 on 2026-08-28 12:01

from decimal import Decimal

import django.core.validators
import django.db.models.deletion
import django.db.models.expressions
import django.utils.timezone
import django_fsm
import model_utils.fields
import netfields.fields
from django.conf import settings
from django.db import migrations, models

import waldur_core.core.fields
import waldur_core.core.validators
import waldur_core.logging.mixins
import waldur_core.media.validators
import waldur_core.permissions.mixins

# Trigger from 0254_slurm_partition_qos_offering_trigger (not expressible on the model).
FORWARD_SQL = """
CREATE OR REPLACE FUNCTION marketplace_slurm_partition_qos_offering_check()
RETURNS TRIGGER AS $$
BEGIN
    IF (
        SELECT offering_id FROM marketplace_offeringpartition
        WHERE id = NEW.partition_id
    ) IS DISTINCT FROM (
        SELECT offering_id FROM marketplace_slurmofferingqos
        WHERE id = NEW.qos_id
    ) THEN
        RAISE EXCEPTION
            'SlurmPartitionQoS: partition and qos must belong to the same offering';
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS marketplace_slurm_partition_qos_offering_check
    ON marketplace_slurmpartitionqos;

CREATE TRIGGER marketplace_slurm_partition_qos_offering_check
    BEFORE INSERT OR UPDATE ON marketplace_slurmpartitionqos
    FOR EACH ROW
    EXECUTE FUNCTION marketplace_slurm_partition_qos_offering_check();
"""

REVERSE_SQL = """
DROP TRIGGER IF EXISTS marketplace_slurm_partition_qos_offering_check
    ON marketplace_slurmpartitionqos;
DROP FUNCTION IF EXISTS marketplace_slurm_partition_qos_offering_check();
"""


class Migration(migrations.Migration):
    replaces = [
        ("marketplace", "0226_alter_offeringcomponent_limit_period"),
        (
            "marketplace",
            "0227_fix_maintenanceannouncementofferingtemplate_related_name",
        ),
        ("marketplace", "0228_component_usage_poll_record"),
        ("marketplace", "0229_remove_offeringuserrole_offering_and_more"),
        ("marketplace", "0230_delete_offeringuserrole_delete_resourceuser_and_more"),
        ("marketplace", "0231_offeringprofile_offering_profile"),
        ("marketplace", "0232_cleanup_orphan_role_availabilities"),
        ("marketplace", "0233_repair_limit_period_after_0226"),
        ("marketplace", "0234_resource_project_soft_delete"),
        ("marketplace", "0235_offeringgroup_offering_offering_group"),
        ("marketplace", "0236_project_order_auto_approval"),
        ("marketplace", "0237_resourcelimitchangerequest"),
        ("marketplace", "0238_alter_softwareversion_options_and_more"),
        ("marketplace", "0239_offeringuser_runtime_state"),
        ("marketplace", "0240_deactivate_orphaned_offering_roles"),
        ("marketplace", "0241_offering_role_group"),
        ("marketplace", "0242_resource_end_date_updated_at"),
        (
            "marketplace",
            "0243_offeringuserattributeconfig_expose_organization_vat_code",
        ),
        ("marketplace", "0244_offeringuserattributeconfig_expose_organization_address"),
        ("marketplace", "0245_plancomponent_discount_formula"),
        ("marketplace", "0246_plancomponent_discount_aggregation"),
        ("marketplace", "0247_posixidpool_posixidentity_and_more"),
        ("marketplace", "0248_posixidpool_optional_namespaces"),
        ("marketplace", "0249_offeringuserattributeconfig_expose_primary_gid_and_more"),
        ("marketplace", "0250_resource_usage_limit_restriction"),
        ("marketplace", "0251_resourceaccesssubnet"),
        ("marketplace", "0252_offeringaccesssubnet"),
        ("marketplace", "0253_slurmofferingqos_slurmpartitionqos_and_more"),
        ("marketplace", "0254_slurm_partition_qos_offering_trigger"),
        ("marketplace", "0253_resourceapikey"),
        ("marketplace", "0254_resourcemembersyncstatus"),
        ("marketplace", "0255_null_stale_scope_content_types"),
        ("marketplace", "0256_resource_api_key_drop_terminating"),
        ("marketplace", "0257_drop_resource_api_key_fingerprint"),
        ("marketplace", "0258_derive_service_access_mode"),
        ("marketplace", "0259_access_subnet_offering_scopes"),
        ("marketplace", "0260_order_message_timestamps"),
        ("marketplace", "0261_resourceenddatechangerequest"),
        ("marketplace", "0262_category_description_km_category_title_km_and_more"),
        ("marketplace", "0263_remove_category_default_tenant_category"),
    ]

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("core", "0040_personalaccesstoken_allowed_networks"),
        ("core", "__first__"),
        ("marketplace", "0225_add_expose_address_to_offering_user_attribute_config"),
        ("permissions", "0021_alter_role_name_roleavailability"),
        ("policy", "0016_sync_slurm_policy_period_with_component"),
        ("structure", "0077_affiliation_redesign"),
        ("structure", "0079_accesssubnet_scopes"),
        ("waldur_keycloak", "0004_alter_offeringkeycloakgroup_role"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccessSubnetOfferingScope",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uuid", waldur_core.core.fields.UUIDField()),
            ],
            options={
                "ordering": ["offering__name"],
            },
            bases=(models.Model, waldur_core.logging.mixins.LoggableMixin),
        ),
        migrations.CreateModel(
            name="ComponentUsagePollRecord",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "last_poll_time",
                    models.DateTimeField(
                        help_text="When this resource+component was last polled."
                    ),
                ),
                (
                    "raw_usage",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Raw value from the backend API at last poll.",
                        max_digits=20,
                    ),
                ),
                (
                    "elapsed_hours",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Hours since previous poll (capped at 24h).",
                        max_digits=10,
                    ),
                ),
                (
                    "increment",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="raw_usage × elapsed_hours added to the running total.",
                        max_digits=20,
                    ),
                ),
                (
                    "accumulated_total",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Running total for the current billing period.",
                        max_digits=20,
                    ),
                ),
                (
                    "billing_period",
                    models.DateField(help_text="Month this accumulation belongs to."),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OfferingAccessSubnet",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=4096, verbose_name="description"
                    ),
                ),
                ("uuid", waldur_core.core.fields.UUIDField()),
                (
                    "inet",
                    netfields.fields.CidrAddressField(
                        blank=True, max_length=43, null=True
                    ),
                ),
            ],
            options={
                "ordering": ["inet"],
            },
            bases=(models.Model, waldur_core.logging.mixins.LoggableMixin),
        ),
        migrations.CreateModel(
            name="OfferingGroup",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=4096, verbose_name="description"
                    ),
                ),
                ("uuid", waldur_core.core.fields.UUIDField()),
                ("title", models.CharField(max_length=255)),
                (
                    "icon",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="marketplace_offering_group_icons",
                        validators=[
                            waldur_core.media.validators.FileTypeValidator(
                                allowed_types=[
                                    "image/png",
                                    "image/gif",
                                    "image/jpeg",
                                    "image/svg",
                                    "image/svg+xml",
                                    "image/x-icon",
                                ]
                            )
                        ],
                    ),
                ),
            ],
            options={
                "verbose_name": "Offering group",
                "verbose_name_plural": "Offering groups",
                "ordering": ("title",),
            },
        ),
        migrations.CreateModel(
            name="OfferingProfile",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=4096, verbose_name="description"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=150,
                        validators=[waldur_core.core.validators.validate_name],
                        verbose_name="name",
                    ),
                ),
                ("uuid", waldur_core.core.fields.UUIDField()),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="OfferingRoleGroup",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("backend_metadata", models.JSONField(blank=True, default=dict)),
                ("object_id", models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="PosixIdentity",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("uuid", waldur_core.core.fields.UUIDField()),
                ("uid", models.BigIntegerField(blank=True, null=True)),
                ("gid", models.BigIntegerField(blank=True, null=True)),
                ("object_id", models.PositiveIntegerField()),
                ("released_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "POSIX identity",
                "verbose_name_plural": "POSIX identities",
                "ordering": ("pool", "uid", "gid"),
            },
        ),
        migrations.CreateModel(
            name="PosixIdPool",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=4096, verbose_name="description"
                    ),
                ),
                ("uuid", waldur_core.core.fields.UUIDField()),
                ("min_uid", models.BigIntegerField(blank=True, null=True)),
                ("max_uid", models.BigIntegerField(blank=True, null=True)),
                ("next_uid", models.BigIntegerField(blank=True, null=True)),
                ("min_gid", models.BigIntegerField(blank=True, null=True)),
                ("max_gid", models.BigIntegerField(blank=True, null=True)),
                ("next_gid", models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "POSIX ID pool",
                "verbose_name_plural": "POSIX ID pools",
            },
        ),
        migrations.CreateModel(
            name="ProjectOrderAutoApproval",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("uuid", waldur_core.core.fields.UUIDField()),
                (
                    "monthly_cost_limit",
                    models.DecimalField(
                        decimal_places=10,
                        max_digits=22,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                ("enabled", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Project order auto-approval",
            },
        ),
        migrations.CreateModel(
            name="ResourceApiKey",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("uuid", waldur_core.core.fields.UUIDField()),
                ("error_message", models.TextField(blank=True)),
                ("error_traceback", models.TextField(blank=True)),
                (
                    "client_id",
                    models.CharField(blank=True, db_index=True, max_length=255),
                ),
                ("key_ciphertext", models.TextField(blank=True)),
                (
                    "state",
                    django_fsm.FSMField(
                        choices=[
                            ("Creating", "Creating"),
                            ("OK", "OK"),
                            ("Updating", "Updating"),
                            ("Erred", "Erred"),
                        ],
                        default="Creating",
                        max_length=50,
                    ),
                ),
            ],
            options={
                "verbose_name": "Resource API key",
            },
        ),
        migrations.CreateModel(
            name="ResourceEndDateChangeRequest",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("uuid", waldur_core.core.fields.UUIDField()),
                (
                    "state",
                    django_fsm.FSMIntegerField(
                        choices=[
                            (1, "draft"),
                            (2, "pending"),
                            (3, "approved"),
                            (4, "rejected"),
                            (5, "canceled"),
                        ],
                        default=1,
                    ),
                ),
                (
                    "reviewed_at",
                    models.DateTimeField(
                        blank=True,
                        editable=False,
                        help_text="Timestamp when the review was completed",
                        null=True,
                    ),
                ),
                (
                    "review_comment",
                    models.TextField(
                        blank=True,
                        help_text="Optional comment provided during review",
                        null=True,
                    ),
                ),
                (
                    "requested_end_date",
                    models.DateField(
                        help_text="The requested new end date for the resource"
                    ),
                ),
                (
                    "comment",
                    models.TextField(
                        blank=True,
                        help_text="Optional comment from the requester",
                        null=True,
                    ),
                ),
                (
                    "backend_id",
                    models.CharField(
                        blank=True,
                        help_text="Identifier of this request in an external approval system. Empty means it has not been submitted there yet.",
                        max_length=255,
                    ),
                ),
            ],
            options={
                "verbose_name": "Resource end date change request",
                "verbose_name_plural": "Resource end date change requests",
                "ordering": ["created"],
            },
            bases=(models.Model, waldur_core.logging.mixins.LoggableMixin),
        ),
        migrations.CreateModel(
            name="ResourceLimitChangeRequest",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("uuid", waldur_core.core.fields.UUIDField()),
                (
                    "state",
                    django_fsm.FSMIntegerField(
                        choices=[
                            (1, "draft"),
                            (2, "pending"),
                            (3, "approved"),
                            (4, "rejected"),
                            (5, "canceled"),
                        ],
                        default=1,
                    ),
                ),
                (
                    "reviewed_at",
                    models.DateTimeField(
                        blank=True,
                        editable=False,
                        help_text="Timestamp when the review was completed",
                        null=True,
                    ),
                ),
                (
                    "review_comment",
                    models.TextField(
                        blank=True,
                        help_text="Optional comment provided during review",
                        null=True,
                    ),
                ),
                ("requested_limits", models.JSONField()),
            ],
            options={
                "verbose_name": "Resource limit change request",
                "verbose_name_plural": "Resource limit change requests",
                "ordering": ["created"],
            },
        ),
        migrations.CreateModel(
            name="ResourceMemberSyncStatus",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("uuid", waldur_core.core.fields.UUIDField()),
                (
                    "scope_type",
                    models.CharField(
                        choices=[
                            ("resource", "Resource"),
                            ("resource_project", "Resource project"),
                        ],
                        max_length=32,
                    ),
                ),
                ("role_name", models.CharField(max_length=150)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("synced", "Synced"),
                            ("pending", "Pending"),
                            ("missing_in_idp", "Missing in identity provider"),
                            ("error", "Error"),
                        ],
                        max_length=32,
                    ),
                ),
                ("message", models.TextField(blank=True, default="")),
            ],
            options={
                "verbose_name": "Resource member sync status",
                "verbose_name_plural": "Resource member sync statuses",
            },
        ),
        migrations.CreateModel(
            name="ResourceProject",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=150,
                        validators=[waldur_core.core.validators.validate_name],
                        verbose_name="name",
                    ),
                ),
                ("uuid", waldur_core.core.fields.UUIDField()),
                ("error_message", models.TextField(blank=True)),
                ("error_traceback", models.TextField(blank=True)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "backend_id",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "state",
                    django_fsm.FSMIntegerField(
                        choices=[
                            (1, "Creating"),
                            (2, "OK"),
                            (3, "Erred"),
                            (4, "Updating"),
                            (5, "Terminating"),
                            (6, "Terminated"),
                        ],
                        default=1,
                    ),
                ),
                (
                    "limits",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Dictionary mapping component types to quota values. Same format as Resource.limits.",
                    ),
                ),
                (
                    "current_usages",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Dictionary mapping component types to current usage amounts. Populated by backend synchronization.",
                    ),
                ),
                ("is_removed", models.BooleanField(default=False)),
                ("removed_date", models.DateTimeField(blank=True, null=True)),
                ("termination_metadata", models.JSONField(blank=True, null=True)),
            ],
            options={
                "ordering": ["created"],
                "base_manager_name": "objects",
            },
            bases=(waldur_core.permissions.mixins.PermissionMixin, models.Model),
        ),
        migrations.CreateModel(
            name="SlurmOfferingQoS",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("uuid", waldur_core.core.fields.UUIDField()),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the SLURM QOS.",
                        max_length=255,
                        validators=[
                            django.core.validators.RegexValidator(
                                inverse_match=True,
                                message="QoS name cannot consist only of digits.",
                                regex="^\\d+$",
                            )
                        ],
                    ),
                ),
                ("description", models.CharField(blank=True, max_length=255)),
                (
                    "max_nodes",
                    models.PositiveIntegerField(
                        blank=True, help_text="Maximum nodes per job", null=True
                    ),
                ),
                (
                    "min_nodes",
                    models.PositiveIntegerField(
                        blank=True, help_text="Minimum nodes per job", null=True
                    ),
                ),
                (
                    "default_time",
                    models.PositiveIntegerField(
                        blank=True, help_text="Default time limit in minutes", null=True
                    ),
                ),
                (
                    "max_time",
                    models.PositiveIntegerField(
                        blank=True, help_text="Maximum wall time in minutes", null=True
                    ),
                ),
                (
                    "grace_time",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Preemption grace time in seconds",
                        null=True,
                    ),
                ),
                (
                    "priority",
                    models.PositiveIntegerField(
                        blank=True, help_text="Scheduling priority", null=True
                    ),
                ),
                (
                    "grp_tres",
                    models.CharField(
                        blank=True,
                        help_text="Aggregate TRES the QOS may allocate at once (GrpTRES)",
                        max_length=255,
                    ),
                ),
                (
                    "max_tres_per_job",
                    models.CharField(
                        blank=True,
                        help_text="Max TRES per job (MaxTRESPerJob)",
                        max_length=255,
                    ),
                ),
                (
                    "max_tres_per_node",
                    models.CharField(
                        blank=True,
                        help_text="Max TRES per node (MaxTRESPerNode)",
                        max_length=255,
                    ),
                ),
                (
                    "max_tres_per_user",
                    models.CharField(
                        blank=True,
                        help_text="Max TRES per user (MaxTRESPerUser)",
                        max_length=255,
                    ),
                ),
                (
                    "min_tres_per_job",
                    models.CharField(
                        blank=True,
                        help_text="Min TRES per job (MinTRESPerJob)",
                        max_length=255,
                    ),
                ),
                (
                    "flags",
                    models.CharField(
                        blank=True,
                        help_text="Comma-separated QOS flags (e.g. DenyOnLimit, OverPartQOS)",
                        max_length=255,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SlurmPartitionQoS",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("uuid", waldur_core.core.fields.UUIDField()),
                (
                    "is_default",
                    models.BooleanField(
                        default=False,
                        help_text="Default QOS for this partition (seeds SLURM DefaultQOS).",
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="offeringuserrole",
            name="offering",
        ),
        migrations.RemoveField(
            model_name="resourceuser",
            name="role",
        ),
        migrations.RemoveField(
            model_name="resourceuser",
            name="resource",
        ),
        migrations.RemoveField(
            model_name="resourceuser",
            name="user",
        ),
        migrations.AlterModelOptions(
            name="softwareversion",
            options={"ordering": ["package", "version", "module_version"]},
        ),
        migrations.AlterUniqueTogether(
            name="softwareversion",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="category",
            name="default_tenant_category",
        ),
        migrations.RemoveField(
            model_name="plancomponent",
            name="discount_rate",
        ),
        migrations.RemoveField(
            model_name="plancomponent",
            name="discount_threshold",
        ),
        migrations.AddField(
            model_name="category",
            name="description_km",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="category",
            name="title_km",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="categorygroup",
            name="description_km",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="categorygroup",
            name="title_km",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="offeringuser",
            name="runtime_state",
            field=models.CharField(
                choices=[
                    ("Active", "Active"),
                    ("Pending account linking", "Pending account linking"),
                    ("Pending additional validation", "Pending additional validation"),
                ],
                default="Active",
                help_text="Operational/access state of the user account. Separate from lifecycle state; can be set by the service provider at any time.",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="offeringuserattributeconfig",
            name="expose_organization_address",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="offeringuserattributeconfig",
            name="expose_organization_vat_code",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="offeringuserattributeconfig",
            name="expose_primary_gid",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="offeringuserattributeconfig",
            name="expose_uid_number",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="order",
            name="auto_approved_cost_limit_snapshot",
            field=models.DecimalField(
                blank=True, decimal_places=10, max_digits=22, null=True
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="consumer_message_updated_at",
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="provider_message_updated_at",
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="plancomponent",
            name="discount_aggregation",
            field=models.CharField(
                choices=[
                    ("resource", "Per resource"),
                    ("customer", "Aggregated per customer"),
                ],
                default="customer",
                help_text="Whether the volume discount is computed on a single resource's usage or aggregated across all of the customer's resources of this offering.",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="plancomponent",
            name="discount_formula",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Volume discount formula evaluated with the billed quantity bound to `usage`; returns a discount percentage (clamped to 0-100). Empty means no discount. Example: '10 if usage >= 100 else 0'.",
            ),
        ),
        migrations.AddField(
            model_name="resource",
            name="end_date_updated_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Timestamp of the last end_date change.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="resource",
            name="usage_limit_restriction",
            field=models.CharField(
                blank=True,
                choices=[("paused", "Paused"), ("downscaled", "Downscaled")],
                default="",
                help_text="Which restriction (paused or downscaled) was automatically applied because reported usage reached a component limit. Empty when no such restriction is active. Used so the automatic lift never clears a restriction that was set for another reason.",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="softwareversion",
            name="module_version",
            field=models.CharField(
                blank=True,
                default="",
                help_text="EESSI EasyBuild module version",
                max_length=150,
            ),
        ),
        migrations.AlterField(
            model_name="maintenanceannouncementofferingtemplate",
            name="maintenance_template",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="affected_offerings",
                to="marketplace.maintenanceannouncementtemplate",
            ),
        ),
        migrations.AlterField(
            model_name="offeringcomponent",
            name="limit_period",
            field=models.CharField(
                choices=[
                    (
                        "month",
                        "Maximum monthly - every month service provider can report up to the amount requested by user.",
                    ),
                    (
                        "quarterly",
                        "Maximum quarterly - every quarter service provider can report up to the amount requested by user.",
                    ),
                    (
                        "annual",
                        "Maximum annually - every year service provider can report up to the amount requested by user.",
                    ),
                    (
                        "total",
                        "Maximum total - SP can report up to the requested amount over the whole active state of resource.",
                    ),
                ],
                default="month",
                max_length=10,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="softwareversion",
            unique_together={("package", "version", "module_version")},
        ),
        migrations.AddIndex(
            model_name="softwareversion",
            index=models.Index(
                fields=["package", "module_version"],
                name="marketplace_package_30aa27_idx",
            ),
        ),
        migrations.AddField(
            model_name="accesssubnetofferingscope",
            name="access_subnet",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="structure.accesssubnet",
            ),
        ),
        migrations.AddField(
            model_name="accesssubnetofferingscope",
            name="offering",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="access_subnet_scopes",
                to="marketplace.offering",
            ),
        ),
        migrations.AddField(
            model_name="componentusagepollrecord",
            name="component",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="marketplace.offeringcomponent",
            ),
        ),
        migrations.AddField(
            model_name="componentusagepollrecord",
            name="resource",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="usage_poll_records",
                to="marketplace.resource",
            ),
        ),
        migrations.AddField(
            model_name="offeringaccesssubnet",
            name="offering",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="default_access_subnets",
                to="marketplace.offering",
            ),
        ),
        migrations.AddField(
            model_name="offeringgroup",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="offering_groups",
                to="structure.customer",
            ),
        ),
        migrations.AddField(
            model_name="offering",
            name="offering_group",
            field=models.ForeignKey(
                blank=True,
                help_text="Logical group this offering belongs to. Group must share the same customer.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="offerings",
                to="marketplace.offeringgroup",
            ),
        ),
        migrations.AddField(
            model_name="offeringprofile",
            name="roles",
            field=models.ManyToManyField(
                blank=True,
                help_text="Role catalog. These roles become assignable on every offering bound to this profile.",
                related_name="offering_profiles",
                to="permissions.role",
            ),
        ),
        migrations.AddField(
            model_name="offering",
            name="profile",
            field=models.ForeignKey(
                blank=True,
                help_text="Service profile (logical grouping). When set, the offering's user-role catalog is reconciled from the profile and managed centrally by staff. Leave empty for per-offering custom roles.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="offerings",
                to="marketplace.offeringprofile",
            ),
        ),
        migrations.AddField(
            model_name="offeringrolegroup",
            name="content_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddField(
            model_name="offeringrolegroup",
            name="offering",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="role_groups",
                to="marketplace.offering",
            ),
        ),
        migrations.AddField(
            model_name="offeringrolegroup",
            name="role",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="permissions.role",
            ),
        ),
        migrations.AddField(
            model_name="posixidentity",
            name="content_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddField(
            model_name="posixidentity",
            name="offering",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="posix_identities",
                to="marketplace.offering",
            ),
        ),
        migrations.AddField(
            model_name="posixidpool",
            name="offering",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="posix_pool",
                to="marketplace.offering",
            ),
        ),
        migrations.AddField(
            model_name="posixidpool",
            name="service_provider",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="posix_pool",
                to="marketplace.serviceprovider",
            ),
        ),
        migrations.AddField(
            model_name="posixidentity",
            name="pool",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="identities",
                to="marketplace.posixidpool",
            ),
        ),
        migrations.AddField(
            model_name="projectorderautoapproval",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="projectorderautoapproval",
            name="modified_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="projectorderautoapproval",
            name="project",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="order_auto_approval",
                to="structure.project",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="auto_approved_by_rule",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_orders",
                to="marketplace.projectorderautoapproval",
            ),
        ),
        migrations.AddField(
            model_name="resourceapikey",
            name="resource",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="api_keys",
                to="marketplace.resource",
            ),
        ),
        migrations.AddField(
            model_name="resourceenddatechangerequest",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="resourceenddatechangerequest",
            name="resource",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="end_date_change_requests",
                to="marketplace.resource",
            ),
        ),
        migrations.AddField(
            model_name="resourceenddatechangerequest",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who performed the review",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="resourcelimitchangerequest",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="resourcelimitchangerequest",
            name="resource",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="limit_change_requests",
                to="marketplace.resource",
            ),
        ),
        migrations.AddField(
            model_name="resourcelimitchangerequest",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who performed the review",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="resourcemembersyncstatus",
            name="resource",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="member_sync_statuses",
                to="marketplace.resource",
            ),
        ),
        migrations.AddField(
            model_name="resourcemembersyncstatus",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="resourceproject",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_resource_projects",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="resourceproject",
            name="removed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="removed_resource_projects",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="resourceproject",
            name="resource",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="projects",
                to="marketplace.resource",
            ),
        ),
        migrations.AddField(
            model_name="resourcemembersyncstatus",
            name="resource_project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="member_sync_statuses",
                to="marketplace.resourceproject",
            ),
        ),
        migrations.AddField(
            model_name="slurmofferingqos",
            name="offering",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="qos_profiles",
                to="marketplace.offering",
            ),
        ),
        migrations.AddField(
            model_name="slurmpartitionqos",
            name="partition",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="qos_options",
                to="marketplace.offeringpartition",
            ),
        ),
        migrations.AddField(
            model_name="slurmpartitionqos",
            name="qos",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="partition_links",
                to="marketplace.slurmofferingqos",
            ),
        ),
        migrations.DeleteModel(
            name="OfferingUserRole",
        ),
        migrations.DeleteModel(
            name="ResourceUser",
        ),
        migrations.AlterUniqueTogether(
            name="accesssubnetofferingscope",
            unique_together={("access_subnet", "offering")},
        ),
        migrations.AlterUniqueTogether(
            name="componentusagepollrecord",
            unique_together={("resource", "component")},
        ),
        migrations.AlterUniqueTogether(
            name="offeringaccesssubnet",
            unique_together={("offering", "inet")},
        ),
        migrations.AddIndex(
            model_name="offeringrolegroup",
            index=models.Index(
                fields=["content_type", "object_id"],
                name="marketplace_content_cb515a_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="offeringrolegroup",
            unique_together={("offering", "content_type", "object_id", "role")},
        ),
        migrations.AddConstraint(
            model_name="posixidpool",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("offering__isnull", True), ("service_provider__isnull", False)
                    ),
                    models.Q(
                        ("offering__isnull", False), ("service_provider__isnull", True)
                    ),
                    _connector="OR",
                ),
                name="marketplace_posixidpool_exactly_one_scope",
            ),
        ),
        migrations.AddConstraint(
            model_name="posixidpool",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("min_uid__gte", 1000),
                    ("min_uid__lte", models.F("max_uid")),
                    ("max_uid__lte", 4294967294),
                    ("next_uid__gte", models.F("min_uid")),
                    (
                        "next_uid__lte",
                        django.db.models.expressions.CombinedExpression(
                            models.F("max_uid"), "+", models.Value(1)
                        ),
                    ),
                ),
                name="marketplace_posixidpool_uid_bounds",
            ),
        ),
        migrations.AddConstraint(
            model_name="posixidpool",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("min_gid__gte", 1000),
                    ("min_gid__lte", models.F("max_gid")),
                    ("max_gid__lte", 4294967294),
                    ("next_gid__gte", models.F("min_gid")),
                    (
                        "next_gid__lte",
                        django.db.models.expressions.CombinedExpression(
                            models.F("max_gid"), "+", models.Value(1)
                        ),
                    ),
                ),
                name="marketplace_posixidpool_gid_bounds",
            ),
        ),
        migrations.AddConstraint(
            model_name="posixidpool",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("max_uid__isnull", True),
                        ("min_uid__isnull", True),
                        ("next_uid__isnull", True),
                    ),
                    models.Q(
                        ("max_uid__isnull", False),
                        ("min_uid__isnull", False),
                        ("next_uid__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="marketplace_posixidpool_uid_all_or_nothing",
            ),
        ),
        migrations.AddConstraint(
            model_name="posixidpool",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("max_gid__isnull", True),
                        ("min_gid__isnull", True),
                        ("next_gid__isnull", True),
                    ),
                    models.Q(
                        ("max_gid__isnull", False),
                        ("min_gid__isnull", False),
                        ("next_gid__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="marketplace_posixidpool_gid_all_or_nothing",
            ),
        ),
        migrations.AddConstraint(
            model_name="posixidpool",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("min_uid__isnull", False),
                    ("min_gid__isnull", False),
                    _connector="OR",
                ),
                name="marketplace_posixidpool_at_least_one_namespace",
            ),
        ),
        migrations.AddIndex(
            model_name="posixidentity",
            index=models.Index(
                fields=["content_type", "object_id"],
                name="mp_posixidentity_consumer_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="posixidentity",
            index=models.Index(
                fields=["pool", "uid"], name="mp_posixidentity_pool_uid_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="posixidentity",
            index=models.Index(
                fields=["pool", "gid"], name="mp_posixidentity_pool_gid_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="posixidentity",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("released_at__isnull", True), ("uid__isnull", False)
                ),
                fields=("pool", "uid"),
                name="marketplace_posixidentity_active_uid",
            ),
        ),
        migrations.AddConstraint(
            model_name="posixidentity",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("gid__isnull", False), ("released_at__isnull", True)
                ),
                fields=("pool", "gid"),
                name="marketplace_posixidentity_active_gid",
            ),
        ),
        migrations.AddConstraint(
            model_name="posixidentity",
            constraint=models.UniqueConstraint(
                condition=models.Q(("released_at__isnull", True)),
                fields=("content_type", "object_id"),
                name="marketplace_posixidentity_active_consumer",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="resourceapikey",
            unique_together={("resource", "client_id")},
        ),
        migrations.AddConstraint(
            model_name="resourceenddatechangerequest",
            constraint=models.UniqueConstraint(
                condition=models.Q(("state", 2)),
                fields=("resource", "created_by"),
                name="unique_pending_end_date_request_per_resource_and_user",
            ),
        ),
        migrations.AddConstraint(
            model_name="resourcelimitchangerequest",
            constraint=models.UniqueConstraint(
                condition=models.Q(("state", 2)),
                fields=("resource", "created_by"),
                name="unique_pending_limit_change_request_per_resource_and_user",
            ),
        ),
        migrations.AddConstraint(
            model_name="resourceproject",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_removed", False)),
                fields=("resource", "name"),
                name="uniq_active_resource_project_name_per_resource",
            ),
        ),
        migrations.AddIndex(
            model_name="resourcemembersyncstatus",
            index=models.Index(
                fields=["resource", "user"], name="marketplace_resourc_ca8616_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="slurmofferingqos",
            index=models.Index(
                fields=["offering", "name"], name="marketplace_offerin_1107c0_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="slurmofferingqos",
            unique_together={("offering", "name")},
        ),
        migrations.AddConstraint(
            model_name="slurmpartitionqos",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_default", True)),
                fields=("partition",),
                name="unique_default_qos_per_partition",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="slurmpartitionqos",
            unique_together={("partition", "qos")},
        ),
        migrations.RunSQL(sql=FORWARD_SQL, reverse_sql=REVERSE_SQL),
    ]
