# Generated by Django 6.0.3 on 2026-03-30 20:22
#
# WAL-9907: The original RunPython here unconditionally rewrote every NULL/empty
# OfferingComponent.limit_period to "month". On deployments using the implicit
# policy.period contract (component.limit_period left empty,
# SlurmPeriodicUsagePolicy.period = MONTH_3 / MONTH_12 / TOTAL) this silently
# flipped quarterly/annual offerings to monthly. The backfill below now honors
# the policy intent before falling back to "month".
#
# Idempotent on already-migrated sites (where every limit_period is already
# "month"): the WHERE clauses match no rows. Sites that ran the broken version
# of this migration must additionally apply
# 0229_repair_limit_period_after_0226 to undo the damage — Django will not
# re-run a migration whose row already exists in django_migrations.

from django.db import migrations, models

# Mirrors invoices.PeriodMixin.Periods integer values:
#   1 = TOTAL, 2 = MONTH_1, 3 = MONTH_3, 4 = MONTH_12.
# MONTH_1 (the default policy period) is intentionally absent — those
# components fall through to the "month" default in phase 2.
POLICY_PERIOD_TO_LIMIT_PERIOD = {
    1: "total",
    3: "quarterly",
    4: "annual",
}


def backfill_limit_period(apps, schema_editor):
    OfferingComponent = apps.get_model("marketplace", "OfferingComponent")
    SlurmPeriodicUsagePolicy = apps.get_model("policy", "SlurmPeriodicUsagePolicy")

    # Phase 1: components on offerings whose policy declares a non-monthly period
    # inherit the corresponding limit_period string. Iterating per-policy keeps
    # the decision auditable and avoids a cross-app subquery in raw UPDATE form.
    for policy in SlurmPeriodicUsagePolicy.objects.exclude(period=2):
        derived = POLICY_PERIOD_TO_LIMIT_PERIOD.get(policy.period)
        if not derived:
            continue
        OfferingComponent.objects.filter(
            offering_id=policy.scope_id,
            billing_type="limit",
        ).filter(
            models.Q(limit_period__isnull=True) | models.Q(limit_period="")
        ).update(limit_period=derived)

    # Phase 2: everything still NULL/empty defaults to "month".
    OfferingComponent.objects.filter(limit_period__isnull=True).update(
        limit_period="month"
    )
    OfferingComponent.objects.filter(limit_period="").update(limit_period="month")


class Migration(migrations.Migration):
    dependencies = [
        ("marketplace", "0225_add_expose_address_to_offering_user_attribute_config"),
        # Needed to read SlurmPeriodicUsagePolicy.scope_id / .period during the
        # smart backfill.
        ("policy", "0016_sync_slurm_policy_period_with_component"),
    ]

    operations = [
        migrations.RunPython(backfill_limit_period, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="offeringcomponent",
            name="limit_period",
            field=models.CharField(
                choices=[
                    (
                        "month",
                        "Maximum monthly - every month service provider can report up to the amount requested by user.",
                    ),
                    (
                        "quarterly",
                        "Maximum quarterly - every quarter service provider can report up to the amount requested by user.",
                    ),
                    (
                        "annual",
                        "Maximum annually - every year service provider can report up to the amount requested by user.",
                    ),
                    (
                        "total",
                        "Maximum total - SP can report up to the requested amount over the whole active state of resource.",
                    ),
                ],
                default="month",
                max_length=10,
            ),
        ),
    ]
