# Generated by Django 6.0.4 on 2026-04-23 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("marketplace", "0226_alter_offeringcomponent_limit_period"),
    ]

    operations = [
        migrations.AlterField(
            model_name="maintenanceannouncementofferingtemplate",
            name="maintenance_template",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="affected_offerings",
                to="marketplace.maintenanceannouncementtemplate",
            ),
        ),
    ]
