# Generated by Django 6.0.4 on 2026-04-26 19:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("marketplace", "0229_remove_offeringuserrole_offering_and_more"),
        ("waldur_keycloak", "0004_alter_offeringkeycloakgroup_role"),
    ]

    operations = [
        migrations.DeleteModel(
            name="OfferingUserRole",
        ),
        migrations.DeleteModel(
            name="ResourceUser",
        ),
        migrations.AlterUniqueTogether(
            name="resourceproject",
            unique_together={("resource", "name")},
        ),
    ]
