# Generated by Django 6.0.4 on 2026-04-27 06:29

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models

import waldur_core.core.fields
import waldur_core.core.validators


class Migration(migrations.Migration):
    dependencies = [
        ("marketplace", "0230_delete_offeringuserrole_delete_resourceuser_and_more"),
        ("permissions", "0021_alter_role_name_roleavailability"),
    ]

    operations = [
        migrations.CreateModel(
            name="OfferingProfile",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=4096, verbose_name="description"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=150,
                        validators=[waldur_core.core.validators.validate_name],
                        verbose_name="name",
                    ),
                ),
                ("uuid", waldur_core.core.fields.UUIDField()),
                (
                    "roles",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Role catalog. These roles become assignable on every offering bound to this profile.",
                        related_name="offering_profiles",
                        to="permissions.role",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="offering",
            name="profile",
            field=models.ForeignKey(
                blank=True,
                help_text="Service profile (logical grouping). When set, the offering's user-role catalog is reconciled from the profile and managed centrally by staff. Leave empty for per-offering custom roles.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="offerings",
                to="marketplace.offeringprofile",
            ),
        ),
    ]
