# Generated by Django 6.0.4 on 2026-05-11 10:00

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import waldur_core.core.fields
import waldur_core.media.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("marketplace", "0233_repair_limit_period_after_0226"),
        ("structure", "0077_affiliation_redesign"),
    ]

    operations = [
        migrations.CreateModel(
            name="OfferingGroup",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=4096, verbose_name="description"
                    ),
                ),
                ("uuid", waldur_core.core.fields.UUIDField()),
                ("title", models.CharField(max_length=255)),
                (
                    "icon",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="marketplace_offering_group_icons",
                        validators=[
                            waldur_core.media.validators.FileTypeValidator(
                                allowed_types=[
                                    "image/png",
                                    "image/gif",
                                    "image/jpeg",
                                    "image/svg",
                                    "image/svg+xml",
                                    "image/x-icon",
                                ]
                            )
                        ],
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="offering_groups",
                        to="structure.customer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Offering group",
                "verbose_name_plural": "Offering groups",
                "ordering": ("title",),
            },
        ),
        migrations.AddField(
            model_name="offering",
            name="offering_group",
            field=models.ForeignKey(
                blank=True,
                help_text="Logical group this offering belongs to. Group must share the same customer.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="offerings",
                to="marketplace.offeringgroup",
            ),
        ),
    ]
