# Generated by Django 6.0.6 on 2026-06-10 12:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("marketplace", "0241_offering_role_group"),
    ]

    operations = [
        migrations.AddField(
            model_name="resource",
            name="end_date_updated_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Timestamp of the last end_date change.",
                null=True,
            ),
        ),
    ]
