# Generated by Django 6.0.6 on 2026-06-22 20:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("marketplace", "0242_resource_end_date_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="offeringuserattributeconfig",
            name="expose_organization_vat_code",
            field=models.BooleanField(default=False),
        ),
    ]
