# Generated by Django 6.0.6 on 2026-06-28 14:23

import django.db.models.deletion
import django.db.models.expressions
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models

import waldur_core.core.fields

from ._enable_posix_account_backfill import backfill_enable_posix_account
from ._posix_pool_backfill import backfill_posix_pools


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("marketplace", "0246_plancomponent_discount_aggregation"),
    ]

    operations = [
        migrations.CreateModel(
            name="PosixIdPool",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=4096, verbose_name="description"
                    ),
                ),
                ("uuid", waldur_core.core.fields.UUIDField()),
                ("min_uid", models.BigIntegerField(blank=True, null=True)),
                ("max_uid", models.BigIntegerField(blank=True, null=True)),
                ("next_uid", models.BigIntegerField(blank=True, null=True)),
                ("min_gid", models.BigIntegerField(blank=True, null=True)),
                ("max_gid", models.BigIntegerField(blank=True, null=True)),
                ("next_gid", models.BigIntegerField(blank=True, null=True)),
                (
                    "offering",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="posix_pool",
                        to="marketplace.offering",
                    ),
                ),
                (
                    "service_provider",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="posix_pool",
                        to="marketplace.serviceprovider",
                    ),
                ),
            ],
            options={
                "verbose_name": "POSIX ID pool",
                "verbose_name_plural": "POSIX ID pools",
            },
        ),
        migrations.CreateModel(
            name="PosixIdentity",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("uuid", waldur_core.core.fields.UUIDField()),
                ("uid", models.BigIntegerField(blank=True, null=True)),
                ("gid", models.BigIntegerField(blank=True, null=True)),
                ("object_id", models.PositiveIntegerField()),
                ("released_at", models.DateTimeField(blank=True, null=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "offering",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="posix_identities",
                        to="marketplace.offering",
                    ),
                ),
                (
                    "pool",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="identities",
                        to="marketplace.posixidpool",
                    ),
                ),
            ],
            options={
                "verbose_name": "POSIX identity",
                "verbose_name_plural": "POSIX identities",
                "ordering": ("pool", "uid", "gid"),
            },
        ),
        migrations.AddConstraint(
            model_name="posixidpool",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("offering__isnull", True), ("service_provider__isnull", False)
                    ),
                    models.Q(
                        ("offering__isnull", False), ("service_provider__isnull", True)
                    ),
                    _connector="OR",
                ),
                name="marketplace_posixidpool_exactly_one_scope",
            ),
        ),
        migrations.AddConstraint(
            model_name="posixidpool",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("min_uid__gte", 1000),
                    ("min_uid__lte", models.F("max_uid")),
                    ("max_uid__lte", 4294967294),
                    ("next_uid__gte", models.F("min_uid")),
                    (
                        "next_uid__lte",
                        django.db.models.expressions.CombinedExpression(
                            models.F("max_uid"), "+", models.Value(1)
                        ),
                    ),
                ),
                name="marketplace_posixidpool_uid_bounds",
            ),
        ),
        migrations.AddConstraint(
            model_name="posixidpool",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("min_gid__gte", 1000),
                    ("min_gid__lte", models.F("max_gid")),
                    ("max_gid__lte", 4294967294),
                    ("next_gid__gte", models.F("min_gid")),
                    (
                        "next_gid__lte",
                        django.db.models.expressions.CombinedExpression(
                            models.F("max_gid"), "+", models.Value(1)
                        ),
                    ),
                ),
                name="marketplace_posixidpool_gid_bounds",
            ),
        ),
        migrations.AddIndex(
            model_name="posixidentity",
            index=models.Index(
                fields=["content_type", "object_id"],
                name="mp_posixidentity_consumer_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="posixidentity",
            index=models.Index(
                fields=["pool", "uid"], name="mp_posixidentity_pool_uid_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="posixidentity",
            index=models.Index(
                fields=["pool", "gid"], name="mp_posixidentity_pool_gid_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="posixidentity",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("released_at__isnull", True), ("uid__isnull", False)
                ),
                fields=("pool", "uid"),
                name="marketplace_posixidentity_active_uid",
            ),
        ),
        migrations.AddConstraint(
            model_name="posixidentity",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("gid__isnull", False), ("released_at__isnull", True)
                ),
                fields=("pool", "gid"),
                name="marketplace_posixidentity_active_gid",
            ),
        ),
        migrations.AddConstraint(
            model_name="posixidentity",
            constraint=models.UniqueConstraint(
                condition=models.Q(("released_at__isnull", True)),
                fields=("content_type", "object_id"),
                name="marketplace_posixidentity_active_consumer",
            ),
        ),
        # Fold legacy POSIX configuration into the new pool/identity tables, then
        # stamp enable_posix_account on offerings that predate the option. Both
        # are one-time data moves, so they are elidable when squashing.
        migrations.RunPython(
            backfill_posix_pools, migrations.RunPython.noop, elidable=True
        ),
        migrations.RunPython(
            backfill_enable_posix_account, migrations.RunPython.noop, elidable=True
        ),
    ]
