# Generated by Django 6.0.6 on 2026-07-05 22:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("marketplace", "0248_posixidpool_optional_namespaces"),
    ]

    operations = [
        migrations.AddField(
            model_name="offeringuserattributeconfig",
            name="expose_primary_gid",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="offeringuserattributeconfig",
            name="expose_uid_number",
            field=models.BooleanField(default=False),
        ),
    ]
