# Generated by Django 6.0.7 on 2026-07-16 15:15

import django.db.models.deletion
import netfields.fields
from django.db import migrations, models

import waldur_core.core.fields
import waldur_core.logging.mixins
import waldur_core.structure.models


class Migration(migrations.Migration):
    dependencies = [
        ("marketplace", "0250_resource_usage_limit_restriction"),
    ]

    operations = [
        migrations.CreateModel(
            name="ResourceAccessSubnet",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=4096, verbose_name="description"
                    ),
                ),
                ("uuid", waldur_core.core.fields.UUIDField()),
                (
                    "inet",
                    netfields.fields.CidrAddressField(
                        blank=True,
                        max_length=43,
                        null=True,
                        validators=[waldur_core.structure.models.validate_cidr_32],
                    ),
                ),
                (
                    "resource",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="access_subnet_set",
                        to="marketplace.resource",
                    ),
                ),
            ],
            options={
                "ordering": ["inet"],
                "unique_together": {("resource", "inet")},
            },
            bases=(models.Model, waldur_core.logging.mixins.LoggableMixin),
        ),
    ]
