# Generated by Django 6.0.7 on 2026-07-25 18:34

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.conf import settings
from django.db import migrations, models

import waldur_core.core.fields


class Migration(migrations.Migration):
    dependencies = [
        ("marketplace", "0252_offeringaccesssubnet"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ResourceMemberSyncStatus",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("uuid", waldur_core.core.fields.UUIDField()),
                (
                    "scope_type",
                    models.CharField(
                        choices=[
                            ("resource", "Resource"),
                            ("resource_project", "Resource project"),
                        ],
                        max_length=32,
                    ),
                ),
                ("role_name", models.CharField(max_length=150)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("synced", "Synced"),
                            ("pending", "Pending"),
                            ("missing_in_idp", "Missing in identity provider"),
                            ("error", "Error"),
                        ],
                        max_length=32,
                    ),
                ),
                ("message", models.TextField(blank=True, default="")),
                (
                    "resource",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="member_sync_statuses",
                        to="marketplace.resource",
                    ),
                ),
                (
                    "resource_project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="member_sync_statuses",
                        to="marketplace.resourceproject",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Resource member sync status",
                "verbose_name_plural": "Resource member sync statuses",
                "indexes": [
                    models.Index(
                        fields=["resource", "user"],
                        name="marketplace_resourc_ca8616_idx",
                    )
                ],
            },
        ),
        migrations.AddField(
            model_name="resourceproject",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_resource_projects",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
