# Generated by Django 6.0.7 on 2026-07-25 07:37

import django.db.models.deletion
import django.utils.timezone
import django_fsm
import model_utils.fields
from django.db import migrations, models

import waldur_core.core.fields


class Migration(migrations.Migration):
    dependencies = [
        ("marketplace", "0252_offeringaccesssubnet"),
    ]

    operations = [
        migrations.CreateModel(
            name="ResourceApiKey",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("uuid", waldur_core.core.fields.UUIDField()),
                ("error_message", models.TextField(blank=True)),
                ("error_traceback", models.TextField(blank=True)),
                (
                    "client_id",
                    models.CharField(blank=True, db_index=True, max_length=255),
                ),
                ("key_ciphertext", models.TextField(blank=True)),
                ("fingerprint", models.CharField(blank=True, max_length=64)),
                (
                    "state",
                    django_fsm.FSMField(
                        choices=[
                            ("Creating", "Creating"),
                            ("OK", "OK"),
                            ("Updating", "Updating"),
                            ("Terminating", "Terminating"),
                            ("Erred", "Erred"),
                        ],
                        default="Creating",
                        max_length=50,
                    ),
                ),
                (
                    "resource",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="api_keys",
                        to="marketplace.resource",
                    ),
                ),
            ],
            options={
                "verbose_name": "Resource API key",
                "unique_together": {("resource", "client_id")},
            },
        ),
    ]
