# Generated by Django 6.0.7 on 2026-08-12 06:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("marketplace", "0261_resourceenddatechangerequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="description_km",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="category",
            name="title_km",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="categorygroup",
            name="description_km",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="categorygroup",
            name="title_km",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
