# Generated by Django 6.0.7 on 2026-08-13 08:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("marketplace", "0262_category_description_km_category_title_km_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="default_tenant_category",
        ),
    ]
