# Generated by Django 6.0.7 on 2026-08-04 10:56

from django.db import migrations

import waldur_mastermind.marketplace.secret_options


class Migration(migrations.Migration):
    dependencies = [
        ("marketplace", "0263_remove_category_default_tenant_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="offering",
            name="secret_options",
            field=waldur_mastermind.marketplace.secret_options.SecretOptionsField(
                blank=True,
                default=dict,
                help_text="Private data used by specific plugin, such as credentials and hooks.",
            ),
        ),
    ]
