# Generated by Django 6.0.8 on 2026-09-03 15:35

from importlib import import_module

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import waldur_core.core.migration_operations
import waldur_mastermind.marketplace.secret_options


def _original(name):
    """A replaced migration's module: its data code runs from there, unchanged."""
    return import_module(__name__.rpartition(".")[0] + "." + name)


class Migration(migrations.Migration):
    replaces = [
        ("marketplace", "0264_nullify_slurm_resource_scopes"),
        ("marketplace", "0265_drop_slurm_tables"),
        ("marketplace", "0266_archive_slurm_offerings"),
        ("marketplace", "0267_terminate_slurm_resources"),
        ("marketplace", "0268_alter_offering_secret_options"),
        ("marketplace", "0269_encrypt_existing_secret_options"),
        ("marketplace", "0270_scrub_secret_options_from_reversion"),
        ("marketplace", "0271_missing_usage_policy"),
        ("marketplace", "0272_alter_customerserviceaccount_options_and_more"),
        ("marketplace", "0273_alter_componentusagemonthly_options_and_more"),
        (
            "marketplace",
            "0274_alter_category_options_alter_categorycolumn_options_and_more",
        ),
        ("marketplace", "0275_alter_accesssubnetofferingscope_options"),
        ("marketplace", "0276_posix_identity_principals"),
        ("marketplace", "0277_order_mp_order_attachment_idx_and_more"),
        ("marketplace", "0278_one_time_plan_component_amount"),
        ("marketplace", "0279_croatian_translation_fields"),
    ]

    dependencies = [
        ("analytics", "0001_squashed_0003"),
        ("billing", "0002_drop_limit_and_threshold"),
        ("contenttypes", "0002_remove_content_type_name"),
        ("core", "__first__"),
        ("logging", "0024_alter_webhook_destination_url"),
        ("marketplace", "0263_remove_category_default_tenant_category"),
        ("permissions", "0021_alter_role_name_roleavailability"),
        ("quotas", "0005_drop_zero_usage"),
        ("reversion", "0002_add_index_on_version_for_content_type_and_db"),
        ("structure", "0085_remove_project_display_credit_reports"),
        ("support", "0021_allow_nullable_request_type_backend_id"),
    ]

    operations = [
        migrations.RunPython(
            code=_original("0264_nullify_slurm_resource_scopes").nullify_slurm_scopes,
            reverse_code=migrations.RunPython.noop,
        ),
        waldur_core.core.migration_operations.FlushDeferredSql(),
        migrations.RunSQL(
            sql="\nDROP TABLE IF EXISTS waldur_slurm_allocationuserusage CASCADE;\nDROP TABLE IF EXISTS waldur_slurm_association CASCADE;\nDROP TABLE IF EXISTS waldur_slurm_allocation CASCADE;\n",
            reverse_sql="",
        ),
        waldur_core.core.migration_operations.FlushDeferredSql(),
        migrations.RunPython(
            code=_original("0265_drop_slurm_tables").drop_slurm_content_types,
            reverse_code=migrations.RunPython.noop,
        ),
        waldur_core.core.migration_operations.FlushDeferredSql(),
        migrations.RunPython(
            code=_original("0266_archive_slurm_offerings").archive_slurm_offerings,
            reverse_code=migrations.RunPython.noop,
        ),
        waldur_core.core.migration_operations.FlushDeferredSql(),
        migrations.RunPython(
            code=_original("0267_terminate_slurm_resources").terminate_slurm_resources,
            reverse_code=migrations.RunPython.noop,
        ),
        waldur_core.core.migration_operations.FlushDeferredSql(),
        migrations.AlterField(
            model_name="offering",
            name="secret_options",
            field=waldur_mastermind.marketplace.secret_options.SecretOptionsField(
                blank=True,
                default=dict,
                help_text="Private data used by specific plugin, such as credentials and hooks.",
            ),
        ),
        waldur_core.core.migration_operations.FlushDeferredSql(),
        migrations.RunPython(
            code=_original(
                "0269_encrypt_existing_secret_options"
            ).encrypt_existing_secret_options,
            reverse_code=migrations.RunPython.noop,
        ),
        waldur_core.core.migration_operations.FlushDeferredSql(),
        migrations.RunPython(
            code=_original(
                "0270_scrub_secret_options_from_reversion"
            ).scrub_secret_options,
            reverse_code=migrations.RunPython.noop,
        ),
        waldur_core.core.migration_operations.FlushDeferredSql(),
        migrations.AddField(
            model_name="componentusage",
            name="missing_usage_policy",
            field=models.CharField(
                choices=[
                    ("none", "Leave the period unreported."),
                    ("reuse", "Reuse the reported value every month until changed."),
                    ("zero", "Record zero when no usage is reported."),
                ],
                default="none",
                help_text="What to record when no usage is reported for the following billing period.",
                max_length=10,
            ),
        ),
        waldur_core.core.migration_operations.FlushDeferredSql(),
        migrations.RunPython(
            code=_original("0271_missing_usage_policy").set_policy_from_recurring,
            reverse_code=_original(
                "0271_missing_usage_policy"
            ).set_recurring_from_policy,
        ),
        waldur_core.core.migration_operations.FlushDeferredSql(),
        migrations.AlterModelOptions(
            name="accesssubnetofferingscope",
            options={"ordering": ["offering__name", "id"]},
        ),
        migrations.AlterModelOptions(
            name="category",
            options={
                "ordering": ["title", "id"],
                "verbose_name": "Category",
                "verbose_name_plural": "Categories",
            },
        ),
        migrations.AlterModelOptions(
            name="categorycolumn",
            options={"ordering": ["category", "index", "id"]},
        ),
        migrations.AlterModelOptions(
            name="categorygroup",
            options={
                "ordering": ["title", "id"],
                "verbose_name": "Category group",
                "verbose_name_plural": "Category groups",
            },
        ),
        migrations.AlterModelOptions(
            name="componentusagemonthly",
            options={"ordering": ["-billing_period", "id"]},
        ),
        migrations.AlterModelOptions(
            name="courseaccount",
            options={"ordering": ["created", "id"], "verbose_name": "Course account"},
        ),
        migrations.AlterModelOptions(
            name="customerserviceaccount",
            options={
                "ordering": ["created", "id"],
                "verbose_name": "Customer service account",
            },
        ),
        migrations.AlterModelOptions(
            name="integrationstatus",
            options={"ordering": ["id"]},
        ),
        migrations.AlterModelOptions(
            name="maintenanceannouncement",
            options={
                "ordering": ["-scheduled_start", "id"],
                "verbose_name": "Maintenance announcement",
                "verbose_name_plural": "Maintenance announcements",
            },
        ),
        migrations.AlterModelOptions(
            name="maintenanceannouncementtemplate",
            options={
                "ordering": ["-created", "id"],
                "verbose_name": "Maintenance announcement",
                "verbose_name_plural": "Maintenance announcements",
            },
        ),
        migrations.AlterModelOptions(
            name="offering",
            options={"ordering": ["name", "id"], "verbose_name": "Offering"},
        ),
        migrations.AlterModelOptions(
            name="offeringaccesssubnet",
            options={"ordering": ["inet", "id"]},
        ),
        migrations.AlterModelOptions(
            name="offeringcomponent",
            options={"ordering": ["name", "id"]},
        ),
        migrations.AlterModelOptions(
            name="offeringgroup",
            options={
                "ordering": ["title", "id"],
                "verbose_name": "Offering group",
                "verbose_name_plural": "Offering groups",
            },
        ),
        migrations.AlterModelOptions(
            name="offeringprofile",
            options={"ordering": ["name", "id"]},
        ),
        migrations.AlterModelOptions(
            name="offeringtermsofservice",
            options={"ordering": ["-created", "id"]},
        ),
        migrations.AlterModelOptions(
            name="offeringuser",
            options={"ordering": ["username", "id"]},
        ),
        migrations.AlterModelOptions(
            name="order",
            options={"ordering": ["created", "id"], "verbose_name": "Order"},
        ),
        migrations.AlterModelOptions(
            name="plan",
            options={"ordering": ["name", "id"]},
        ),
        migrations.AlterModelOptions(
            name="plancomponent",
            options={"ordering": ["component__name", "id"]},
        ),
        migrations.AlterModelOptions(
            name="posixidentity",
            options={
                "ordering": ["pool", "uid", "gid", "id"],
                "verbose_name": "POSIX identity",
                "verbose_name_plural": "POSIX identities",
            },
        ),
        migrations.AlterModelOptions(
            name="projectserviceaccount",
            options={
                "ordering": ["created", "id"],
                "verbose_name": "Project service account",
            },
        ),
        migrations.AlterModelOptions(
            name="resource",
            options={"ordering": ["created", "id"]},
        ),
        migrations.AlterModelOptions(
            name="resourceenddatechangerequest",
            options={
                "ordering": ["created", "id"],
                "verbose_name": "Resource end date change request",
                "verbose_name_plural": "Resource end date change requests",
            },
        ),
        migrations.AlterModelOptions(
            name="resourcelimitchangerequest",
            options={
                "ordering": ["created", "id"],
                "verbose_name": "Resource limit change request",
                "verbose_name_plural": "Resource limit change requests",
            },
        ),
        migrations.AlterModelOptions(
            name="resourceproject",
            options={"base_manager_name": "objects", "ordering": ["created", "id"]},
        ),
        migrations.AlterModelOptions(
            name="robotaccount",
            options={"ordering": ["created", "id"]},
        ),
        migrations.AlterModelOptions(
            name="softwarecatalog",
            options={"ordering": ["name", "catalog_type", "version", "id"]},
        ),
        migrations.AlterModelOptions(
            name="softwarepackage",
            options={"ordering": ["name", "id"]},
        ),
        migrations.AlterModelOptions(
            name="softwaretarget",
            options={"ordering": ["-created", "id"]},
        ),
        migrations.AlterModelOptions(
            name="softwareversion",
            options={"ordering": ["package", "version", "module_version", "id"]},
        ),
        migrations.AlterModelOptions(
            name="userofferingconsent",
            options={
                "ordering": ["-created", "id"],
                "verbose_name": "User offering consent",
            },
        ),
        migrations.RemoveConstraint(
            model_name="posixidentity",
            name="marketplace_posixidentity_active_consumer",
        ),
        migrations.RemoveField(
            model_name="componentusage",
            name="recurring",
        ),
        migrations.AddField(
            model_name="posixidentity",
            name="recyclable",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="posixidentity",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="posix_identities",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="posixidentity",
            name="content_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AlterField(
            model_name="posixidentity",
            name="object_id",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="posixidentity",
            name="offering",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="posix_identities",
                to="marketplace.offering",
            ),
        ),
        waldur_core.core.migration_operations.FlushDeferredSql(),
        migrations.RunPython(
            code=_original(
                "_posix_identity_principals"
            ).backfill_posix_identity_principals,
            reverse_code=migrations.RunPython.noop,
        ),
        waldur_core.core.migration_operations.FlushDeferredSql(),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                condition=models.Q(("attachment__isnull", False)),
                fields=["attachment"],
                name="mp_order_attachment_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                condition=models.Q(("provider_message_attachment__isnull", False)),
                fields=["provider_message_attachment"],
                name="mp_order_provider_att_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                condition=models.Q(("consumer_message_attachment__isnull", False)),
                fields=["consumer_message_attachment"],
                name="mp_order_consumer_att_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="posixidentity",
            index=models.Index(fields=["user"], name="mp_posixidentity_user_idx"),
        ),
        migrations.AddConstraint(
            model_name="posixidentity",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("content_type__isnull", False), ("released_at__isnull", True)
                ),
                fields=("pool", "content_type", "object_id"),
                name="marketplace_posixidentity_active_consumer",
            ),
        ),
        migrations.AddConstraint(
            model_name="posixidentity",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("released_at__isnull", True), ("user__isnull", False)
                ),
                fields=("pool", "user"),
                name="marketplace_posixidentity_active_user",
            ),
        ),
        migrations.AddConstraint(
            model_name="posixidentity",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("content_type__isnull", True),
                        ("object_id__isnull", True),
                        ("user__isnull", False),
                    ),
                    models.Q(
                        ("content_type__isnull", False),
                        ("object_id__isnull", False),
                        ("user__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="marketplace_posixidentity_exactly_one_principal",
            ),
        ),
        waldur_core.core.migration_operations.FlushDeferredSql(),
        migrations.RunPython(
            code=_original("0278_one_time_plan_component_amount").set_default_amount,
            reverse_code=_original(
                "0278_one_time_plan_component_amount"
            ).unset_default_amount,
        ),
        waldur_core.core.migration_operations.FlushDeferredSql(),
        migrations.AddField(
            model_name="category",
            name="description_hr",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="category",
            name="title_hr",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="categorygroup",
            name="description_hr",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="categorygroup",
            name="title_hr",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
