# Generated by Django 6.0.8 on 2026-08-19 21:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("marketplace", "0271_missing_usage_policy"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customerserviceaccount",
            options={
                "ordering": ["created", "id"],
                "verbose_name": "Customer service account",
            },
        ),
        migrations.AlterModelOptions(
            name="projectserviceaccount",
            options={
                "ordering": ["created", "id"],
                "verbose_name": "Project service account",
            },
        ),
    ]
