# Generated by Django 6.0.8 on 2026-08-28 10:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("marketplace", "0279_croatian_translation_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="description_mk",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="category",
            name="description_sq",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="category",
            name="title_mk",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="category",
            name="title_sq",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="categorygroup",
            name="description_mk",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="categorygroup",
            name="description_sq",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="categorygroup",
            name="title_mk",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="categorygroup",
            name="title_sq",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
