# Generated by Django 6.0.8 on 2026-09-08 21:35

import django.db.models.deletion
import django.utils.timezone
import django_fsm
import model_utils.fields
from django.conf import settings
from django.db import migrations, models

import waldur_core.core.fields
import waldur_core.logging.mixins


class Migration(migrations.Migration):
    dependencies = [
        ("marketplace", "0285_offeringcomponent_limit_precision"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="serviceprovider",
            name="account_homedir_prefix",
            field=models.CharField(
                blank=True,
                help_text="Provider-level default home directory prefix. Blank means each offering decides for itself.",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="serviceprovider",
            name="account_login_shell",
            field=models.CharField(
                blank=True,
                help_text="Provider-level default login shell. Blank means each offering decides for itself.",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="serviceprovider",
            name="account_scope",
            field=models.CharField(
                choices=[
                    ("offering", "Per offering"),
                    ("provider", "Per service provider"),
                ],
                default="offering",
                help_text="Default for this provider's offerings: hold user accounts per offering (the historical behaviour) or once per provider. Choose 'provider' when one directory fronts several offerings. Any single offering can override this with an 'account_scope' plugin option, so a provider can run both -- for example a cluster with its own separate directory alongside offerings that share the main one.",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="serviceprovider",
            name="account_username_generation_policy",
            field=models.CharField(
                blank=True,
                help_text="Provider-level default for the offering plugin option of the same name. Blank means each offering decides for itself.",
                max_length=50,
            ),
        ),
        migrations.CreateModel(
            name="ServiceProviderAccount",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("uuid", waldur_core.core.fields.UUIDField()),
                ("backend_metadata", models.JSONField(blank=True, default=dict)),
                ("username", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "is_restricted",
                    models.BooleanField(
                        default=False,
                        help_text="Signal to service if the user account is restricted or not",
                    ),
                ),
                (
                    "state",
                    django_fsm.FSMIntegerField(
                        choices=[
                            (1, "Requested"),
                            (2, "Creating"),
                            (3, "Pending account linking"),
                            (4, "Pending additional validation"),
                            (5, "OK"),
                            (6, "Requested deletion"),
                            (7, "Deleting"),
                            (8, "Deleted"),
                            (9, "Error creating"),
                            (10, "Error deleting"),
                        ],
                        default=1,
                    ),
                ),
                (
                    "runtime_state",
                    models.CharField(
                        choices=[
                            ("Active", "Active"),
                            ("Pending account linking", "Pending account linking"),
                            (
                                "Pending additional validation",
                                "Pending additional validation",
                            ),
                        ],
                        default="Active",
                        help_text="Operational/access state of the user account. Separate from lifecycle state; can be set by the service provider at any time.",
                        max_length=50,
                    ),
                ),
                (
                    "service_provider_comment",
                    models.TextField(
                        blank=True,
                        help_text="Additional comment for pending states like validation or account linking",
                    ),
                ),
                (
                    "service_provider_comment_url",
                    models.URLField(
                        blank=True,
                        help_text="URL link for additional information or actions related to service provider comment",
                    ),
                ),
                (
                    "service_provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="provider_accounts",
                        to="marketplace.serviceprovider",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Service provider account",
                "ordering": ["username", "id"],
                "abstract": False,
            },
            bases=(models.Model, waldur_core.logging.mixins.LoggableMixin),
        ),
        migrations.AddField(
            model_name="offeringuser",
            name="service_provider_account",
            field=models.ForeignKey(
                blank=True,
                help_text="Provider-level account backing this one. When set, the username and POSIX attributes are owned there and must not be written here.",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="offering_users",
                to="marketplace.serviceprovideraccount",
            ),
        ),
        migrations.AddIndex(
            model_name="serviceprovideraccount",
            index=models.Index(
                fields=["service_provider", "user"],
                name="mp_spaccount_provider_user_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="serviceprovideraccount",
            unique_together={("service_provider", "user")},
        ),
    ]
