# Generated by Django 6.0.8 on 2026-09-15 14:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("marketplace", "0291_enable_limit_change_requests_where_used"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="old_cost",
            field=models.DecimalField(
                blank=True, decimal_places=10, max_digits=22, null=True
            ),
        ),
    ]
