# Generated by Django 6.0.8 on 2026-09-28 14:15

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models

import waldur_core.core.fields
import waldur_core.logging.mixins


class Migration(migrations.Migration):
    dependencies = [
        ("marketplace", "0298_order_placed_automatically_help_text"),
    ]

    operations = [
        migrations.CreateModel(
            name="OfferingKpi",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=4096, verbose_name="description"
                    ),
                ),
                ("uuid", waldur_core.core.fields.UUIDField()),
                (
                    "name",
                    models.CharField(
                        help_text="Display name for the measured unit, for example, Floating IP.",
                        max_length=150,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        help_text="Unique internal name of the measured unit, for example floating_ip.",
                        max_length=50,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[a-zA-Z0-9_\\-\\/:]+$",
                                message="Internal name must contain only alphanumeric characters, underscores, hyphens, and slashes.",
                            )
                        ],
                    ),
                ),
                (
                    "measured_unit",
                    models.CharField(
                        blank=True,
                        help_text="Unit of measurement, for example, GB.",
                        max_length=30,
                    ),
                ),
                (
                    "aggregation",
                    models.CharField(
                        choices=[
                            ("sum", "Sum"),
                            ("avg", "Average"),
                            ("last", "Last value"),
                            ("min", "Minimum"),
                            ("max", "Maximum"),
                        ],
                        default="sum",
                        help_text="How datapoints roll up into one project-level figure.",
                        max_length=10,
                    ),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[
                            ("up", "Higher is better"),
                            ("down", "Lower is better"),
                            ("neutral", "Neutral"),
                        ],
                        default="neutral",
                        help_text="Which way this KPI has to move to count as an improvement.",
                        max_length=10,
                    ),
                ),
                (
                    "target",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Optional value the project is aiming for.",
                        max_digits=20,
                        null=True,
                    ),
                ),
                (
                    "cadence",
                    models.CharField(
                        choices=[
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                            ("quarterly", "Quarterly"),
                        ],
                        default="monthly",
                        help_text="How often the service is expected to report this KPI.",
                        max_length=10,
                    ),
                ),
                (
                    "attribute",
                    models.CharField(
                        blank=True,
                        help_text="Datapoint attribute this KPI is broken down by, for example course. Empty when the KPI has no breakdown.",
                        max_length=50,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[a-zA-Z0-9_\\-\\/:]+$",
                                message="Internal name must contain only alphanumeric characters, underscores, hyphens, and slashes.",
                            )
                        ],
                    ),
                ),
                (
                    "offering",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kpis",
                        to="marketplace.offering",
                    ),
                ),
            ],
            options={
                "ordering": ["name", "id"],
                "unique_together": {("type", "offering")},
            },
            bases=(waldur_core.logging.mixins.LoggableMixin, models.Model),
        ),
        migrations.CreateModel(
            name="ResourceKpiValue",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("uuid", waldur_core.core.fields.UUIDField()),
                ("value", models.DecimalField(decimal_places=2, max_digits=20)),
                (
                    "timestamp",
                    models.DateTimeField(help_text="When the measurement was taken."),
                ),
                (
                    "attributes",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="OpenTelemetry-style attributes qualifying this datapoint, for example the course or the support queue.",
                    ),
                ),
                (
                    "kpi",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="values",
                        to="marketplace.offeringkpi",
                    ),
                ),
                (
                    "resource",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kpi_values",
                        to="marketplace.resource",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp", "id"],
                "indexes": [
                    models.Index(
                        fields=["resource", "kpi", "timestamp"],
                        name="marketplace_resourc_99b82d_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("resource", "kpi", "timestamp", "attributes"),
                        name="unique_resource_kpi_datapoint",
                    )
                ],
            },
            bases=(models.Model, waldur_core.logging.mixins.LoggableMixin),
        ),
    ]
