# Generated by Django 6.0.8 on 2026-10-01 22:04

import django.db.models.deletion
import django.db.models.expressions
import django.db.models.functions.text
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models

import waldur_core.core.fields


class Migration(migrations.Migration):
    dependencies = [
        ("marketplace", "0299_offeringkpi_resourcekpivalue"),
        ("structure", "0041_squashed_0085"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceProviderProjectGroup",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("uuid", waldur_core.core.fields.UUIDField()),
                ("name", models.CharField(max_length=32)),
                ("gid", models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Service provider project group",
                "ordering": ["name", "id"],
            },
        ),
        migrations.AddField(
            model_name="posixidpool",
            name="max_group_gid",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="posixidpool",
            name="min_group_gid",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="posixidpool",
            name="next_group_gid",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="serviceprovider",
            name="account_options",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Account settings for this provider's offerings: account_scope, username_generation_policy, username_anonymized_prefix, homedir_prefix and login_shell. Each applies to every offering that does not set the plugin option of the same name. project_groups_enabled is the provider's own: it gives every project using the provider's services one POSIX group.",
            ),
        ),
        migrations.AddConstraint(
            model_name="posixidpool",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("max_group_gid__isnull", True),
                        ("min_group_gid__isnull", True),
                        ("next_group_gid__isnull", True),
                    ),
                    models.Q(
                        ("max_group_gid__isnull", False),
                        ("min_group_gid__isnull", False),
                        ("next_group_gid__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="marketplace_posixidpool_group_gid_all_or_nothing",
            ),
        ),
        migrations.AddConstraint(
            model_name="posixidpool",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("min_group_gid__gte", 1000),
                    ("min_group_gid__lte", models.F("max_group_gid")),
                    ("max_group_gid__lte", 4294967294),
                    ("next_group_gid__gte", models.F("min_group_gid")),
                    (
                        "next_group_gid__lte",
                        django.db.models.expressions.CombinedExpression(
                            models.F("max_group_gid"), "+", models.Value(1)
                        ),
                    ),
                ),
                name="marketplace_posixidpool_group_gid_bounds",
            ),
        ),
        migrations.AddField(
            model_name="serviceproviderprojectgroup",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="provider_project_groups",
                to="structure.project",
            ),
        ),
        migrations.AddField(
            model_name="serviceproviderprojectgroup",
            name="service_provider",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="project_groups",
                to="marketplace.serviceprovider",
            ),
        ),
        migrations.AddConstraint(
            model_name="serviceproviderprojectgroup",
            constraint=models.UniqueConstraint(
                models.F("service_provider"),
                django.db.models.functions.text.Lower("name"),
                name="marketplace_spprojectgroup_unique_name",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="serviceproviderprojectgroup",
            unique_together={("service_provider", "project")},
        ),
    ]
