# Generated by Django 6.0.8 on 2026-10-06 13:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("marketplace", "0303_delete_kpi_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="resource",
            name="paused_by_grace_period",
            field=models.BooleanField(
                default=False,
                help_text="Waldur paused the resource because its project entered the grace period after its end date. Lets the pause be lifted when the end date is extended, without lifting a pause set for another reason.",
            ),
        ),
    ]
