# Generated by Django 6.0.8 on 2026-10-08 20:44

from django.db import migrations

import waldur_core.core.fields


class Migration(migrations.Migration):
    dependencies = [
        ("marketplace", "0304_resource_paused_by_grace_period"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resourceapikey",
            name="key_ciphertext",
            field=waldur_core.core.fields.CiphertextField(blank=True),
        ),
    ]
