#!/usr/bin/env sh
set -e

echo "[+] Install dependencies in case of absence"
poetry install -vvv

echo "[+] Setup test settings"
cat > src/waldur_mastermind/test_settings.py <<-EOF
from waldur_core.server.test_settings import *
from django.db.backends.base.schema import BaseDatabaseSchemaEditor

# Data written to unlogged tables is not written to the write-ahead log,
# which makes them considerably faster than ordinary tables.
BaseDatabaseSchemaEditor.sql_create_table = "CREATE UNLOGGED TABLE %(table)s (%(definition)s)"

DATABASES = {
'default': {
  'ENGINE': 'django.db.backends.postgresql',
  'NAME': 'test_waldur',
  'USER': 'runner',
  'HOST': 'postgres',
  'PORT': 5432,
  'PASSWORD': 'waldur',
  }
}
EOF

echo "[+] Running unit tests"
pytest \
    --test-group-count $CI_NODE_TOTAL \
    --test-group=$CI_NODE_INDEX \
    --test-group-random-seed=12345 \
    --reuse-db \
    --junitxml=report.xml \
    --cov=src/ \
    --ds=waldur_mastermind.test_settings \
    src
