API_GROUPS = {
    'auth': ['/api-auth/', '/api/auth-valimo/',],
    'users': ['/api/users/', '/api/user-invitations/', '/api/user-counters/',],
    'customers': [
        '/api/customers/',
        '/api/customer-permissions-log/',
        '/api/customer-permissions-reviews/',
        '/api/customer-permissions/',
    ],
    'marketplace': [
        '/api/marketplace-bookings/',
        '/api/marketplace-cart-items/',
        '/api/marketplace-categories/',
        '/api/marketplace-category-component-usages/',
        '/api/marketplace-checklists-categories/',
        '/api/marketplace-checklists/',
        '/api/marketplace-component-usages/',
        '/api/marketplace-offering-files/',
        '/api/marketplace-offerings/',
        '/api/marketplace-order-items/',
        '/api/marketplace-orders/',
        '/api/marketplace-plans/',
        '/api/marketplace-plugins/',
        '/api/marketplace-public-api/',
        '/api/marketplace-resource-offerings/',
        '/api/marketplace-resources/',
        '/api/marketplace-screenshots/',
        '/api/marketplace-service-providers/',
    ],
    'reporting': [
        '/api/support-feedback-average-report/',
        '/api/support-feedback-report/',
    ],
}
