# Generated by Django 3.2.20 on 2023-10-06 13:01

import django.db.models.deletion
import django.utils.timezone
import django_fsm
import model_utils.fields
from django.db import migrations, models

import waldur_core.core.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("marketplace", "0098_robotaccount_responsible_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="LexisLink",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("uuid", waldur_core.core.fields.UUIDField()),
                ("error_message", models.TextField(blank=True)),
                ("error_traceback", models.TextField(blank=True)),
                (
                    "state",
                    django_fsm.FSMIntegerField(
                        choices=[
                            (1, "pending"),
                            (2, "executing"),
                            (3, "OK"),
                            (4, "erred"),
                        ],
                        default=1,
                    ),
                ),
                (
                    "heappe_project_id",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "robot_account",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lexis_link",
                        to="marketplace.robotaccount",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lexis Link",
                "ordering": ("created",),
            },
        ),
    ]
