# Generated by Django 6.0.8 on 2026-08-20 13:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("waldur_pid", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="datacitereferral",
            options={"ordering": ["relation_type", "published", "id"]},
        ),
    ]
