# Generated by Django 4.2.23 on 2025-08-29 12:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("checklist", "0003_add_min_max_values_to_question"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="dependency_logic_operator",
            field=models.CharField(
                choices=[
                    ("and", "All conditions must be true (AND)"),
                    ("or", "At least one condition must be true (OR)"),
                ],
                default="and",
                help_text="Defines how multiple dependencies are evaluated. AND: All dependencies must be satisfied. OR: At least one dependency must be satisfied.",
                max_length=10,
            ),
        ),
    ]
