# Generated by Django 4.2.24 on 2025-11-10 15:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("checklist", "0007_alter_checklist_checklist_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="allowed_file_types",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of allowed file extensions (e.g., ['.pdf', '.doc', '.docx']). If empty, all file types are allowed.",
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="allowed_mime_types",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of allowed MIME types (e.g., ['application/pdf', 'application/msword']). If empty, MIME type validation is not enforced. When both extensions and MIME types are specified, files must match both criteria for security.",
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="max_file_size_mb",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Maximum file size in megabytes. If not set, no size limit is enforced.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="max_files_count",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Maximum number of files allowed for MULTIPLE_FILES type questions. If not set, no count limit is enforced.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="question_type",
            field=models.CharField(
                choices=[
                    ("boolean", "Yes/No/N/A"),
                    ("single_select", "Single selection"),
                    ("multi_select", "Multiple selection"),
                    ("text_input", "Text input"),
                    ("text_area", "Text area"),
                    ("number", "Number input"),
                    ("date", "Date input"),
                    ("file", "File input"),
                    ("multiple_files", "Multiple files input"),
                ],
                default="boolean",
                help_text="Type of question and expected answer format",
                max_length=20,
            ),
        ),
    ]
