# Generated by Django 4.2.23 on 2025-08-04 13:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("checklist", "0008_remove_checklist_description_ar_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="question",
            name="category",
        ),
        migrations.RemoveField(
            model_name="question",
            name="solution",
        ),
    ]
