# Generated by Django 4.2.24 on 2026-01-02 08:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("checklist", "0008_question_allowed_file_types_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="max_value",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                help_text="Maximum value allowed for NUMBER, YEAR, and RATING type questions",
                max_digits=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="min_value",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                help_text="Minimum value allowed for NUMBER, YEAR, and RATING type questions",
                max_digits=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="question_type",
            field=models.CharField(
                choices=[
                    ("boolean", "Yes/No/N/A"),
                    ("single_select", "Single selection"),
                    ("multi_select", "Multiple selection"),
                    ("text_input", "Text input"),
                    ("text_area", "Text area"),
                    ("number", "Number input"),
                    ("date", "Date input"),
                    ("file", "File input"),
                    ("multiple_files", "Multiple files input"),
                    ("phone_number", "Phone number"),
                    ("year", "Year"),
                    ("email", "Email address"),
                    ("url", "URL"),
                    ("country", "Country"),
                    ("rating", "Rating"),
                    ("datetime", "Date and time"),
                ],
                default="boolean",
                help_text="Type of question and expected answer format",
                max_length=20,
            ),
        ),
    ]
