# Generated by Django 4.2.23
from django.db import migrations


def rename_tables_if_exist(apps, schema_editor):
    """Rename tables from marketplace_checklist_* to checklist_* if they exist."""
    with schema_editor.connection.cursor() as cursor:
        # Check if the old tables exist and rename them
        tables_to_rename = [
            ("marketplace_checklist_category", "checklist_category"),
            ("marketplace_checklist_checklist", "checklist_checklist"),
            (
                "marketplace_checklist_checklist_customers",
                "checklist_checklist_customers",
            ),
            ("marketplace_checklist_checklist_roles", "checklist_checklist_roles"),
            ("marketplace_checklist_question", "checklist_question"),
            ("marketplace_checklist_questionoption", "checklist_questionoption"),
            (
                "marketplace_checklist_questiondependency",
                "checklist_questiondependency",
            ),
            ("marketplace_checklist_answer", "checklist_answer"),
        ]

        for old_table, new_table in tables_to_rename:
            # Check if old table exists
            cursor.execute(
                "SELECT EXISTS (SELECT FROM information_schema.tables WHERE table_name = %s);",
                [old_table],
            )
            table_exists = cursor.fetchone()[0]

            if table_exists:
                cursor.execute(f"ALTER TABLE {old_table} RENAME TO {new_table};")
                print(f"Renamed table {old_table} to {new_table}")
            else:
                print(f"Table {old_table} does not exist, skipping rename")

        # Update Django's content type table to reflect the new app name
        cursor.execute(
            "UPDATE django_content_type SET app_label = 'checklist' WHERE app_label = 'marketplace_checklist';"
        )

        # Update Django's migration recorder table
        cursor.execute(
            "UPDATE django_migrations SET app = 'checklist' WHERE app = 'marketplace_checklist';"
        )


def reverse_rename_tables(apps, schema_editor):
    """Reverse the table renaming."""
    with schema_editor.connection.cursor() as cursor:
        # Rename tables back
        tables_to_rename = [
            ("checklist_category", "marketplace_checklist_category"),
            ("checklist_checklist", "marketplace_checklist_checklist"),
            (
                "checklist_checklist_customers",
                "marketplace_checklist_checklist_customers",
            ),
            ("checklist_checklist_roles", "marketplace_checklist_checklist_roles"),
            ("checklist_question", "marketplace_checklist_question"),
            ("checklist_questionoption", "marketplace_checklist_questionoption"),
            (
                "checklist_questiondependency",
                "marketplace_checklist_questiondependency",
            ),
            ("checklist_answer", "marketplace_checklist_answer"),
        ]

        for old_table, new_table in tables_to_rename:
            cursor.execute(f"ALTER TABLE {old_table} RENAME TO {new_table};")

        # Revert Django's content type table
        cursor.execute(
            "UPDATE django_content_type SET app_label = 'marketplace_checklist' WHERE app_label = 'checklist';"
        )

        # Revert Django's migration recorder table
        cursor.execute(
            "UPDATE django_migrations SET app = 'marketplace_checklist' WHERE app = 'checklist';"
        )


class Migration(migrations.Migration):
    dependencies = [
        ("checklist", "0009_remove_question_category_remove_question_solution"),
    ]

    operations = [
        migrations.RunPython(
            rename_tables_if_exist,
            reverse_rename_tables,
        ),
    ]
