# Generated by Django 4.2.24 on 2026-01-12 10:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("checklist", "0009_add_question_types"),
    ]

    operations = [
        migrations.AlterField(
            model_name="checklist",
            name="checklist_type",
            field=models.CharField(
                choices=[
                    ("project_compliance", "Project compliance"),
                    ("proposal_compliance", "Proposal compliance"),
                    ("offering_compliance", "Offering compliance"),
                    ("project_metadata", "Project metadata"),
                    ("onboarding_customer", "Onboarding customer data"),
                    ("onboarding_intent", "Onboarding intent/purpose data"),
                ],
                default="project_compliance",
                help_text="Type of compliance this checklist addresses",
                max_length=20,
            ),
        ),
    ]
