# Generated by Django 4.2.24 on 2026-01-19 06:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("checklist", "0010_alter_checklist_checklist_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="checklist",
            name="category",
        ),
        migrations.DeleteModel(
            name="Category",
        ),
    ]
