# Generated by Django 6.0.4 on 2026-04-11 14:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("checklist", "0011_remove_checklist_category_delete_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="checklist",
            name="checklist_type",
            field=models.CharField(
                choices=[
                    ("project_compliance", "Project compliance"),
                    ("proposal_compliance", "Proposal compliance"),
                    ("offering_compliance", "Offering compliance"),
                    ("project_metadata", "Project metadata"),
                    ("onboarding_customer", "Onboarding customer data"),
                    ("onboarding_intent", "Onboarding intent/purpose data"),
                    ("workflow_step", "Workflow step evaluation"),
                ],
                default="project_compliance",
                help_text="Type of compliance this checklist addresses",
                max_length=20,
            ),
        ),
    ]
