# Generated by Django 6.0.5 on 2026-05-16 14:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("checklist", "0012_alter_checklist_checklist_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="likert_allow_na",
            field=models.BooleanField(
                default=False,
                help_text="Allow respondents to choose 'N/A' as an answer for LIKERT type questions.",
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="likert_high_label",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Label for the highest point on the Likert scale (e.g. 'Strongly agree'). Optional.",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="likert_low_label",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Label for the lowest point on the Likert scale (e.g. 'Strongly disagree'). Optional.",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="likert_scale_length",
            field=models.PositiveSmallIntegerField(
                blank=True,
                choices=[(3, "3 point"), (5, "5 point"), (7, "7 point")],
                help_text="Number of points on the Likert scale (3, 5, or 7). Required for LIKERT type questions.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="rich_text_char_limit",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Maximum number of characters allowed in RICH_TEXT type answers. If not set, no limit is enforced.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="rich_text_toolbar_level",
            field=models.CharField(
                blank=True,
                choices=[
                    ("minimal", "Minimal"),
                    ("standard", "Standard"),
                    ("extended", "Extended"),
                ],
                default="standard",
                help_text="Toolbar level for the rich text editor: 'minimal', 'standard', or 'extended'.",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="question_type",
            field=models.CharField(
                choices=[
                    ("boolean", "Yes/No/N/A"),
                    ("single_select", "Single selection"),
                    ("multi_select", "Multiple selection"),
                    ("text_input", "Text input"),
                    ("text_area", "Text area"),
                    ("number", "Number input"),
                    ("date", "Date input"),
                    ("file", "File input"),
                    ("multiple_files", "Multiple files input"),
                    ("phone_number", "Phone number"),
                    ("year", "Year"),
                    ("email", "Email address"),
                    ("url", "URL"),
                    ("country", "Country"),
                    ("rating", "Rating"),
                    ("datetime", "Date and time"),
                    ("likert", "Likert scale"),
                    ("rich_text", "Rich text"),
                ],
                default="boolean",
                help_text="Type of question and expected answer format",
                max_length=20,
            ),
        ),
    ]
