# Generated by Django 6.0.8 on 2026-08-20 13:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("checklist", "0013_add_likert_rich_text_question_types"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="checklist",
            options={"ordering": ["checklist_type", "name", "id"]},
        ),
        migrations.AlterModelOptions(
            name="checklistcompletion",
            options={
                "ordering": ["-modified", "id"],
                "verbose_name": "Checklist completion",
                "verbose_name_plural": "Checklist completions",
            },
        ),
        migrations.AlterModelOptions(
            name="question",
            options={"ordering": ["checklist", "order", "id"]},
        ),
        migrations.AlterModelOptions(
            name="questiondependency",
            options={
                "ordering": ["created", "id"],
                "verbose_name": "Question dependency",
                "verbose_name_plural": "Question dependencies",
            },
        ),
        migrations.AlterModelOptions(
            name="questionoption",
            options={"ordering": ["order", "id"]},
        ),
    ]
