# Generated by Django 6.0.8 on 2026-08-26 15:38

import django.contrib.postgres.indexes
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("checklist", "0014_alter_checklist_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="answer",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["answer_data"], name="checklist_answer_data_gin"
            ),
        ),
    ]
