# Generated by Django 2.2.13 on 2020-12-28 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('waldur_slurm', '0015_allocation_error_traceback'),
    ]

    operations = [
        migrations.RemoveField(model_name='allocation', name='deposit_limit',),
        migrations.RemoveField(model_name='allocation', name='deposit_usage',),
        migrations.RemoveField(model_name='allocationusage', name='deposit_usage',),
        migrations.RemoveField(model_name='allocationuserusage', name='deposit_usage',),
    ]
