# Generated by Django 3.2.13 on 2022-05-30 15:22

import re

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waldur_slurm', '0024_change_default_allocation_limits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='association',
            name='username',
            field=models.CharField(
                max_length=128,
                validators=[
                    django.core.validators.RegexValidator(
                        re.compile('^[a-zA-Z0-9_.][a-zA-Z0-9_.-]*[a-zA-Z0-9_.$-]?$'),
                        'Enter a valid username.',
                        'invalid',
                    )
                ],
            ),
        ),
    ]
