# Generated by Django 3.2.13 on 2022-07-07 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0031_project_image'),
        ('waldur_slurm', '0025_change_validation_for_association_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allocation',
            name='service_settings',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='+',
                to='structure.servicesettings',
            ),
        ),
    ]
