#!/usr/bin/env bash
set -e

echo '[+] Copying source code'
cp -r /mnt /tmp

echo '[+] Installing Python package manager'
pip3 install poetry
poetry config virtualenvs.create false

echo '[+] Installing Python package under test'
cd /tmp/mnt
poetry install
pre-commit run --all

echo '[+] Generating Django configuration for application'
cat > /tmp/mnt/src/waldur_mastermind/test_settings.py << EOF
from waldur_core.server.test_settings import *
from django.db.backends.base.schema import BaseDatabaseSchemaEditor

# Data written to unlogged tables is not written to the write-ahead log,
# which makes them considerably faster than ordinary tables.
BaseDatabaseSchemaEditor.sql_create_table = "CREATE UNLOGGED TABLE %(table)s (%(definition)s)"

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'waldur',
        'USER': 'root',
        'HOST': 'db',
        'PORT': 5432,
        'PASSWORD': 'secret',
    }
}
EOF

if [ -f /mnt/test_report.xml ]; then
    echo '[+] Cleaning up old test report'
    rm /mnt/test_report.xml
fi

if [ -f /mnt/coverage.xml ]; then
    echo '[+] Cleaning up old coverage report'
    rm /mnt/coverage.xml
fi

echo '[+] Running unit tests'
pytest \
    --numprocesses=${NUM_PROCESSES} \
    --reuse-db \
    --ds=waldur_mastermind.test_settings \
    --junitxml=/mnt/test_report.xml \
    --cov=src \
    --cov-report xml:/mnt/coverage.xml \
    src

if [ -f /mnt/test_report.xml ]; then
    echo '[+] Updating permissions for test report'
    chown -R user:user /mnt/test_report.xml
fi

if [ -f /mnt/coverage.xml ]; then
    echo '[+] Updating permissions and file path for coverage report'
    chown -R user:user /mnt/coverage.xml
    sed \
        --in-place \
        --expression='s/<source>\/tmp\/mnt\/src<\/source>/<source>src<\/source>/' \
        /mnt/coverage.xml
fi
