# Generated by Django 6.0.8 on 2026-08-27 07:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import waldur_core.core.fields
import waldur_core.core.validators


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PasskeyCredential",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=150,
                        validators=[waldur_core.core.validators.validate_name],
                        verbose_name="name",
                    ),
                ),
                ("uuid", waldur_core.core.fields.UUIDField()),
                ("credential_id", models.TextField(db_index=True, unique=True)),
                ("public_key", models.TextField()),
                ("sign_count", models.PositiveBigIntegerField(default=0)),
                ("aaguid", models.CharField(blank=True, max_length=36)),
                ("transports", models.JSONField(blank=True, default=list)),
                (
                    "attachment",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("platform", "Platform"),
                            ("cross-platform", "Cross-platform"),
                            ("", "Unknown"),
                        ],
                        default="",
                        max_length=20,
                    ),
                ),
                ("rp_id", models.CharField(max_length=253)),
                ("is_backup_eligible", models.BooleanField(default=False)),
                ("is_backed_up", models.BooleanField(default=False)),
                ("is_discoverable", models.BooleanField(default=False)),
                ("is_user_verified", models.BooleanField(default=False)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                ("last_used_ip", models.GenericIPAddressField(blank=True, null=True)),
                ("use_count", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("revocation_reason", models.TextField(blank=True)),
                (
                    "revoked_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="revoked_passkey_credentials",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="passkey_credentials",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "passkey credential",
                "verbose_name_plural": "passkey credentials",
                "ordering": ["-created", "id"],
            },
        ),
        migrations.CreateModel(
            name="PasskeyCeremony",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uuid", waldur_core.core.fields.UUIDField()),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("registration", "Registration"),
                            ("signin", "Passwordless sign-in"),
                            ("mfa", "Second factor"),
                        ],
                        max_length=20,
                    ),
                ),
                ("challenge", models.TextField()),
                ("rp_id", models.CharField(max_length=253)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                ("attempts", models.PositiveSmallIntegerField(default=0)),
                ("consumed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="passkey_ceremonies",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "passkey ceremony",
                "verbose_name_plural": "passkey ceremonies",
                "ordering": ["-created", "id"],
                "indexes": [
                    models.Index(
                        fields=["expires_at"], name="passkeys_pa_expires_c03920_idx"
                    )
                ],
            },
        ),
    ]
