# Generated by Django 2.2.13 on 2020-11-09 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openstack', '0011_drop_invalid_volume_type_quotas'),
    ]

    operations = [
        migrations.AddField(
            model_name='securitygrouprule',
            name='description',
            field=models.CharField(
                blank=True, max_length=2000, verbose_name='description'
            ),
        ),
    ]
