# Generated by Django 2.2.13 on 2020-12-18 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('openstack', '0018_cidr_ipv6'),
    ]

    operations = [
        migrations.AddField(
            model_name='floatingip',
            name='port',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='floating_ips',
                to='openstack.Port',
            ),
        ),
    ]
