# Generated by Django 4.2.24 on 2025-10-08 07:53

import django.db.models.deletion
import django.utils.timezone
import django_fsm
import model_utils.fields
from django.db import migrations, models

import waldur_core.core.fields
import waldur_core.core.validators


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("marketplace", "0184_add_model_indexes"),
    ]

    operations = [
        migrations.CreateModel(
            name="AgentIdentity",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=150,
                        validators=[waldur_core.core.validators.validate_name],
                        verbose_name="name",
                    ),
                ),
                ("slug", models.SlugField()),
                ("uuid", waldur_core.core.fields.UUIDField()),
                ("version", models.CharField(blank=True, max_length=100, null=True)),
                ("dependencies", models.JSONField(default=list)),
                (
                    "config_file_path",
                    models.CharField(
                        blank=True,
                        help_text="Example: '/etc/waldur/agent.yaml'",
                        max_length=150,
                        null=True,
                        validators=[waldur_core.core.validators.validate_unix_path],
                        verbose_name="Config file Path",
                    ),
                ),
                ("config_file_content", models.TextField(blank=True, null=True)),
                (
                    "last_restarted",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Last restarted at",
                    ),
                ),
                (
                    "offering",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="marketplace.offering",
                    ),
                ),
            ],
            options={
                "verbose_name": "Agent identity",
                "ordering": ["created"],
            },
        ),
        migrations.CreateModel(
            name="AgentService",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=150,
                        validators=[waldur_core.core.validators.validate_name],
                        verbose_name="name",
                    ),
                ),
                ("uuid", waldur_core.core.fields.UUIDField()),
                ("mode", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "state",
                    django_fsm.FSMIntegerField(
                        choices=[(1, "Active"), (2, "Idle"), (3, "Error")], default=1
                    ),
                ),
                ("statistics", models.JSONField(default=dict)),
                (
                    "identity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="marketplace_site_agent.agentidentity",
                    ),
                ),
            ],
            options={
                "verbose_name": "Agent service",
                "ordering": ["created"],
                "unique_together": {("identity", "name")},
            },
        ),
        migrations.CreateModel(
            name="AgentProcessor",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=150,
                        validators=[waldur_core.core.validators.validate_name],
                        verbose_name="name",
                    ),
                ),
                ("uuid", waldur_core.core.fields.UUIDField()),
                (
                    "last_run",
                    models.DateTimeField(
                        blank=True,
                        default=django.utils.timezone.now,
                        null=True,
                        verbose_name="Last run",
                    ),
                ),
                (
                    "backend_type",
                    models.CharField(
                        help_text="Type of the backend, for example SLURM.",
                        max_length=100,
                        verbose_name="Backend type",
                    ),
                ),
                (
                    "backend_version",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Backend version",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="marketplace_site_agent.agentservice",
                    ),
                ),
            ],
            options={
                "verbose_name": "Agent processor",
                "ordering": ["created"],
                "unique_together": {("service", "name")},
            },
        ),
    ]
