# Generated by Django 6.0.7 on 2026-07-19 07:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("logging", "0025_eventconsumer"),
        ("marketplace_site_agent", "0003_siteagentlog"),
    ]

    operations = [
        migrations.AddField(
            model_name="agentidentity",
            name="event_consumer",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="agent_identity",
                to="logging.eventconsumer",
            ),
        ),
    ]
