# Generated by Django 6.0.8 on 2026-08-20 13:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("marketplace_site_agent", "0004_agentidentity_event_consumer"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="agentidentity",
            options={"ordering": ["created", "id"], "verbose_name": "Agent identity"},
        ),
        migrations.AlterModelOptions(
            name="agentprocessor",
            options={"ordering": ["created", "id"], "verbose_name": "Agent processor"},
        ),
        migrations.AlterModelOptions(
            name="agentservice",
            options={"ordering": ["created", "id"], "verbose_name": "Agent service"},
        ),
        migrations.AlterModelOptions(
            name="siteagentlog",
            options={
                "ordering": ["-timestamp", "id"],
                "verbose_name": "Site agent log",
            },
        ),
    ]
