# Generated by Django 2.2.13 on 2020-10-06 18:25

from django.db import migrations

import waldur_core.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('openstack_tenant', '0004_fill_tenant_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='internalip',
            name='allowed_address_pairs',
            field=waldur_core.core.fields.JSONField(
                default=list,
                help_text='A server can send a packet with source address which matches one of the specified allowed address pairs.',
            ),
        ),
    ]
