# Generated by Django 2.2.13 on 2020-10-13 17:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('openstack_tenant', '0006_error_traceback'),
    ]

    operations = [
        migrations.AddField(
            model_name='subnet',
            name='is_connected',
            field=models.BooleanField(
                default=True,
                help_text='Is subnet connected to the default tenant router.',
            ),
        ),
    ]
