# Generated by Django 2.2.13 on 2020-12-03 16:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('openstack_tenant', '0013_securitygrouprule_remote_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='securitygrouprule',
            name='cidr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
