# Generated by Django 6.0.8 on 2026-08-28 12:02

from decimal import Decimal

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models

import waldur_core.core.fields


class Migration(migrations.Migration):
    replaces = [
        ("invoices", "0002_invoiceitem_backend_uuid"),
        (
            "invoices",
            "0003_alter_invoice_total_cost_alter_invoiceitem_quantity_and_more",
        ),
        ("invoices", "0004_invoice_total_price"),
        ("invoices", "0005_projectcredit_customercredit_invoiceitem_credit"),
        ("invoices", "0006_customercredit_end_date_and_more"),
        ("invoices", "0007_customercredit_minimal_consumption_logic"),
        ("invoices", "0008_remove_projectcredit_use_organisation_credit"),
        ("invoices", "0009_max_digits_of_credit"),
        (
            "invoices",
            "0010_rename_minimal_consumption_customercredit_expected_consumption_and_more",
        ),
        ("invoices", "0011_projectcredit_minimal_consumption"),
        ("invoices", "0012_invoice_events"),
    ]

    dependencies = [
        ("invoices", "0001_squashed_0062"),
        ("logging", "0015_event_index"),
        ("marketplace", "0140_categorycolumn_uuid"),
        ("structure", "0046_project_start_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="total_price",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                editable=False,
                help_text="Cached value for total price.",
                max_digits=22,
            ),
        ),
        migrations.AddField(
            model_name="invoiceitem",
            name="backend_uuid",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="total_cost",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                editable=False,
                help_text="Cached value for total cost.",
                max_digits=22,
            ),
        ),
        migrations.AlterField(
            model_name="invoiceitem",
            name="quantity",
            field=models.DecimalField(decimal_places=10, default=0, max_digits=22),
        ),
        migrations.AlterField(
            model_name="invoiceitem",
            name="unit_price",
            field=models.DecimalField(
                decimal_places=10,
                default=0,
                max_digits=22,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
            ),
        ),
        migrations.CreateModel(
            name="CustomerCredit",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("uuid", waldur_core.core.fields.UUIDField()),
                (
                    "value",
                    models.DecimalField(
                        decimal_places=5,
                        default=0,
                        max_digits=16,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                ("end_date", models.DateField(null=True)),
                (
                    "minimal_consumption_logic",
                    models.CharField(
                        choices=[("fixed", "Fixed"), ("linear", "Linear")],
                        default="fixed",
                        max_length=10,
                    ),
                ),
                (
                    "expected_consumption",
                    models.DecimalField(
                        decimal_places=5,
                        default=0,
                        max_digits=16,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                ("apply_as_minimal_consumption", models.BooleanField(default=True)),
                (
                    "grace_coefficient",
                    models.DecimalField(decimal_places=0, default=0, max_digits=3),
                ),
                (
                    "customer",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="structure.customer",
                    ),
                ),
                ("offerings", models.ManyToManyField(to="marketplace.offering")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="invoiceitem",
            name="credit",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="invoices.customercredit",
            ),
        ),
        migrations.CreateModel(
            name="ProjectCredit",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("uuid", waldur_core.core.fields.UUIDField()),
                (
                    "value",
                    models.DecimalField(
                        decimal_places=5,
                        default=0,
                        max_digits=16,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                ("apply_as_minimal_consumption", models.BooleanField(default=True)),
                ("end_date", models.DateField(null=True)),
                (
                    "expected_consumption",
                    models.DecimalField(
                        decimal_places=5,
                        default=0,
                        max_digits=16,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                (
                    "grace_coefficient",
                    models.DecimalField(
                        decimal_places=0, default=Decimal("0"), max_digits=3
                    ),
                ),
                (
                    "minimal_consumption_logic",
                    models.CharField(
                        choices=[("fixed", "Fixed"), ("linear", "Linear")],
                        default="fixed",
                        max_length=10,
                    ),
                ),
                (
                    "project",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="structure.project",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
