# Generated by Django 4.2.10 on 2024-02-26 06:23

from decimal import Decimal

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("invoices", "0002_invoiceitem_backend_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="total_cost",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                editable=False,
                help_text="Cached value for total cost.",
                max_digits=22,
            ),
        ),
        migrations.AlterField(
            model_name="invoiceitem",
            name="quantity",
            field=models.DecimalField(decimal_places=10, default=0, max_digits=22),
        ),
        migrations.AlterField(
            model_name="invoiceitem",
            name="unit_price",
            field=models.DecimalField(
                decimal_places=10,
                default=0,
                max_digits=22,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
            ),
        ),
    ]
