# Generated by Django 4.2.16 on 2024-11-18 13:08

from decimal import Decimal

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("invoices", "0008_remove_projectcredit_use_organisation_credit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customercredit",
            name="minimal_consumption",
            field=models.DecimalField(
                decimal_places=5,
                default=0,
                max_digits=16,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
            ),
        ),
        migrations.AlterField(
            model_name="customercredit",
            name="value",
            field=models.DecimalField(
                decimal_places=5,
                default=0,
                max_digits=16,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
            ),
        ),
        migrations.AlterField(
            model_name="projectcredit",
            name="value",
            field=models.DecimalField(
                decimal_places=5,
                default=0,
                max_digits=16,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
            ),
        ),
    ]
