# Generated by Django 4.2.16 on 2024-12-10 17:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("invoices", "0009_max_digits_of_credit"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customercredit",
            old_name="minimal_consumption",
            new_name="expected_consumption",
        ),
        migrations.AddField(
            model_name="customercredit",
            name="apply_as_minimal_consumption",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="customercredit",
            name="grace_coefficient",
            field=models.DecimalField(decimal_places=0, default=0, max_digits=3),
        ),
    ]
