# Generated by Django 4.2.23 on 2025-08-05 13:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("invoices", "0015_fix_credit_end_dates"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoiceitem",
            name="unit",
            field=models.CharField(
                choices=[
                    ("month", "Per month"),
                    ("quarter", "Per quarter"),
                    ("half_month", "Per half month"),
                    ("day", "Per day"),
                    ("hour", "Per hour"),
                    ("quantity", "Quantity"),
                ],
                default="day",
                max_length=30,
            ),
        ),
    ]
