# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-11 14:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import waldur_mastermind.invoices.models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0002_immutable_default_json'),
        ('invoices', '0024_immutable_default_json'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceDowntime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(default=waldur_mastermind.invoices.models.get_default_downtime_start, help_text='Date and time when downtime has started.')),
                ('end', models.DateTimeField(default=django.utils.timezone.now, help_text='Date and time when downtime has ended.')),
                ('settings', models.ForeignKey(help_text='Private OpenStackTenant service settings.', on_delete=django.db.models.deletion.CASCADE, to='structure.ServiceSettings')),
            ],
        ),
    ]
