# Generated by Django 6.0.6 on 2026-06-11 16:26

from decimal import Decimal

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models

import waldur_core.core.fields


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("invoices", "0024_fix_project_credit_end_dates"),
        ("structure", "0077_affiliation_redesign"),
    ]

    operations = [
        migrations.CreateModel(
            name="CreditTransaction",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uuid", waldur_core.core.fields.UUIDField()),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("amount", models.DecimalField(decimal_places=5, max_digits=16)),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("staff_grant", "Staff grant"),
                            ("compensation", "Compensation"),
                            ("affiliate_fee", "Affiliate fee"),
                            ("transfer_in", "Transfer in"),
                            ("transfer_out", "Transfer out"),
                            ("payout", "Payout"),
                            ("expiry", "Expiry"),
                            ("rollback", "Rollback"),
                            ("adjustment", "Adjustment"),
                        ],
                        max_length=30,
                    ),
                ),
                ("object_id", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "credit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="invoices.customercredit",
                    ),
                ),
            ],
            options={
                "ordering": ["-created"],
            },
        ),
        migrations.CreateModel(
            name="CustomerAffiliate",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("uuid", waldur_core.core.fields.UUIDField()),
                (
                    "fee_percent",
                    models.DecimalField(
                        decimal_places=5,
                        default=0,
                        max_digits=8,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("100")),
                        ],
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "affiliate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="affiliate_terms",
                        to="structure.customer",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="affiliate_links",
                        to="structure.customer",
                    ),
                ),
            ],
            options={
                "ordering": ["created"],
                "unique_together": {("customer", "affiliate")},
            },
        ),
        migrations.CreateModel(
            name="AffiliateFeeAccrual",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("uuid", waldur_core.core.fields.UUIDField()),
                ("amount", models.DecimalField(decimal_places=5, max_digits=16)),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="affiliate_fee_accruals",
                        to="invoices.invoice",
                    ),
                ),
                (
                    "affiliate_link",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="accruals",
                        to="invoices.customeraffiliate",
                    ),
                ),
            ],
            options={
                "ordering": ["-created"],
                "unique_together": {("affiliate_link", "invoice")},
            },
        ),
    ]
