# Generated by Django 6.0.6 on 2026-07-03 12:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("invoices", "0025_affiliates_and_credit_ledger"),
    ]

    operations = [
        migrations.AddField(
            model_name="credittransaction",
            name="comment",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="credittransaction",
            name="transaction_type",
            field=models.CharField(
                choices=[
                    ("staff_grant", "Staff grant"),
                    ("compensation", "Compensation"),
                    ("affiliate_fee", "Affiliate fee"),
                    ("transfer_in", "Transfer in"),
                    ("transfer_out", "Transfer out"),
                    ("payout", "Payout"),
                    ("expiry", "Expiry"),
                    ("rollback", "Rollback"),
                    ("adjustment", "Adjustment"),
                    ("withdrawable_adjustment", "Withdrawable adjustment"),
                ],
                max_length=30,
            ),
        ),
    ]
