# Generated by Django 6.0.8 on 2026-08-20 13:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("invoices", "0028_credittransaction_billing_period_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="credittransaction",
            options={"ordering": ["-created", "id"]},
        ),
        migrations.AlterModelOptions(
            name="customeraffiliate",
            options={"ordering": ["created", "id"]},
        ),
    ]
