# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-09-09 17:02
from __future__ import unicode_literals

from django.db import migrations, models


def get_name(item):
    if item.details.get('name'):
        return item.details.get('name')
    if item.details:
        return ', '.join(['%s: %s' % (k, v) for k, v in item.details.items()])
    if item.content_type:
        return '%s.%s' % (item.content_type.app_label, item.content_type.model)
    return ''


def init_invoice_item_name(apps, schema_editor):
    GenericInvoiceItem = apps.get_model('invoices', 'GenericInvoiceItem')
    for item in GenericInvoiceItem.objects.all():
        item.name = get_name(item)
        item.save(update_fields=['name'])


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0030_json_details_on_genericinvoiceitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='genericinvoiceitem',
            name='name',
            field=models.TextField(default=''),
        ),
        migrations.RunPython(init_invoice_item_name),
    ]
