# Generated by Django 6.0.8 on 2026-09-01 16:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("invoices", "0020_squashed_0030"),
        (
            "marketplace",
            "0280_category_description_mk_category_description_sq_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="customercredit",
            name="offerings",
            field=models.ManyToManyField(
                blank=True,
                help_text="Offerings the credit may be drawn against. Leave empty to allow all offerings: an empty list means unrestricted, not none. Cost on any other offering is invoiced normally and is never compensated from this credit.",
                to="marketplace.offering",
            ),
        ),
    ]
