# Generated by Django 6.0.8 on 2026-09-15 12:05

from django.db import migrations, models


def check_single_active_link(apps, schema_editor):
    # Refuse to pick a winner automatically: links carry fee history, so
    # which one stays active is an operator decision.
    CustomerAffiliate = apps.get_model("invoices", "CustomerAffiliate")
    duplicates = (
        CustomerAffiliate.objects.filter(is_active=True)
        .values("customer_id", "customer__name")
        .annotate(count=models.Count("id"))
        .filter(count__gt=1)
    )
    if duplicates:
        names = ", ".join(sorted(row["customer__name"] for row in duplicates))
        raise RuntimeError(
            "Cannot enforce one active affiliate per organization: these "
            f"organizations have several active affiliate links: {names}. "
            "Deactivate all but one link for each, then re-run the migration."
        )


class Migration(migrations.Migration):
    dependencies = [
        ("invoices", "0031_credit_offerings_help_text"),
        ("structure", "0041_squashed_0085"),
    ]

    operations = [
        migrations.RunPython(check_single_active_link, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="customeraffiliate",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True)),
                fields=("customer",),
                name="invoices_one_active_affiliate_per_customer",
            ),
        ),
    ]
