# Generated by Django 2.2.10 on 2020-04-02 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0010_customer_geolocation'),
        ('invoices', '0034_paymentprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentprofile',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterUniqueTogether(
            name='paymentprofile',
            unique_together={('organization', 'is_active')},
        ),
    ]
