# Generated by Django 2.2.10 on 2020-04-16 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0036_paymentprofile_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentprofile',
            name='is_active',
            field=models.NullBooleanField(default=True),
        ),
    ]
