# Generated by Django 2.2.13 on 2020-08-12 17:04
from django.db import migrations, models

import waldur_mastermind.invoices.models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0039_payment_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='created',
            field=models.DateField(
                null=True,
                blank=True,
                default=waldur_mastermind.invoices.models.get_created_date,
            ),
        ),
    ]
