# Generated by Django 2.2.13 on 2020-08-12 17:04
import datetime

from django.db import migrations, models

import waldur_mastermind.invoices.models


def fill_created_field(apps, schema_editor):
    Invoice = apps.get_model('invoices', 'Invoice')
    for invoice in Invoice.objects.all():
        invoice.created = datetime.date(year=invoice.year, month=invoice.month, day=1)
        invoice.save()


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0039_payment_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='created',
            field=models.DateField(
                null=True,
                blank=True,
                default=waldur_mastermind.invoices.models.get_created_date,
            ),
        ),
        migrations.RunPython(fill_created_field),
    ]
