# Generated by Django 2.2.13 on 2021-03-17 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0050_fix_slurm_invoice_items_for_march'),
    ]

    operations = [
        migrations.RemoveField(model_name='invoiceitem', name='product_code',),
    ]
