# Generated by Django 3.2 on 2022-02-01 08:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('invoices', '0059_json_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentprofile',
            name='is_active',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
