LANGUAGE_CHOICES = [
    "en",
    "et",
    "lt",
    "lv",
    "ru",
    "it",
    "de",
    "da",
    "sv",
    "es",
    "fr",
    "nb",
    "ar",
    "cs",
]

CONSTANCE_BACKEND = "constance.backends.database.DatabaseBackend"
CONSTANCE_DBS = "default"
CONSTANCE_SUPERUSER_ONLY = False
CONSTANCE_IGNORE_ADMIN_VERSION_CHECK = True
CONSTANCE_ADDITIONAL_FIELDS = {
    "image_field": ["django.forms.ImageField", {"required": False}],
    "email_field": ["django.forms.EmailField", {"required": False}],
    "color_field": ["django.forms.CharField", {"required": False}],
    "html_field": ["django.forms.CharField", {"required": False}],
    "text_field": ["django.forms.CharField", {"required": False}],
    "url_field": ["django.forms.URLField", {"required": False}],
    "secret_field": ["django.forms.CharField", {"required": False}],
    "dict_field": ["waldur_core.core.serializers.DictField", {"required": False}],
    "list_field": ["waldur_core.core.serializers.ListField", {"required": False}],
    "country_list_field": [
        "waldur_core.core.serializers.ListField",
        {"required": False},
    ],
    "choice_field": ["django.forms.ChoiceField", {"required": False}],
}
CONSTANCE_CONFIG = {
    "SITE_NAME": ("Waldur", "Human-friendly name of the Waldur deployment."),
    "SITE_DESCRIPTION": (
        "Your single pane of control for managing projects, teams and resources in a self-service manner.",
        "Description of the Waldur deployment.",
    ),
    "HOMEPORT_URL": (
        "https://example.com/",
        "It is used for rendering callback URL in HomePort",
    ),
    "RANCHER_USERNAME_INPUT_LABEL": (
        "Username",
        "Label for the username field in Rancher external user resource access management.",
    ),
    "SITE_ADDRESS": ("", "It is used in marketplace order header."),
    "SITE_EMAIL": ("", "It is used in marketplace order header and UI footer."),
    "SITE_PHONE": ("", "It is used in marketplace order header and UI footer."),
    "CURRENCY_NAME": (
        "EUR",
        "It is used in marketplace order details and invoices for currency formatting.",
    ),
    "THUMBNAIL_SIZE": (
        "120x120",
        "Size of the thumbnail to generate when screenshot is uploaded for an offering.",
    ),
    "ANONYMOUS_USER_CAN_VIEW_OFFERINGS": (
        True,
        "Allow anonymous users to see shared offerings in active, paused and archived states",
    ),
    "ANONYMOUS_USER_CAN_VIEW_PLANS": (True, "Allow anonymous users to see plans"),
    "NOTIFY_STAFF_ABOUT_APPROVALS": (
        False,
        "If true, users with staff role are notified when request for order approval is generated",
    ),
    "NOTIFY_ABOUT_RESOURCE_CHANGE": (
        True,
        "If true, notify users about resource changes from Marketplace perspective. Can generate duplicate events if plugins also log",
    ),
    "DISABLE_SENDING_NOTIFICATIONS_ABOUT_RESOURCE_UPDATE": (
        True,
        "Disable only resource update events.",
    ),
    "MARKETPLACE_LANDING_PAGE": (
        "Marketplace",
        "Marketplace landing page title.",
    ),
    "ENABLE_STALE_RESOURCE_NOTIFICATIONS": (
        False,
        "Enable reminders to owners about resources of shared offerings that have not generated any cost for the last 3 months.",
    ),
    "TELEMETRY_URL": (
        "https://telemetry.waldur.com/",
        "URL for sending telemetry data.",
    ),
    "TELEMETRY_VERSION": (1, "Telemetry service version."),
    "SCRIPT_RUN_MODE": (
        "docker",
        'Type of jobs deployment. Valid values: "docker" for simple docker deployment, "k8s" for Kubernetes-based one',
    ),
    "DOCKER_CLIENT": (
        {"base_url": "unix:///var/run/docker.sock"},
        "Options for docker client. See also: <https://docker-py.readthedocs.io/en/stable/client.html#docker.client.DockerClient>",
        "dict_field",
    ),
    "DOCKER_RUN_OPTIONS": (
        {"mem_limit": "512m"},
        "Options for docker runtime. See also: <https://docker-py.readthedocs.io/en/stable/containers.html#docker.models.containers.ContainerCollection.run>",
        "dict_field",
    ),
    "DOCKER_SCRIPT_DIR": (
        "",
        "Path to folder on executor machine where to create temporary submission scripts. If None, uses OS-dependent location. OS X users, see <https://github.com/docker/for-mac/issues/1532>",
    ),
    "DOCKER_REMOVE_CONTAINER": (True, "Remove Docker container after script execution"),
    "DOCKER_IMAGES": (
        {
            "python": {"image": "python:3.11-alpine", "command": "python"},
            "shell": {"image": "alpine:3", "command": "sh"},
            "ansible": {
                "image": "alpine/ansible:2.18.6",
                "command": "ansible-playbook",
            },
        },
        "Key is command to execute script, value is a dictionary of image name and command.",
        "dict_field",
    ),
    "DOCKER_VOLUME_NAME": (
        "waldur-docker-compose_waldur_script_launchzone",
        "A name of the shared volume to store scripts",
    ),
    "K8S_NAMESPACE": ("default", "Kubernetes namespace where jobs will be executed"),
    "K8S_CONFIG_PATH": ("~/.kube/config", "Path to Kubernetes configuration file"),
    "K8S_JOB_TIMEOUT": (
        30 * 60,
        "Timeout for execution of one Kubernetes job in seconds",
    ),
    "ENABLE_STRICT_CHECK_ACCEPTING_INVITATION": (
        False,
        "If true, user email in Waldur database and in invitatation must strictly match.",
    ),
    "INVITATION_DISABLE_MULTIPLE_ROLES": (
        False,
        "Do not allow user to grant multiple roles in the same project or organization using invitation.",
    ),
    "DEFAULT_IDP": ("", "Triggers authentication flow at once."),
    "DOCS_URL": ("", "Renders link to docs in header", "url_field"),
    "SHORT_PAGE_TITLE": ("Waldur", "It is used as prefix for page title."),
    "FULL_PAGE_TITLE": (
        "Waldur | Cloud Service Management",
        "It is used as default page title if it's not specified explicitly.",
    ),
    "PROJECT_END_DATE_MANDATORY": (
        False,
        "If true, project end date field becomes mandatory when creating or updating projects.",
    ),
    "ENABLE_ORDER_START_DATE": (
        False,
        "Allow setting start date to control when resource creation order is processed.",
    ),
    "BRAND_COLOR": (
        "#307300",
        "Brand color is used for button background.",
        "color_field",
    ),
    "HERO_LINK_LABEL": (
        "",
        "Label for link in hero section of HomePort landing page. It can be lead to support site or blog post.",
    ),
    "HERO_LINK_URL": (
        "",
        "Link URL in hero section of HomePort landing page.",
        "url_field",
    ),
    "SUPPORT_PORTAL_URL": (
        "",
        "Link URL to support portal. Rendered as a shortcut on dashboard",
        "url_field",
    ),
    "COMMON_FOOTER_TEXT": (
        "",
        "Common footer in txt format for all emails.",
        "text_field",
    ),
    "COMMON_FOOTER_HTML": (
        "",
        "Common footer in html format for all emails.",
        "html_field",
    ),
    "LANGUAGE_CHOICES": (
        ",".join(LANGUAGE_CHOICES),
        "List of enabled languages",
    ),
    "DISABLE_DARK_THEME": (False, "Toggler to disable dark theme."),
    # images, logos, favicons
    "POWERED_BY_LOGO": (
        "",
        "The image rendered at the bottom of login menu in HomePort.",
        "image_field",
    ),
    "HERO_IMAGE": (
        "",
        "The image rendered at hero section of HomePort landing page.",
        "image_field",
    ),
    "MARKETPLACE_HERO_IMAGE": (
        "",
        "The image rendered at hero section of Marketplace landing page. Please, use a wide image (min. 1920×600px) with no text or logos. Keep the center area clean, and choose a darker image for dark mode or a brighter image for light mode.",
        "image_field",
    ),
    "CALL_MANAGEMENT_HERO_IMAGE": (
        "",
        "The image rendered at hero section of Call Management landing page. Please, use a wide image (min. 1920×600px) with no text or logos. Keep the center area clean, and choose a darker image for dark mode or a brighter image for light mode.",
        "image_field",
    ),
    "SIDEBAR_LOGO": (
        "",
        "The image rendered at the top of sidebar menu in HomePort.",
        "image_field",
    ),
    "SIDEBAR_LOGO_DARK": (
        "",
        "The image rendered at the top of sidebar menu in dark mode.",
        "image_field",
    ),
    "SIDEBAR_LOGO_MOBILE": (
        "",
        "The image rendered at the top of mobile sidebar menu in HomePort.",
        "image_field",
    ),
    "SIDEBAR_STYLE": (
        "dark",
        "Style of sidebar. Possible values: dark, light, accent.",
    ),
    "SITE_LOGO": ("", "The image used in marketplace order header.", "image_field"),
    "LOGIN_LOGO": ("", "A custom .png image file for login page", "image_field"),
    "FAVICON": ("", "A custom favicon .png image file", "image_field"),
    "OFFERING_LOGO_PLACEHOLDER": ("", "Default logo for offering", "image_field"),
    # service desk integration settings
    "WALDUR_SUPPORT_ENABLED": (
        True,
        "Toggler for support plugin.",
    ),
    "WALDUR_SUPPORT_ACTIVE_BACKEND_TYPE": (
        "atlassian",
        "Type of support backend. Possible values: atlassian, zammad, smax.",
    ),
    "WALDUR_SUPPORT_DISPLAY_REQUEST_TYPE": (
        True,
        "Toggler for request type displaying",
    ),
    # Atlassian settings
    "ATLASSIAN_MAP_WALDUR_USERS_TO_SERVICEDESK_AGENTS": (
        False,
        "Toggler for mapping between waldur user and service desk agents.",
    ),
    "ATLASSIAN_API_URL": (
        "https://example.com/",
        "Atlassian API server URL",
        "url_field",
    ),
    "ATLASSIAN_USERNAME": ("USERNAME", "Username for access user"),
    "ATLASSIAN_PASSWORD": ("PASSWORD", "Password for access user", "secret_field"),
    "ATLASSIAN_EMAIL": ("", "Email for access user", "email_field"),
    "ATLASSIAN_USE_OLD_API": (
        False,
        "Toggler for legacy API usage.",
    ),
    "ATLASSIAN_TOKEN": ("", "Token for access user", "secret_field"),
    "ATLASSIAN_PERSONAL_ACCESS_TOKEN": (
        "",
        "Personal Access Token for user",
        "secret_field",
    ),
    "ATLASSIAN_OAUTH2_CLIENT_ID": ("", "OAuth 2.0 Client ID", "secret_field"),
    "ATLASSIAN_OAUTH2_ACCESS_TOKEN": ("", "OAuth 2.0 Access Token", "secret_field"),
    "ATLASSIAN_OAUTH2_TOKEN_TYPE": ("Bearer", "OAuth 2.0 Token Type"),
    "ATLASSIAN_VERIFY_SSL": (
        True,
        "Toggler for SSL verification",
    ),
    "ATLASSIAN_PROJECT_ID": ("", "Service desk ID or key"),
    "ATLASSIAN_SHARED_USERNAME": (
        False,
        "Is Service Desk username the same as in Waldur",
    ),
    "ATLASSIAN_CUSTOM_ISSUE_FIELD_MAPPING_ENABLED": (
        True,
        "Should extra issue field mappings be applied",
    ),
    "ATLASSIAN_DEFAULT_OFFERING_ISSUE_TYPE": (
        "Service Request",
        "Issue type used for request-based item processing.",
    ),
    "ATLASSIAN_EXCLUDED_ATTACHMENT_TYPES": (
        "",
        "Comma-separated list of file extenstions not allowed for attachment.",
    ),
    "ATLASSIAN_ISSUE_TYPES": (
        "Informational, Service Request, Change Request, Incident",
        "Comma-separated list of enabled issue types. First type is the default one.",
    ),
    "ATLASSIAN_SUPPORT_TYPE_MAPPING": (
        {
            "Informational": "Get IT help",
            "Service Request": "Request new software",
            "Change Request": "Change Request",
            "Incident": "Report a system problem",
        },
        "Mapping from frontend issue types to backend request types",
        "dict_field",
    ),
    "ATLASSIAN_DESCRIPTION_TEMPLATE": ("", "Template for issue description"),
    "ATLASSIAN_SUMMARY_TEMPLATE": ("", "Template for issue summary"),
    "ATLASSIAN_AFFECTED_RESOURCE_FIELD": ("", "Affected resource field name"),
    "ATLASSIAN_IMPACT_FIELD": ("Impact", "Impact field name"),
    "ATLASSIAN_ORGANISATION_FIELD": ("", "Organisation field name"),
    "ATLASSIAN_RESOLUTION_SLA_FIELD": ("", "Resolution SLA field name"),
    "ATLASSIAN_PROJECT_FIELD": ("", "Project field name"),
    "ATLASSIAN_REPORTER_FIELD": ("Original Reporter", "Reporter field name"),
    "ATLASSIAN_CALLER_FIELD": ("Caller", "Caller field name"),
    "ATLASSIAN_SLA_FIELD": ("Time to first response", "SLA field name"),
    "ATLASSIAN_LINKED_ISSUE_TYPE": ("Relates", "Type of linked issue field name"),
    "ATLASSIAN_SATISFACTION_FIELD": (
        "Customer satisfaction",
        "Customer satisfaction field name",
    ),
    "ATLASSIAN_REQUEST_FEEDBACK_FIELD": (
        "Request feedback",
        "Request feedback field name",
    ),
    "ATLASSIAN_TEMPLATE_FIELD": ("", "Template field name"),
    "ATLASSIAN_WALDUR_BACKEND_ID_FIELD": (
        "customfield_10200",
        "Waldur backend ID custom field ID (fallback when field lookup by name fails)",
    ),
    # Zammad settings
    "ZAMMAD_API_URL": (
        "",
        "Zammad API server URL. For example <https://localhost:8080/>",
        "url_field",
    ),
    "ZAMMAD_TOKEN": ("", "Authorization token.", "secret_field"),
    "ZAMMAD_GROUP": (
        "",
        "The name of the group to which the ticket will be added. "
        "If not specified, the first group will be used.",
    ),
    "ZAMMAD_ARTICLE_TYPE": (
        "email",
        "Type of a comment. "
        "Default is email because it allows support to reply to tickets directly in Zammad"
        "<https://docs.zammad.org/en/latest/api/ticket/articles.html#articles/>",
    ),
    "ZAMMAD_COMMENT_MARKER": (
        "Created by Waldur",
        "Marker for comment. "
        "Used for separating comments made via Waldur from natively added "
        "comments.",
    ),
    "ZAMMAD_COMMENT_PREFIX": ("User: {name}", "Comment prefix with user info."),
    "ZAMMAD_COMMENT_COOLDOWN_DURATION": (
        5,
        "Time in minutes. "
        "Time in minutes while comment deletion is available "
        "<https://github.com/zammad/zammad/issues/2687/>, "
        "<https://github.com/zammad/zammad/issues/3086/>",
    ),
    # SMAX settings
    "SMAX_API_URL": (
        "",
        "SMAX API server URL. For example <https://localhost:8080/>",
        "url_field",
    ),
    "SMAX_TENANT_ID": ("", "User tenant ID."),
    "SMAX_LOGIN": ("", "Authorization login."),
    "SMAX_PASSWORD": ("", "Authorization password.", "secret_field"),
    "SMAX_ORGANISATION_FIELD": ("", "Organisation field name."),
    "SMAX_PROJECT_FIELD": ("", "Project field name."),
    "SMAX_AFFECTED_RESOURCE_FIELD": ("", "Resource field name."),
    "SMAX_TIMES_TO_PULL": (
        10,
        "The maximum number of attempts to pull user from backend.",
    ),
    "SMAX_SECONDS_TO_WAIT": (
        1,
        "Duration in seconds of delay between pull user attempts.",
    ),
    "SMAX_CREATION_SOURCE_NAME": ("", "Creation source name."),
    "SMAX_REQUESTS_OFFERING": ("", "Requests offering code for all issues."),
    "SMAX_VERIFY_SSL": (True, "Toggler for SSL verification"),
    # Service accounts
    "ENABLE_MOCK_SERVICE_ACCOUNT_BACKEND": (
        False,
        "Enable mock returns for the service account service",
    ),
    # Course accounts
    "ENABLE_MOCK_COURSE_ACCOUNT_BACKEND": (
        False,
        "Enable mock returns for the course account service",
    ),
    # Proposal settings
    "PROPOSAL_REVIEW_DURATION": (7, "Review duration in days."),
    "USER_TABLE_COLUMNS": ("", "Comma-separated list of columns for users table."),
    "AUTO_APPROVE_USER_TOS": (
        False,
        "Mark terms of services as approved for new users.",
    ),
    # FREEIPA settings
    "FREEIPA_ENABLED": (
        False,
        "Enable integration of identity provisioning in configured FreeIPA.",
    ),
    "FREEIPA_HOSTNAME": ("ipa.example.com", "Hostname of FreeIPA server."),
    "FREEIPA_USERNAME": (
        "admin",
        "Username of FreeIPA user with administrative privileges.",
    ),
    "FREEIPA_PASSWORD": (
        "secret",
        "Password of FreeIPA user with administrative privileges",
        "secret_field",
    ),
    "FREEIPA_VERIFY_SSL": (
        True,
        "Validate TLS certificate of FreeIPA web interface / REST API",
    ),
    "FREEIPA_USERNAME_PREFIX": (
        "waldur_",
        "Prefix to be appended to all usernames created in FreeIPA by Waldur",
    ),
    "FREEIPA_GROUPNAME_PREFIX": (
        "waldur_",
        "Prefix to be appended to all group names created in FreeIPA by Waldur",
    ),
    "FREEIPA_BLACKLISTED_USERNAMES": (
        ["root"],
        "List of username that users are not allowed to select",
        "list_field",
    ),
    "FREEIPA_GROUP_SYNCHRONIZATION_ENABLED": (
        True,
        "Optionally disable creation of user groups in FreeIPA matching Waldur structure",
    ),
    "KEYCLOAK_ICON": (
        "",
        "A custom PNG icon for Keycloak login button",
        "image_field",
    ),
    "COUNTRIES": (
        [
            "AL",
            "AT",
            "BA",
            "BE",
            "BG",
            "CH",
            "CY",
            "CZ",
            "DE",
            "DK",
            "EE",
            "ES",
            "EU",
            "FI",
            "FR",
            "GB",
            "GE",
            "GR",
            "HR",
            "HU",
            "IE",
            "IS",
            "IT",
            "LT",
            "LU",
            "LV",
            "MC",
            "MK",
            "MT",
            "NL",
            "NO",
            "PL",
            "PT",
            "RO",
            "RS",
            "SE",
            "SI",
            "SK",
            "UA",
        ],
        "It is used in organization creation dialog in order to limit country choices to predefined set.",
        "country_list_field",
    ),
    "OIDC_AUTH_URL": (
        "",
        "OIDC authentication endpoint URL.",
    ),
    "OIDC_INTROSPECTION_URL": (
        "",
        "OIDC introspection endpoint URL for validating access tokens.",
    ),
    "OIDC_CLIENT_ID": (
        "",
        "Client ID for authenticating against the introspection endpoint.",
    ),
    "OIDC_CLIENT_SECRET": (
        "",
        "Client secret for authenticating against the introspection endpoint.",
    ),
    "OIDC_USER_FIELD": (
        "username",
        "Field name from the introspection response to identify the user (e.g., 'username', 'email', 'client_id').",
    ),
    "OIDC_CACHE_TIMEOUT": (
        300,
        "Number of seconds to cache token introspection results.",
    ),
    "OIDC_ACCESS_TOKEN_ENABLED": (
        False,
        "If true, OIDC complete view returns access token instead of Waldur token",
    ),
    "OIDC_BLOCK_CREATION_OF_UNINVITED_USERS": (
        False,
        "If true, block creation of an account on OIDC login if user email is not provided or provided and is not in the list of one of the active invitations.",
    ),
    "DEACTIVATE_USER_IF_NO_ROLES": (
        False,
        "Deactivate user if all roles are revoked (except staff/support)",
    ),
    "MAINTENANCE_ANNOUNCEMENT_NOTIFY_BEFORE_MINUTES": (
        60,
        "How many minutes before scheduled maintenance users should be notified.",
    ),
    "MAINTENANCE_ANNOUNCEMENT_NOTIFY_SYSTEM": (
        ["AdminAnnouncement"],
        "How maintenance notifications are delivered. Choices: AdminAnnouncement or BroadcastMessage.",
        "list_field",
    ),
    "ENFORCE_USER_CONSENT_FOR_OFFERINGS": (
        False,
        "If True, users must have active consent to access offerings that have active Terms of Service.",
    ),
    "ONBOARDING_VERIFICATION_EXPIRY_HOURS": (
        48,
        "Number of hours after which onboarding verifications expire.",
    ),
    "ONBOARDING_ARIREGISTER_BASE_URL": (
        "https://demo-ariregxmlv6.rik.ee/",
        "Base URL for Estonian Äriregister API endpoint.",
        "url_field",
    ),
    "ONBOARDING_ARIREGISTER_USERNAME": (
        "",
        "Username for Estonian Äriregister API authentication.",
        "text_field",
    ),
    "ONBOARDING_ARIREGISTER_PASSWORD": (
        "",
        "Password for Estonian Äriregister API authentication.",
        "secret_field",
    ),
    "ONBOARDING_ARIREGISTER_TIMEOUT": (
        30,
        "Timeout in seconds for Estonian Äriregister API requests.",
    ),
    "ONBOARDING_WICO_API_URL": (
        "https://api.wirtschaftscompass.at/",
        "WirtschaftsCompass API server URL",
        "url_field",
    ),
    "ONBOARDING_WICO_TOKEN": ("", "WirtschaftsCompass API token", "secret_field"),
}

CONSTANCE_CONFIG_FIELDSETS = {
    "Branding": (
        "SITE_NAME",
        "SHORT_PAGE_TITLE",
        "FULL_PAGE_TITLE",
        "SITE_DESCRIPTION",
        "HOMEPORT_URL",
        "RANCHER_USERNAME_INPUT_LABEL",
    ),
    "Marketplace Branding": (
        "SITE_ADDRESS",
        "SITE_EMAIL",
        "SITE_PHONE",
        "CURRENCY_NAME",
        "MARKETPLACE_LANDING_PAGE",
        "COUNTRIES",
    ),
    "Marketplace": (
        "THUMBNAIL_SIZE",
        "ANONYMOUS_USER_CAN_VIEW_OFFERINGS",
        "ANONYMOUS_USER_CAN_VIEW_PLANS",
        "NOTIFY_STAFF_ABOUT_APPROVALS",
        "NOTIFY_ABOUT_RESOURCE_CHANGE",
        "DISABLE_SENDING_NOTIFICATIONS_ABOUT_RESOURCE_UPDATE",
        "ENABLE_STALE_RESOURCE_NOTIFICATIONS",
        "ENABLE_MOCK_SERVICE_ACCOUNT_BACKEND",
        "ENABLE_MOCK_COURSE_ACCOUNT_BACKEND",
        "ENFORCE_USER_CONSENT_FOR_OFFERINGS",
        "ENABLE_ORDER_START_DATE",
    ),
    "Project": ("PROJECT_END_DATE_MANDATORY",),
    "Telemetry": (
        "TELEMETRY_URL",
        "TELEMETRY_VERSION",
    ),
    "Custom Scripts": (
        "SCRIPT_RUN_MODE",
        "DOCKER_CLIENT",
        "DOCKER_RUN_OPTIONS",
        "DOCKER_SCRIPT_DIR",
        "DOCKER_REMOVE_CONTAINER",
        "DOCKER_IMAGES",
        "DOCKER_VOLUME_NAME",
        "K8S_NAMESPACE",
        "K8S_CONFIG_PATH",
        "K8S_JOB_TIMEOUT",
    ),
    "Notifications": (
        "COMMON_FOOTER_TEXT",
        "COMMON_FOOTER_HTML",
        "MAINTENANCE_ANNOUNCEMENT_NOTIFY_BEFORE_MINUTES",
        "MAINTENANCE_ANNOUNCEMENT_NOTIFY_SYSTEM",
    ),
    "Links": (
        "DOCS_URL",
        "HERO_LINK_LABEL",
        "HERO_LINK_URL",
        "SUPPORT_PORTAL_URL",
    ),
    "Theme": (
        "SIDEBAR_STYLE",
        "BRAND_COLOR",
        "DISABLE_DARK_THEME",
    ),
    "Images": (
        "SITE_LOGO",
        "SIDEBAR_LOGO",
        "SIDEBAR_LOGO_MOBILE",
        "SIDEBAR_LOGO_DARK",
        "POWERED_BY_LOGO",
        "HERO_IMAGE",
        "MARKETPLACE_HERO_IMAGE",
        "CALL_MANAGEMENT_HERO_IMAGE",
        "LOGIN_LOGO",
        "FAVICON",
        "OFFERING_LOGO_PLACEHOLDER",
        "KEYCLOAK_ICON",
    ),
    "Service desk integration settings": (
        "WALDUR_SUPPORT_ENABLED",
        "WALDUR_SUPPORT_ACTIVE_BACKEND_TYPE",
        "WALDUR_SUPPORT_DISPLAY_REQUEST_TYPE",
    ),
    "Atlassian settings": (
        "ATLASSIAN_API_URL",
        "ATLASSIAN_USERNAME",
        "ATLASSIAN_PASSWORD",
        "ATLASSIAN_EMAIL",
        "ATLASSIAN_TOKEN",
        "ATLASSIAN_PERSONAL_ACCESS_TOKEN",
        "ATLASSIAN_OAUTH2_CLIENT_ID",
        "ATLASSIAN_OAUTH2_ACCESS_TOKEN",
        "ATLASSIAN_OAUTH2_TOKEN_TYPE",
        "ATLASSIAN_PROJECT_ID",
        "ATLASSIAN_DEFAULT_OFFERING_ISSUE_TYPE",
        "ATLASSIAN_EXCLUDED_ATTACHMENT_TYPES",
        "ATLASSIAN_ISSUE_TYPES",
        "ATLASSIAN_SUPPORT_TYPE_MAPPING",
        "ATLASSIAN_AFFECTED_RESOURCE_FIELD",
        "ATLASSIAN_DESCRIPTION_TEMPLATE",
        "ATLASSIAN_SUMMARY_TEMPLATE",
        "ATLASSIAN_IMPACT_FIELD",
        "ATLASSIAN_ORGANISATION_FIELD",
        "ATLASSIAN_RESOLUTION_SLA_FIELD",
        "ATLASSIAN_PROJECT_FIELD",
        "ATLASSIAN_REPORTER_FIELD",
        "ATLASSIAN_CALLER_FIELD",
        "ATLASSIAN_SLA_FIELD",
        "ATLASSIAN_LINKED_ISSUE_TYPE",
        "ATLASSIAN_SATISFACTION_FIELD",
        "ATLASSIAN_REQUEST_FEEDBACK_FIELD",
        "ATLASSIAN_TEMPLATE_FIELD",
        "ATLASSIAN_WALDUR_BACKEND_ID_FIELD",
        "ATLASSIAN_CUSTOM_ISSUE_FIELD_MAPPING_ENABLED",
        "ATLASSIAN_SHARED_USERNAME",
        "ATLASSIAN_VERIFY_SSL",
        "ATLASSIAN_USE_OLD_API",
        "ATLASSIAN_MAP_WALDUR_USERS_TO_SERVICEDESK_AGENTS",
    ),
    "Zammad settings": (
        "ZAMMAD_API_URL",
        "ZAMMAD_TOKEN",
        "ZAMMAD_GROUP",
        "ZAMMAD_ARTICLE_TYPE",
        "ZAMMAD_COMMENT_MARKER",
        "ZAMMAD_COMMENT_PREFIX",
        "ZAMMAD_COMMENT_COOLDOWN_DURATION",
    ),
    "SMAX settings": (
        "SMAX_API_URL",
        "SMAX_TENANT_ID",
        "SMAX_LOGIN",
        "SMAX_PASSWORD",
        "SMAX_ORGANISATION_FIELD",
        "SMAX_PROJECT_FIELD",
        "SMAX_AFFECTED_RESOURCE_FIELD",
        "SMAX_REQUESTS_OFFERING",
        "SMAX_SECONDS_TO_WAIT",
        "SMAX_TIMES_TO_PULL",
        "SMAX_CREATION_SOURCE_NAME",
        "SMAX_VERIFY_SSL",
    ),
    "Proposal settings": ("PROPOSAL_REVIEW_DURATION",),
    "Table settings": ("USER_TABLE_COLUMNS",),
    "Localization": ("LANGUAGE_CHOICES",),
    "User settings": (
        "AUTO_APPROVE_USER_TOS",
        "ENABLE_STRICT_CHECK_ACCEPTING_INVITATION",
        "INVITATION_DISABLE_MULTIPLE_ROLES",
        "DEFAULT_IDP",
        "DEACTIVATE_USER_IF_NO_ROLES",
        "OIDC_BLOCK_CREATION_OF_UNINVITED_USERS",
        "OIDC_ACCESS_TOKEN_ENABLED",
    ),
    "FreeIPA settings": (
        "FREEIPA_ENABLED",
        "FREEIPA_HOSTNAME",
        "FREEIPA_USERNAME",
        "FREEIPA_PASSWORD",
        "FREEIPA_VERIFY_SSL",
        "FREEIPA_USERNAME_PREFIX",
        "FREEIPA_GROUPNAME_PREFIX",
        "FREEIPA_BLACKLISTED_USERNAMES",
        "FREEIPA_GROUP_SYNCHRONIZATION_ENABLED",
    ),
    "OIDC auth settings": (
        "OIDC_AUTH_URL",
        "OIDC_INTROSPECTION_URL",
        "OIDC_CLIENT_ID",
        "OIDC_CLIENT_SECRET",
        "OIDC_USER_FIELD",
        "OIDC_CACHE_TIMEOUT",
    ),
    "Onboarding settings": (
        "ONBOARDING_VERIFICATION_EXPIRY_HOURS",
        "ONBOARDING_ARIREGISTER_BASE_URL",
        "ONBOARDING_ARIREGISTER_USERNAME",
        "ONBOARDING_ARIREGISTER_PASSWORD",
        "ONBOARDING_ARIREGISTER_TIMEOUT",
        "ONBOARDING_WICO_API_URL",
        "ONBOARDING_WICO_TOKEN",
    ),
}

PUBLIC_CONSTANCE_SETTINGS = (
    # Whitelabeling settings
    "SITE_NAME",
    "SITE_DESCRIPTION",
    "SITE_ADDRESS",
    "SITE_EMAIL",
    "SITE_PHONE",
    "CURRENCY_NAME",
    "ANONYMOUS_USER_CAN_VIEW_OFFERINGS",
    "DOCS_URL",
    "SHORT_PAGE_TITLE",
    "FULL_PAGE_TITLE",
    "BRAND_COLOR",
    "HERO_LINK_LABEL",
    "HERO_LINK_URL",
    "SUPPORT_PORTAL_URL",
    "SITE_LOGO",
    "SIDEBAR_LOGO",
    "SIDEBAR_LOGO_MOBILE",
    "SIDEBAR_LOGO_DARK",
    "SIDEBAR_STYLE",
    "POWERED_BY_LOGO",
    "HERO_IMAGE",
    "MARKETPLACE_HERO_IMAGE",
    "CALL_MANAGEMENT_HERO_IMAGE",
    "LOGIN_LOGO",
    "FAVICON",
    "OFFERING_LOGO_PLACEHOLDER",
    "COMMON_FOOTER_TEXT",
    "COMMON_FOOTER_HTML",
    "LANGUAGE_CHOICES",
    "DISABLE_DARK_THEME",
    "MARKETPLACE_LANDING_PAGE",
    "ENABLE_ORDER_START_DATE",
    # Support plugin
    "WALDUR_SUPPORT_ENABLED",
    "WALDUR_SUPPORT_DISPLAY_REQUEST_TYPE",
    "WALDUR_SUPPORT_ACTIVE_BACKEND_TYPE",
    "USER_TABLE_COLUMNS",
    # FreeIPA
    "FREEIPA_ENABLED",
    "FREEIPA_USERNAME_PREFIX",
    "DEFAULT_IDP",
    "HOMEPORT_URL",
    "KEYCLOAK_ICON",
    "RANCHER_USERNAME_INPUT_LABEL",
    "ENFORCE_USER_CONSENT_FOR_OFFERINGS",
    "OIDC_ACCESS_TOKEN_ENABLED",
)
